//! Known answers for the base STARK's Poseidon1 instance, computed by ZisK's own
//! Rust implementation (`proofman-fields`, pil2-proofman v1.3.0-alpha, MIT OR
//! Apache-2.0), printed as a Rust module for `crypto::hash::poseidon1_w16`.
//!
//! Covers every primitive the base proof uses: the width-16 and width-8
//! permutations, the leaf linear hash, the 4-ary Merkle root (with its zero
//! padding) and a path checked by ZisK's `verify_mt`, the Fiat–Shamir transcript,
//! and the grinding hash. Inputs come from the LCG of `p1_params.py kat_inputs`,
//! so the consumer regenerates them instead of storing them.
use proofman_fields::{
    linear_hash_seq, partial_merkle_tree, poseidon1_hash, verify_mt, Goldilocks, Hash,
    Poseidon1_16, Poseidon1_8, PrimeField64, Transcript,
};

const P: u64 = 0xFFFF_FFFF_0000_0001;

/// `n` felts from the LCG seeded with `seed` (the `kat_inputs` stream when the
/// seed is `0x9E3779B97F4A7C15`).
fn felts(seed: u64, n: usize) -> Vec<u64> {
    let mut x = seed;
    (0..n)
        .map(|_| {
            x = x
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            x % P
        })
        .collect()
}

fn gl(v: &[u64]) -> Vec<Goldilocks> {
    v.iter().map(|&x| Goldilocks::new(x)).collect()
}

fn canon(v: &[Goldilocks]) -> Vec<u64> {
    v.iter().map(|x| x.as_canonical_u64()).collect()
}

fn list(v: &[u64]) -> String {
    v.iter().map(|x| format!("0x{x:016x}")).collect::<Vec<_>>().join(", ")
}

const SEED_KAT: u64 = 0x9E37_79B9_7F4A_7C15;
const SEED_LEAF: u64 = 0x1EAF;
const SEED_TREE: u64 = 0x7EEE;
const SEED_ROWS: u64 = 0x2075;
const SEED_TRANSCRIPT: u64 = 0x75C1;
const SEED_GRIND: u64 = 0x6F1D;

const LEAF_LENS: [usize; 15] = [1, 3, 4, 5, 8, 11, 12, 13, 23, 24, 25, 36, 64, 100, 245];
const TREE_LEAVES: [usize; 9] = [1, 2, 3, 4, 5, 16, 17, 21, 64];
const PATH_ROWS: usize = 21;
const PATH_WIDTH: usize = 7;
const PATH_INDICES: [usize; 4] = [0, 3, 13, 20];
const GRIND_BITS: u32 = 10;

fn perm16(x: &[u64]) -> Vec<u64> {
    let s: [Goldilocks; 16] = gl(x).try_into().unwrap();
    canon(&poseidon1_hash::<Goldilocks, Poseidon1_16, 16>(&s))
}

fn perm8(x: &[u64]) -> Vec<u64> {
    let s: [Goldilocks; 8] = gl(x).try_into().unwrap();
    canon(&poseidon1_hash::<Goldilocks, Poseidon1_8, 8>(&s))
}

fn kat_inputs(t: usize) -> Vec<Vec<u64>> {
    vec![(0..t as u64).collect(), vec![0; t], vec![P - 1; t], felts(SEED_KAT, t)]
}

/// Every level of the 4-ary tree over `leaves`, bottom first: a level whose
/// length is not a multiple of 4 is padded with zero digests before its parents
/// are hashed (`partial_merkle_tree`'s rule).
fn levels(leaves: &[[Goldilocks; 4]]) -> Vec<Vec<[Goldilocks; 4]>> {
    let mut out = vec![leaves.to_vec()];
    while out.last().unwrap().len() > 1 {
        let mut cur = out.last().unwrap().clone();
        while cur.len() % 4 != 0 {
            cur.push([Goldilocks::new(0); 4]);
        }
        *out.last_mut().unwrap() = cur.clone();
        let next = cur
            .chunks(4)
            .map(|c| {
                let mut s = [Goldilocks::new(0); 16];
                for (i, d) in c.iter().enumerate() {
                    s[4 * i..4 * i + 4].copy_from_slice(d);
                }
                <Poseidon1_16 as Hash<Goldilocks>>::hash(&mut s);
                [s[0], s[1], s[2], s[3]]
            })
            .collect();
        out.push(next);
    }
    out
}

fn main() {
    println!("//! Known answers computed by ZisK's own Rust implementation of its Poseidon1");
    println!("//! instance: `proofman-fields` of pil2-proofman v1.3.0-alpha (d485fac2, MIT OR");
    println!("//! Apache-2.0).");
    println!("//!");
    println!("//! GENERATED by `scripts/poseidon1/zisk_crosscheck`; do not edit by hand. Inputs are");
    println!("//! the LCG stream of `tests::felts`, so only the outputs are stored.");
    println!();

    println!("/// `(input, permute(input))` at width 16: `[0..16)`, zeros, `p − 1`, LCG.");
    println!("pub const PERM16: [([u64; 16], [u64; 16]); 4] = [");
    for x in kat_inputs(16) {
        println!("    ([{}], [{}]),", list(&x), list(&perm16(&x)));
    }
    println!("];");
    println!();

    println!("/// `(input, permute(input))` at width 8 (the grinding permutation).");
    println!("pub const PERM8: [([u64; 8], [u64; 8]); 4] = [");
    for x in kat_inputs(8) {
        println!("    ([{}], [{}]),", list(&x), list(&perm8(&x)));
    }
    println!("];");
    println!();

    println!("/// Seed of the leaf inputs: `linear_hash(felts(SEED_LEAF, len))`.");
    println!("pub const SEED_LEAF: u64 = 0x{SEED_LEAF:x};");
    println!("/// `(len, digest)`: the width-16 linear hash (ZisK's leaf hash).");
    println!("pub const LINEAR_HASH: [(usize, [u64; 4]); {}] = [", LEAF_LENS.len());
    for n in LEAF_LENS {
        let st = linear_hash_seq::<Goldilocks, Poseidon1_16>(&gl(&felts(SEED_LEAF, n)));
        // The trait's leaf digest, the one `verify_mt` uses, is the same four lanes.
        let d = <Poseidon1_16 as Hash<Goldilocks>>::linear_hash(&gl(&felts(SEED_LEAF, n)));
        assert_eq!(canon(&st[..4]), canon(&d));
        println!("    ({n}, [{}]),", list(&canon(&d)));
    }
    println!("];");
    println!();

    println!("/// Seed of the tree inputs: leaf digest `i` is `felts(SEED_TREE, 4·n)[4i..4i+4]`.");
    println!("pub const SEED_TREE: u64 = 0x{SEED_TREE:x};");
    println!("/// `(leaves, root)`: `partial_merkle_tree` at arity 4.");
    println!("pub const MERKLE4_ROOTS: [(usize, [u64; 4]); {}] = [", TREE_LEAVES.len());
    for n in TREE_LEAVES {
        let flat = gl(&felts(SEED_TREE, 4 * n));
        let root = partial_merkle_tree::<Goldilocks, Poseidon1_16>(&flat, n as u64, 4);
        let digests: Vec<[Goldilocks; 4]> =
            flat.chunks(4).map(|c| [c[0], c[1], c[2], c[3]]).collect();
        let mine = levels(&digests).last().unwrap()[0];
        assert_eq!(canon(&root), canon(&mine), "level rule disagrees at {n} leaves");
        println!("    ({n}, [{}]),", list(&canon(&root)));
    }
    println!("];");
    println!();

    // A path over hashed rows, checked by ZisK's verifier before it is printed.
    let rows: Vec<Vec<Goldilocks>> = gl(&felts(SEED_ROWS, PATH_ROWS * PATH_WIDTH))
        .chunks(PATH_WIDTH)
        .map(<[Goldilocks]>::to_vec)
        .collect();
    let leaves: Vec<[Goldilocks; 4]> = rows
        .iter()
        .map(|r| <Poseidon1_16 as Hash<Goldilocks>>::linear_hash(r))
        .collect();
    let lv = levels(&leaves);
    let root = lv.last().unwrap()[0];
    println!("/// Seed of the path rows: `{PATH_ROWS}` rows of `{PATH_WIDTH}` felts, `felts(SEED_ROWS, ·)` row-major.");
    println!("pub const SEED_ROWS: u64 = 0x{SEED_ROWS:x};");
    println!("pub const PATH_ROWS: usize = {PATH_ROWS};");
    println!("pub const PATH_WIDTH: usize = {PATH_WIDTH};");
    println!("/// The root over the rows' linear hashes.");
    println!("pub const PATH_ROOT: [u64; 4] = [{}];", list(&canon(&root)));
    let depth = lv.len() - 1;
    println!(
        "/// `(index, siblings)`: per level, the three other children in child order (12 felts),"
    );
    println!("/// as ZisK's `verify_mt` reads them; every path here passes it.");
    println!(
        "pub const PATHS: [(usize, [[u64; 12]; {depth}]); {}] = [",
        PATH_INDICES.len()
    );
    for idx in PATH_INDICES {
        let mut mp: Vec<Vec<Goldilocks>> = Vec::new();
        let mut i = idx;
        for level in &lv[..depth] {
            let group = i / 4 * 4;
            let mut sib = Vec::new();
            for c in group..group + 4 {
                if c != i {
                    sib.extend_from_slice(&level[c]);
                }
            }
            mp.push(sib);
            i /= 4;
        }
        assert!(verify_mt::<Goldilocks, Poseidon1_16, Poseidon1_16>(
            &root,
            &[],
            &mp,
            idx as u64,
            &rows[idx],
            4,
            0
        ));
        // Negative control: a flipped sibling felt must fail ZisK's verifier.
        let mut bad = mp.clone();
        bad[0][0] = bad[0][0] + Goldilocks::new(1);
        assert!(!verify_mt::<Goldilocks, Poseidon1_16, Poseidon1_16>(
            &root,
            &[],
            &bad,
            idx as u64,
            &rows[idx],
            4,
            0
        ));
        let levels: Vec<String> = mp.iter().map(|s| format!("[{}]", list(&canon(s)))).collect();
        println!("    ({idx}, [{}]),", levels.join(", "));
    }
    println!("];");
    println!();

    // The transcript script; the consumer replays the same calls.
    let t = felts(SEED_TRANSCRIPT, 4 + 4 + 4 + 12 + 30);
    let (a, rest) = t.split_at(4);
    let (b, rest) = rest.split_at(4);
    let (c, rest) = rest.split_at(4);
    let (d, e) = rest.split_at(12);
    let mut tr: Transcript<Goldilocks, Poseidon1_16> = Transcript::new();
    let mut out: Vec<u64> = Vec::new();
    let field = |tr: &mut Transcript<Goldilocks, Poseidon1_16>, out: &mut Vec<u64>| {
        let mut v = [Goldilocks::new(0); 3];
        tr.get_field(&mut v);
        out.extend(canon(&v));
    };
    tr.put(&gl(a));
    tr.put(&gl(b));
    field(&mut tr, &mut out);
    field(&mut tr, &mut out);
    tr.put(&gl(c));
    field(&mut tr, &mut out);
    tr.put(&gl(d));
    field(&mut tr, &mut out);
    tr.put(&gl(e));
    for _ in 0..6 {
        field(&mut tr, &mut out);
    }
    out.extend(canon(&tr.get_state()));
    let last = &out[out.len() - 16 - 3..out.len() - 16].to_vec();
    let mut tq: Transcript<Goldilocks, Poseidon1_16> = Transcript::new();
    tq.put(&gl(last));
    tq.put(&[Goldilocks::new(12345)]);
    let queries = tq.get_permutations(10, 21);
    println!("/// Seed of the transcript inputs (4 + 4 + 4 + 12 + 30 felts, in call order).");
    println!("pub const SEED_TRANSCRIPT: u64 = 0x{SEED_TRANSCRIPT:x};");
    println!("/// The script: put 4, put 4, field, field, put 4, field, put 12, field, put 30,");
    println!("/// field ×6, then `get_state` (16): every squeezed felt in order.");
    println!("pub const TRANSCRIPT_OUT: [u64; {}] = [{}];", out.len(), list(&out));
    println!("/// A fresh transcript fed the last field squeezed above and the nonce 12345:");
    println!("/// `get_permutations(10, 21)` (ZisK's query indices).");
    println!("pub const TRANSCRIPT_QUERIES: [u64; 10] = [{}];", list(&queries));
    println!();

    let ch = felts(SEED_GRIND, 3);
    let pow = |nonce: u64| {
        let mut s = [Goldilocks::new(0); 8];
        s[0] = Goldilocks::new(ch[0]);
        s[1] = Goldilocks::new(ch[1]);
        s[2] = Goldilocks::new(ch[2]);
        s[3] = Goldilocks::new(nonce);
        <Poseidon1_8 as Hash<Goldilocks>>::hash(&mut s);
        s[0].as_canonical_u64()
    };
    let lanes: Vec<String> = (0..4u64).map(|n| format!("({n}, 0x{:016x})", pow(n))).collect();
    let smallest = (0u64..).find(|&n| pow(n) < 1u64 << (64 - GRIND_BITS)).unwrap();
    println!("/// The grinding challenge, `felts(SEED_GRIND, 3)`.");
    println!("pub const SEED_GRIND: u64 = 0x{SEED_GRIND:x};");
    println!("/// `(nonce, lane 0)` of the width-8 permutation of `[c0, c1, c2, nonce, 0, 0, 0, 0]`.");
    println!("pub const GRIND_LANE0: [(u64, u64); 4] = [{}];", lanes.join(", "));
    println!("/// The smallest nonce whose lane 0 is below `2^(64 − GRIND_BITS)`.");
    println!("pub const GRIND_BITS: u32 = {GRIND_BITS};");
    println!("pub const GRIND_SMALLEST_NONCE: u64 = {smallest};");
}
