//! Poseidon-original ("Poseidon1") over Goldilocks at width 12 — the hash
//! matrix's first real candidate behind the `LFM_HASH` socket.
//!
//! # Why this hash and not Poseidon2
//!
//! Poseidon2 is BROKEN (eprint 2026/306 exploits the structure of its linear
//! layers) and must never be built here. Poseidon-original is the same S-box
//! family with a dense MDS that lacks the exploited structure, and it is where
//! the ecosystem moved.
//!
//! # Parameter provenance — READ THIS BEFORE TRUSTING A MEASUREMENT
//!
//! Parameters are taken from the vendored Plonky3 tree,
//! `others/Plonky3/goldilocks/src/poseidon1.rs` @ 4aed8fe4, which documents
//! them as generated by the Grain LFSR of the Poseidon paper (Appendix E) with
//! `field_type=1, alpha=7 (exp_flag=0), n=64, t=12, R_F=8, R_P=22`, via
//! `poseidon/generate_constants.py --field goldilocks --width 12`:
//!
//! - `ALPHA = 7` — the smallest valid exponent, because Goldilocks has
//!   `p - 1 = 2^32 · 3 · 5 · 17 · 257 · 65537`, so neither 3 nor 5 is coprime to
//!   `p - 1`. **A cube S-box is not a permutation over this field**, which is
//!   why the in-tree HADES skeleton in `crypto/crypto/src/hash/poseidon/` can
//!   never serve as an oracle: it hardcodes `x^3`.
//! - `R_F = 8` full rounds (4 initial + 4 terminal), `R_P = 22` partial.
//! - The MDS matrix is CIRCULANT with first row `MDS_CIRC_ROW`.
//!
//! ⚠ **Ship-grade parameter selection is a separate cryptographic decision for
//! the ecosystem and is NOT settled by this measurement.** These parameters are
//! adequate to measure the AIR's SHAPE — cells depend on round counts and the
//! S-box degree, not on the numeric values of the constants — and they come from
//! a published generator, but choosing what to ship is not ours.
//!
//! # Oracle
//!
//! [`tests::the_permutation_matches_the_plonky3_known_answer_vector`] pins the
//! whole permutation against Plonky3's own known-answer test
//! (`goldilocks/src/poseidon1.rs::test_poseidon_goldilocks_width_12`), an
//! EXTERNAL vector we did not compute. That is the differential this module
//! rests on.

use crate::tables::types::FE;

use super::hash::{HASH_STATE_FELTS, LfmHasher};
use super::word::LfmWord;

/// The S-box exponent. See the provenance note: 7 is forced by Goldilocks.
pub const ALPHA: u32 = 7;
/// Full rounds per half; `R_F = 2 * HALF_FULL_ROUNDS = 8`.
pub const HALF_FULL_ROUNDS: usize = 4;
/// Partial rounds, S-box on lane 0 only.
pub const PARTIAL_ROUNDS: usize = 22;
/// Total rounds — the figure the AIR's column count is linear in.
pub const NUM_ROUNDS: usize = 2 * HALF_FULL_ROUNDS + PARTIAL_ROUNDS;

/// First ROW of the circulant MDS matrix, so `M[i][j] = MDS_CIRC_ROW[(j - i) mod 12]`.
///
/// From `others/Plonky3/goldilocks/src/mds.rs:92` (`MATRIX_CIRC_MDS_12_SML_ROW`).
pub const MDS_CIRC_ROW: [u64; HASH_STATE_FELTS] = [1, 1, 2, 1, 8, 9, 10, 7, 5, 9, 4, 10];

/// Round constants, `[round][lane]`, in the order
/// `[initial_full (4), partial (22), terminal_full (4)]`.
pub const ROUND_CONSTANTS: [[u64; HASH_STATE_FELTS]; NUM_ROUNDS] = [
    [
        0x13dcf33aba214f46,
        0x30b3b654a1da6d83,
        0x1fc634ada6159b56,
        0x937459964dc03466,
        0xedd2ef2ca7949924,
        0xede9affde0e22f68,
        0x8515b9d6bac9282d,
        0x6b5c07b4e9e900d8,
        0x1ec66368838c8a08,
        0x9042367d80d1fbab,
        0x400283564a3c3799,
        0x4a00be0466bca75e,
    ],
    [
        0x7913beee58e3817f,
        0xf545e88532237d90,
        0x22f8cb8736042005,
        0x6f04990e247a2623,
        0xfe22e87ba37c38cd,
        0xd20e32c85ffe2815,
        0x117227674048fe73,
        0x4e9fb7ea98a6b145,
        0xe0866c232b8af08b,
        0x00bbc77916884964,
        0x7031c0fb990d7116,
        0x240a9e87cf35108f,
    ],
    [
        0x2e6363a5a12244b3,
        0x5e1c3787d1b5011c,
        0x4132660e2a196e8b,
        0x3a013b648d3d4327,
        0xf79839f49888ea43,
        0xfe85658ebafe1439,
        0xb6889825a14240bd,
        0x578453605541382b,
        0x4508cda8f6b63ce9,
        0x9c3ef35848684c91,
        0x0812bde23c87178c,
        0xfe49638f7f722c14,
    ],
    [
        0x8e3f688ce885cbf5,
        0xb8e110acf746a87d,
        0xb4b2e8973a6dabef,
        0x9e714c5da3d462ec,
        0x6438f9033d3d0c15,
        0x24312f7cf1a27199,
        0x23f843bb47acbf71,
        0x9183f11a34be9f01,
        0x839062fbb9d45dbf,
        0x24b56e7e6c2e43fa,
        0xe1683da61c962a72,
        0xa95c63971a19bfa7,
    ],
    [
        0x4adf842aa75d4316,
        0xf8fbb871aa4ab4eb,
        0x68e85b6eb2dd6aeb,
        0x07a0b06b2d270380,
        0xd94e0228bd282de4,
        0x8bdd91d3250c5278,
        0x209c68b88bba778f,
        0xb5e18cdab77f3877,
        0xb296a3e808da93fa,
        0x8370ecbda11a327e,
        0x3f9075283775dad8,
        0xb78095bb23c6aa84,
    ],
    [
        0x3f36b9fe72ad4e5f,
        0x69bc96780b10b553,
        0x3f1d341f2eb7b881,
        0x4e939e9815838818,
        0xda366b3ae2a31604,
        0xbc89db1e7287d509,
        0x6102f411f9ef5659,
        0x58725c5e7ac1f0ab,
        0x0df5856c798883e7,
        0xf7bb62a8da4c961b,
        0xc68be7c94882a24d,
        0xaf996d5d5cdaedd9,
    ],
    [
        0x9717f025e7daf6a5,
        0x6436679e6e7216f4,
        0x8a223d99047af267,
        0xbb512e35a133ba9a,
        0xfbbf44097671aa03,
        0xf04058ebf6811e61,
        0x5cca84703fac7ffb,
        0x9b55c7945de6469f,
        0x8e05bf09808e934f,
        0x2ea900de876307d7,
        0x7748fff2b38dfb89,
        0x6b99a676dd3b5d81,
    ],
    [
        0xac4bb7c627cf7c13,
        0xadb6ebe5e9e2f5ba,
        0x2d33378cafa24ae3,
        0x1e5b73807543f8c2,
        0x09208814bfebb10f,
        0x782e64b6bb5b93dd,
        0xadd5a48eac90b50f,
        0xadd4c54c736ea4b1,
        0xd58dbb86ed817fd8,
        0x6d5ed1a533f34ddd,
        0x28686aa3e36b7cb9,
        0x591abd3476689f36,
    ],
    [
        0x047d766678f13875,
        0xa2a11112625f5b49,
        0x21fd10a3f8304958,
        0xf9b40711443b0280,
        0xd2697eb8b2bde88e,
        0x3493790b51731b3f,
        0x11caf9dd73764023,
        0x7acfb8f72878164e,
        0x744ec4db23cefc26,
        0x1e00e58f422c6340,
        0x21dd28d906a62dda,
        0xf32a46ab5f465b5f,
    ],
    [
        0xbfce13201f3f7e6b,
        0xf30d2e7adb5304e2,
        0xecdf4ee4abad48e9,
        0xf94e82182d395019,
        0x4ee52e3744d887c5,
        0xa1341c7cac0083b2,
        0x2302fb26c30c834a,
        0xaea3c587273bf7d3,
        0xf798e24961823ec7,
        0x962deba3e9a2cd94,
        0xb36ee79485ca4707,
        0xd380199eddd2de52,
    ],
    [
        0x70971fc4e6f85305,
        0x8e722f6e5dc32699,
        0xa0883df133052b92,
        0x8f86c6a3eb7d01a4,
        0x763649c8b670bdc5,
        0x830d5c82b808759b,
        0xaa1da8bb91da02e7,
        0x9bc9bf629e211c4d,
        0x0f0a899b10a4dea8,
        0xb883bdcee7c6b356,
        0x78c7101e7496ae1e,
        0x2fd6c5a8bf1e5ca6,
    ],
    [
        0xe2a6e06e61fcec9c,
        0xebfce7d5c5b3dbd5,
        0xca2eeca4bb485d85,
        0xc2b875537c42eb69,
        0x6faf849976873328,
        0xfc3fcb6e81ad4cc3,
        0x180dd95503955a28,
        0xd40f19a3c9fe1520,
        0x49d178ddbf7fd96d,
        0x3950bee2e10e0297,
        0x437b90cf295be062,
        0xa5cd126edffad23b,
    ],
    [
        0xdf58134c134491c2,
        0x0677eca229d9f7bd,
        0x492200a1f7d83a3c,
        0xafb58c9810a43645,
        0x7659077c5a9c208e,
        0x30b4bc83706995cd,
        0xc98fa77bbbef3a3b,
        0x84a82905750b3109,
        0x72f2a02326aeb69b,
        0x8d27a2a2d73a848a,
        0xaa9e30a80bde4b68,
        0x63abb1415e050474,
    ],
    [
        0x1c4bd1e816050a7e,
        0x15d1502e4f469dfd,
        0x53989d594b0c4cd8,
        0x7a1a4c83cb7e377e,
        0x1b52f8a9944e480e,
        0xeb7b03f76a91a79e,
        0x0073a4fc9328c69e,
        0x2c7b16f8620d9de4,
        0x950d052963e46bc4,
        0x8d201ba1a9c89fac,
        0xd3502941bdf35503,
        0x7c6dfcd5af8676fb,
    ],
    [
        0xf8a6cd02e92cdb0b,
        0x6e7500f3a5464b22,
        0x07637eabba4bdd20,
        0x88b82717beee0e14,
        0xbaa2b1cd3dd4c79a,
        0xdfecc3aebec4cfa6,
        0x7561087b0cff0166,
        0x538fcac317a703a6,
        0xd7d6c6eeeeeeea19,
        0xd647b1ee441658a0,
        0xdf4442110236c546,
        0x559ef2c6dd73ec15,
    ],
    [
        0x4c0f5fc6c0dda3d1,
        0x685010cc3100cea7,
        0x2fb6ba8aa0344440,
        0xb515f0a3ca75f1fb,
        0x886887eaecb87c10,
        0xf03ec3fd710abb04,
        0xd3b4763e17f543ef,
        0x50d9e5716e78083a,
        0x0bce2385cf8d74ff,
        0xaf23032cd5f0e04b,
        0xd366aa112b6159d9,
        0x810a3ad3ac7979db,
    ],
    [
        0x0a4a11d794be40a2,
        0xeebf0cf23b668a3f,
        0x600873fb011d761b,
        0x0bfb5591a02ff618,
        0xa16e2a528910af52,
        0xf6553653e2878421,
        0xccbe7c7a601a30c0,
        0xb18b214fe489f5b3,
        0xe21017ab9e153425,
        0x586099ede17af9a6,
        0x385078b514f50647,
        0xc02b3a9afb89883d,
    ],
    [
        0x6d3fbd3b4a9f1de6,
        0x4b4d40a41b0f473c,
        0x838f1887b8f31711,
        0x9396895be5c58a41,
        0x6247a479d66fc2e3,
        0x13fe228a98f2d0a2,
        0x5ba5fde765f9481e,
        0xafb89fa62267e117,
        0xfa4dc1bebcaa6333,
        0xdbab590882b87289,
        0xc3b6c08e23ba9301,
        0xd84b5de94a324fb7,
    ],
    [
        0x0d0c371c5b35b850,
        0x7964f570e7188038,
        0x5daf18bbd996604c,
        0x6743bc47b9595258,
        0x5528b9362c59bb71,
        0xac45e25b7127b68c,
        0xa2077d7dfbb606b6,
        0xf3faac6faee378af,
        0x0c6388b51545e884,
        0xd27dbb6944917b61,
        0x89bcac584344c104,
        0x856bab802ce7402d,
    ],
    [
        0x2cff3000be1fcd0a,
        0x765f2977fa72a917,
        0x1443711329f5f9d5,
        0xd35cd0261af2f951,
        0x2a1bb986084ec281,
        0x2334a54b758f23f2,
        0xa9b8cb612caf706b,
        0xb6ba11c4ab1a1017,
        0xde96b0824b4b46e2,
        0xc59d4272c6d92e2c,
        0x389bb5107611754d,
        0x23647fbc77657372,
    ],
    [
        0xd5ef60d6f76a42fa,
        0xebb406bb79ac9819,
        0x55faccc709a2f423,
        0xd9d6ea97490091cd,
        0xef3ce5069647a7e4,
        0xdf31625d3fa78464,
        0x242e60fd68f10f66,
        0x39c966cc815f084d,
        0x20e2e22e02bae3f7,
        0xb38919d3f1173d7c,
        0xf17769f6c77084d9,
        0xcc051d8094cac41f,
    ],
    [
        0x942069f5d6eece7e,
        0x8d61d3e6f141c572,
        0xc5cef9d85dd605f4,
        0x938f2ac2bf885997,
        0x23bddbace7c48f6c,
        0xc90a6c5ba98537e4,
        0x0be6ee2cca90f6ae,
        0xa026175394ae0e90,
        0x29fca3e314c77628,
        0x2aa2aa8738ab7b77,
        0xe11bbd31fbb8cac6,
        0xb5bbbef1b78a23af,
    ],
    [
        0x8b62a5551e9a9797,
        0x3f91073d4d491c80,
        0x4cfa44976396424a,
        0xf8dcb2dfb3aa1b44,
        0x3849409eba1a95f5,
        0x070845799f234380,
        0x184c0093667da1ba,
        0xbd66aafccd51601e,
        0xee6d14e92155b490,
        0x626f2ec1865bc544,
        0x1bd2854bf6485986,
        0x368b8497472f12ef,
    ],
    [
        0x4f88cdcdfb791921,
        0xe2c0acfeda9ae781,
        0x9739bc21773469b3,
        0x00ce3ad64dc4bb8f,
        0xaab85a321ee7a4c8,
        0xd5de825be97004f4,
        0x48d676d3a043b1c6,
        0x9c6180b1ff643097,
        0x34882a89dd590b09,
        0xae7e6b0d249c3b1d,
        0x8c016908a04885a1,
        0x83ebaaebc9ae0721,
    ],
    [
        0xab21b42e0f642307,
        0xdb46631f62bb29c1,
        0xef29f0399e09b5d9,
        0x5b52fbb3613b8ba1,
        0x57e129fcc96922e6,
        0xcdeb14c9d9204b3a,
        0x1341ef0da8536e34,
        0xd7e3400f2bacde63,
        0x6911eeb42f70d7e5,
        0xc3a2a910a4679767,
        0x1773cbe4a0f6bb28,
        0xe17b0d53e843eab5,
    ],
    [
        0x587fa39990b62800,
        0x0d5d32788135879d,
        0x277f7b31fd3a4cdb,
        0xa435290ee56d7efa,
        0xea6f40be35159925,
        0xcb73377a506171cb,
        0xe43c367ce731d82a,
        0x6eb305031ca10c43,
        0xc019a8c622cc84cb,
        0xd5614f5658c612e6,
        0x7b1ecbe957c3ff98,
        0x60db6ee9651a8478,
    ],
    [
        0x9271d450fc9b4117,
        0xcffeea06b6e3aac1,
        0xfa4a44c748d1cd8e,
        0xe64db01ba569b469,
        0xd31005160e4045fe,
        0x39e0fa013e025f79,
        0xe243be574196a956,
        0x205b2a681e3d2642,
        0x79cae5ad93486bab,
        0xfdf567844e32c295,
        0x331679589bfb7189,
        0xaf06ee32297b89c2,
    ],
    [
        0xa6bcae311e498491,
        0x9d16f52c96ac8b3e,
        0x48a674b59393fa35,
        0x0f9e65da3fde3796,
        0x1e098310fc84578c,
        0x559ae5fab1ae8dad,
        0x56bd4d624078881d,
        0xfd8bbbf8fbe817b5,
        0x82d30695c44df534,
        0x3ec0a97bc41127c5,
        0x1eb8b64adaa22078,
        0x82c45e418d60c983,
    ],
    [
        0xb092280f484d55bf,
        0xcd317c9537697939,
        0xd3be2e352feb79f3,
        0xca6d866539a390e5,
        0xb5efb1a494e55ee6,
        0xfa9013ac89756e9e,
        0xaeb88efd1e981242,
        0x13ee477cdab6e0dc,
        0xce7df902c40da2d3,
        0xf3fbaf0d4e6f5f34,
        0xf96354ada6785f38,
        0x13b5692812406886,
    ],
    [
        0xf03cae030a0f4418,
        0x7d3172887aa98e1a,
        0x8a2c2644f2faf7b9,
        0x80d721abee696d00,
        0x27c8b903a4d68267,
        0xaf0b7b12f90291b8,
        0x00acd08cfdff3817,
        0x4659ee496c634328,
        0xf5b25c10730dbff1,
        0xdde3a153297329c2,
        0x50c0b70d6910a44b,
        0x23c7426af725a6a0,
    ],
];

/// Poseidon-original over Goldilocks, width 12 — a real cryptographic hash
/// behind the `LFM_HASH` contract, replacing `TestPermutation`.
pub struct PoseidonGoldilocks;

impl PoseidonGoldilocks {
    /// `x^7` by square-and-multiply: `x^2`, `x^3 = x^2 * x`, `x^7 = (x^3)^2 * x`.
    ///
    /// Written in exactly the association the AIR's degree-3 lowering uses, so
    /// the executor and the chip agree by construction rather than by luck.
    fn sbox(x: &FE) -> FE {
        let x2 = x * x;
        let x3 = &x2 * x;
        let x6 = &x3 * &x3;
        &x6 * x
    }

    /// The circulant MDS product.
    fn mds(state: &[FE; HASH_STATE_FELTS]) -> [FE; HASH_STATE_FELTS] {
        core::array::from_fn(|i| {
            let mut acc = FE::zero();
            for (j, s) in state.iter().enumerate() {
                let c = FE::from(MDS_CIRC_ROW[(j + HASH_STATE_FELTS - i) % HASH_STATE_FELTS]);
                acc += c * s;
            }
            acc
        })
    }

    fn add_round_constants(state: &mut [FE; HASH_STATE_FELTS], round: usize) {
        for (k, s) in state.iter_mut().enumerate() {
            *s += FE::from(ROUND_CONSTANTS[round][k]);
        }
    }
}

impl LfmHasher for PoseidonGoldilocks {
    fn permute(&self, state: [FE; HASH_STATE_FELTS]) -> [FE; HASH_STATE_FELTS] {
        let mut s = state;
        let mut round = 0;
        for _ in 0..HALF_FULL_ROUNDS {
            Self::add_round_constants(&mut s, round);
            for lane in s.iter_mut() {
                *lane = Self::sbox(lane);
            }
            s = Self::mds(&s);
            round += 1;
        }
        for _ in 0..PARTIAL_ROUNDS {
            Self::add_round_constants(&mut s, round);
            s[0] = Self::sbox(&s[0]);
            s = Self::mds(&s);
            round += 1;
        }
        for _ in 0..HALF_FULL_ROUNDS {
            Self::add_round_constants(&mut s, round);
            for lane in s.iter_mut() {
                *lane = Self::sbox(lane);
            }
            s = Self::mds(&s);
            round += 1;
        }
        debug_assert_eq!(round, NUM_ROUNDS, "every round constant row is consumed");
        s
    }

    /// The capacity cell for `Compress` mode.
    ///
    /// ⚠ ZERO capacity, i.e. the plain sponge compression of `[a ‖ b ‖ 0]`.
    /// Domain separation is a cryptographic decision of the same class as
    /// parameter selection and is deliberately NOT invented here; a shipped
    /// design may well want a nonzero, length- or position-dependent IV.
    fn compress_iv(&self) -> LfmWord {
        [FE::zero(), FE::zero(), FE::zero(), FE::zero()]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Plonky3's own known-answer vector — an EXTERNAL oracle.
    ///
    /// Source: `others/Plonky3/goldilocks/src/poseidon1.rs`,
    /// `test_poseidon_goldilocks_width_12` (input `0..11`). Nothing in this
    /// repository produced these twelve numbers, which is the point: they check
    /// the constants, the round order, the S-box exponent, the MDS orientation
    /// and the partial-round lane all at once.
    const PLONKY3_KAT_OUT: [u64; HASH_STATE_FELTS] = [
        15595088881848875364,
        9564850329150784619,
        13607005230761744521,
        12117102595842533385,
        2814257411756993122,
        11640647689983397089,
        14363867760831937423,
        13323891071259596526,
        11219803511311150468,
        9221595262780869902,
        5898229059046891887,
        18181291031484020550,
    ];

    #[test]
    fn the_permutation_matches_the_plonky3_known_answer_vector() {
        let input: [FE; HASH_STATE_FELTS] = core::array::from_fn(|i| FE::from(i as u64));
        let got = PoseidonGoldilocks.permute(input);
        let want: [FE; HASH_STATE_FELTS] = core::array::from_fn(|i| FE::from(PLONKY3_KAT_OUT[i]));
        assert_eq!(
            got, want,
            "the permutation must match Plonky3's KAT exactly"
        );
    }

    /// The S-box exponent must be coprime to `p - 1`, or the S-box is not a
    /// permutation. This is the exact trap the in-tree HADES skeleton falls into
    /// with its hardcoded `x^3`, so the property is asserted rather than trusted.
    #[test]
    fn the_sbox_exponent_is_coprime_to_the_group_order() {
        // Goldilocks: p = 2^64 - 2^32 + 1, and p - 1 = 2^32 · 3 · 5 · 17 · 257 · 65537.
        const P_MINUS_ONE: u128 = (1u128 << 64) - (1u128 << 32);
        fn gcd(a: u128, b: u128) -> u128 {
            if b == 0 { a } else { gcd(b, a % b) }
        }
        assert_eq!(
            gcd(ALPHA as u128, P_MINUS_ONE),
            1,
            "x^{ALPHA} must be a permutation over Goldilocks"
        );
        for bad in [3u128, 5] {
            assert_ne!(
                gcd(bad, P_MINUS_ONE),
                1,
                "{bad} divides p-1, so x^{bad} is NOT a permutation — the skeleton's bug"
            );
        }
    }

    #[test]
    fn the_round_constant_table_has_one_row_per_round() {
        assert_eq!(ROUND_CONSTANTS.len(), NUM_ROUNDS);
        assert_eq!(NUM_ROUNDS, 30, "8 full + 22 partial");
    }
}
