//! The four sequence vectors, and what each one is for.

use super::whir_transcript_kats::{Script, Step, run};

/// K1 — ORDER. Distinct, asymmetric values, so swapping any two absorbs moves
/// the result. A script of equal values would pass a swap.
const K1_ORDER: Script = Script {
    name: "order",
    steps: &[
        Step::AbsorbBytes {
            seed: 0x11,
            len: 32,
        },
        Step::AbsorbExt { seed: 0x2222_2222 },
        Step::SampleExt,
        Step::AbsorbBytes { seed: 0x33, len: 8 },
        Step::SampleExt,
        Step::SampleU64 { bound: 1 << 20 },
    ],
};

/// K2 — WIDTH AND PADDING. Every length class mod 8 and mod 64, because the
/// leaf sponge's padding flag is `len mod 8` and its block is 64 bytes. A
/// trailing partial group zero-extended on the wrong side lands here.
const K2_WIDTH: Script = Script {
    name: "width",
    steps: &[
        Step::AbsorbBytes { seed: 0x41, len: 0 },
        Step::SampleExt,
        Step::AbsorbBytes { seed: 0x42, len: 1 },
        Step::SampleExt,
        Step::AbsorbBytes { seed: 0x43, len: 7 },
        Step::SampleExt,
        Step::AbsorbBytes { seed: 0x44, len: 8 },
        Step::SampleExt,
        Step::AbsorbBytes { seed: 0x45, len: 9 },
        Step::SampleExt,
        Step::AbsorbBytes {
            seed: 0x46,
            len: 63,
        },
        Step::SampleExt,
        Step::AbsorbBytes {
            seed: 0x47,
            len: 64,
        },
        Step::SampleExt,
        Step::AbsorbBytes {
            seed: 0x48,
            len: 65,
        },
        Step::SampleExt,
        Step::AbsorbBytes {
            seed: 0x49,
            len: 72,
        },
        Step::SampleExt,
    ],
};

/// K3 — CHAIN ADVANCE. Consecutive draws with no absorb between them. A
/// squeeze re-absorbs its own output; drop that and every draw after the first
/// repeats, which one squeeze cannot show.
const K3_CHAIN: Script = Script {
    name: "chain",
    steps: &[
        Step::AbsorbBytes {
            seed: 0x51,
            len: 32,
        },
        Step::SampleExt,
        Step::SampleExt,
        Step::SampleExt,
        Step::SampleExt,
        Step::SampleExt,
        Step::SampleExt,
    ],
};

/// K4 — SAMPLER OFFSET. An asymmetric interleaving of the two samplers and an
/// absorb. An extension element takes three of a squeeze's four candidates and
/// an absorb discards the rest, so a one-candidate slip still produces
/// plausible field elements and is invisible to anything but pinned values.
const K4_OFFSET: Script = Script {
    name: "offset",
    steps: &[
        Step::AbsorbBytes {
            seed: 0x61,
            len: 24,
        },
        Step::SampleU64 { bound: 1 << 23 },
        Step::SampleExt,
        Step::SampleU64 { bound: 1 << 19 },
        Step::SampleU64 { bound: 1 << 19 },
        Step::SampleExt,
        Step::AbsorbBytes {
            seed: 0x62,
            len: 32,
        },
        Step::SampleExt,
        Step::SampleU64 { bound: 4 },
    ],
};

const SCRIPTS: &[&Script] = &[&K1_ORDER, &K2_WIDTH, &K3_CHAIN, &K4_OFFSET];

/// Prints the vectors in the form the table below takes. Run after a
/// deliberate change to the transcript, never to make a red test green.
#[test]
#[ignore = "generator, not a test"]
fn print_whir_transcript_vectors() {
    for s in SCRIPTS {
        let o = run(s);
        let ext: Vec<String> = o
            .ext
            .iter()
            .map(|e| {
                let [a, b, c] = *e.value();
                format!("({}, {}, {})", a.value(), b.value(), c.value())
            })
            .collect();
        println!("// {}", s.name);
        println!("state {}", hex(&o.state));
        println!("ext   [{}]", ext.join(", "));
        println!("u64s  {:?}\n", o.u64s);
    }
}

fn hex(b: &[u8; 32]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// ★ The vectors. GENERATED by the test above — recordings of this
/// transcript, not a specification of it (see the module header).
///
/// ⚠ The SAMPLED VALUES are pinned, not only the state, and that is
/// load-bearing rather than thorough. A squeeze re-absorbs its output, so the
/// chain advances once per SQUEEZE — a sampler reading the wrong eight bytes of
/// the RIGHT squeeze returns a different value from an identical chain, leaving
/// the final state untouched. Pinning the state alone would have been blind to
/// exactly the failure K4 exists to catch.
pub struct Vector {
    pub name: &'static str,
    pub state: &'static str,
    /// Sampled extension elements, three coordinates each, flattened.
    pub ext: &'static [u64],
    pub u64s: &'static [u64],
}

const VECTORS: &[Vector] = &[
    Vector {
        name: "order",
        state: "c59cae7a0b68bd9979abad5ccdfb56a6fe41376e33b9c6af33c9d3abbf771e8b",
        ext: &[
            5076344684520935901,
            13481200151466509943,
            16683032029069390868,
            1376745799081504414,
            17851777139959444118,
            1864588735162070927,
        ],
        u64s: &[144076],
    },
    Vector {
        name: "width",
        state: "3d35cdbb8dd36f6937a25b596c077a630c3b5d8917073d61cbf82ebfd7076f19",
        ext: &[
            0,
            0,
            0,
            13779361758518057625,
            12861723740627776268,
            1850467284123532435,
            1483117093021199727,
            15817517280666576414,
            9696778708142809560,
            12000993751906614372,
            8022334130801498047,
            11287794890553842288,
            9755754461561997648,
            11710191894463407300,
            122339190123564887,
            4801124081631589251,
            210538569640777557,
            11301051852487502001,
            3437677669383980337,
            15204956286457165234,
            15610975559828333221,
            14734763767558745501,
            9832650469355206763,
            5246191761053816184,
            9584292669402132547,
            18430272915700838563,
            4262435669781350388,
        ],
        u64s: &[],
    },
    Vector {
        name: "chain",
        state: "17ed4136b20cb6bf075fb0a69bcb70bd2f84e85d0d616b777f86dc4472bdb11f",
        ext: &[
            12482777032374998597,
            17123056680038681210,
            15285331874205903840,
            11971505191909278852,
            17560771582447933866,
            9573896076222905442,
            8298914713805243577,
            11930008621129790039,
            8209673665337805593,
            11264933134106569355,
            15636484629095859538,
            2339114142658380897,
            9932494386427677841,
            17740759830813518525,
            5773334258638364270,
            3369130016219959262,
            9334649995654086438,
            15117490715794284312,
        ],
        u64s: &[],
    },
    Vector {
        name: "offset",
        state: "73bf7c069df5f3d26760c9fd3d3c5259aaddc92a8667170ace9fb98407ef50b9",
        ext: &[
            5510470753300211043,
            6140529258356735583,
            13714250910034146583,
            14904270912001888584,
            8534709010995452892,
            10669800597048532156,
            10638644543122064108,
            4984655170130837497,
            9626235538098858159,
        ],
        u64s: &[785996, 520380, 330140, 1],
    },
];

#[test]
fn the_whir_transcript_scripts_reproduce_their_vectors() {
    for (s, want) in SCRIPTS.iter().zip(VECTORS) {
        assert_eq!(
            s.name, want.name,
            "the script table and the vector table must agree in order"
        );
        let got = run(s);
        let flat: Vec<u64> = got
            .ext
            .iter()
            .flat_map(|e| {
                let [a, b, c] = *e.value();
                [*a.value(), *b.value(), *c.value()]
            })
            .collect();
        assert_eq!(
            flat.as_slice(),
            want.ext,
            "{}: a sampled extension element moved — the draw schedule or the \
             buffer offset changed",
            want.name
        );
        assert_eq!(
            got.u64s.as_slice(),
            want.u64s,
            "{}: a sampled u64 moved",
            want.name
        );
        assert_eq!(
            hex(&got.state),
            want.state,
            "{}: the transcript's sequence moved. If that was deliberate, rerun \
             `print_whir_transcript_vectors` and say in the commit which absorb \
             or draw changed; if it was not, the emitter and the host have \
             diverged",
            want.name
        );
    }
}

/// ⚠ An edge the vectors above happen to record, worth its own name.
///
/// `sponge_leaf_bytes` returns the capacity's low lanes without permuting when
/// there is nothing to absorb, and those lanes are zero — so squeezing a
/// transcript that has absorbed nothing yields the ZERO digest and hence a zero
/// challenge. Production never reaches it: every WHIR transcript absorbs its
/// statement tag before drawing anything. This test is here so that a path
/// which one day samples first fails loudly rather than drawing a constant.
#[test]
fn an_empty_rpx_transcript_squeezes_to_zero_which_production_never_reaches() {
    let empty = Script {
        name: "empty",
        steps: &[Step::SampleExt],
    };
    let o = run(&empty);
    let [a, b, c] = *o.ext[0].value();
    assert_eq!(
        (*a.value(), *b.value(), *c.value()),
        (0, 0, 0),
        "the empty squeeze is documented as the un-permuted capacity; if it is \
         no longer zero the sponge's empty case changed"
    );
    // And the guard that makes it harmless: a statement tag first.
    let tagged = Script {
        name: "tagged",
        steps: &[
            Step::AbsorbBytes {
                seed: 0x71,
                len: 41,
            },
            Step::SampleExt,
        ],
    };
    let t = run(&tagged);
    let [a, b, c] = *t.ext[0].value();
    assert_ne!(
        (*a.value(), *b.value(), *c.value()),
        (0, 0, 0),
        "a challenge drawn after a statement absorb must not be the zero element"
    );
}

/// K3's own property, which no single pinned value can express: a squeeze
/// re-absorbs its output, so consecutive draws cannot repeat.
#[test]
fn consecutive_draws_never_repeat_because_a_squeeze_advances_the_chain() {
    let o = run(&K3_CHAIN);
    for i in 0..o.ext.len() {
        for j in (i + 1)..o.ext.len() {
            assert_ne!(
                o.ext[i], o.ext[j],
                "draws {i} and {j} are equal — the squeeze did not chain its \
                 output back in, and every draw after the first is a repeat"
            );
        }
    }
}
