-- [patched by patch_aeneas_math_types.py]
-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [math]: type definitions
import Aeneas
import Math.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace math

/-- Trait declaration: [core::fmt::UpperHex]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 1432:0-1432:32
    Name pattern: [core::fmt::UpperHex]
    Visibility: public -/
@[rust_trait "core::fmt::UpperHex"]
structure core.fmt.UpperHex (Self : Type) where
  fmt : Self → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 188:0-188:31
    Name pattern: [core::ops::arith::Sub]
    Visibility: public -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31
    Name pattern: [core::ops::arith::Mul]
    Visibility: public -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 460:0-460:31
    Name pattern: [core::ops::arith::Div]
    Visibility: public -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 690:0-690:19
    Name pattern: [core::ops::arith::Neg]
    Visibility: public -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- Trait declaration: [core::ops::arith::AddAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 768:0-768:37
    Name pattern: [core::ops::arith::AddAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::MulAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 901:0-901:37
    Name pattern: [core::ops::arith::MulAssign]
    Visibility: public -/
@[rust_trait "core::ops::arith::MulAssign"]
structure core.ops.arith.MulAssign (Self : Type) (Rhs : Type) where
  mul_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::bit::Shr]
    Source: '/rustc/library/core/src/ops/bit.rs', lines 584:0-584:31
    Name pattern: [core::ops::bit::Shr]
    Visibility: public -/
@[rust_trait "core::ops::bit::Shr"]
structure core.ops.bit.Shr (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  shr : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::bit::ShrAssign]
    Source: '/rustc/library/core/src/ops/bit.rs', lines 1026:0-1026:37
    Name pattern: [core::ops::bit::ShrAssign]
    Visibility: public -/
@[rust_trait "core::ops::bit::ShrAssign"]
structure core.ops.bit.ShrAssign (Self : Type) (Rhs : Type) where
  shr_assign : Self → Rhs → Result Self

/-- [core::str::pattern::SearchStep]
    Source: '/rustc/library/core/src/str/pattern.rs', lines 186:0-186:19
    Name pattern: [core::str::pattern::SearchStep]
    Visibility: public -/
@[discriminant isize, rust_type "core::str::pattern::SearchStep"]
inductive core.str.pattern.SearchStep where
| Match : Std.Usize → Std.Usize → core.str.pattern.SearchStep
| Reject : Std.Usize → Std.Usize → core.str.pattern.SearchStep
| Done : core.str.pattern.SearchStep

/-- Trait declaration: [core::str::pattern::Searcher]
    Source: '/rustc/library/core/src/str/pattern.rs', lines 213:0-213:29
    Name pattern: [core::str::pattern::Searcher]
    Visibility: public -/
@[rust_trait "core::str::pattern::Searcher"]
structure core.str.pattern.Searcher (Self : Type) where
  haystack : Self → Result Str
  next : Self → Result (core.str.pattern.SearchStep × Self)

/-- Trait declaration: [rand_core::RngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.6.4/src/lib.rs', lines 142:0-142:17
    Name pattern: [rand_core::RngCore]
    Visibility: public -/
@[rust_trait "rand_core::RngCore"]
structure rand_core.RngCore (Self : Type) where
  next_u32 : Self → Result (Std.U32 × Self)
  next_u64 : Self → Result (Std.U64 × Self)
  fill_bytes : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))
  try_fill_bytes : Self → Slice Std.U8 → Result ((core.result.Result Unit
    rand_core.error.Error) × Self × (Slice Std.U8))

/-- Trait declaration: [rand::rng::Rng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.8.5/src/rng.rs', lines 55:0-55:22
    Name pattern: [rand::rng::Rng]
    Visibility: public -/
@[rust_trait "rand::rng::Rng"] axiom rand.rng.Rng (Self : Type) : Type

/-- Trait declaration: [rand::rng::Fill]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.8.5/src/rng.rs', lines 314:0-314:14
    Name pattern: [rand::rng::Fill]
    Visibility: public -/
@[rust_trait "rand::rng::Fill"] axiom rand.rng.Fill (Self : Type) : Type

/-- [math::errors::ByteConversionError]
    Source: 'crypto/math/src/errors.rs', lines 2:0-6:1
    Visibility: public -/
@[discriminant isize]
inductive errors.ByteConversionError where
| FromBEBytesError : errors.ByteConversionError
| FromLEBytesError : errors.ByteConversionError
| ValueNotReduced : errors.ByteConversionError

/-- [math::errors::CreationError]
    Source: 'crypto/math/src/errors.rs', lines 9:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive errors.CreationError where
| InvalidHexString : errors.CreationError
| HexStringIsTooBig : errors.CreationError
| CanonicalOutOfRange : errors.CreationError
| EmptyString : errors.CreationError

/-- [math::errors::DeserializationError]
    Source: 'crypto/math/src/errors.rs', lines 17:0-22:1
    Visibility: public -/
@[discriminant isize]
inductive errors.DeserializationError where
| InvalidAmountOfBytes : errors.DeserializationError
| FieldFromBytesError : errors.DeserializationError
| PointerSizeError : errors.DeserializationError
| InvalidValue : errors.DeserializationError

/-- Trait declaration: [math::unsigned_integer::traits::IsUnsignedInteger]
    Source: 'crypto/math/src/unsigned_integer/traits.rs', lines 6:0-19:1
    Visibility: public -/
structure unsigned_integer.traits.IsUnsignedInteger (Self : Type) where
  coreopsbitShrSelfUsizeSelfInst : core.ops.bit.Shr Self Std.Usize Self
  coreopsbitShrAssignSelfUsizeInst : core.ops.bit.ShrAssign Self Std.Usize
  coreopsbitBitAndInst : core.ops.bit.BitAnd Self Self Self
  corecmpEqInst : core.cmp.Eq Self
  corecmpOrdInst : core.cmp.Ord Self
  coreconvertFromSelfU16Inst : core.convert.From Self Std.U16
  coremarkerCopyInst : core.marker.Copy Self
  corefmtDisplayInst : core.fmt.Display Self
  corefmtLowerHexInst : core.fmt.LowerHex Self
  corefmtUpperHexInst : core.fmt.UpperHex Self
  coreopsarithAddInst : core.ops.arith.Add Self Self Self

/-- Trait declaration: [math::traits::ByteConversion]
    Source: 'crypto/math/src/traits.rs', lines 5:0-34:1
    Visibility: public -/
structure traits.ByteConversion (Self : Type) where
  BYTE_LEN : Result Std.Usize
  to_bytes_be : Self → Result (alloc.vec.Vec Std.U8)
  to_bytes_le : Self → Result (alloc.vec.Vec Std.U8)
  from_bytes_be : Slice Std.U8 → Result (core.result.Result Self
    errors.ByteConversionError)
  from_bytes_le : Slice Std.U8 → Result (core.result.Result Self
    errors.ByteConversionError)
  write_bytes_be : Self → Slice Std.U8 → Result (Slice Std.U8)

/-- [math::field::errors::FieldError]
    Source: 'crypto/math/src/field/errors.rs', lines 2:0-8:1
    Visibility: public -/
@[discriminant isize]
inductive field.errors.FieldError where
| DivisionByZero : field.errors.FieldError
| RootOfUnityError : Std.U64 → field.errors.FieldError
| InvZeroError : field.errors.FieldError

/-- Trait declaration: [math::field::traits::IsField]
    Source: 'crypto/math/src/field/traits.rs', lines 99:0-189:1
    Visibility: public -/
structure field.traits.IsField (Self : Type) (Self_BaseType : Type) where
  corefmtDebugInst : core.fmt.Debug Self
  corecloneCloneInst : core.clone.Clone Self
  corecloneCloneBaseTypeInst : core.clone.Clone Self_BaseType
  corefmtDebugBaseTypeInst : core.fmt.Debug Self_BaseType
  traitsByteConversionInst : traits.ByteConversion Self_BaseType
  coredefaultDefaultInst : core.default.Default Self_BaseType
  add : Self_BaseType → Self_BaseType → Result Self_BaseType
  double : Self_BaseType → Result Self_BaseType
  mul : Self_BaseType → Self_BaseType → Result Self_BaseType
  square : Self_BaseType → Result Self_BaseType
  pow : forall {T : Type} (unsigned_integertraitsIsUnsignedIntegerInst :
    unsigned_integer.traits.IsUnsignedInteger T), Self_BaseType → T →
    Result Self_BaseType
  sub : Self_BaseType → Self_BaseType → Result Self_BaseType
  neg : Self_BaseType → Result Self_BaseType
  inv : Self_BaseType → Result (core.result.Result Self_BaseType
    field.errors.FieldError)
  div : Self_BaseType → Self_BaseType → Result (core.result.Result
    Self_BaseType field.errors.FieldError)
  eq : Self_BaseType → Self_BaseType → Result Bool
  zero : Result Self_BaseType
  one : Result Self_BaseType
  from_u64 : Std.U64 → Result Self_BaseType
  from_base_type : Self_BaseType → Result Self_BaseType

/-- [math::field::element::FieldElement]
    Source: 'crypto/math/src/field/element.rs', lines 50:0-52:1
    Visibility: public -/
structure field.element.FieldElement (F : Type) (Clause0_BaseType : Type) where
  value : Clause0_BaseType

/-- Trait declaration: [math::field::traits::IsFFTField]
    Source: 'crypto/math/src/field/traits.rs', lines 70:0-96:1
    Visibility: public -/
structure field.traits.IsFFTField (Self : Type) (Self_Clause0_BaseType : Type)
  where
  TWO_ADICITY : Result Std.U64
  TWO_ADIC_PRIMITVE_ROOT_OF_UNITY : Result Self_Clause0_BaseType
  IsFieldInst : field.traits.IsField Self Self_Clause0_BaseType
  field_name : Result Str
  get_primitive_root_of_unity : Std.U64 → Result (core.result.Result
    (field.element.FieldElement Self Self_Clause0_BaseType)
    field.errors.FieldError)

/-- Trait declaration: [math::field::traits::IsSubFieldOf]
    Source: 'crypto/math/src/field/traits.rs', lines 17:0-25:1
    Visibility: public -/
structure field.traits.IsSubFieldOf (Self : Type) (F : Type)
  (Self_Clause0_BaseType : Type) (Self_Clause1_BaseType : Type) where
  IsFieldInst : field.traits.IsField Self Self_Clause0_BaseType
  IsFieldClause1Inst : field.traits.IsField F Self_Clause1_BaseType
  mul : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    Self_Clause1_BaseType
  add : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    Self_Clause1_BaseType
  div : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    (core.result.Result Self_Clause1_BaseType field.errors.FieldError)
  sub : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    Self_Clause1_BaseType
  embed : Self_Clause0_BaseType → Result Self_Clause1_BaseType
  to_subfield_vec : Self_Clause1_BaseType → Result (alloc.vec.Vec
    Self_Clause0_BaseType)

/-- [math::fft::bowers_fft::LayerTwiddles]
    Source: 'crypto/math/src/fft/bowers_fft.rs', lines 437:0-440:1
    Visibility: public -/
structure fft.bowers_fft.LayerTwiddles (F : Type) (Clause0_BaseType : Type)
  where
  layers : alloc.vec.Vec (alloc.vec.Vec (field.element.FieldElement F
    Clause0_BaseType))

/-- [math::field::traits::IsFFTField::get_primitive_root_of_unity::closure]
    Source: 'crypto/math/src/field/traits.rs', lines 93:73-93:94 -/
@[reducible]
def field.traits.IsFFTField.get_primitive_root_of_unity.closure (Self : Type)
  (Clause0_Clause0_BaseType : Type) :=
Unit

/-- [math::fft::errors::FFTError]
    Source: 'crypto/math/src/fft/errors.rs', lines 6:0-13:1
    Visibility: public -/
@[discriminant isize]
inductive fft.errors.FFTError where
| RootOfUnityError : Std.U64 → fft.errors.FFTError
| InputError : Std.Usize → fft.errors.FFTError
| OrderError : Std.U64 → fft.errors.FFTError
| DomainSizeError : Std.Usize → fft.errors.FFTError
| InvalidCosetOffset : fft.errors.FFTError

/-- [math::field::traits::LegendreSymbol]
    Source: 'crypto/math/src/field/traits.rs', lines 198:0-202:1
    Visibility: public -/
@[discriminant isize]
inductive field.traits.LegendreSymbol where
| MinusOne : field.traits.LegendreSymbol
| Zero : field.traits.LegendreSymbol
| One : field.traits.LegendreSymbol

/-- Trait declaration: [math::field::traits::IsPrimeField]
    Source: 'crypto/math/src/field/traits.rs', lines 204:0-297:1
    Visibility: public -/
structure field.traits.IsPrimeField (Self : Type) (Self_CanonicalType : Type)
  (Self_Clause0_BaseType : Type) where
  IsFieldInst : field.traits.IsField Self Self_Clause0_BaseType
  unsigned_integertraitsIsUnsignedIntegerInst :
    unsigned_integer.traits.IsUnsignedInteger Self_CanonicalType
  canonical : Self_Clause0_BaseType → Result Self_CanonicalType
  modulus_minus_one : Result Self_CanonicalType
  from_hex : Str → Result (core.result.Result Self_Clause0_BaseType
    errors.CreationError)
  field_bit_size : Result Std.Usize
  legendre_symbol : Self_Clause0_BaseType → Result
    field.traits.LegendreSymbol
  sqrt : Self_Clause0_BaseType → Result (Option (Self_Clause0_BaseType ×
    Self_Clause0_BaseType))

/-- [math::field::element::{impl core::iter::traits::accum::Sum<math::field::element::FieldElement<F, Clause0_BaseType>> for math::field::element::FieldElement<F, Clause0_BaseType>}::sum::closure]
    Source: 'crypto/math/src/field/element.rs', lines 285:32-285:64 -/
@[reducible]
def field.element.SumFieldElementFieldElement.sum.closure (F : Type) (I : Type)
  (Clause0_BaseType : Type) :=
Unit

/-- [math::field::element::{math::field::element::FieldElement<F, Clause0_BaseType>}::from_hex_str::closure#1]
    Source: 'crypto/math/src/field/element.rs', lines 641:52-641:87 -/
@[reducible]
def field.element.FieldElement.from_hex_str.closure_1 (F : Type)
  (Clause0_BaseType : Type) (Clause2_CanonicalType : Type)
  (Clause2_Clause0_BaseType : Type) :=
Unit

/-- [math::field::element::{math::field::element::FieldElement<F, Clause0_BaseType>}::from_hex_str::closure]
    Source: 'crypto/math/src/field/element.rs', lines 639:57-639:92 -/
@[reducible]
def field.element.FieldElement.from_hex_str.closure (F : Type)
  (Clause0_BaseType : Type) (Clause2_CanonicalType : Type)
  (Clause2_Clause0_BaseType : Type) :=
Unit

/-- [math::field::traits::IsPrimeField::sqrt::closure]
    Source: 'crypto/math/src/field/traits.rs', lines 286:45-286:72 -/
@[reducible]
def field.traits.IsPrimeField.sqrt.closure (Self : Type) (Clause0_CanonicalType
  : Type) (Clause0_Clause0_BaseType : Type) :=
Unit

/-- [math::field::element::{math::field::element::FieldElement<F, Clause0_Clause0_BaseType>}::sqrt::closure]
    Source: 'crypto/math/src/field/element.rs', lines 664:18-664:81 -/
@[reducible]
def field.element.FieldElement.sqrt.closure (F : Type) (Clause0_CanonicalType :
  Type) (Clause0_Clause0_BaseType : Type) :=
Unit

/-- [math::field::goldilocks::GoldilocksField]
    Source: 'crypto/math/src/field/goldilocks.rs', lines 53:0-53:27
    Visibility: public -/
@[reducible]
def field.goldilocks.GoldilocksField := Unit

/-- [math::field::goldilocks::{impl math::traits::ByteConversion for math::field::element::FieldElement<math::field::goldilocks::GoldilocksField, u64>}::from_bytes_le::closure]
    Source: 'crypto/math/src/field/goldilocks.rs', lines 463:25-463:81 -/
@[reducible]
def field.goldilocks.ByteConversionFieldElementGoldilocksFieldU64.from_bytes_le.closure
  :=
Unit

/-- [math::traits::{impl math::traits::ByteConversion for u64}::from_bytes_le::closure]
    Source: 'crypto/math/src/traits.rs', lines 95:25-95:66 -/
@[reducible]
def traits.ByteConversionU64.from_bytes_le.closure := Unit

/-- [math::traits::{impl math::traits::ByteConversion for u64}::from_bytes_be::closure]
    Source: 'crypto/math/src/traits.rs', lines 81:25-81:66 -/
@[reducible]
def traits.ByteConversionU64.from_bytes_be.closure := Unit

/-- [math::field::goldilocks::{impl math::traits::ByteConversion for math::field::element::FieldElement<math::field::goldilocks::GoldilocksField, u64>}::from_bytes_be::closure]
    Source: 'crypto/math/src/field/goldilocks.rs', lines 448:25-448:81 -/
@[reducible]
def field.goldilocks.ByteConversionFieldElementGoldilocksFieldU64.from_bytes_be.closure
  :=
Unit

/-- [math::field::extensions_goldilocks::Degree2GoldilocksExtensionField]
    Source: 'crypto/math/src/field/extensions_goldilocks.rs', lines 102:0-102:43
    Visibility: public -/
@[reducible]
def field.extensions_goldilocks.Degree2GoldilocksExtensionField := Unit

/-- [math::field::extensions_goldilocks::Degree3GoldilocksExtensionField]
    Source: 'crypto/math/src/field/extensions_goldilocks.rs', lines 281:0-281:43
    Visibility: public -/
@[reducible]
def field.extensions_goldilocks.Degree3GoldilocksExtensionField := Unit

/-- Trait declaration: [math::traits::AsBytes]
    Source: 'crypto/math/src/traits.rs', lines 39:0-42:1
    Visibility: public -/
structure traits.AsBytes (Self : Type) where
  as_bytes : Self → Result (alloc.vec.Vec Std.U8)

/-- Trait declaration: [math::field::traits::HasDefaultTranscript]
    Source: 'crypto/math/src/field/traits.rs', lines 300:0-304:1
    Visibility: public -/
structure field.traits.HasDefaultTranscript (Self : Type)
  (Self_Clause0_BaseType : Type) where
  IsFieldInst : field.traits.IsField Self Self_Clause0_BaseType
  get_random_field_element_from_rng : forall {T1 : Type} (randrngRngInst :
    rand.rng.Rng T1), T1 → Result ((field.element.FieldElement Self
    Self_Clause0_BaseType) × T1)

/-- [math::field::goldilocks::{impl math::field::traits::IsPrimeField<u64, u64> for math::field::goldilocks::GoldilocksField}::from_hex::closure]
    Source: 'crypto/math/src/field/goldilocks.rs', lines 496:21-496:56 -/
@[reducible]
def field.goldilocks.IsPrimeFieldGoldilocksFieldU64U64.from_hex.closure := Unit

/-- [math::field::traits::RootsConfig]
    Source: 'crypto/math/src/field/traits.rs', lines 9:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive field.traits.RootsConfig where
| Natural : field.traits.RootsConfig
| NaturalInversed : field.traits.RootsConfig
| BitReverse : field.traits.RootsConfig
| BitReverseInversed : field.traits.RootsConfig

/-- [math::polynomial::Polynomial]
    Source: 'crypto/math/src/polynomial.rs', lines 13:0-15:1
    Visibility: public -/
structure polynomial.Polynomial (FE : Type) where
  coefficients : alloc.vec.Vec FE

/-- [math::polynomial::{math::polynomial::Polynomial<math::field::element::FieldElement<F, Clause0_BaseType>>}::evaluate::closure]
    Source: 'crypto/math/src/polynomial.rs', lines 59:40-61:13 -/
@[reducible]
def polynomial.PolynomialFieldElement.evaluate.closure (F : Type) (E : Type)
  (Clause0_BaseType : Type) (Clause1_BaseType : Type) (Clause2_Clause0_BaseType
  : Type) (Clause2_Clause1_BaseType : Type) :=
  field.element.FieldElement E Clause1_BaseType

/-- [math::polynomial::{math::polynomial::Polynomial<math::field::element::FieldElement<F, Clause0_BaseType>>}::scale_coeffs::closure]
    Source: 'crypto/math/src/polynomial.rs', lines 129:17-129:39 -/
@[reducible]
def polynomial.PolynomialFieldElement.scale_coeffs.closure (F : Type)
  (Clause0_BaseType : Type) :=
  field.element.FieldElement F Clause0_BaseType

/-- [math::polynomial::barycentric_inv_denoms::closure]
    Source: 'crypto/math/src/polynomial.rs', lines 206:67-206:79 -/
@[reducible]
def polynomial.barycentric_inv_denoms.closure (F : Type) (E : Type)
  (Clause0_Clause0_BaseType : Type) (Clause0_Clause1_BaseType : Type)
  (Clause1_BaseType : Type) :=
  field.element.FieldElement E Clause1_BaseType

/-- [math::polynomial::{math::polynomial::Polynomial<math::field::element::FieldElement<E, Clause0_BaseType>>}::interpolate_offset_fft::closure]
    Source: 'crypto/math/src/polynomial.rs', lines 374:46-374:78 -/
@[reducible]
def polynomial.PolynomialFieldElement.interpolate_offset_fft.closure (E : Type)
  (F : Type) (Clause0_BaseType : Type) (Clause1_Clause0_BaseType : Type)
  (Clause2_Clause0_BaseType : Type) (Clause2_Clause1_BaseType : Type) :=
Unit

/-- Trait declaration: [math::spill_safe::SpillSafe]
    Source: 'crypto/math/src/spill_safe.rs', lines 17:0-17:45
    Visibility: public -/
structure spill_safe.SpillSafe (Self : Type) where
  coremarkerCopyInst : core.marker.Copy Self

/-- Trait declaration: [math::traits::Deserializable]
    Source: 'crypto/math/src/traits.rs', lines 101:0-105:1
    Visibility: public -/
structure traits.Deserializable (Self : Type) where
  deserialize : Slice Std.U8 → Result (core.result.Result Self
    errors.DeserializationError)

end math
