-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [math]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::ops::range::RangeInclusive]
    Source: '/rustc/library/core/src/ops/range.rs', lines 357:0-357:30
    Name pattern: [core::ops::range::RangeInclusive]
    Visibility: public -/
@[rust_type "core::ops::range::RangeInclusive"]
axiom core.ops.range.RangeInclusive (Idx : Type) : Type

/-- [core::num::error::ParseIntError]
    Source: '/rustc/library/core/src/num/error.rs', lines 74:0-74:24
    Name pattern: [core::num::error::ParseIntError]
    Visibility: public -/
@[rust_type "core::num::error::ParseIntError"]
axiom core.num.error.ParseIntError : Type

/-- [core::str::pattern::StrSearcher]
    Source: '/rustc/library/core/src/str/pattern.rs', lines 1064:0-1064:30
    Name pattern: [core::str::pattern::StrSearcher]
    Visibility: public -/
@[rust_type "core::str::pattern::StrSearcher"]
axiom core.str.pattern.StrSearcher : Type

/-- [num_bigint::biguint::BigUint]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-bigint-0.4.6/src/biguint.rs', lines 34:0-34:18
    Name pattern: [num_bigint::biguint::BigUint]
    Visibility: public -/
@[rust_type "num_bigint::biguint::BigUint"]
axiom num_bigint.biguint.BigUint : Type

/-- [num_bigint::ParseBigIntError]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/num-bigint-0.4.6/src/lib.rs', lines 129:0-129:27
    Name pattern: [num_bigint::ParseBigIntError]
    Visibility: public -/
@[rust_type "num_bigint::ParseBigIntError"]
axiom num_bigint.ParseBigIntError : Type

/-- [rand_core::error::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.6.4/src/error.rs', lines 21:0-21:16
    Name pattern: [rand_core::error::Error]
    Visibility: public -/
@[rust_type "rand_core::error::Error"]
axiom rand_core.error.Error : Type

