name: 'Setup Rust Environment'
description: 'Sets up Rust and caches dependencies'
runs:
  using: "composite"
  steps:

    - name: Free Disk Space
      uses: ./.github/actions/free-disk

    - name: Restore Rust toolchain cache
      id: rust-cache
      uses: actions/cache@v4
      with:
        path: /home/runner/lambda_rust
        key: rust-src-${{ runner.os }}-149354

    - name: Install Rust
      if: steps.rust-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        cd $HOME
        git clone https://github.com/rust-lang/rust.git
        cd rust
        cat <<'EOF' > bootstrap.toml
        # See bootstrap.example.toml for documentation of available options
        #
        profile = "dist"  # Includes one of the default files in src/bootstrap/defaults
        change-id = 149354
        rust.lld = true
        [build]
        docs = false
        EOF
        ./x.py build --stage 1
        DESTDIR="$HOME/lambda_rust" ./x.py install --stage 1
    
    - name: Add Rust to PATH
      shell: bash
      run: echo "$HOME/lambda_rust/usr/local/bin" >> $GITHUB_PATH
