name: 'Setup Rust Environment'
description: 'Sets up Rust and caches dependencies'
runs:
  using: "composite"
  steps:

    - name: Free Disk Space
      uses: ./.github/actions/free-disk

    - name: Download Rust
      shell: bash
      run: |
        cd $HOME
        mkdir lambda_rust
        cd lambda_rust
        wget https://lambda.alignedlayer.com/my_rust.tar.gz 
        tar -xzvf my_rust.tar.gz
        rm my_rust.tar.gz
    
    - name: Add Rust to PATH
      shell: bash
      run: echo "$HOME/lambda_rust/usr/local/bin" >> $GITHUB_PATH
