name: 'Setup Rust Environment'
description: 'Sets up Rust and caches dependencies'
runs:
  using: "composite"
  steps:

    - name: Free Disk Space
      uses: ./.github/actions/free-disk

    - name: Download Rust
      shell: bash
      run: |
        cd $HOME
        wget https://lambda.alignedlayer.com/lambda_rust.tar.gz 
        tar -xzvf lambda_rust.tar.gz
        rm lambda_rust.tar.gz
    
    - name: Add Rust to PATH
      shell: bash
      run: echo "$HOME/lambda_rust/usr/local/bin" >> $GITHUB_PATH
