//! KECCAK_RC: Precomputed round constant lookup table for Keccak-f[1600].
//!
//! 24 rows (one per round), padded to 32. Each row maps a round index to its
//! 8-byte round constant. The round chip looks up `(round) → rc[8]` via the
//! `KeccakRc` bus.
//!
//! Follows the BITWISE preprocessed-table pattern: precomputed columns are
//! committed via a static lookup table (with recompute as fallback for
//! `ProofOptions` not covered by the static table).

use math::polynomial::Polynomial;
use stark::config::Commitment;
use stark::lookup::{BusInteraction, BusValue, Multiplicity, Packing};
use stark::proof::options::ProofOptions;
use stark::prover::evaluate_polynomial_on_lde_domain;
use stark::trace::TraceTable;

use executor::vm::instruction::execution::KECCAK_RC;

use super::types::{BusId, FE, GoldilocksExtension, GoldilocksField, VmTable};

// =========================================================================
// Column indices
// =========================================================================

pub mod cols {
    /// Round index (0..23)
    pub const ROUND: usize = 0;
    /// RC bytes [0..7] — 8 bytes of the round constant (little-endian)
    pub const RC: usize = 1;
    pub const RC_END: usize = RC + 8; // = 9
    /// Multiplicity (how many times this row is looked up)
    pub const MU: usize = 9;

    pub const NUM_COLUMNS: usize = 10;
}

/// Number of precomputed columns (everything except MU).
pub const NUM_PRECOMPUTED_COLS: usize = 9;

/// Number of real rows (one per keccak round).
pub const NUM_REAL_ROWS: usize = 24;

/// Number of rows in the trace (padded to next power of 2).
pub const NUM_ROWS: usize = 32;

/// Whether this table is preprocessed.
pub const fn is_preprocessed() -> bool {
    true
}

/// Generate one precomputed row: [round, rc_byte0, ..., rc_byte7].
pub const fn generate_row(round: usize) -> [u64; NUM_PRECOMPUTED_COLS] {
    let rc_val = if round < 24 { KECCAK_RC[round] } else { 0 };
    [
        round as u64,
        rc_val & 0xFF,
        (rc_val >> 8) & 0xFF,
        (rc_val >> 16) & 0xFF,
        (rc_val >> 24) & 0xFF,
        (rc_val >> 32) & 0xFF,
        (rc_val >> 40) & 0xFF,
        (rc_val >> 48) & 0xFF,
        (rc_val >> 56) & 0xFF,
    ]
}

// =========================================================================
// Preprocessed commitment
// =========================================================================

/// Returns the static KECCAK_RC preprocessed commitment for `blowup_factor`,
/// or `None` if no value is shipped for it. Values were generated by the
/// `compute_static_commitments` binary at the project's standard
/// `coset_offset = 3` (the value every in-tree `ProofOptions` constructor
/// pins) and pinned by `keccak_rc_static_matches_recompute_*` tests so any
/// drift in the AIR or FFT pipeline is caught at test time. The verifier
/// reads these from its compiled binary — no input data is trusted.
///
/// # Regenerating
///
/// Only regenerate these match arms after a *deliberate, reviewed* change
/// to the KECCAK_RC table layout, the AIR's preprocessed column count, or
/// the FFT / LDE / Merkle pipeline. Run:
///
/// ```text
/// cargo run --bin compute_static_commitments --release
/// ```
///
/// and paste the printed match arms over the ones below.
///
/// **If a drift test failed, do not regenerate first.** The drift tests
/// exist to force a human to ask "why did this change?" before the new
/// bytes get blessed. Re-pasting on a drift failure silently launders an
/// unintended table change into the verifier's compiled-in trust anchor.
#[cfg(not(feature = "cuda"))]
fn static_commitment(blowup_factor: u8) -> Option<Commitment> {
    match blowup_factor {
        2 => Some([
            0x00, 0x0c, 0x3a, 0xe9, 0x22, 0x2f, 0x88, 0xc5, 0x3f, 0xb9, 0x75, 0xc2, 0xa5, 0x65,
            0x88, 0x23, 0xcf, 0xe1, 0x2b, 0x38, 0xa3, 0x60, 0xca, 0xb5, 0x22, 0x55, 0xd8, 0xf7,
            0x4c, 0xbe, 0xbf, 0x08,
        ]),
        4 => Some([
            0xac, 0xab, 0x8e, 0x85, 0xf7, 0x25, 0x02, 0x25, 0xdf, 0xbb, 0xe0, 0xeb, 0x2f, 0x03,
            0xad, 0xf4, 0xeb, 0xc4, 0xa2, 0x95, 0x17, 0x19, 0x55, 0x18, 0xec, 0x0e, 0x4e, 0xa8,
            0x6f, 0x0c, 0x33, 0x53,
        ]),
        8 => Some([
            0x79, 0x01, 0xf1, 0x22, 0xb8, 0x73, 0xef, 0xb4, 0x9a, 0x96, 0x9e, 0x7e, 0x73, 0xd0,
            0xdc, 0x89, 0x41, 0x99, 0xbe, 0xce, 0x07, 0x7e, 0xa7, 0xd2, 0x50, 0x70, 0x4b, 0xd3,
            0x98, 0x1c, 0x9f, 0xab,
        ]),
        _ => None,
    }
}

/// R4's keccak arm: under `cuda` the machine commits with `KeccakStarkHash`
/// (`stark::config` pins the aliases there), so its static pins are the
/// pre-flip keccak constants — restored verbatim from the flip re-bless's
/// parent. One arm per configuration: a single set would make one of the two
/// builds reject every honest proof with PrecomputedCommitmentMismatch at
/// prove time, which is exactly how the gap was found on a GPU box.
#[cfg(feature = "cuda")]
fn static_commitment(blowup_factor: u8) -> Option<Commitment> {
    match blowup_factor {
        2 => Some([
            0xab, 0x7a, 0xad, 0xf5, 0xbf, 0xa2, 0xd5, 0x5c, 0x29, 0x83, 0x83, 0xe6, 0x2e, 0x47,
            0xa0, 0xa5, 0x22, 0xf9, 0x57, 0x89, 0x5a, 0x5c, 0xbb, 0x1f, 0x34, 0xbc, 0x21, 0x72,
            0xa9, 0x2c, 0x85, 0xe3,
        ]),
        4 => Some([
            0xfb, 0x42, 0x58, 0x76, 0xf4, 0x30, 0x98, 0x04, 0xef, 0x8c, 0x4e, 0x65, 0xf7, 0x1a,
            0x29, 0x03, 0xd2, 0xc6, 0x12, 0x0d, 0x18, 0xe1, 0x28, 0x6e, 0x70, 0xeb, 0xa8, 0x11,
            0x3c, 0x3e, 0xe1, 0xdd,
        ]),
        8 => Some([
            0x9f, 0x91, 0xaf, 0xb6, 0x5b, 0x75, 0x1e, 0xfb, 0x73, 0x93, 0x2c, 0xc4, 0xa8, 0xe1,
            0xb5, 0x21, 0x91, 0x5d, 0x6a, 0x19, 0x2e, 0x1d, 0xa8, 0x80, 0x21, 0x1f, 0x36, 0x76,
            0x9b, 0x8e, 0x3d, 0xb6,
        ]),
        _ => None,
    }
}

/// Exposed for the `compute_static_commitments` binary and the
/// drift-detection tests in `static_commitments_tests`. Production callers
/// should go through [`preprocessed_commitment`] so the static const-table
/// shortcut is used when applicable.
#[doc(hidden)]
pub fn compute_preprocessed_commitment(options: &ProofOptions) -> Commitment {
    // Generate precomputed columns
    let mut columns: Vec<Vec<FE>> = (0..NUM_PRECOMPUTED_COLS)
        .map(|_| Vec::with_capacity(NUM_ROWS))
        .collect();
    for idx in 0..NUM_ROWS {
        let row = generate_row(idx);
        for (col_idx, &value) in row.iter().enumerate() {
            columns[col_idx].push(FE::from(value));
        }
    }

    // Interpolate each column to a polynomial
    let polys: Vec<Polynomial<FE>> = columns
        .iter()
        .map(|col| {
            Polynomial::interpolate_fft::<GoldilocksField>(col)
                .expect("FFT interpolation failed for keccak_rc column")
        })
        .collect();

    // Evaluate on LDE domain
    let blowup_factor = options.blowup_factor as usize;
    let coset_offset = FE::from(options.coset_offset);
    let lde_columns: Vec<Vec<FE>> = polys
        .iter()
        .map(|poly| {
            evaluate_polynomial_on_lde_domain(poly, blowup_factor, NUM_ROWS, &coset_offset)
                .expect("LDE evaluation failed for keccak_rc polynomial")
        })
        .collect();

    // ★ Through the LFM commit helper, which commits under the BLOCK PATH's pin
    // rather than `stark`'s default aliases. This root is a PREPROCESSED
    // commitment the block path's verifier absorbs, so it has to be built with
    // the hash that path commits under — on a branch that pins an algebraic
    // hash, a root left on the alias would be the one BLAKE3 artifact in an RPO
    // proof, and it would fail as a root nothing reconstructs.
    crate::lfm::commit::commit_lde_columns(&lde_columns)
}

/// Returns the preprocessed commitment for the keccak_rc table.
///
/// Looks up `blowup_factor` via [`static_commitment`] when `coset_offset == 3`
/// (the value every in-tree `ProofOptions` constructor pins, and the offset
/// the static bytes were generated for); on miss — either a non-3 coset or a
/// `blowup_factor` outside `STATIC_BLOWUP_FACTORS` — recomputes from scratch.
#[inline]
pub fn preprocessed_commitment(options: &ProofOptions) -> Commitment {
    if options.coset_offset == 3
        && let Some(commitment) = static_commitment(options.blowup_factor)
    {
        return commitment;
    }
    log::warn!(
        "keccak_rc preprocessed commitment not static for (blowup={}, coset={}); \
         falling back to recompute. Add a match arm to `static_commitment` by running \
         `cargo run --bin compute_static_commitments --release`.",
        options.blowup_factor,
        options.coset_offset,
    );
    compute_preprocessed_commitment(options)
}

// =========================================================================
// Trace generation
// =========================================================================

/// Generate the KECCAK_RC trace table.
///
/// All precomputed columns are filled; MU is initialized to zero and must be
/// updated via `update_multiplicities` after all round-chip lookups are known.
pub fn generate_keccak_rc_trace() -> TraceTable<GoldilocksField, GoldilocksExtension> {
    let mut trace = TraceTable::new_main(
        crate::tables::types::zeroed_fe_vec(NUM_ROWS * cols::NUM_COLUMNS),
        cols::NUM_COLUMNS,
        1,
    );
    let table = &mut trace.main_table;

    for idx in 0..NUM_ROWS {
        let row = generate_row(idx);
        for (col_idx, &value) in row.iter().enumerate() {
            table.set_u64(idx, col_idx, value);
        }
        // MU = 0 (will be updated later)
    }

    trace
}

/// Increment MU for each round lookup.
///
/// Called after the round chip's trace is generated. Each keccak permutation
/// call produces 24 round lookups (one per round), so each round row's MU
/// equals the number of keccak operations.
pub fn update_multiplicities(
    trace: &mut TraceTable<GoldilocksField, GoldilocksExtension>,
    num_keccak_ops: usize,
) {
    for round in 0..NUM_REAL_ROWS {
        trace
            .main_table
            .set_u64(round, cols::MU, num_keccak_ops as u64);
    }
}

// =========================================================================
// Bus interactions
// =========================================================================

/// Single receiver on the KeccakRc bus.
///
/// Format: [round(Direct), rc[0](Direct), ..., rc[7](Direct)]
pub fn bus_interactions() -> Vec<BusInteraction> {
    let mut values = vec![BusValue::Packed {
        start_column: cols::ROUND,
        packing: Packing::Direct,
    }];
    for i in 0..8 {
        values.push(BusValue::Packed {
            start_column: cols::RC + i,
            packing: Packing::Direct,
        });
    }

    vec![BusInteraction::receiver(
        BusId::KeccakRc,
        Multiplicity::Column(cols::MU),
        values,
    )]
}
