//! KECCAK_RC: Precomputed round constant lookup table for Keccak-f[1600].
//!
//! 24 rows (one per round), padded to 32. Each row maps a round index to its
//! 8-byte round constant. The round chip looks up `(round) → rc[8]` via the
//! `KeccakRc` bus.
//!
//! Follows the BITWISE preprocessed-table pattern: precomputed columns are
//! committed via a static lookup table (with recompute as fallback for
//! `ProofOptions` not covered by the static table).

use math::fft::bit_reversing::in_place_bit_reverse_permute;
use math::field::element::FieldElement;
use math::polynomial::Polynomial;
use stark::config::{BatchedMerkleTree, Commitment};
use stark::lookup::{BusInteraction, BusValue, Multiplicity, Packing};
use stark::proof::options::ProofOptions;
use stark::prover::evaluate_polynomial_on_lde_domain;
use stark::trace::{TraceTable, columns2rows};

use executor::vm::instruction::execution::KECCAK_RC;

use super::types::{BusId, FE, GoldilocksExtension, GoldilocksField};

// =========================================================================
// Column indices
// =========================================================================

pub mod cols {
    /// Round index (0..23)
    pub const ROUND: usize = 0;
    /// RC bytes [0..7] — 8 bytes of the round constant (little-endian)
    pub const RC: usize = 1;
    pub const RC_END: usize = RC + 8; // = 9
    /// Multiplicity (how many times this row is looked up)
    pub const MU: usize = 9;

    pub const NUM_COLUMNS: usize = 10;
}

/// Number of precomputed columns (everything except MU).
pub const NUM_PRECOMPUTED_COLS: usize = 9;

/// Number of real rows (one per keccak round).
pub const NUM_REAL_ROWS: usize = 24;

/// Number of rows in the trace (padded to next power of 2).
pub const NUM_ROWS: usize = 32;

/// Whether this table is preprocessed.
pub const fn is_preprocessed() -> bool {
    true
}

/// Generate one precomputed row: [round, rc_byte0, ..., rc_byte7].
pub const fn generate_row(round: usize) -> [u64; NUM_PRECOMPUTED_COLS] {
    let rc_val = if round < 24 { KECCAK_RC[round] } else { 0 };
    [
        round as u64,
        rc_val & 0xFF,
        (rc_val >> 8) & 0xFF,
        (rc_val >> 16) & 0xFF,
        (rc_val >> 24) & 0xFF,
        (rc_val >> 32) & 0xFF,
        (rc_val >> 40) & 0xFF,
        (rc_val >> 48) & 0xFF,
        (rc_val >> 56) & 0xFF,
    ]
}

// =========================================================================
// Preprocessed commitment
// =========================================================================

/// Returns the static KECCAK_RC preprocessed commitment for `blowup_factor`,
/// or `None` if no value is shipped for it. Values were generated by the
/// `compute_static_commitments` binary at the project's standard
/// `coset_offset = 3` (the value every in-tree `ProofOptions` constructor
/// pins) and pinned by `keccak_rc_static_matches_recompute_*` tests so any
/// drift in the AIR or FFT pipeline is caught at test time. The verifier
/// reads these from its compiled binary — no input data is trusted.
///
/// # Regenerating
///
/// Only regenerate these match arms after a *deliberate, reviewed* change
/// to the KECCAK_RC table layout, the AIR's preprocessed column count, or
/// the FFT / LDE / Merkle pipeline. Run:
///
/// ```text
/// cargo run --bin compute_static_commitments --release
/// ```
///
/// and paste the printed match arms over the ones below.
///
/// **If a drift test failed, do not regenerate first.** The drift tests
/// exist to force a human to ask "why did this change?" before the new
/// bytes get blessed. Re-pasting on a drift failure silently launders an
/// unintended table change into the verifier's compiled-in trust anchor.
fn static_commitment(blowup_factor: u8) -> Option<Commitment> {
    match blowup_factor {
        2 => Some([
            0xe8, 0x06, 0x8b, 0xb2, 0xbd, 0x3d, 0x80, 0xf3, 0x92, 0x95, 0x31, 0x1a, 0xfd, 0x55,
            0xba, 0x12, 0x3f, 0x76, 0xeb, 0x44, 0x32, 0x57, 0x9d, 0xb7, 0x7f, 0x1e, 0x63, 0xb4,
            0x98, 0xb5, 0xb0, 0xb7,
        ]),
        4 => Some([
            0xa9, 0xfb, 0xc9, 0x15, 0x1c, 0x22, 0x75, 0xe7, 0x56, 0xeb, 0x6d, 0xf9, 0xfe, 0x83,
            0x2a, 0xb1, 0xa7, 0x1a, 0x20, 0x71, 0x9b, 0x0c, 0xff, 0x6b, 0x3f, 0x57, 0xc6, 0x84,
            0x3e, 0xbf, 0xc8, 0xaa,
        ]),
        8 => Some([
            0x5c, 0x30, 0xf6, 0xa0, 0xcf, 0x78, 0x43, 0x15, 0x5b, 0x5d, 0x18, 0x34, 0x44, 0xba,
            0x81, 0x9a, 0x64, 0x05, 0x5c, 0x79, 0x26, 0x18, 0x09, 0x24, 0x6b, 0xa2, 0x3f, 0x5f,
            0x77, 0x09, 0xd5, 0xfc,
        ]),
        _ => None,
    }
}

/// Exposed for the `compute_static_commitments` binary and the
/// drift-detection tests in `static_commitments_tests`. Production callers
/// should go through [`preprocessed_commitment`] so the static const-table
/// shortcut is used when applicable.
#[doc(hidden)]
pub fn compute_preprocessed_commitment(options: &ProofOptions) -> Commitment {
    // Generate precomputed columns
    let mut columns: Vec<Vec<FE>> = (0..NUM_PRECOMPUTED_COLS)
        .map(|_| Vec::with_capacity(NUM_ROWS))
        .collect();
    for idx in 0..NUM_ROWS {
        let row = generate_row(idx);
        for (col_idx, &value) in row.iter().enumerate() {
            columns[col_idx].push(FE::from(value));
        }
    }

    // Interpolate each column to a polynomial
    let polys: Vec<Polynomial<FE>> = columns
        .iter()
        .map(|col| {
            Polynomial::interpolate_fft::<GoldilocksField>(col)
                .expect("FFT interpolation failed for keccak_rc column")
        })
        .collect();

    // Evaluate on LDE domain
    let blowup_factor = options.blowup_factor as usize;
    let coset_offset = FE::from(options.coset_offset);
    let mut lde_columns: Vec<Vec<FE>> = polys
        .iter()
        .map(|poly| {
            evaluate_polynomial_on_lde_domain(poly, blowup_factor, NUM_ROWS, &coset_offset)
                .expect("LDE evaluation failed for keccak_rc polynomial")
        })
        .collect();

    // Bit-reverse permute
    for col in lde_columns.iter_mut() {
        in_place_bit_reverse_permute(col);
    }

    // Build Merkle tree
    let lde_rows = columns2rows(lde_columns);
    let tree = BatchedMerkleTree::<GoldilocksField>::build(&lde_rows)
        .expect("Failed to build Merkle tree for keccak_rc LDE");

    tree.root
}

/// Returns the preprocessed commitment for the keccak_rc table.
///
/// Looks up `blowup_factor` via [`static_commitment`] when `coset_offset == 3`
/// (the value every in-tree `ProofOptions` constructor pins, and the offset
/// the static bytes were generated for); on miss — either a non-3 coset or a
/// `blowup_factor` outside `STATIC_BLOWUP_FACTORS` — recomputes from scratch.
#[inline]
pub fn preprocessed_commitment(options: &ProofOptions) -> Commitment {
    if options.coset_offset == 3
        && let Some(commitment) = static_commitment(options.blowup_factor)
    {
        return commitment;
    }
    log::warn!(
        "keccak_rc preprocessed commitment not static for (blowup={}, coset={}); \
         falling back to recompute. Add a match arm to `static_commitment` by running \
         `cargo run --bin compute_static_commitments --release`.",
        options.blowup_factor,
        options.coset_offset,
    );
    compute_preprocessed_commitment(options)
}

// =========================================================================
// Trace generation
// =========================================================================

/// Generate the KECCAK_RC trace table.
///
/// All precomputed columns are filled; MU is initialized to zero and must be
/// updated via `update_multiplicities` after all round-chip lookups are known.
pub fn generate_keccak_rc_trace() -> TraceTable<GoldilocksField, GoldilocksExtension> {
    let mut data = vec![FE::zero(); NUM_ROWS * cols::NUM_COLUMNS];

    for idx in 0..NUM_ROWS {
        let base = idx * cols::NUM_COLUMNS;
        let row = generate_row(idx);
        for (col_idx, &value) in row.iter().enumerate() {
            data[base + col_idx] = FE::from(value);
        }
        // MU = 0 (will be updated later)
    }

    TraceTable::new_main(data, cols::NUM_COLUMNS, 1)
}

/// Increment MU for each round lookup.
///
/// Called after the round chip's trace is generated. Each keccak permutation
/// call produces 24 round lookups (one per round), so each round row's MU
/// equals the number of keccak operations.
pub fn update_multiplicities(
    trace: &mut TraceTable<GoldilocksField, GoldilocksExtension>,
    num_keccak_ops: usize,
) {
    let mu = FieldElement::from(num_keccak_ops as u64);
    for round in 0..NUM_REAL_ROWS {
        trace.set_main(round, cols::MU, mu);
    }
}

// =========================================================================
// Bus interactions
// =========================================================================

/// Single receiver on the KeccakRc bus.
///
/// Format: [round(Direct), rc[0](Direct), ..., rc[7](Direct)]
pub fn bus_interactions() -> Vec<BusInteraction> {
    let mut values = vec![BusValue::Packed {
        start_column: cols::ROUND,
        packing: Packing::Direct,
    }];
    for i in 0..8 {
        values.push(BusValue::Packed {
            start_column: cols::RC + i,
            packing: Packing::Direct,
        });
    }

    vec![BusInteraction::receiver(
        BusId::KeccakRc,
        Multiplicity::Column(cols::MU),
        values,
    )]
}
