//! SHA256_K: verifier-committed 64-round constant table.
use super::{
    sha256_common::*,
    types::{BusId, FE, GoldilocksExtension, GoldilocksField},
};
use math::polynomial::Polynomial;
use stark::commitment::{ROWS_PER_LEAF, commit_bit_reversed};
use stark::prover::evaluate_polynomial_on_lde_domain;
use stark::{
    config::Commitment, lookup::BusInteraction, proof::options::ProofOptions, trace::TraceTable,
};
pub const WIDTH: usize = 3;
/// One row per round constant. Already a power of two, so the main trace and
/// the preprocessed columns cover the same domain with no padding row.
pub const NUM_ROWS: usize = 64;
/// Columns 0 and 1 (round index, constant) are the preprocessed pair; column 2
/// is the prover's multiplicity.
pub const NUM_PRECOMPUTED_COLS: usize = 2;
pub fn generate(n: usize) -> TraceTable<GoldilocksField, GoldilocksExtension> {
    trace(
        (0..NUM_ROWS)
            .map(|i| vec![i as u64, executor::sha256::K[i] as u64, n as u64])
            .collect(),
        WIDTH,
    )
}
pub fn bus_interactions() -> Vec<BusInteraction> {
    vec![recv(BusId::ShaK, 2, vec![col(0), col(1)])]
}

/// Returns the static SHA256_K preprocessed commitment for `blowup_factor`, or
/// `None` if no value is shipped for it. Values were generated by the
/// `compute_static_commitments` binary at the project's standard
/// `coset_offset = 3` and are pinned by the `sha256_k_static_matches_recompute_*`
/// tests so any drift in the AIR or FFT pipeline is caught at test time. The
/// verifier reads these from its compiled binary — no input data is trusted,
/// and the recursion guest does not pay an FFT and a Merkle commit to rebuild
/// them on every verification.
///
/// # Regenerating
///
/// Only regenerate these match arms after a *deliberate, reviewed* change to
/// the SHA256_K table layout, the AIR's preprocessed column count, or the FFT /
/// LDE / Merkle pipeline. Run:
///
/// ```text
/// cargo run --bin compute_static_commitments --release
/// ```
///
/// and paste the printed match arms over the ones below.
///
/// **If a drift test failed, do not regenerate first.** Re-pasting on a drift
/// failure silently launders an unintended table change into the verifier's
/// compiled-in trust anchor.
fn static_commitment(blowup_factor: u8) -> Option<Commitment> {
    match blowup_factor {
        2 => Some([
            0xa1, 0xff, 0x3c, 0x73, 0xac, 0xd6, 0x18, 0x9d, 0x56, 0x2e, 0x9e, 0x06, 0x8c, 0xf9,
            0x07, 0x8c, 0xcf, 0x41, 0x5e, 0xe3, 0x7f, 0x69, 0xc5, 0x74, 0xe9, 0x79, 0x39, 0x66,
            0x4b, 0x9f, 0x0a, 0xdf,
        ]),
        4 => Some([
            0x4b, 0x87, 0xa2, 0xff, 0x80, 0xd3, 0x4a, 0x1c, 0x2f, 0xb1, 0x3a, 0x55, 0x14, 0xdf,
            0x82, 0x41, 0x3a, 0x2b, 0x3a, 0x86, 0xb7, 0xa8, 0x74, 0xa9, 0xa8, 0xd8, 0xce, 0x12,
            0xa1, 0xf2, 0x09, 0xe3,
        ]),
        8 => Some([
            0x86, 0x11, 0x6e, 0xf4, 0x85, 0xec, 0xe6, 0x3d, 0x22, 0xf0, 0x5d, 0x2f, 0x10, 0x6b,
            0x27, 0xa4, 0x58, 0xeb, 0x9f, 0x6b, 0xc1, 0x90, 0x8c, 0x5a, 0xa2, 0x22, 0x28, 0x2e,
            0x8d, 0x2b, 0x9e, 0xfe,
        ]),
        _ => None,
    }
}

/// Computes the Merkle commitment over the SHA256_K round-constant columns.
///
/// Exposed for the `compute_static_commitments` binary and the drift-detection
/// tests in `static_commitments_tests`. Production callers should go through
/// [`preprocessed_commitment`] so the static const-table shortcut is used.
#[doc(hidden)]
pub fn compute_preprocessed_commitment(options: &ProofOptions) -> Commitment {
    let columns: Vec<Vec<FE>> = vec![
        (0..NUM_ROWS).map(|i| FE::from(i as u64)).collect(),
        executor::sha256::K
            .iter()
            .map(|k| FE::from(*k as u64))
            .collect(),
    ];
    let polys: Vec<_> = columns
        .iter()
        .map(|c| {
            Polynomial::interpolate_fft::<GoldilocksField>(c)
                .expect("FFT interpolation failed for sha256_k column")
        })
        .collect();
    let lde: Vec<_> = polys
        .iter()
        .map(|p| {
            evaluate_polynomial_on_lde_domain(
                p,
                options.blowup_factor as usize,
                NUM_ROWS,
                &FE::from(options.coset_offset),
            )
            .expect("LDE evaluation failed for sha256_k polynomial")
        })
        .collect();
    commit_bit_reversed(&lde, ROWS_PER_LEAF)
        .expect("Failed to build Merkle tree for sha256_k LDE")
        .1
}

/// Returns the preprocessed commitment for the SHA256_K table.
///
/// Looks up `blowup_factor` via [`static_commitment`] when `coset_offset == 3`
/// (the value every in-tree `ProofOptions` constructor pins, and the offset the
/// static bytes were generated for); on miss — either a non-3 coset or a
/// `blowup_factor` outside `STATIC_BLOWUP_FACTORS` — recomputes from scratch.
#[inline]
pub fn preprocessed_commitment(options: &ProofOptions) -> Commitment {
    if options.coset_offset == 3
        && let Some(commitment) = static_commitment(options.blowup_factor)
    {
        return commitment;
    }
    log::warn!(
        "sha256_k preprocessed commitment not static for (blowup={}, coset={}); \
         falling back to recompute. Add a match arm to `static_commitment` by running \
         `cargo run --bin compute_static_commitments --release`.",
        options.blowup_factor,
        options.coset_offset,
    );
    compute_preprocessed_commitment(options)
}
