-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [executor]: type definitions
import Aeneas
import Executor.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace executor

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core::hash::BuildHasher]
    Source: '/rustc/library/core/src/hash/mod.rs', lines 637:0-637:21
    Name pattern: [core::hash::BuildHasher]
    Visibility: public -/
@[rust_trait "core::hash::BuildHasher" (parentClauses := ["HasherInst"])]
structure core.hash.BuildHasher (Self : Type) (Self_Hasher : Type) where
  HasherInst : core.hash.Hasher Self_Hasher
  build_hasher : Self → Result Self_Hasher

/-- [core::str::pattern::SearchStep]
    Source: '/rustc/library/core/src/str/pattern.rs', lines 186:0-186:19
    Name pattern: [core::str::pattern::SearchStep]
    Visibility: public -/
@[discriminant isize, rust_type "core::str::pattern::SearchStep"]
inductive core.str.pattern.SearchStep where
| Match : Std.Usize → Std.Usize → core.str.pattern.SearchStep
| Reject : Std.Usize → Std.Usize → core.str.pattern.SearchStep
| Done : core.str.pattern.SearchStep

/-- Trait declaration: [core::str::pattern::Searcher]
    Source: '/rustc/library/core/src/str/pattern.rs', lines 213:0-213:29
    Name pattern: [core::str::pattern::Searcher]
    Visibility: public -/
@[rust_trait "core::str::pattern::Searcher"]
structure core.str.pattern.Searcher (Self : Type) where
  haystack : Self → Result Str
  next : Self → Result (core.str.pattern.SearchStep × Self)

/-- [std::collections::hash::map::Entry]
    Source: '/rustc/library/std/src/collections/hash/map.rs', lines 1950:0-1955:1
    Name pattern: [std::collections::hash::map::Entry]
    Visibility: public -/
@[discriminant isize, rust_type "std::collections::hash::map::Entry"
  (mutRegions := #[0])]
inductive std.collections.hash.map.Entry (K : Type) (V : Type) (A : Type) where
| Occupied :
  std.collections.hash.map.OccupiedEntry K V A →
  std.collections.hash.map.Entry K V A
| Vacant :
  std.collections.hash.map.VacantEntry K V A →
  std.collections.hash.map.Entry K V A

/-- Trait declaration: [std::io::Write]
    Source: '/rustc/library/std/src/io/mod.rs', lines 1384:0-1384:15
    Name pattern: [std::io::Write]
    Visibility: public -/
@[rust_trait "std::io::Write"]
structure std.io.Write (Self : Type) where
  write : Self → Slice Std.U8 → Result ((core.result.Result Std.Usize
    std.io.error.Error) × Self)
  flush : Self → Result ((core.result.Result Unit std.io.error.Error) ×
    Self)
  write_fmt : Self → core.fmt.Arguments → Result ((core.result.Result Unit
    std.io.error.Error) × Self)

/-- Trait declaration: [alloc::borrow::ToOwned]
    Source: '/rustc/library/alloc/src/borrow.rs', lines 27:0-27:17
    Name pattern: [alloc::borrow::ToOwned]
    Visibility: public -/
@[rust_trait "alloc::borrow::ToOwned"
  (parentClauses := ["coreborrowBorrowInst"])]
structure alloc.borrow.ToOwned (Self : Type) (Self_Owned : Type) where
  coreborrowBorrowInst : core.borrow.Borrow Self_Owned Self
  to_owned : Self → Result Self_Owned

/-- [alloc::borrow::Cow]
    Source: '/rustc/library/alloc/src/borrow.rs', lines 169:0-169:32
    Name pattern: [alloc::borrow::Cow]
    Visibility: public -/
@[discriminant isize, rust_type "alloc::borrow::Cow"]
inductive alloc.borrow.Cow (B : Type) (Clause0_Owned : Type) where
| Borrowed : B → alloc.borrow.Cow B Clause0_Owned
| Owned : Clause0_Owned → alloc.borrow.Cow B Clause0_Owned

/-- Trait declaration: [alloc::slice::Join]
    Source: '/rustc/library/alloc/src/slice.rs', lines 714:0-714:25
    Name pattern: [alloc::slice::Join]
    Visibility: public -/
@[rust_trait "alloc::slice::Join"]
structure alloc.slice.Join (Self : Type) (Separator : Type) (Self_Output :
  Type) where
  join : Self → Separator → Result Self_Output

/-- [executor::elf::ExecutableHeader]
    Source: 'executor/src/elf.rs', lines 22:0-51:1
    Visibility: public -/
structure elf.ExecutableHeader where
  _e_ident : Array Std.U8 16#usize
  e_type : Std.U16
  e_machine : Std.U16
  _e_version : Std.U32
  e_entry : Std.U64
  e_phoff : Std.U64
  e_shoff : Std.U64
  _e_flags : Std.U32
  _e_ehsize : Std.U16
  e_phentsize : Std.U16
  e_phnum : Std.U16
  e_shentsize : Std.U16
  e_shnum : Std.U16
  _e_shstrndx : Std.U16

/-- [executor::elf::ProgramHeader]
    Source: 'executor/src/elf.rs', lines 54:0-71:1
    Visibility: public -/
structure elf.ProgramHeader where
  p_type : Std.U32
  p_flags : Std.U32
  p_offset : Std.U64
  p_vaddr : Std.U64
  _p_paddr : Std.U64
  p_filesz : Std.U64
  p_memsz : Std.U64
  _p_align : Std.U64

/-- [executor::elf::ElfProgram]
    Source: 'executor/src/elf.rs', lines 74:0-77:1
    Visibility: public -/
structure elf.ElfProgram where
  ehdr : elf.ExecutableHeader
  phdrs : alloc.vec.Vec elf.ProgramHeader

/-- [executor::elf::ElfError]
    Source: 'executor/src/elf.rs', lines 234:0-265:1
    Visibility: public -/
@[discriminant isize]
inductive elf.ElfError where
| Not64Bit : elf.ElfError
| NotRiscV : elf.ElfError
| NotExecutable : elf.ElfError
| InvalidEntryPoint : elf.ElfError
| TooManyProgramHeaders : elf.ElfError
| UnalignedVAddr : elf.ElfError
| AddrTooLarge : elf.ElfError
| InvalidOffset : elf.ElfError
| ExecutableHeaderSize : elf.ElfError
| InvalidELFMagicNumber : elf.ElfError
| NotLittleEndian : elf.ElfError
| InvalidElfVersion : elf.ElfError
| Casting : elf.ElfError
| ProgramHeaderSize : elf.ElfError
| InvalidProgram : elf.ElfError

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#13]
    Source: 'executor/src/elf.rs', lines 159:64-159:85 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_13 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#12]
    Source: 'executor/src/elf.rs', lines 157:74-157:95 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_12 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#11]
    Source: 'executor/src/elf.rs', lines 156:64-156:85 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_11 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#10]
    Source: 'executor/src/elf.rs', lines 154:74-154:95 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_10 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#9]
    Source: 'executor/src/elf.rs', lines 153:64-153:85 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_9 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#8]
    Source: 'executor/src/elf.rs', lines 151:75-151:96 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_8 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#7]
    Source: 'executor/src/elf.rs', lines 150:74-150:95 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_7 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#6]
    Source: 'executor/src/elf.rs', lines 149:74-149:95 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_6 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#5]
    Source: 'executor/src/elf.rs', lines 148:74-148:95 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_5 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#4]
    Source: 'executor/src/elf.rs', lines 147:74-147:95 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_4 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#3]
    Source: 'executor/src/elf.rs', lines 146:64-146:85 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_3 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#2]
    Source: 'executor/src/elf.rs', lines 144:64-144:85 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_2 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure#1]
    Source: 'executor/src/elf.rs', lines 142:73-142:94 -/
@[reducible]
def elf.ExecutableHeader.parse.closure_1 := Unit

/-- [executor::elf::{executor::elf::ExecutableHeader}::parse::closure]
    Source: 'executor/src/elf.rs', lines 114:21-114:42 -/
@[reducible]
def elf.ExecutableHeader.parse.closure := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure#7]
    Source: 'executor/src/elf.rs', lines 200:74-200:95 -/
@[reducible]
def elf.ProgramHeader.parse.closure_7 := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure#6]
    Source: 'executor/src/elf.rs', lines 199:74-199:95 -/
@[reducible]
def elf.ProgramHeader.parse.closure_6 := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure#5]
    Source: 'executor/src/elf.rs', lines 198:75-198:96 -/
@[reducible]
def elf.ProgramHeader.parse.closure_5 := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure#4]
    Source: 'executor/src/elf.rs', lines 197:74-197:95 -/
@[reducible]
def elf.ProgramHeader.parse.closure_4 := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure#3]
    Source: 'executor/src/elf.rs', lines 196:74-196:95 -/
@[reducible]
def elf.ProgramHeader.parse.closure_3 := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure#2]
    Source: 'executor/src/elf.rs', lines 195:74-195:95 -/
@[reducible]
def elf.ProgramHeader.parse.closure_2 := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure#1]
    Source: 'executor/src/elf.rs', lines 194:72-194:93 -/
@[reducible]
def elf.ProgramHeader.parse.closure_1 := Unit

/-- [executor::elf::{executor::elf::ProgramHeader}::parse::closure]
    Source: 'executor/src/elf.rs', lines 193:71-193:92 -/
@[reducible]
def elf.ProgramHeader.parse.closure := Unit

/-- [executor::elf::Segment]
    Source: 'executor/src/elf.rs', lines 216:0-223:1
    Visibility: public -/
structure elf.Segment where
  base_addr : Std.U64
  values : alloc.vec.Vec Std.U32
  is_executable : Bool

/-- [executor::elf::Elf]
    Source: 'executor/src/elf.rs', lines 225:0-229:1
    Visibility: public -/
structure elf.Elf where
  entry_point : Std.U64
  data : alloc.vec.Vec elf.Segment

/-- [executor::elf::{executor::elf::Elf}::load::closure#1]
    Source: 'executor/src/elf.rs', lines 323:29-323:44 -/
@[reducible]
def elf.Elf.load.closure_1 := Unit

/-- [executor::elf::{executor::elf::Elf}::load::closure]
    Source: 'executor/src/elf.rs', lines 288:20-288:69 -/
@[reducible]
def elf.Elf.load.closure := Unit

/-- [executor::elf::FunctionSymbol]
    Source: 'executor/src/elf.rs', lines 333:0-340:1
    Visibility: public -/
structure elf.FunctionSymbol where
  «name» : String
  address : Std.U64
  size : Std.U64

/-- [executor::elf::SymbolTable]
    Source: 'executor/src/elf.rs', lines 344:0-347:1
    Visibility: public -/
structure elf.SymbolTable where
  functions : alloc.vec.Vec elf.FunctionSymbol

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#11]
    Source: 'executor/src/elf.rs', lines 526:30-526:43 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_11 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#10]
    Source: 'executor/src/elf.rs', lines 510:21-510:40 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_10 := Std.Usize

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#9]
    Source: 'executor/src/elf.rs', lines 509:26-509:37 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_9 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#8]
    Source: 'executor/src/elf.rs', lines 480:29-480:50 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_8 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#7]
    Source: 'executor/src/elf.rs', lines 475:29-475:50 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_7 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#6]
    Source: 'executor/src/elf.rs', lines 469:29-469:50 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_6 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#5]
    Source: 'executor/src/elf.rs', lines 440:25-440:46 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_5 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#4]
    Source: 'executor/src/elf.rs', lines 435:25-435:46 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_4 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#3]
    Source: 'executor/src/elf.rs', lines 409:33-409:54 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_3 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#2]
    Source: 'executor/src/elf.rs', lines 404:33-404:54 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_2 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure#1]
    Source: 'executor/src/elf.rs', lines 399:33-399:54 -/
@[reducible]
def elf.SymbolTable.try_parse.closure_1 := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::try_parse::closure]
    Source: 'executor/src/elf.rs', lines 391:29-391:50 -/
@[reducible]
def elf.SymbolTable.try_parse.closure := Unit

/-- [executor::elf::{executor::elf::SymbolTable}::lookup::closure]
    Source: 'executor/src/elf.rs', lines 535:70-535:83 -/
@[reducible]
def elf.SymbolTable.lookup.closure := Unit

/-- [executor::flamegraph::FlamegraphError]
    Source: 'executor/src/flamegraph.rs', lines 18:0-21:1
    Visibility: public -/
@[discriminant isize]
inductive flamegraph.FlamegraphError where
| InstructionNotFound : flamegraph.FlamegraphError

/-- [executor::flamegraph::FlamegraphGenerator]
    Source: 'executor/src/flamegraph.rs', lines 24:0-31:1
    Visibility: public -/
structure flamegraph.FlamegraphGenerator where
  symbols : elf.SymbolTable
  call_stack : alloc.vec.Vec Std.U64
  stack_counts : std.collections.hash.map.HashMap String Std.U64
    std.hash.random.RandomState Global

/-- [executor::vm::logs::Log]
    Source: 'executor/src/vm/logs.rs', lines 15:0-29:1
    Visibility: public -/
structure vm.logs.Log where
  current_pc : Std.U64
  next_pc : Std.U64
  src1_val : Std.U64
  src2_val : Std.U64
  dst_val : Std.U64

/-- [executor::vm::instruction::decoding::CsrOp]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 162:0-169:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.decoding.CsrOp where
| CSRRW : vm.instruction.decoding.CsrOp
| CSRRS : vm.instruction.decoding.CsrOp
| CSRRC : vm.instruction.decoding.CsrOp
| CSRRWI : vm.instruction.decoding.CsrOp
| CSRRSI : vm.instruction.decoding.CsrOp
| CSRRCI : vm.instruction.decoding.CsrOp

/-- [executor::vm::instruction::decoding::Comparison]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 152:0-159:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.decoding.Comparison where
| Equal : vm.instruction.decoding.Comparison
| NotEqual : vm.instruction.decoding.Comparison
| LessThan : vm.instruction.decoding.Comparison
| GreaterOrEqual : vm.instruction.decoding.Comparison
| LessThanUnsigned : vm.instruction.decoding.Comparison
| GreaterOrEqualUnsigned : vm.instruction.decoding.Comparison

/-- [executor::vm::instruction::decoding::LoadStoreWidth]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 116:0-124:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.decoding.LoadStoreWidth where
| Byte : vm.instruction.decoding.LoadStoreWidth
| Half : vm.instruction.decoding.LoadStoreWidth
| Word : vm.instruction.decoding.LoadStoreWidth
| DoubleWord : vm.instruction.decoding.LoadStoreWidth
| ByteUnsigned : vm.instruction.decoding.LoadStoreWidth
| HalfUnsigned : vm.instruction.decoding.LoadStoreWidth
| WordUnsigned : vm.instruction.decoding.LoadStoreWidth

/-- [executor::vm::instruction::decoding::ArithOp]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 86:0-105:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.decoding.ArithOp where
| Add : vm.instruction.decoding.ArithOp
| Sub : vm.instruction.decoding.ArithOp
| Xor : vm.instruction.decoding.ArithOp
| Or : vm.instruction.decoding.ArithOp
| And : vm.instruction.decoding.ArithOp
| ShiftLeftLogical : vm.instruction.decoding.ArithOp
| ShiftRightLogical : vm.instruction.decoding.ArithOp
| ShiftRightArith : vm.instruction.decoding.ArithOp
| SetLessThan : vm.instruction.decoding.ArithOp
| SetLessThanU : vm.instruction.decoding.ArithOp
| Mul : vm.instruction.decoding.ArithOp
| MulHigh : vm.instruction.decoding.ArithOp
| MulHighSignedUnsigned : vm.instruction.decoding.ArithOp
| MulHighUnsigned : vm.instruction.decoding.ArithOp
| Div : vm.instruction.decoding.ArithOp
| DivUnsigned : vm.instruction.decoding.ArithOp
| Remainder : vm.instruction.decoding.ArithOp
| RemainderUnsigned : vm.instruction.decoding.ArithOp

/-- [executor::vm::instruction::decoding::Instruction]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 172:0-242:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.decoding.Instruction where
| Arith :
  Std.U32 →
  Std.U32 →
  Std.U32 →
  vm.instruction.decoding.ArithOp →
  vm.instruction.decoding.Instruction
| ArithImm :
  Std.U32 →
  Std.U32 →
  Std.I32 →
  vm.instruction.decoding.ArithOp →
  vm.instruction.decoding.Instruction
| ArithW :
  Std.U32 →
  Std.U32 →
  Std.U32 →
  vm.instruction.decoding.ArithOp →
  vm.instruction.decoding.Instruction
| ArithImmW :
  Std.U32 →
  Std.U32 →
  Std.I32 →
  vm.instruction.decoding.ArithOp →
  vm.instruction.decoding.Instruction
| JumpAndLink : Std.U32 → Std.I32 → vm.instruction.decoding.Instruction
| JumpAndLinkRegister :
  Std.U32 →
  Std.U32 →
  Std.I32 →
  vm.instruction.decoding.Instruction
| Store :
  Std.U32 →
  Std.I32 →
  Std.U32 →
  vm.instruction.decoding.LoadStoreWidth →
  vm.instruction.decoding.Instruction
| Load :
  Std.U32 →
  Std.I32 →
  Std.U32 →
  vm.instruction.decoding.LoadStoreWidth →
  vm.instruction.decoding.Instruction
| Branch :
  Std.U32 →
  Std.U32 →
  vm.instruction.decoding.Comparison →
  Std.I32 →
  vm.instruction.decoding.Instruction
| LoadUpperImm : Std.U32 → Std.U32 → vm.instruction.decoding.Instruction
| AddUpperImmToPc : Std.U32 → Std.U32 → vm.instruction.decoding.Instruction
| CSR :
  Std.U32 →
  Std.U32 →
  Std.U32 →
  vm.instruction.decoding.CsrOp →
  vm.instruction.decoding.Instruction
| EcallEbreak : vm.instruction.decoding.Instruction
| Fence : vm.instruction.decoding.Instruction

/-- [executor::vm::execution::{executor::vm::execution::InstructionCache}::get::closure]
    Source: 'executor/src/vm/execution.rs', lines 214:34-222:17 -/
@[reducible]
def vm.execution.InstructionCache.get.closure := Std.U64

/-- [executor::vm::execution::InstructionSegment]
    Source: 'executor/src/vm/execution.rs', lines 132:0-135:1
    Visibility: public -/
structure vm.execution.InstructionSegment where
  base_addr : Std.U64
  instructions : alloc.vec.Vec vm.instruction.decoding.Instruction

/-- [executor::vm::execution::InstructionCache]
    Source: 'executor/src/vm/execution.rs', lines 143:0-145:1
    Visibility: public -/
structure vm.execution.InstructionCache where
  segments : alloc.vec.Vec vm.execution.InstructionSegment

/-- [executor::flamegraph::{executor::flamegraph::FlamegraphGenerator}::resolve_address::closure#1]
    Source: 'executor/src/flamegraph.rs', lines 82:28-82:57 -/
@[reducible]
def flamegraph.FlamegraphGenerator.resolve_address.closure_1 := Std.U64

/-- [executor::flamegraph::{executor::flamegraph::FlamegraphGenerator}::resolve_address::closure]
    Source: 'executor/src/flamegraph.rs', lines 81:17-81:42 -/
@[reducible]
def flamegraph.FlamegraphGenerator.resolve_address.closure := Unit

/-- [executor::flamegraph::{executor::flamegraph::FlamegraphGenerator}::format_stack::closure]
    Source: 'executor/src/flamegraph.rs', lines 72:17-72:51 -/
@[reducible]
def flamegraph.FlamegraphGenerator.format_stack.closure :=
  flamegraph.FlamegraphGenerator

/-- [executor::flamegraph::{executor::flamegraph::FlamegraphGenerator}::write_folded::closure]
    Source: 'executor/src/flamegraph.rs', lines 137:27-137:46 -/
@[reducible]
def flamegraph.FlamegraphGenerator.write_folded.closure (W : Type) := Unit

/-- [executor::vm::execution::ReturnValues]
    Source: 'executor/src/vm/execution.rs', lines 16:0-19:1
    Visibility: public -/
structure vm.execution.ReturnValues where
  memory_values : alloc.vec.Vec Std.U8
  register_values : (Std.I64 × Std.I64)

/-- [executor::vm::memory::U64BuildHasher]
    Source: 'executor/src/vm/memory.rs', lines 29:0-29:26
    Visibility: public -/
@[reducible]
def vm.memory.U64BuildHasher := Unit

/-- [executor::vm::execution::ExecutionResult]
    Source: 'executor/src/vm/execution.rs', lines 22:0-28:1
    Visibility: public -/
structure vm.execution.ExecutionResult where
  return_values : vm.execution.ReturnValues
  logs : alloc.vec.Vec vm.logs.Log
  instructions : std.collections.hash.map.HashMap Std.U64
    vm.instruction.decoding.Instruction vm.memory.U64BuildHasher Global

/-- [executor::vm::registers::Registers]
    Source: 'executor/src/vm/registers.rs', lines 8:0-8:32
    Visibility: public -/
@[reducible]
def vm.registers.Registers := Array Std.U64 31#usize

/-- [executor::vm::memory::Memory]
    Source: 'executor/src/vm/memory.rs', lines 54:0-61:1
    Visibility: public -/
structure vm.memory.Memory where
  cells : std.collections.hash.map.HashMap Std.U64 (Array Std.U8 4#usize)
    vm.memory.U64BuildHasher Global
  public_output : alloc.vec.Vec Std.U8

/-- [executor::vm::execution::Executor]
    Source: 'executor/src/vm/execution.rs', lines 34:0-40:1
    Visibility: public -/
structure vm.execution.Executor where
  memory : vm.memory.Memory
  registers : vm.registers.Registers
  pc : Std.U64
  instructions : vm.execution.InstructionCache
  logs : alloc.vec.Vec vm.logs.Log

/-- [executor::vm::memory::MemoryError]
    Source: 'executor/src/vm/memory.rs', lines 263:0-274:1
    Visibility: public -/
@[discriminant isize]
inductive vm.memory.MemoryError where
| UnalignedAccess : vm.memory.MemoryError
| CommitSizeExceeded : vm.memory.MemoryError
| PrivateInputSizeExceeded : vm.memory.MemoryError
| AddressOverflow : vm.memory.MemoryError
| AllocationFailed : vm.memory.MemoryError

/-- [executor::vm::memory::U64Hasher]
    Source: 'executor/src/vm/memory.rs', lines 7:0-7:26
    Visibility: public -/
@[reducible]
def vm.memory.U64Hasher := Std.U64

/-- [executor::vm::memory::{executor::vm::memory::Memory}::store_private_inputs::closure]
    Source: 'executor/src/vm/memory.rs', lines 218:48-218:89 -/
@[reducible]
def vm.memory.Memory.store_private_inputs.closure := Unit

/-- [executor::vm::memory::{executor::vm::memory::Memory}::store_byte::closure]
    Source: 'executor/src/vm/memory.rs', lines 79:28-79:43 -/
@[reducible]
def vm.memory.Memory.store_byte.closure := Unit

/-- [executor::vm::instruction::decoding::Opcode]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 18:0-33:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.decoding.Opcode where
| Arith : vm.instruction.decoding.Opcode
| ArithImm : vm.instruction.decoding.Opcode
| Load : vm.instruction.decoding.Opcode
| Store : vm.instruction.decoding.Opcode
| Branch : vm.instruction.decoding.Opcode
| JumpAndLinkRegister : vm.instruction.decoding.Opcode
| JumpAndLink : vm.instruction.decoding.Opcode
| LoadUpperImm : vm.instruction.decoding.Opcode
| AddUpperImmToPc : vm.instruction.decoding.Opcode
| System : vm.instruction.decoding.Opcode
| ArithImm32 : vm.instruction.decoding.Opcode
| Arith32 : vm.instruction.decoding.Opcode
| Fence : vm.instruction.decoding.Opcode

/-- [executor::vm::instruction::decoding::InstructionError]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 615:0-634:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.decoding.InstructionError where
| UnknownOpcode : Std.U32 → vm.instruction.decoding.InstructionError
| UnknownOpcodeFuncIdentifier :
  vm.instruction.decoding.Opcode →
  Std.U32 →
  vm.instruction.decoding.InstructionError
| InvalidInstruction : vm.instruction.decoding.InstructionError
| InvalidLoadStoreWidth : Std.U32 → vm.instruction.decoding.InstructionError
| UnknownSRVariant : Std.I32 → vm.instruction.decoding.InstructionError
| UnknownSLVariant : Std.I32 → vm.instruction.decoding.InstructionError
| InvalidJALR : vm.instruction.decoding.InstructionError
| InvalidSystemInstruction :
  Std.U32 →
  vm.instruction.decoding.InstructionError
| InvalidW32Instruction : vm.instruction.decoding.InstructionError

/-- [executor::vm::registers::RegisterError]
    Source: 'executor/src/vm/registers.rs', lines 79:0-82:1
    Visibility: public -/
@[discriminant isize]
inductive vm.registers.RegisterError where
| InvalidRegister : Std.U32 → vm.registers.RegisterError

/-- [executor::vm::instruction::execution::ExecutionError]
    Source: 'executor/src/vm/instruction/execution.rs', lines 511:0-538:1
    Visibility: public -/
@[discriminant isize]
inductive vm.instruction.execution.ExecutionError where
| SubImmNotSupported : vm.instruction.execution.ExecutionError
| StoreBytesUnsignedNotSupported : vm.instruction.execution.ExecutionError
| StoreHalfUnsignedNotSupported : vm.instruction.execution.ExecutionError
| StoreWordUnsignedNotSupported : vm.instruction.execution.ExecutionError
| MemoryError :
  vm.memory.MemoryError →
  vm.instruction.execution.ExecutionError
| RegisterError :
  vm.registers.RegisterError →
  vm.instruction.execution.ExecutionError
| UnknownSyscall : Std.U64 → vm.instruction.execution.ExecutionError
| Panic : String → vm.instruction.execution.ExecutionError
| IncorrectMessage : vm.instruction.execution.ExecutionError
| InvalidWSuffixOperation :
  vm.instruction.decoding.ArithOp →
  vm.instruction.execution.ExecutionError
| InvalidCommitFd : Std.U64 → vm.instruction.execution.ExecutionError
| UnalignedKeccakStateAddress :
  Std.U64 →
  vm.instruction.execution.ExecutionError
| KeccakStateAddressOverflow :
  Std.U64 →
  vm.instruction.execution.ExecutionError

/-- [executor::vm::execution::ExecutorError]
    Source: 'executor/src/vm/execution.rs', lines 251:0-260:1
    Visibility: public -/
@[discriminant isize]
inductive vm.execution.ExecutorError where
| Instruction :
  vm.instruction.decoding.InstructionError →
  vm.execution.ExecutorError
| ExecutionError :
  vm.instruction.execution.ExecutionError →
  vm.execution.ExecutorError
| MemoryError : vm.memory.MemoryError → vm.execution.ExecutorError
| InstructionAddressMisaligned : Std.U64 → vm.execution.ExecutorError

/-- [executor::vm::instruction::decoding::InstructionFormat]
    Source: 'executor/src/vm/instruction/decoding.rs', lines 58:0-65:1 -/
@[discriminant isize]
inductive vm.instruction.decoding.InstructionFormat where
| R : vm.instruction.decoding.InstructionFormat
| I : vm.instruction.decoding.InstructionFormat
| S : vm.instruction.decoding.InstructionFormat
| B : vm.instruction.decoding.InstructionFormat
| U : vm.instruction.decoding.InstructionFormat
| J : vm.instruction.decoding.InstructionFormat

/-- [executor::vm::execution::{executor::vm::execution::InstructionCache}::new::closure#1]
    Source: 'executor/src/vm/execution.rs', lines 192:21-192:47 -/
@[reducible]
def vm.execution.InstructionCache.new.closure_1 := Unit

/-- [executor::vm::execution::{executor::vm::execution::InstructionCache}::new::closure]
    Source: 'executor/src/vm/execution.rs', lines 188:42-188:61 -/
@[reducible]
def vm.execution.InstructionCache.new.closure := Unit

/-- [executor::vm::memory::{executor::vm::memory::Memory}::load_bytes::closure#1]
    Source: 'executor/src/vm/memory.rs', lines 230:21-230:54 -/
@[reducible]
def vm.memory.Memory.load_bytes.closure_1 := Unit

/-- [executor::vm::memory::{executor::vm::memory::Memory}::load_bytes::closure]
    Source: 'executor/src/vm/memory.rs', lines 226:53-226:86 -/
@[reducible]
def vm.memory.Memory.load_bytes.closure := Unit

/-- [executor::vm::memory::{executor::vm::memory::Memory}::store_half::closure]
    Source: 'executor/src/vm/memory.rs', lines 174:32-174:47 -/
@[reducible]
def vm.memory.Memory.store_half.closure := Unit

/-- [executor::vm::instruction::execution::{executor::vm::instruction::decoding::Instruction}::execute::closure#2]
    Source: 'executor/src/vm/instruction/execution.rs', lines 318:59-318:95 -/
@[reducible]
def vm.instruction.execution.Instruction.execute.closure_2 := Unit

/-- [executor::vm::instruction::execution::{executor::vm::instruction::decoding::Instruction}::execute::closure#1]
    Source: 'executor/src/vm/instruction/execution.rs', lines 309:59-309:95 -/
@[reducible]
def vm.instruction.execution.Instruction.execute.closure_1 := Unit

/-- [executor::vm::instruction::execution::{executor::vm::instruction::decoding::Instruction}::execute::closure]
    Source: 'executor/src/vm/instruction/execution.rs', lines 297:29-297:83 -/
@[reducible]
def vm.instruction.execution.Instruction.execute.closure := Std.U64

/-- [executor::vm::instruction::execution::SyscallNumbers]
    Source: 'executor/src/vm/instruction/execution.rs', lines 10:0-17:1
    Visibility: public -/
@[discriminant isize [0,1,2,64,93]]
inductive vm.instruction.execution.SyscallNumbers where
| KeccakPermute : vm.instruction.execution.SyscallNumbers
| Print : vm.instruction.execution.SyscallNumbers
| Panic : vm.instruction.execution.SyscallNumbers
| Commit : vm.instruction.execution.SyscallNumbers
| Halt : vm.instruction.execution.SyscallNumbers

/-- [executor::vm::execution::{executor::vm::execution::InstructionCache}::from_map::closure]
    Source: 'executor/src/vm/execution.rs', lines 158:28-158:45 -/
@[reducible]
def vm.execution.InstructionCache.from_map.closure := Unit

/-- [executor::vm::execution::{executor::vm::execution::InstructionCache}::instruction_count::closure]
    Source: 'executor/src/vm/execution.rs', lines 235:33-235:57 -/
@[reducible]
def vm.execution.InstructionCache.instruction_count.closure := Unit

end executor
