//! The windowed trace builder builds the whole-run tables
//! (`tables::trace_builder::WindowedTraceBuilder`).

use executor::elf::Elf;
use executor::vm::execution::Executor;
use executor::vm::logs::Log;
use math::field::element::FieldElement;
use stark::trace::TraceTable;

use crate::tables::MaxRowsConfig;
use crate::tables::trace_builder::{StreamTable, Traces, WindowedTraceBuilder};
use crate::tables::types::{GoldilocksExtension, GoldilocksField};
use crate::test_utils::asm_elf_bytes;

type Table = TraceTable<GoldilocksField, GoldilocksExtension>;

fn run(name: &str) -> (Elf, Vec<Log>) {
    let program = Elf::load(&asm_elf_bytes(name)).expect("the ELF loads");
    let logs = Executor::new(&program, Vec::new())
        .expect("the executor starts")
        .run()
        .expect("the program runs")
        .logs;
    (program, logs)
}

fn whole(program: &Elf, logs: &[Log], max_rows: &MaxRowsConfig) -> Traces {
    Traces::from_elf_and_logs(
        program,
        logs,
        max_rows,
        &[],
        #[cfg(feature = "disk-spill")]
        stark::storage_mode::StorageMode::Ram,
    )
    .expect("the whole-run build")
}

/// The windowed build over windows of `window` cycles (the last window is the
/// rest, at least one cycle), with its streamed chunks put back; and how many
/// chunks it streamed.
fn windowed(
    program: &Elf,
    logs: &[Log],
    max_rows: &MaxRowsConfig,
    window: usize,
) -> (Traces, usize) {
    let mut builder = WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder");
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut chunks = Vec::new();
    for w in logs[..cut].chunks(window) {
        chunks.extend(builder.push(w).expect("a window"));
    }
    let streamed = chunks.len();
    let mut traces = builder.finish(&logs[cut..]).expect("the last window");
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    (traces, streamed)
}

/// [`windowed`] through `push_jobs`, each chunk generated by its job.
fn windowed_jobs(program: &Elf, logs: &[Log], max_rows: &MaxRowsConfig, window: usize) -> Traces {
    let mut builder = WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder");
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut chunks = Vec::new();
    for w in logs[..cut].chunks(window) {
        chunks.extend(
            builder
                .push_jobs(w)
                .expect("a window")
                .into_iter()
                .map(|job| job.generate()),
        );
    }
    let mut traces = builder.finish(&logs[cut..]).expect("the last window");
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    traces
}

/// [`windowed`] with the builder split: the walker on one thread, the
/// accumulator on another, the chunks generated by their jobs.
fn windowed_split(program: &Elf, logs: &[Log], max_rows: &MaxRowsConfig, window: usize) -> Traces {
    let mut builder = WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder");
    let body = logs.len() - 1;
    let cut = body - body % window;
    let chunks = {
        let (mut walker, mut accumulator) = builder.split();
        std::thread::scope(|scope| {
            let (tx, rx) = std::sync::mpsc::sync_channel(2);
            let walking = scope.spawn(move || {
                for w in logs[..cut].chunks(window) {
                    tx.send(walker.walk(w).expect("a window"))
                        .expect("the accumulator");
                }
            });
            let mut chunks = Vec::new();
            for walked in rx {
                chunks.extend(
                    accumulator
                        .absorb(walked)
                        .into_iter()
                        .map(|job| job.generate()),
                );
            }
            walking.join().expect("the walker");
            chunks
        })
    };
    let mut traces = builder.finish(&logs[cut..]).expect("the last window");
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    traces
}

fn rows(t: &Table) -> Vec<Vec<FieldElement<GoldilocksField>>> {
    (0..t.main_table.height)
        .map(|r| t.main_table.get_row(r).to_vec())
        .collect()
}

/// Equal tables — row for row, or as row multisets for the tables that lay
/// their rows out in `HashMap` order.
fn same(what: &str, a: &Table, b: &Table, hashed: bool) {
    assert_eq!(
        (a.main_table.width, a.main_table.height),
        (b.main_table.width, b.main_table.height),
        "{what}: shape"
    );
    let (mut ra, mut rb) = (rows(a), rows(b));
    if hashed {
        let key = |r: &Vec<FieldElement<GoldilocksField>>| {
            r.iter().map(|v| v.canonical()).collect::<Vec<u64>>()
        };
        ra.sort_by_key(key);
        rb.sort_by_key(key);
    }
    assert!(ra == rb, "{what}: rows differ");
}

fn same_list(what: &str, a: &[Table], b: &[Table], hashed: bool) {
    assert_eq!(a.len(), b.len(), "{what}: table count");
    for (i, (x, y)) in a.iter().zip(b).enumerate() {
        same(&format!("{what}[{i}]"), x, y, hashed);
    }
}

fn same_traces(a: &Traces, b: &Traces) {
    same_list("CPU", &a.cpus, &b.cpus, false);
    same_list("MEMW_R", &a.memw_registers, &b.memw_registers, false);
    same_list("MEMW_A", &a.memw_aligneds, &b.memw_aligneds, false);
    same_list("MEMW", &a.memws, &b.memws, false);
    same_list("LOAD", &a.loads, &b.loads, false);
    same_list("STORE", &a.stores, &b.stores, false);
    same_list("SHIFT", &a.shifts, &b.shifts, false);
    same_list("CPU32", &a.cpu32s, &b.cpu32s, false);
    same_list("COMMIT", &a.commits, &b.commits, false);
    same_list("KECCAK", &a.keccaks, &b.keccaks, false);
    same_list("KECCAK_RND", &a.keccak_rnds, &b.keccak_rnds, false);
    same_list("ECSM", &a.ecsms, &b.ecsms, false);
    same_list("ECDAS", &a.ecdases, &b.ecdases, false);
    same_list("HINT", &a.hints, &b.hints, false);
    same_list("PAGE", &a.pages, &b.pages, false);
    same_list("LT", &a.lts, &b.lts, true);
    same_list("MUL", &a.muls, &b.muls, true);
    same_list("DVRM", &a.dvrms, &b.dvrms, true);
    same_list("BRANCH", &a.branches, &b.branches, true);
    same_list("EQ", &a.eqs, &b.eqs, true);
    same_list("BYTEWISE", &a.bytewises, &b.bytewises, true);
    same("BITWISE", &a.bitwise, &b.bitwise, false);
    same("DECODE", &a.decode, &b.decode, false);
    same("REGISTER", &a.register, &b.register, false);
    same("HALT", &a.halt, &b.halt, false);
    same("KECCAK_RC", &a.keccak_rc, &b.keccak_rc, false);
    same("BLAKE3", &a.blake3, &b.blake3, false);
    assert_eq!(a.public_output_bytes, b.public_output_bytes);
    assert_eq!(a.num_blake3_ops, b.num_blake3_ops);
    assert_eq!(a.page_configs.len(), b.page_configs.len());
    assert_eq!(
        format!("{:?}", a.table_counts()),
        format!("{:?}", b.table_counts())
    );
}

/// ★ The builder is a schedule: at every window length — one cycle, less than a
/// chunk, exactly a chunk, not a divisor of it, longer than the run — the
/// windowed build is the whole-run build, table for table, and it did stream.
#[test]
fn windowed_builds_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    for name in [
        "sub",
        "all_instructions_64",
        "test_keccak",
        "test_keccak_multi",
    ] {
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        for window in [1, 7, 32, 33, 1000, logs.len()] {
            let (traces, streamed) = windowed(&program, &logs, &max_rows, window.max(1));
            same_traces(&reference, &traces);
            if logs.len() > 2 * max_rows.cpu && window < logs.len() / 2 {
                assert!(streamed > 0, "{name}, window {window}: nothing streamed");
            }
        }
    }
}

/// The same through chunk jobs generated by the caller.
#[test]
fn windowed_jobs_build_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    for name in ["all_instructions_64", "test_keccak_multi"] {
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        for window in [7, 33] {
            same_traces(
                &reference,
                &windowed_jobs(&program, &logs, &max_rows, window),
            );
        }
    }
}

/// The same with the builder split across two threads.
#[test]
fn a_split_builder_builds_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    for name in ["all_instructions_64", "test_keccak_multi"] {
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        for window in [1, 7, 33] {
            same_traces(
                &reference,
                &windowed_split(&program, &logs, &max_rows, window),
            );
        }
    }
}

/// And at the production chunk sizes, where a small program streams nothing
/// and the builder is the whole-run build over windows.
#[test]
fn windowed_builds_the_whole_run_tables_at_production_sizes() {
    let max_rows = MaxRowsConfig::default();
    let (program, logs) = run("all_instructions_64");
    let reference = whole(&program, &logs, &max_rows);
    let (traces, _) = windowed(&program, &logs, &max_rows, 64);
    same_traces(&reference, &traces);
}

/// A non-final window may not halt, as a whole-run build refuses an epoch that
/// halts early.
#[test]
fn a_window_that_halts_before_the_end_is_refused() {
    let max_rows = MaxRowsConfig::small();
    let (program, logs) = run("sub");
    let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows).expect("the builder");
    assert!(builder.push(&logs).is_err());
}

/// A streamed chunk only goes back into a placeholder.
#[test]
fn a_chunk_is_only_put_back_into_its_placeholder() {
    let max_rows = MaxRowsConfig::small();
    let (program, logs) = run("all_instructions_64");
    let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows).expect("the builder");
    let chunks = builder.push(&logs[..logs.len() - 1]).expect("a window");
    assert!(
        chunks.iter().any(|c| c.table == StreamTable::Cpu),
        "a CPU chunk streams"
    );
    let mut traces = builder.finish(&logs[logs.len() - 1..]).expect("the rest");
    let again: Vec<_> = chunks
        .iter()
        .filter(|c| c.table == StreamTable::Cpu)
        .map(|c| crate::tables::trace_builder::StreamedChunk {
            table: c.table,
            index: c.index,
            trace: c.trace.clone(),
        })
        .collect();
    traces.insert_streamed(chunks).expect("first time");
    assert!(traces.insert_streamed(again).is_err());
}

/// One digest per table: its width and its rows (sorted for the six tables
/// that lay their rows out in `HashMap` order, whose row order no two builds
/// share).
fn table_digests(t: &Traces) -> Vec<(String, String)> {
    use rayon::prelude::*;
    let mut tables: Vec<(String, &Table, bool)> = Vec::new();
    let lists: [(&str, &Vec<Table>, bool); 21] = [
        ("CPU", &t.cpus, false),
        ("MEMW_R", &t.memw_registers, false),
        ("MEMW_A", &t.memw_aligneds, false),
        ("MEMW", &t.memws, false),
        ("LOAD", &t.loads, false),
        ("STORE", &t.stores, false),
        ("SHIFT", &t.shifts, false),
        ("CPU32", &t.cpu32s, false),
        ("COMMIT", &t.commits, false),
        ("KECCAK", &t.keccaks, false),
        ("KECCAK_RND", &t.keccak_rnds, false),
        ("ECSM", &t.ecsms, false),
        ("ECDAS", &t.ecdases, false),
        ("HINT", &t.hints, false),
        ("PAGE", &t.pages, false),
        ("LT", &t.lts, true),
        ("MUL", &t.muls, true),
        ("DVRM", &t.dvrms, true),
        ("BRANCH", &t.branches, true),
        ("EQ", &t.eqs, true),
        ("BYTEWISE", &t.bytewises, true),
    ];
    for (name, list, hashed) in lists {
        for (i, table) in list.iter().enumerate() {
            tables.push((format!("{name}[{i}]"), table, hashed));
        }
    }
    for (name, table) in [
        ("BITWISE", &t.bitwise),
        ("DECODE", &t.decode),
        ("REGISTER", &t.register),
        ("HALT", &t.halt),
        ("KECCAK_RC", &t.keccak_rc),
        ("BLAKE3", &t.blake3),
    ] {
        tables.push((name.to_string(), table, false));
    }
    tables
        .into_par_iter()
        .map(|(name, table, hashed)| {
            // Streamed, never materialized: a block's traces are tens of GiB.
            // A HashMap-ordered table is digested as the sorted list of its
            // rows' digests (32 bytes a row), which is order-free.
            let row_bytes = |r: usize| -> Vec<u8> {
                table
                    .main_table
                    .get_row(r)
                    .iter()
                    .flat_map(|v| v.canonical().to_le_bytes())
                    .collect()
            };
            let mut h = blake3::Hasher::new();
            h.update(&(table.main_table.width as u64).to_le_bytes());
            h.update(&(table.main_table.height as u64).to_le_bytes());
            if hashed {
                let mut rows: Vec<[u8; 32]> = (0..table.main_table.height)
                    .map(|r| *blake3::hash(&row_bytes(r)).as_bytes())
                    .collect();
                rows.sort_unstable();
                for row in rows {
                    h.update(&row);
                }
            } else {
                for r in 0..table.main_table.height {
                    h.update(&row_bytes(r));
                }
            }
            (name, h.finalize().to_hex()[..16].to_string())
        })
        .collect()
}

/// ★ Box only (`--ignored`): on a real block, the windowed build — split across
/// a walker and an accumulator thread, its chunks generated on a third, beside a
/// thread that keeps the host's memory busy — gives the whole-run build's
/// tables, twice. Reads `BLOCK_WHIR_ELF` and `BLOCK_WHIR_INPUT`; prints
/// `DETERMINISM` lines.
#[test]
#[ignore = "a real block: box only"]
fn the_windowed_build_of_a_real_block_is_the_whole_run_build_every_time() {
    use std::sync::atomic::{AtomicBool, Ordering};

    let elf = std::fs::read(std::env::var("BLOCK_WHIR_ELF").expect("BLOCK_WHIR_ELF")).unwrap();
    let input =
        std::fs::read(std::env::var("BLOCK_WHIR_INPUT").expect("BLOCK_WHIR_INPUT")).unwrap();
    let program = Elf::load(&elf).expect("the ELF loads");
    let max_rows = MaxRowsConfig::uniform(1 << 21);
    let logs = Executor::new(&program, input.clone())
        .expect("the executor starts")
        .run()
        .expect("the block runs")
        .logs;
    let reference = {
        let t = Traces::from_elf_and_logs(
            &program,
            &logs,
            &max_rows,
            &input,
            #[cfg(feature = "disk-spill")]
            stark::storage_mode::StorageMode::Ram,
        )
        .expect("the whole-run build");
        table_digests(&t)
    };
    println!("DETERMINISM whole-run: {} tables", reference.len());
    let window = 1usize << 20;
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut runs_equal = 0usize;
    for run_index in 0..2 {
        let stop = AtomicBool::new(false);
        let digests = std::thread::scope(|scope| {
            // The contention: a thread copying a GiB back and forth.
            let busy = scope.spawn(|| {
                let mut a = vec![1u8; 1 << 30];
                let mut b = vec![0u8; 1 << 30];
                while !stop.load(Ordering::Relaxed) {
                    b.copy_from_slice(&a);
                    a.copy_from_slice(&b);
                }
            });
            let mut builder =
                WindowedTraceBuilder::new(&program, &input, &max_rows).expect("the builder");
            let chunks = {
                let (mut walker, mut accumulator) = builder.split();
                std::thread::scope(|inner| {
                    let (wtx, wrx) = std::sync::mpsc::sync_channel(2);
                    let (jtx, jrx) = std::sync::mpsc::sync_channel(64);
                    let logs = &logs;
                    inner.spawn(move || {
                        for w in logs[..cut].chunks(window) {
                            wtx.send(walker.walk(w).expect("a window"))
                                .expect("accumulator");
                        }
                    });
                    let generator = inner.spawn(move || {
                        jrx.into_iter()
                            .map(crate::tables::trace_builder::ChunkJob::generate)
                            .collect::<Vec<_>>()
                    });
                    for walked in wrx {
                        for job in accumulator.absorb(walked) {
                            jtx.send(job).expect("generator");
                        }
                    }
                    drop(jtx);
                    generator.join().expect("the generator")
                })
            };
            let streamed = chunks.len();
            let mut traces = builder.finish(&logs[cut..]).expect("the last window");
            traces.insert_streamed(chunks).expect("placeholders");
            stop.store(true, Ordering::Relaxed);
            busy.join().expect("the busy thread");
            println!("DETERMINISM windowed run {run_index}: {streamed} chunks streamed");
            table_digests(&traces)
        });
        let differing: Vec<&String> = reference
            .iter()
            .zip(&digests)
            .filter(|(a, b)| a != b)
            .map(|(a, _)| &a.0)
            .collect();
        println!(
            "DETERMINISM windowed run {run_index}: {} tables, {} differ from the whole-run build {:?}",
            digests.len(),
            differing.len(),
            differing
        );
        if digests.len() == reference.len() && differing.is_empty() {
            runs_equal += 1;
        }
    }
    println!("DETERMINISM RESULT: {runs_equal}/2 windowed runs equal the whole-run build");
    assert_eq!(runs_equal, 2);
}
