//! The windowed trace builder builds the whole-run tables
//! (`tables::trace_builder::WindowedTraceBuilder`).

use executor::elf::Elf;
use executor::vm::execution::Executor;
use executor::vm::logs::Log;
use math::field::element::FieldElement;
use stark::trace::TraceTable;

use crate::tables::MaxRowsConfig;
use crate::tables::trace_builder::{Counter, StreamTable, Traces, WalkLean, WindowedTraceBuilder};
use crate::tables::types::{GoldilocksExtension, GoldilocksField};
use crate::test_utils::asm_elf_bytes;

type Table = TraceTable<GoldilocksField, GoldilocksExtension>;

fn run(name: &str) -> (Elf, Vec<Log>) {
    let program = Elf::load(&asm_elf_bytes(name)).expect("the ELF loads");
    let logs = Executor::new(&program, Vec::new())
        .expect("the executor starts")
        .run()
        .expect("the program runs")
        .logs;
    (program, logs)
}

fn whole(program: &Elf, logs: &[Log], max_rows: &MaxRowsConfig) -> Traces {
    Traces::from_elf_and_logs(
        program,
        logs,
        max_rows,
        &[],
        #[cfg(feature = "disk-spill")]
        stark::storage_mode::StorageMode::Ram,
    )
    .expect("the whole-run build")
}

/// The windowed build over windows of `window` cycles (the last window is the
/// rest, at least one cycle), with its streamed chunks put back; and how many
/// chunks it streamed.
fn windowed(
    program: &Elf,
    logs: &[Log],
    max_rows: &MaxRowsConfig,
    window: usize,
) -> (Traces, usize) {
    let mut builder = WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder");
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut chunks = Vec::new();
    for w in logs[..cut].chunks(window) {
        chunks.extend(builder.push(w).expect("a window"));
    }
    let streamed = chunks.len();
    let mut traces = builder.finish(&logs[cut..]).expect("the last window");
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    (traces, streamed)
}

/// [`windowed`] through `push_jobs`, each chunk generated by its job.
fn windowed_jobs(program: &Elf, logs: &[Log], max_rows: &MaxRowsConfig, window: usize) -> Traces {
    let mut builder = WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder");
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut chunks = Vec::new();
    for w in logs[..cut].chunks(window) {
        chunks.extend(
            builder
                .push_jobs(w)
                .expect("a window")
                .into_iter()
                .map(|job| job.generate()),
        );
    }
    let mut traces = builder.finish(&logs[cut..]).expect("the last window");
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    traces
}

/// [`windowed`] with the builder split: the walker on one thread, the
/// accumulator on another, the chunks generated by their jobs.
fn windowed_split(program: &Elf, logs: &[Log], max_rows: &MaxRowsConfig, window: usize) -> Traces {
    let mut builder = WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder");
    let body = logs.len() - 1;
    let cut = body - body % window;
    let chunks = {
        let (mut walker, mut accumulator) = builder.split();
        std::thread::scope(|scope| {
            let (tx, rx) = std::sync::mpsc::sync_channel(2);
            let walking = scope.spawn(move || {
                for w in logs[..cut].chunks(window) {
                    tx.send(walker.walk(w).expect("a window"))
                        .expect("the accumulator");
                }
            });
            let mut chunks = Vec::new();
            for walked in rx {
                chunks.extend(
                    accumulator
                        .absorb(walked)
                        .into_iter()
                        .map(|job| job.generate()),
                );
            }
            walking.join().expect("the walker");
            chunks
        })
    };
    let mut traces = builder.finish(&logs[cut..]).expect("the last window");
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    traces
}

fn rows(t: &Table) -> Vec<Vec<FieldElement<GoldilocksField>>> {
    (0..t.main_table.height)
        .map(|r| t.main_table.get_row(r).to_vec())
        .collect()
}

/// Equal tables, row for row — also the six that lay their rows out in
/// `HashMap` order, since every such map in the process hashes with one state
/// (`tables::trace_hash`).
fn same(what: &str, a: &Table, b: &Table) {
    assert_eq!(
        (a.main_table.width, a.main_table.height),
        (b.main_table.width, b.main_table.height),
        "{what}: shape"
    );
    assert!(rows(a) == rows(b), "{what}: rows differ");
}

fn same_list(what: &str, a: &[Table], b: &[Table]) {
    assert_eq!(a.len(), b.len(), "{what}: table count");
    for (i, (x, y)) in a.iter().zip(b).enumerate() {
        same(&format!("{what}[{i}]"), x, y);
    }
}

fn same_traces(a: &Traces, b: &Traces) {
    same_list("CPU", &a.cpus, &b.cpus);
    same_list("MEMW_R", &a.memw_registers, &b.memw_registers);
    same_list("MEMW_A", &a.memw_aligneds, &b.memw_aligneds);
    same_list("MEMW", &a.memws, &b.memws);
    same_list("LOAD", &a.loads, &b.loads);
    same_list("STORE", &a.stores, &b.stores);
    same_list("SHIFT", &a.shifts, &b.shifts);
    same_list("CPU32", &a.cpu32s, &b.cpu32s);
    same_list("COMMIT", &a.commits, &b.commits);
    same_list("KECCAK", &a.keccaks, &b.keccaks);
    same_list("KECCAK_RND", &a.keccak_rnds, &b.keccak_rnds);
    same_list("ECSM", &a.ecsms, &b.ecsms);
    same_list("ECDAS", &a.ecdases, &b.ecdases);
    same_list("HINT", &a.hints, &b.hints);
    same_list("PAGE", &a.pages, &b.pages);
    same_list("LT", &a.lts, &b.lts);
    same_list("MUL", &a.muls, &b.muls);
    same_list("DVRM", &a.dvrms, &b.dvrms);
    same_list("BRANCH", &a.branches, &b.branches);
    same_list("EQ", &a.eqs, &b.eqs);
    same_list("BYTEWISE", &a.bytewises, &b.bytewises);
    same("BITWISE", &a.bitwise, &b.bitwise);
    same("DECODE", &a.decode, &b.decode);
    same("REGISTER", &a.register, &b.register);
    same("HALT", &a.halt, &b.halt);
    same("KECCAK_RC", &a.keccak_rc, &b.keccak_rc);
    same("BLAKE3", &a.blake3, &b.blake3);
    assert_eq!(a.public_output_bytes, b.public_output_bytes);
    assert_eq!(a.num_blake3_ops, b.num_blake3_ops);
    assert_eq!(a.page_configs.len(), b.page_configs.len());
    assert_eq!(
        format!("{:?}", a.table_counts()),
        format!("{:?}", b.table_counts())
    );
}

/// ★ Two builds of one run in one process lay out every table alike, row for
/// row: also LT, EQ, BYTEWISE, BRANCH, MUL and DVRM, which deduplicate through a
/// `HashMap` and lay rows out in its order (each map took fresh random keys
/// before `tables::trace_hash`). Regenerating a streamed chunk needs this.
#[test]
fn every_build_in_a_process_lays_out_the_hash_ordered_tables_alike() {
    use crate::tables::dvrm::{DvrmOperation, generate_dvrm_trace};
    use crate::tables::mul::{MulOperation, generate_mul_trace};
    let mut rows = [0usize; 4];
    for (name, max_rows) in [
        ("all_instructions_64", MaxRowsConfig::small()),
        ("bench_32k", MaxRowsConfig::uniform(1 << 14)),
    ] {
        let (program, logs) = run(name);
        let (a, b) = (
            whole(&program, &logs, &max_rows),
            whole(&program, &logs, &max_rows),
        );
        same_traces(&a, &b);
        for (most, list) in rows
            .iter_mut()
            .zip([&a.lts, &a.eqs, &a.bytewises, &a.branches])
        {
            *most = (*most).max(list.iter().map(|t| t.main_table.height).sum());
        }
    }
    // Enough distinct operations that two hash keys would order them apart.
    assert!(rows.iter().all(|&n| n >= 8), "rows per table: {rows:?}");
    // The programs divide and multiply by few distinct operands: 199 of each.
    let muls: Vec<(MulOperation, bool)> = (1..200u64)
        .map(|i| {
            let op = MulOperation {
                lhs: i.wrapping_mul(0x9e37_79b9_7f4a_7c15),
                lhs_signed: i % 2 == 0,
                rhs: i * 7919,
                rhs_signed: i % 3 == 0,
            };
            (op, i % 5 == 0)
        })
        .collect();
    same(
        "MUL",
        &generate_mul_trace(&muls),
        &generate_mul_trace(&muls),
    );
    let dvrms: Vec<(DvrmOperation, bool)> = (1..200u64)
        .map(|i| {
            let op = DvrmOperation {
                n: i.wrapping_mul(0x9e37_79b9_7f4a_7c15),
                d: i % 13 + 1,
                signed: i % 2 == 0,
            };
            (op, i % 3 == 0)
        })
        .collect();
    same(
        "DVRM",
        &generate_dvrm_trace(&dvrms),
        &generate_dvrm_trace(&dvrms),
    );
}

/// The hash state itself: the process's state hashes alike in every clone, and
/// the fixed state (`LAMBDA_VM_FIXED_TRACE_HASH=1`) is SipHash-1-3 with zero
/// keys, the same in every process.
#[test]
fn the_trace_hash_state_is_one_per_process() {
    use crate::tables::trace_hash::{TraceHashState, trace_hash_state};
    use std::hash::BuildHasher;
    let key = (0x1234_5678_9abc_def0u64, true);
    assert_eq!(
        trace_hash_state().hash_one(key),
        trace_hash_state().hash_one(key)
    );
    assert_eq!(
        TraceHashState::fixed().hash_one(key),
        std::hash::BuildHasherDefault::<std::collections::hash_map::DefaultHasher>::default()
            .hash_one(key)
    );
}

/// ★ The builder is a schedule: at every window length — one cycle, less than a
/// chunk, exactly a chunk, not a divisor of it, longer than the run — the
/// windowed build is the whole-run build, table for table, and it did stream.
#[test]
fn windowed_builds_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    for name in [
        "sub",
        "all_instructions_64",
        "test_keccak",
        "test_keccak_multi",
    ] {
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        for window in [1, 7, 32, 33, 1000, logs.len()] {
            let (traces, streamed) = windowed(&program, &logs, &max_rows, window.max(1));
            same_traces(&reference, &traces);
            if logs.len() > 2 * max_rows.cpu && window < logs.len() / 2 {
                assert!(streamed > 0, "{name}, window {window}: nothing streamed");
            }
        }
    }
}

/// The same through chunk jobs generated by the caller.
#[test]
fn windowed_jobs_build_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    for name in ["all_instructions_64", "test_keccak_multi"] {
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        for window in [7, 33] {
            same_traces(
                &reference,
                &windowed_jobs(&program, &logs, &max_rows, window),
            );
        }
    }
}

/// The same with the builder split across two threads.
#[test]
fn a_split_builder_builds_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    for name in ["all_instructions_64", "test_keccak_multi"] {
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        for window in [1, 7, 33] {
            same_traces(
                &reference,
                &windowed_split(&program, &logs, &max_rows, window),
            );
        }
    }
}

/// And at the production chunk sizes, where a small program streams nothing
/// and the builder is the whole-run build over windows.
#[test]
fn windowed_builds_the_whole_run_tables_at_production_sizes() {
    let max_rows = MaxRowsConfig::default();
    let (program, logs) = run("all_instructions_64");
    let reference = whole(&program, &logs, &max_rows);
    let (traces, _) = windowed(&program, &logs, &max_rows, 64);
    same_traces(&reference, &traces);
}

/// The whole-run KECCAK_RND table cut into tables of `rows` rows — rows
/// `[k·rows, (k+1)·rows)`, as the block proof splits it.
fn split_keccak_rnd(t: &Traces, per: usize) -> Vec<Table> {
    t.keccak_rnds
        .iter()
        .flat_map(|table| {
            let width = table.main_table.width;
            let all = rows(table);
            if all.len() <= per {
                return vec![rebuild(&all, width)];
            }
            all.chunks(per).map(|chunk| rebuild(chunk, width)).collect()
        })
        .collect()
}

fn rebuild(rows: &[Vec<FieldElement<GoldilocksField>>], width: usize) -> Table {
    TraceTable::new_main(rows.iter().flatten().copied().collect(), width, 1)
}

/// A slice of KECCAK_RND rows built from the ops that reach it is that slice of
/// the whole table, wherever the slice cuts an op's 24 rows.
#[test]
fn keccak_rnd_rows_are_slices_of_the_whole_table() {
    use crate::tables::keccak_rnd::{
        KeccakRoundOperation, generate_keccak_rnd_rows, generate_keccak_rnd_trace,
    };
    let ops: Vec<KeccakRoundOperation> = (0..11u64)
        .map(|i| KeccakRoundOperation {
            timestamp: 100 + 3 * i,
            input: core::array::from_fn(|j| i.wrapping_mul(0x9e37_79b9_7f4a_7c15) ^ j as u64),
            output: [0; 25],
        })
        .collect();
    let whole = rows(&generate_keccak_rnd_trace(&ops));
    for (skip, len) in [
        (0, 32),
        (32, 32),
        (50, 64),
        (23, 1),
        (100, 156),
        (256, 0),
        (200, 56),
    ] {
        let slice = rows(&generate_keccak_rnd_rows(&ops, skip, len));
        assert_eq!(slice.len(), len);
        assert!(
            slice[..] == whole[skip..skip + len],
            "rows {skip}..{}",
            skip + len
        );
    }
}

/// ★ With KECCAK_RND cut into chunks, the windowed build streams them and is the
/// whole-run build with KECCAK_RND split the same way, table for table; at
/// one-cycle windows it did stream some.
#[test]
fn windowed_streams_keccak_rnd_as_the_split_whole_run_table() {
    let max_rows = MaxRowsConfig::small();
    for name in ["test_keccak", "test_keccak_multi"] {
        let (program, logs) = run(name);
        let mut reference = whole(&program, &logs, &max_rows);
        for per in [32usize, 64, 128] {
            let split = split_keccak_rnd(&reference, per);
            for window in [1, 7, 33] {
                let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows)
                    .expect("the builder")
                    .keccak_rnd_chunks(per)
                    .expect("a chunk size");
                let body = logs.len() - 1;
                let cut = body - body % window;
                let mut chunks = Vec::new();
                for w in logs[..cut].chunks(window) {
                    chunks.extend(builder.push(w).expect("a window"));
                }
                let streamed = chunks
                    .iter()
                    .filter(|c| c.table == StreamTable::KeccakRnd)
                    .count();
                let mut traces = builder.finish(&logs[cut..]).expect("the last window");
                traces.insert_streamed(chunks).expect("placeholders");
                same_list(
                    &format!("{name} KECCAK_RND/{per} window {window}"),
                    &split,
                    &traces.keccak_rnds,
                );
                // One-cycle windows push every cycle but the last, so every
                // chunk the ops fill before the run ends streams.
                let full = split.iter().filter(|t| t.main_table.height == per).count();
                if window == 1 && full > 1 {
                    assert!(streamed > 0, "{name}, rows {per}: none streamed");
                }
                // Every other table is the whole-run one.
                let keccak =
                    std::mem::replace(&mut reference.keccak_rnds, traces.keccak_rnds.clone());
                same_traces(&reference, &traces);
                reference.keccak_rnds = keccak;
            }
        }
    }
}

/// With KECCAK_RND built as its tables at the finish alone, the windowed build
/// hands none out and is the whole-run build with KECCAK_RND split the same
/// way, table for table — the split's copy without the copy.
#[test]
fn windowed_builds_keccak_rnd_at_finish_as_the_split_whole_run_table() {
    let max_rows = MaxRowsConfig::small();
    for name in ["test_keccak", "test_keccak_multi"] {
        let (program, logs) = run(name);
        let mut reference = whole(&program, &logs, &max_rows);
        for per in [32usize, 64, 128] {
            let split = split_keccak_rnd(&reference, per);
            for window in [1, 33] {
                let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows)
                    .expect("the builder")
                    .keccak_rnd_chunks_at_finish(per)
                    .expect("a chunk size");
                let body = logs.len() - 1;
                let cut = body - body % window;
                let mut chunks = Vec::new();
                for w in logs[..cut].chunks(window) {
                    chunks.extend(builder.push(w).expect("a window"));
                }
                assert!(
                    chunks.iter().all(|c| c.table != StreamTable::KeccakRnd),
                    "{name}: a KECCAK_RND chunk was handed out"
                );
                let mut traces = builder.finish(&logs[cut..]).expect("the last window");
                traces.insert_streamed(chunks).expect("placeholders");
                same_list(
                    &format!("{name} KECCAK_RND/{per} at the finish, window {window}"),
                    &split,
                    &traces.keccak_rnds,
                );
                let keccak =
                    std::mem::replace(&mut reference.keccak_rnds, traces.keccak_rnds.clone());
                same_traces(&reference, &traces);
                reference.keccak_rnds = keccak;
            }
        }
    }
    assert!(
        WindowedTraceBuilder::new(&run("test_keccak").0, &[], &max_rows)
            .expect("the builder")
            .keccak_rnd_chunks_at_finish(16)
            .is_err(),
        "16 rows is under the 32 a KECCAK_RND op's rows need"
    );
}

/// Every LT op with its multiplicity summed over all of `lts`' chunks: what LT's
/// constraints and the bus see, whichever chunk holds an op.
fn lt_multiplicities(lts: &[Table]) -> std::collections::BTreeMap<Vec<u64>, u64> {
    let mu = crate::tables::lt::cols::MU;
    let mut out = std::collections::BTreeMap::new();
    for table in lts {
        for row in rows(table) {
            let m = row[mu].canonical();
            if m == 0 {
                continue;
            }
            let key: Vec<u64> = row
                .iter()
                .enumerate()
                .filter(|(c, _)| *c != mu)
                .map(|(_, v)| v.canonical())
                .collect();
            *out.entry(key).or_insert(0) += m;
        }
    }
    out
}

/// ★ With each window's MEMW-derived LT ops streamed (the block path), every
/// table but LT is the whole-run build's, LT has as many chunks, and every LT
/// op carries its whole-run multiplicity summed over the chunks — though the
/// chunks hold other ops. Dropping one row of one chunk breaks that equality,
/// so it is what the test checks. And it streams more LT chunks than without.
#[test]
fn windowed_streams_memw_lt_with_the_whole_run_lt_multiplicities() {
    let max_rows = MaxRowsConfig::small();
    let mut more_streamed = false;
    for name in ["all_instructions_64", "test_keccak_multi"] {
        let (program, logs) = run(name);
        let mut reference = whole(&program, &logs, &max_rows);
        let want = lt_multiplicities(&reference.lts);
        for window in [1, 7, 33] {
            let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows)
                .expect("the builder")
                .stream_memw_lt();
            let body = logs.len() - 1;
            let cut = body - body % window;
            let mut chunks = Vec::new();
            for w in logs[..cut].chunks(window) {
                chunks.extend(builder.push(w).expect("a window"));
            }
            let lt_streamed = chunks.iter().filter(|c| c.table == StreamTable::Lt).count();
            let mut traces = builder.finish(&logs[cut..]).expect("the last window");
            traces.insert_streamed(chunks).expect("placeholders");
            assert_eq!(
                traces.lts.len(),
                reference.lts.len(),
                "{name}/{window}: LT chunks"
            );
            assert!(
                lt_multiplicities(&traces.lts) == want,
                "{name}/{window}: LT multiplicities"
            );
            let plain_lt = {
                let mut builder =
                    WindowedTraceBuilder::new(&program, &[], &max_rows).expect("the builder");
                logs[..cut]
                    .chunks(window)
                    .flat_map(|w| builder.push(w).expect("a window"))
                    .filter(|c| c.table == StreamTable::Lt)
                    .count()
            };
            assert!(
                lt_streamed >= plain_lt,
                "{name}/{window}: fewer LT chunks streamed"
            );
            more_streamed |= lt_streamed > plain_lt;
            // Every other table is the whole-run one.
            let lts = std::mem::replace(&mut reference.lts, traces.lts.clone());
            same_traces(&reference, &traces);
            reference.lts = lts;

            // The mutation: one row of one chunk dropped (its multiplicity zeroed).
            let mut dropped = traces.lts.clone();
            let mu = crate::tables::lt::cols::MU;
            let (k, row) = dropped
                .iter()
                .enumerate()
                .find_map(|(k, t)| {
                    (0..t.main_table.height)
                        .find(|&r| t.main_table.get(r, mu).canonical() != 0)
                        .map(|r| (k, r))
                })
                .expect("a real LT row");
            dropped[k]
                .main_table
                .set(row, mu, FieldElement::<GoldilocksField>::zero());
            assert!(
                lt_multiplicities(&dropped) != want,
                "{name}/{window}: a dropped row must change the multiplicities"
            );
        }
    }
    assert!(
        more_streamed,
        "the MEMW-derived LT ops never streamed a chunk more"
    );
}

/// [`WindowedTraceBuilder::held_streamed_ops`]'s report.
type Held = [(usize, usize); 8];

/// A windowed build over windows of `window` cycles with the builder `configure`
/// returns, its chunks generated by their jobs on the walker/accumulator split
/// (the block drivers' path) or through `push`; and, under
/// `drop_streamed_ops`, the most streamed ops it held after any window.
fn windowed_with(
    program: &Elf,
    logs: &[Log],
    max_rows: &MaxRowsConfig,
    window: usize,
    split: bool,
    configure: impl Fn(WindowedTraceBuilder<'_>) -> WindowedTraceBuilder<'_>,
) -> (Traces, Option<Held>) {
    let (traces, held, _) = windowed_streaming(program, logs, max_rows, window, split, configure);
    (traces, held)
}

/// [`windowed_with`], and the tables it streamed chunks of.
fn windowed_streaming(
    program: &Elf,
    logs: &[Log],
    max_rows: &MaxRowsConfig,
    window: usize,
    split: bool,
    configure: impl Fn(WindowedTraceBuilder<'_>) -> WindowedTraceBuilder<'_>,
) -> (Traces, Option<Held>, std::collections::BTreeSet<String>) {
    let mut builder =
        configure(WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder"));
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut chunks = Vec::new();
    let mut most: Option<Held> = None;
    let mut note = |held: Option<Held>| {
        if let Some(held) = held {
            let most = most.get_or_insert([(0, 0); 8]);
            for (m, h) in most.iter_mut().zip(held) {
                *m = (m.0.max(h.0), m.1.max(h.1));
            }
        }
    };
    for w in logs[..cut].chunks(window) {
        if split {
            let (mut walker, mut accumulator) = builder.split();
            let walked = walker.walk(w).expect("a window");
            chunks.extend(
                accumulator
                    .absorb(walked)
                    .into_iter()
                    .map(|job| job.generate()),
            );
        } else {
            chunks.extend(builder.push(w).expect("a window"));
        }
        note(builder.held_streamed_ops());
    }
    let streamed = chunks.iter().map(|c| format!("{:?}", c.table)).collect();
    let mut traces = builder.finish(&logs[cut..]).expect("the last window");
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    (traces, most, streamed)
}

/// ★ Dropping each streamed chunk's ops as it leaves builds the whole-run
/// tables, table for table, at every window length, through `push` and through
/// the split; with the MEMW-derived LT ops streamed as well it builds what that
/// builder builds, LT carrying the whole-run multiplicities. Also with CPU
/// chunks of 24 rows, whose dropped chunks each pad 8 rows, and with chunks of 4
/// rows (one op for the rarer tables), so that every streamed table drops
/// chunks.
#[test]
fn dropping_the_streamed_ops_builds_the_same_tables() {
    let small = MaxRowsConfig::small();
    let padded = MaxRowsConfig {
        cpu: 24,
        ..MaxRowsConfig::small()
    };
    let tiny = MaxRowsConfig::uniform(4);
    // The rarer tables (MEMW holds only misaligned and mixed-timestamp
    // accesses and width-1 register writes) get a handful of ops per program:
    // one op a chunk.
    let one_op = MaxRowsConfig {
        memw: 1,
        load: 1,
        shift: 1,
        store: 1,
        ..MaxRowsConfig::uniform(4)
    };
    let mut dropped = std::collections::BTreeSet::new();
    for (name, max_rows) in [
        ("sub", &small),
        ("all_instructions_64", &small),
        ("test_keccak", &small),
        ("test_keccak_multi", &small),
        ("all_instructions_64", &padded),
        ("test_keccak_multi", &padded),
        ("all_instructions_64", &tiny),
        ("test_keccak_multi", &tiny),
        ("misalign_sd", &one_op),
        ("test_commit_split", &one_op),
        ("all_loadstore_32", &one_op),
        ("all_instructions_64", &one_op),
    ] {
        let max_rows = max_rows.clone();
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        let want = lt_multiplicities(&reference.lts);
        for window in [1, 7, 32, 33, 1000, logs.len()] {
            let window = window.max(1);
            let (lt_streamed, _) = windowed_with(&program, &logs, &max_rows, window, false, |b| {
                b.stream_memw_lt()
            });
            for split in [false, true] {
                let (dropping, held, streamed) =
                    windowed_streaming(&program, &logs, &max_rows, window, split, |b| {
                        b.drop_streamed_ops().expect("before any window")
                    });
                assert!(
                    held.is_some() || logs.len() <= window + 1,
                    "{name}/{window}"
                );
                dropped.extend(streamed);
                same_traces(&reference, &dropping);
                let (both, _) = windowed_with(&program, &logs, &max_rows, window, split, |b| {
                    b.stream_memw_lt()
                        .drop_streamed_ops()
                        .expect("before any window")
                });
                same_traces(&lt_streamed, &both);
                assert!(
                    lt_multiplicities(&both.lts) == want,
                    "{name}/{window}: LT multiplicities"
                );
            }
        }
    }
    for table in [
        "Cpu",
        "MemwRegister",
        "MemwAligned",
        "Memw",
        "Load",
        "Lt",
        "Shift",
        "Store",
    ] {
        assert!(dropped.contains(table), "no {table} chunk was dropped");
    }
}

/// The same with KECCAK_RND cut into streamed chunks.
#[test]
fn dropping_the_streamed_ops_streams_keccak_rnd_the_same() {
    let max_rows = MaxRowsConfig::small();
    for name in ["test_keccak", "test_keccak_multi"] {
        let (program, logs) = run(name);
        for per in [32usize, 128] {
            for window in [1, 7, 33] {
                let (keeping, _) = windowed_with(&program, &logs, &max_rows, window, false, |b| {
                    b.keccak_rnd_chunks(per).expect("rows")
                });
                let (dropping, _) = windowed_with(&program, &logs, &max_rows, window, true, |b| {
                    b.keccak_rnd_chunks(per)
                        .expect("rows")
                        .drop_streamed_ops()
                        .expect("before any window")
                });
                same_traces(&keeping, &dropping);
            }
        }
    }
}

/// ★ Dropping bounds what the builder holds: after every window each streamed
/// table holds less than a chunk of ops not handed out, and its lists take room
/// for at most a window's part more — however long the run. Keeping every
/// window would hold the run's ops, which here are many times that.
#[test]
fn dropping_the_streamed_ops_holds_less_than_a_chunk_per_table() {
    let max_rows = MaxRowsConfig::small();
    let maxes = [
        max_rows.cpu,
        max_rows.memw_register,
        max_rows.memw_aligned,
        max_rows.memw,
        max_rows.load,
        max_rows.lt,
        max_rows.shift,
        max_rows.store,
    ];
    let mut long = false;
    for name in ["bench_32k", "test_keccak_multi"] {
        let (program, logs) = run(name);
        for window in [1, 7, 33] {
            let (_, held) = windowed_with(&program, &logs, &max_rows, window, true, |b| {
                b.drop_streamed_ops().expect("before any window")
            });
            let held = held.expect("dropping reports what it holds");
            // A window's part: one CPU op per cycle; at most 256 ops of another
            // table per cycle (a keccak ECALL's memory accesses are the most a
            // cycle makes: ≈ 170 MEMW_A ops on test_keccak_multi).
            for (table, ((not_out, room), max)) in held.iter().zip(maxes).enumerate() {
                let per_cycle = if table == 0 { 1 } else { 256 };
                assert!(
                    *not_out < max,
                    "{name}/{window}: table {table} holds {not_out} ops, a full chunk"
                );
                assert!(
                    *room < max + per_cycle * window,
                    "{name}/{window}: table {table} takes room for {room} ops"
                );
            }
            // Keeping every window would hold the run's CPU ops.
            long |= logs.len() > 100 * (max_rows.cpu + window);
        }
        // Without the option nothing is reported.
        let (_, held) = windowed_with(&program, &logs, &max_rows, 7, true, |b| b);
        assert!(held.is_none());
    }
    assert!(
        long,
        "no run long enough that keeping it would fail the CPU bound"
    );
}

/// The option is set before the first window, or refused.
#[test]
fn dropping_the_streamed_ops_is_refused_after_a_window() {
    let max_rows = MaxRowsConfig::small();
    let (program, logs) = run("all_instructions_64");
    let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows).expect("the builder");
    builder.push(&logs[..7]).expect("a window");
    assert!(builder.drop_streamed_ops().is_err());
}

/// A non-final window may not halt, as a whole-run build refuses an epoch that
/// halts early.
#[test]
fn a_window_that_halts_before_the_end_is_refused() {
    let max_rows = MaxRowsConfig::small();
    let (program, logs) = run("sub");
    let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows).expect("the builder");
    assert!(builder.push(&logs).is_err());
}

/// A streamed chunk only goes back into a placeholder.
#[test]
fn a_chunk_is_only_put_back_into_its_placeholder() {
    let max_rows = MaxRowsConfig::small();
    let (program, logs) = run("all_instructions_64");
    let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows).expect("the builder");
    let chunks = builder.push(&logs[..logs.len() - 1]).expect("a window");
    assert!(
        chunks.iter().any(|c| c.table == StreamTable::Cpu),
        "a CPU chunk streams"
    );
    let mut traces = builder.finish(&logs[logs.len() - 1..]).expect("the rest");
    let again: Vec<_> = chunks
        .iter()
        .filter(|c| c.table == StreamTable::Cpu)
        .map(|c| crate::tables::trace_builder::StreamedChunk {
            table: c.table,
            index: c.index,
            trace: c.trace.clone(),
        })
        .collect();
    traces.insert_streamed(chunks).expect("first time");
    assert!(traces.insert_streamed(again).is_err());
}

/// One digest per table: its width, its height and its rows in order (also
/// for the six that lay their rows out in `HashMap` order: one hash state per
/// process, `tables::trace_hash`).
fn table_digests(t: &Traces) -> Vec<(String, String)> {
    use rayon::prelude::*;
    let mut tables: Vec<(String, &Table)> = Vec::new();
    let lists: [(&str, &Vec<Table>); 21] = [
        ("CPU", &t.cpus),
        ("MEMW_R", &t.memw_registers),
        ("MEMW_A", &t.memw_aligneds),
        ("MEMW", &t.memws),
        ("LOAD", &t.loads),
        ("STORE", &t.stores),
        ("SHIFT", &t.shifts),
        ("CPU32", &t.cpu32s),
        ("COMMIT", &t.commits),
        ("KECCAK", &t.keccaks),
        ("KECCAK_RND", &t.keccak_rnds),
        ("ECSM", &t.ecsms),
        ("ECDAS", &t.ecdases),
        ("HINT", &t.hints),
        ("PAGE", &t.pages),
        ("LT", &t.lts),
        ("MUL", &t.muls),
        ("DVRM", &t.dvrms),
        ("BRANCH", &t.branches),
        ("EQ", &t.eqs),
        ("BYTEWISE", &t.bytewises),
    ];
    for (name, list) in lists {
        for (i, table) in list.iter().enumerate() {
            tables.push((format!("{name}[{i}]"), table));
        }
    }
    for (name, table) in [
        ("BITWISE", &t.bitwise),
        ("DECODE", &t.decode),
        ("REGISTER", &t.register),
        ("HALT", &t.halt),
        ("KECCAK_RC", &t.keccak_rc),
        ("BLAKE3", &t.blake3),
    ] {
        tables.push((name.to_string(), table));
    }
    tables
        .into_par_iter()
        .map(|(name, table)| {
            // Streamed, never materialized: a block's traces are tens of GiB.
            let row_bytes = |r: usize| -> Vec<u8> {
                table
                    .main_table
                    .get_row(r)
                    .iter()
                    .flat_map(|v| v.canonical().to_le_bytes())
                    .collect()
            };
            let mut h = blake3::Hasher::new();
            h.update(&(table.main_table.width as u64).to_le_bytes());
            h.update(&(table.main_table.height as u64).to_le_bytes());
            for r in 0..table.main_table.height {
                h.update(&row_bytes(r));
            }
            (name, h.finalize().to_hex()[..16].to_string())
        })
        .collect()
}

/// ★ Box only (`--ignored`): on a real block, the windowed build — split across
/// a walker and an accumulator thread, its chunks generated on a third, beside a
/// thread that keeps the host's memory busy — gives the whole-run build's
/// tables, twice. Reads `BLOCK_WHIR_ELF` and `BLOCK_WHIR_INPUT`; prints
/// `DETERMINISM` lines.
#[test]
#[ignore = "a real block: box only"]
fn the_windowed_build_of_a_real_block_is_the_whole_run_build_every_time() {
    use std::sync::atomic::{AtomicBool, Ordering};

    let elf = std::fs::read(std::env::var("BLOCK_WHIR_ELF").expect("BLOCK_WHIR_ELF")).unwrap();
    let input =
        std::fs::read(std::env::var("BLOCK_WHIR_INPUT").expect("BLOCK_WHIR_INPUT")).unwrap();
    let program = Elf::load(&elf).expect("the ELF loads");
    let max_rows = MaxRowsConfig::uniform(1 << 21);
    let logs = Executor::new(&program, input.clone())
        .expect("the executor starts")
        .run()
        .expect("the block runs")
        .logs;
    let reference = {
        let t = Traces::from_elf_and_logs(
            &program,
            &logs,
            &max_rows,
            &input,
            #[cfg(feature = "disk-spill")]
            stark::storage_mode::StorageMode::Ram,
        )
        .expect("the whole-run build");
        table_digests(&t)
    };
    println!("DETERMINISM whole-run: {} tables", reference.len());
    let window = 1usize << 20;
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut runs_equal = 0usize;
    for run_index in 0..2 {
        let stop = AtomicBool::new(false);
        let digests = std::thread::scope(|scope| {
            // The contention: a thread copying a GiB back and forth.
            let busy = scope.spawn(|| {
                let mut a = vec![1u8; 1 << 30];
                let mut b = vec![0u8; 1 << 30];
                while !stop.load(Ordering::Relaxed) {
                    b.copy_from_slice(&a);
                    a.copy_from_slice(&b);
                }
            });
            let mut builder =
                WindowedTraceBuilder::new(&program, &input, &max_rows).expect("the builder");
            let chunks = {
                let (mut walker, mut accumulator) = builder.split();
                std::thread::scope(|inner| {
                    let (wtx, wrx) = std::sync::mpsc::sync_channel(2);
                    let (jtx, jrx) = std::sync::mpsc::sync_channel(64);
                    let logs = &logs;
                    inner.spawn(move || {
                        for w in logs[..cut].chunks(window) {
                            wtx.send(walker.walk(w).expect("a window"))
                                .expect("accumulator");
                        }
                    });
                    let generator = inner.spawn(move || {
                        jrx.into_iter()
                            .map(crate::tables::trace_builder::ChunkJob::generate)
                            .collect::<Vec<_>>()
                    });
                    for walked in wrx {
                        for job in accumulator.absorb(walked) {
                            jtx.send(job).expect("generator");
                        }
                    }
                    drop(jtx);
                    generator.join().expect("the generator")
                })
            };
            let streamed = chunks.len();
            let mut traces = builder.finish(&logs[cut..]).expect("the last window");
            traces.insert_streamed(chunks).expect("placeholders");
            stop.store(true, Ordering::Relaxed);
            busy.join().expect("the busy thread");
            println!("DETERMINISM windowed run {run_index}: {streamed} chunks streamed");
            table_digests(&traces)
        });
        let differing: Vec<&String> = reference
            .iter()
            .zip(&digests)
            .filter(|(a, b)| a != b)
            .map(|(a, _)| &a.0)
            .collect();
        println!(
            "DETERMINISM windowed run {run_index}: {} tables, {} differ from the whole-run build {:?}",
            digests.len(),
            differing.len(),
            differing
        );
        if digests.len() == reference.len() && differing.is_empty() {
            runs_equal += 1;
        }
    }
    println!("DETERMINISM RESULT: {runs_equal}/2 windowed runs equal the whole-run build");
    assert_eq!(runs_equal, 2);
}

/// ★ The lean walk (D-EXEC E1: each cycle's decode from a dense table, memory
/// accesses found by page, the in-walk BITWISE lookups counted from the CPU and
/// LOAD ops instead of listed, the routing in one pass) builds the whole-run
/// tables, and so does the walk it replaces: at every window length, with and
/// without dropping the streamed ops (the dropping builds through the split),
/// on programs with keccak calls, narrow and odd-offset loads and stores; and
/// so does each part alone.
#[test]
fn the_lean_walk_builds_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    let only = |f: fn(&mut WalkLean)| {
        let mut lean = WalkLean::NONE;
        f(&mut lean);
        lean
    };
    let parts = [
        only(|l| l.decode = true),
        only(|l| l.memory = true),
        only(|l| l.lookups = true),
        only(|l| l.route = true),
    ];
    for name in [
        "sub",
        "all_instructions_64",
        "test_keccak",
        "test_keccak_multi",
        "lw_sw_offset_odd",
        "test_memw_split_ts",
    ] {
        let (program, logs) = run(name);
        let reference = whole(&program, &logs, &max_rows);
        for window in [1, 7, 32, 33, 1000, logs.len()] {
            let mut settings = vec![WalkLean::NONE, WalkLean::ALL];
            if window == 33 && name.starts_with("test_") {
                settings.extend(parts);
            }
            for lean in settings {
                for drop in [false, true] {
                    let (traces, _) =
                        windowed_with(&program, &logs, &max_rows, window, drop, |builder| {
                            let builder = builder.walk_lean(lean);
                            if drop {
                                builder
                                    .drop_streamed_ops()
                                    .expect("before the first window")
                            } else {
                                builder
                            }
                        });
                    same_traces(&reference, &traces);
                }
            }
        }
    }
}

/// How a build that counts its windows apart feeds its counter.
#[derive(Clone, Copy, Debug)]
enum Counting {
    /// `push`: on the builder's own thread.
    Push,
    /// The split, each window's jobs counted into one counter as they come.
    Split,
    /// The split, every job counted at the end, last first, into two counters.
    SplitReversed,
}

/// The windowed build with the table phase's commutative BITWISE sources
/// counted window by window ([`WindowedTraceBuilder::count_windows_apart`]),
/// ops dropped or kept; `mutate` sees every count job and the counters before
/// they are added (the split only).
fn windowed_counting(
    program: &Elf,
    logs: &[Log],
    max_rows: &MaxRowsConfig,
    window: usize,
    drop: bool,
    counting: Counting,
    mutate: &dyn Fn(&mut Vec<crate::tables::trace_builder::CountJob>, &mut [Counter]),
) -> Result<Traces, crate::Error> {
    let builder = WindowedTraceBuilder::new(program, &[], max_rows).expect("the builder");
    let builder = if drop {
        builder.drop_streamed_ops().expect("before any window")
    } else {
        builder
    };
    let mut builder = builder.count_windows_apart().expect("before any window");
    let body = logs.len() - 1;
    let cut = body - body % window;
    let mut chunks = Vec::new();
    let mut counters = vec![Counter::new(), Counter::new()];
    let mut later = Vec::new();
    for w in logs[..cut].chunks(window) {
        match counting {
            Counting::Push => chunks.extend(builder.push(w)?),
            Counting::Split | Counting::SplitReversed => {
                let (mut walker, mut accumulator) = builder.split();
                let walked = walker.walk(w)?;
                chunks.extend(
                    accumulator
                        .absorb(walked)
                        .into_iter()
                        .map(|job| job.generate()),
                );
                let mut jobs = accumulator.take_count_jobs();
                mutate(&mut jobs, &mut counters);
                if matches!(counting, Counting::Split) {
                    jobs.into_iter().for_each(|job| counters[0].count(job));
                } else {
                    later.extend(jobs);
                }
            }
        }
    }
    let n = later.len();
    for (i, job) in later.into_iter().rev().enumerate() {
        counters[usize::from(2 * i >= n)].count(job);
    }
    if !matches!(counting, Counting::Push) {
        mutate(&mut Vec::new(), &mut counters);
        for counter in counters {
            builder.add_counter(counter)?;
        }
    }
    let mut traces = builder.finish(&logs[cut..])?;
    traces
        .insert_streamed(chunks)
        .expect("every chunk has a placeholder");
    Ok(traces)
}

fn no_mutation(_: &mut Vec<crate::tables::trace_builder::CountJob>, _: &mut [Counter]) {}

/// The programs whose windows carry every source a counter counts: BRANCH,
/// EQ, BYTEWISE, MUL, DVRM and CPU32 (all_instructions_64), KECCAK, BLAKE3 in
/// both modes, ECSM and ECDAS, COMMIT, HINT.
fn counted_programs() -> Vec<(&'static str, Elf, Vec<Log>)> {
    let mut programs: Vec<_> = [
        "all_instructions_64",
        "test_keccak_multi",
        "test_blake3",
        "test_blake3_absorb",
        "test_ecsm_multi",
        "test_commit_split",
    ]
    .into_iter()
    .map(|name| {
        let (program, logs) = run(name);
        (name, program, logs)
    })
    .collect();
    let hint = std::fs::read(
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../executor/program_artifacts/rust/hint_min.elf"),
    )
    .expect("hint_min.elf not found — run `make compile-programs-rust`");
    let program = Elf::load(&hint).expect("the hint guest loads");
    let logs = Executor::new(&program, Vec::new())
        .expect("the executor starts")
        .run()
        .expect("the hint guest runs")
        .logs;
    programs.push(("hint_min", program, logs));
    programs
}

/// ★ Counting the table phase's commutative BITWISE sources window by window
/// builds the whole-run tables, BITWISE included, at every window length, ops
/// dropped or kept, counted on the builder's thread, by one counter as the
/// windows come, or by two counters in reverse order.
#[test]
fn counting_the_windows_apart_builds_the_whole_run_tables() {
    let max_rows = MaxRowsConfig::small();
    for (name, program, logs) in counted_programs() {
        let reference = whole(&program, &logs, &max_rows);
        for window in [1, 7, 33, 1000, logs.len()] {
            for drop in [false, true] {
                for counting in [Counting::Push, Counting::Split, Counting::SplitReversed] {
                    let built = windowed_counting(
                        &program,
                        &logs,
                        &max_rows,
                        window,
                        drop,
                        counting,
                        &no_mutation,
                    )
                    .unwrap_or_else(|e| panic!("{name}/{window}/{drop}/{counting:?}: {e}"));
                    same_traces(&reference, &built);
                }
            }
        }
    }
}

/// The BITWISE table of a build counted apart with `mutate`, against the
/// whole-run one: whether they differ.
fn bitwise_differs(
    name: &str,
    window: usize,
    mutate: &dyn Fn(&mut Vec<crate::tables::trace_builder::CountJob>, &mut [Counter]),
) -> bool {
    let max_rows = MaxRowsConfig::small();
    let (program, logs) = run(name);
    let reference = whole(&program, &logs, &max_rows);
    let built = windowed_counting(
        &program,
        &logs,
        &max_rows,
        window,
        true,
        Counting::Split,
        mutate,
    )
    .expect("the build");
    rows(&reference.bitwise) != rows(&built.bitwise)
}

/// Each part of the counting carries weight: a window's KECCAK lookups left
/// uncounted, or the table phase counting again what the windows counted at
/// the end of SHIFT's list, the in-walk lookups or the LT ops, changes BITWISE.
#[test]
fn the_window_counts_are_load_bearing() {
    assert!(!bitwise_differs("test_keccak_multi", 7, &no_mutation));
    // One window's KECCAK ops, the first window's that has any.
    let forgot = std::cell::Cell::new(false);
    assert!(bitwise_differs("test_keccak_multi", 7, &|jobs, _| {
        if !forgot.get() && jobs.iter_mut().any(|job| job.forget_keccak()) {
            forgot.set(true);
        }
    }));
    assert!(forgot.get(), "a window with KECCAK ops");
    for forget in 0..3 {
        assert!(
            bitwise_differs("all_instructions_64", 7, &|_, counters| {
                for counter in counters.iter_mut() {
                    let counted = counter.counted_mut();
                    match forget {
                        0 => counted.shift_cpu32 = 0,
                        1 => counted.bitwise_cpu32 = 0,
                        _ => counted.lt_dvrm = 0,
                    }
                }
            }),
            "forgetting part {forget}"
        );
    }
}

/// A run whose windows' counts are not all added is refused at `finish`, and
/// counting apart is refused once a window was walked.
#[test]
fn a_run_with_a_window_uncounted_is_refused() {
    let max_rows = MaxRowsConfig::small();
    let (program, logs) = run("all_instructions_64");
    let lost = windowed_counting(
        &program,
        &logs,
        &max_rows,
        7,
        true,
        Counting::Split,
        &|jobs, _| {
            jobs.pop();
        },
    );
    assert!(lost.is_err(), "a lost count job is refused");
    let mut builder = WindowedTraceBuilder::new(&program, &[], &max_rows).expect("the builder");
    builder.push(&logs[..7]).expect("a window");
    assert!(builder.count_windows_apart().is_err());
}
