// Poseidon1 over Goldilocks at width 8 (ZisK's grinding permutation): round constants, the MDS
// row and the Fourier-domain partial rounds. GENERATED by `scripts/poseidon1/p1_params.py cuda8`;
// do not edit by hand. The same tables as `crypto/crypto/src/hash/poseidon1_w8/constants.rs`.
#pragma once
#include <cstdint>
namespace p1w8 {
__device__ __constant__ uint64_t RC[30][8] = {
    {0xdd5743e7f2a5a5d9ull, 0xcb3a864e58ada44bull, 0xffa2449ed32f8cdcull, 0x42025f65d6bd13eeull, 0x7889175e25506323ull, 0x34b98bb03d24b737ull, 0xbdcc535ecc4faa2aull, 0x5b20ad869fc0d033ull},
    {0xf1dda5b9259dfcb4ull, 0x27515210be112d59ull, 0x4227d1718c766c3full, 0x26d333161a5bd794ull, 0x49b938957bf4b026ull, 0x4a56b5938b213669ull, 0x1120426b48c8353dull, 0x6b323c3f10a56cadull},
    {0xce57d6245ddca6b2ull, 0xb1fc8d402bba1eb1ull, 0xb5c5096ca959bd04ull, 0x6db55cd306d31f7full, 0xc49d293a81cb9641ull, 0x1ce55a4fe979719full, 0xa92e60a9d178a4d1ull, 0x002cc64973bcfd8cull},
    {0xcea721cce82fb11bull, 0xe5b55eb8098ece81ull, 0x4e30525c6f1ddd66ull, 0x43c6702827070987ull, 0xaca68430a7b5762aull, 0x3674238634df9c93ull, 0x88cee1c825e33433ull, 0xde99ae8d74b57176ull},
    {0x488897d85ff51f56ull, 0x1140737ccb162218ull, 0xa7eeb9215866ed35ull, 0x9bd2976fee49fcc9ull, 0xc0c8f0de580a3fccull, 0x4fb2dae6ee8fc793ull, 0x343a89f35f37395bull, 0x223b525a77ca72c8ull},
    {0x56ccb62574aaa918ull, 0xc4d507d8027af9edull, 0xa080673cf0b7e95cull, 0xf0184884eb70dcf8ull, 0x044f10b0cb3d5c69ull, 0xe9e3f7993938f186ull, 0x1b761c80e772f459ull, 0x606cec607a1b5facull},
    {0x14a0c2e1d45f03cdull, 0x4eace8855398574full, 0xf905ca7103eff3e6ull, 0xf8c8f8d20862c059ull, 0xb524fe8bdd678e5aull, 0xfbb7865901a1ec41ull, 0x014ef1197d341346ull, 0x9725e20825d07394ull},
    {0xfdb25aef2c5bae3bull, 0xbe5402dc598c971eull, 0x93a5711f04cdca3dull, 0xc45a9a5b2f8fb97bull, 0xfe8946a924933545ull, 0x2af997a27369091cull, 0xaa62c88e0b294011ull, 0x058eb9d810ce9f74ull},
    {0xb3cb23eced349ae4ull, 0xa3648177a77b4a84ull, 0x43153d905992d95dull, 0xf4e2a97cda44aa4bull, 0x5baa2702b908682full, 0x082923bdf4f750d1ull, 0x98ae09a325893803ull, 0xf8a6475077968838ull},
    {0xceb0735bf00b2c5full, 0x0a1a5d953888e072ull, 0x2fcb190489f94475ull, 0xb5be06270dec69fcull, 0x739cb934b09acf8bull, 0x537750b75ec7f25bull, 0xe9dd318bae1f3961ull, 0xf7462137299efe1aull},
    {0xb1f6b8eee9adb940ull, 0xbdebcc8a809dfe6bull, 0x40fc1f791b178113ull, 0x3ac1c3362d014864ull, 0x9a016184bdb8aebaull, 0x95f2394459fbc25eull, 0xe3f34a07a76a66c2ull, 0x8df25f9ad98b1b96ull},
    {0x85ffc27171439d9dull, 0xddcb9a2dcfd26910ull, 0x26b5ba4bf3afb94eull, 0xffff9cc7c7651e2full, 0x8c88364698280b55ull, 0xebc114167b910501ull, 0x2d77b4d89ecfb516ull, 0x332e0828eba151f2ull},
    {0x46fa6a6450dd4735ull, 0xd00db7dd92384a33ull, 0x5fd4fb751f3a5fc5ull, 0x496fb90c0bb65ea2ull, 0xf3baec0bb87cc5c7ull, 0x862a3c0a7d4c7713ull, 0xbf5f38336a3f47d8ull, 0x41ad9dbc1394a20cull},
    {0xcc535945b7dbf0f7ull, 0x82af2bc93685bcecull, 0x8e4c8d0c8cebfccdull, 0x17cb39417e84597eull, 0xd4a965a8c749b232ull, 0xa2cab040f33f3ee5ull, 0xa98811a1fed4e3a6ull, 0x1cc48b54f377e2a1ull},
    {0xe40cd4f6c5609a27ull, 0x11de79ebca97a4a4ull, 0x9177c73d8b7e929dull, 0x2a6fe8085797e792ull, 0x3de6e93329f8d5aeull, 0x3f7af9125da962ffull, 0xd710682cfc77d3acull, 0x48faf05f3b053cf4ull},
    {0x287db8630da89c8bull, 0x4d0de32053cb30e9ull, 0x8b37a4f20c5ada7bull, 0xe7cc6ebe78c84ecfull, 0x240bdc0a66a2610dull, 0x8299e7f02caa1650ull, 0x380a53fefb6e754eull, 0x684a1d8cf8eb6810ull},
    {0xe839452eb4b8a5e1ull, 0xb03fa62e90626af4ull, 0x11a688602fbc5efcull, 0x30dda75c355a2d62ull, 0x0f712adcb73810deull, 0xffdc1102187f1ae1ull, 0x40c34f398254b99cull, 0xede021b9dc289a4aull},
    {0x8b7b05225c4e7dadull, 0x3bc794346f9d9ff9ull, 0xfccb5a57f2ca86ffull, 0xbb1502015a7da9d4ull, 0xd7e0a35d4352a015ull, 0x27af7a44f8160931ull, 0xc37442f6782f4615ull, 0xbdf392a9bd095dcbull},
    {0xc17f55037cf00de9ull, 0xbcffedd34c71a874ull, 0x5eb45d2a8133d1f2ull, 0xbabe251e1612ebdfull, 0x3efeb9fbe438c536ull, 0x2d7cef97b4afe1cfull, 0xe5de1b4660016c0bull, 0xcdcc26c332f5657cull},
    {0xe01dd653daf15809ull, 0xb0a6bdd4b41094b5ull, 0x27eac858b0b03a05ull, 0x51d43b5e93adbdc0ull, 0x8b89a23b0fea5fc9ull, 0xdc8ac3b14f7f2fc1ull, 0xe793f82f1efec039ull, 0x9f6f2cf8969e7b80ull},
    {0x49d45382e0f21d4aull, 0x5f4ad1797cd72786ull, 0x4dc3dbebfd45f795ull, 0x03a3ef84dba6e1bcull, 0x204bc9b3d3fc4c01ull, 0x9ad706081e89b9baull, 0x638bfb4d840e9f89ull, 0x5ef2938cd095ae35ull},
    {0x42cca18ebeb265c8ull, 0xb7b2ec5c29aecbf8ull, 0x0d84f9535dc78f0full, 0x04e64ad942e77b8cull, 0xb4880dffffc9da0bull, 0x16db16d9c29adeb1ull, 0x09bbaf2a0590cd1eull, 0x76460e74961fcf8dull},
    {0xed12a2276dfa1553ull, 0x0b5acec5de0436fdull, 0x3c6cfea033a1f0a8ull, 0x2b5ecefe546cac15ull, 0x6e2d82884cd3bf6full, 0xc134878d1add7b83ull, 0x997963422eb7a280ull, 0x5e834537ac648cf6ull},
    {0x89e779214737c0b7ull, 0x1a8c05e8581ad95bull, 0x8d18b72796437cf7ull, 0xe7252c949e04b106ull, 0x53267c4fd174585aull, 0xa16ef5d9c81dad47ull, 0xda65191937270a46ull, 0xcb2a5b55f2df664cull},
    {0x854aee2dc1924137ull, 0xf37013c9d479ece6ull, 0x0e163bc0630c4696ull, 0x384ee64955048f76ull, 0xf65d814e28ee4ec5ull, 0xe57bc564fd82f1b1ull, 0x4b338937b6876614ull, 0x66ee0b04ed43cd8dull},
    {0x49884bf25f4ef15dull, 0xeb51fe28de1c6f54ull, 0x2cd64e84fce8dfccull, 0x29164a96a541a013ull, 0x173ce7558f4cacb8ull, 0xeb5b1ce5877c89e9ull, 0x5faff4b0f5217bf6ull, 0xac42d0b1c20f205eull},
    {0xfb1d6bf0ca43221bull, 0x97b0a1b01d6a2955ull, 0x08c60bd622952b30ull, 0x43f2be0f9e24147cull, 0xfa7268b7d3730f5dull, 0x43a6c419a23983bbull, 0xcd77c1f7b29b113cull, 0xcfa43c9db8eec29full},
    {0xcaaa95a6c7365decull, 0x0a91193f798f3be0ull, 0x1104497652735dc6ull, 0x35aecb93663b515eull, 0x8dbc9916065aa858ull, 0xada8f7a0266579edull, 0x524dee7bec1ea789ull, 0xa93aee9dd5af9521ull},
    {0x9d1f1b54750d707eull, 0x7c9feab87096d5dcull, 0xa2e1fb19f9d4261bull, 0xb714deb448de6346ull, 0x225d1f0d011c5403ull, 0x1549b7f1d28cedc0ull, 0xaef3e46f97d43942ull, 0x6dfc7ffe0b38bf08ull},
    {0x7de853fdc542b663ull, 0xa68ecc96610657b2ull, 0xe88bb5428af289b1ull, 0xd7cfa1504c5569f5ull, 0x78a9aad0d642d30aull, 0xd68315f2353dce52ull, 0x46e56300f86fcfd5ull, 0x323d95332b145fd6ull},
};
// First ROW of the circulant MDS, `M[i][j] = MDS_ROW[(j - i) mod 8]`. Row sum 43 < 2^6.
__device__ constexpr uint32_t MDS_ROW[8] = {7, 1, 3, 8, 8, 3, 4, 9};
// Fourier-domain partial rounds (`scripts/poseidon1/p1_fourier.py`): OMEGA_POW[k] = 2^(24k) mod p
// (omega = 2^24 has order 8); FD = the circulant's eigenvalues; FD_LAST = FD / 8; FC[k] = DFT(RC[4 + k]).
__device__ constexpr uint64_t OMEGA_POW[8] = {0x0000000000000001ull, 0x0000000001000000ull, 0x0001000000000000ull, 0x000000ffffffff00ull, 0xffffffff00000000ull, 0xfffffffeff000001ull, 0xfffeffff00000001ull, 0xfffffeff00000101ull};
__device__ constexpr uint64_t FD[8] = {0x000000000000002bull, 0x0001020000fffdffull, 0x000d000000000008ull, 0xffff00ff01ffff00ull, 0x0000000000000001ull, 0x0000fdffff0001ffull, 0xfff2ffff00000009ull, 0xfffefefefe000100ull};
__device__ constexpr uint64_t FD_LAST[8] = {0x9fffffff60000006ull, 0x2000203fe01fffc0ull, 0x0001a00000000001ull, 0x1fffe01fe03fffe0ull, 0xdfffffff20000001ull, 0x20001fbfdfe00040ull, 0xfffe5fff00000002ull, 0x1fffdfdfdfc00020ull};
__device__ constexpr uint64_t INV8 = 0xdfffffff20000001ull;
__device__ __constant__ uint64_t FC[22][8] = {
    {0x047c03fc8f57deebull, 0x7fefb4a2472bce98ull, 0x0bdb99339bc8421bull, 0x410249d723ac9a4dull, 0xc679939d4fe32c76ull, 0x559f8baf6a4d16b6ull, 0x4e74f21064fa2f09ull, 0x086d11bc4a85fe90ull},
    {0x16507eeeb9530b49ull, 0x265e2d42c4fc5cdeull, 0x1880193f9d30f371ull, 0x79c8042e0c8189d9ull, 0x17d4163b76d2bb21ull, 0xfe1b302ff8651fe2ull, 0x25ca6cf032495c28ull, 0xabb53430dbd22c24ull},
    {0x9e6dc6b4b65810ccull, 0xd764fb7bf6e872bdull, 0x73182ce99c9ea97full, 0x663381a9a921167eull, 0xe9c7333daf7d21d8ull, 0x5b819aa544557b46ull, 0x2bc9dedbc4a66c78ull, 0xe4d4f987f77ed150ull},
    {0xed7ac9fb6e39e6f3ull, 0x2d799224d3a9b185ull, 0x4bc9f482faac2d36ull, 0x73d7a90838a15417ull, 0x870cec945391f4a4ull, 0x365289afeac57a99ull, 0x309cdb548743852dull, 0x25008c3a281163a4ull},
    {0x844f282a13a6e247ull, 0x95d8034ec81fd984ull, 0x50ec4e5372b9e917ull, 0x333265c9bbc56811ull, 0x5221fc1f370b469cull, 0xc4f85e98385ecf05ull, 0x1677b924db87fa4full, 0xd2812bf7146cba3bull},
    {0x668b4ccfa79ab49full, 0x789cdc3da9f0c61bull, 0x1a4a41c5e1a06dc1ull, 0x1917bae7a52f11ddull, 0x515fa17609e23eddull, 0x22a44fc505ffaffdull, 0x36ff823aef7a8e67ull, 0xb7f601b2a8a1eb5bull},
    {0x8d79ac984b0e748eull, 0xc43335391dcbd6eaull, 0x66d5850001e620eeull, 0x656f362533e9b8b2ull, 0x54555b5488c22b0cull, 0x4b3c60f48f3c9cb7ull, 0xe73bdce4c7e2df5dull, 0xeaf69153cee1fdc7ull},
    {0x636fbb159a54f584ull, 0xde3569274d555dc9ull, 0xc59e21f06d980bd2ull, 0xd0d8dbb8ced7e87eull, 0x69fb14a59d813926ull, 0x281058ed59fb2a8cull, 0xb716f1368040694aull, 0x0ebf92dbee45d84full},
    {0x3b3ed4ccc1a37689ull, 0x2389989a10fd628aull, 0x79391300e2bfaa0bull, 0xb3e3ccea224b21b0ull, 0x78943f686403f2a5ull, 0x3952ce0b9940f572ull, 0xbdc9328d1d0120b4ull, 0x3c3dc5ce94f88c10ull},
    {0x32dafe41a6a7bb88ull, 0x20d589b269231de3ull, 0x404dd808dbf01a03ull, 0x961c7fca1e081bb0ull, 0x7ec7bcfd6f254babull, 0xf7a179b4812c79f1ull, 0x920268770ad96b69ull, 0x30144b40b9f14792ull},
    {0x4f4038fd322e0244ull, 0x30116aabd9e2d06dull, 0x371f2462cccc95faull, 0x1f64098d46d41a82ull, 0xc5b7a22fbc71a9f4ull, 0x583d8ae99ecc25a8ull, 0x3bb7f91b01f97d1full, 0xf0e4afecae1c014cull},
    {0x2f89e4bd6e3d4b76ull, 0xc76a40da901072eaull, 0x5866aa3d2dbd1f7dull, 0xa16bc3d921645420ull, 0xf00d360089eb4f4bull, 0xadb999ae1c153be0ull, 0xba288cb9ab463c23ull, 0xfb37d2fdce8eeb11ull},
    {0x18edc7efd8661cd4ull, 0x150a275ca890f8c9ull, 0x51842fd0cbc4756aull, 0x7f2daf53087ed650ull, 0x7b3ac75c639d81d8ull, 0x59936817e02334a6ull, 0xf8fd0112a7fac6e4ull, 0x75552a8264cf504bull},
    {0x001ae8f789d59b9aull, 0x6fbd851333cab0efull, 0xbe755b5cbada1614ull, 0x3a8044d099afb8a4ull, 0x471ba2aa8b603a0cull, 0xa80e33abcf69a25eull, 0x87c2bb03ae748b4aull, 0x7c1d8981c70b6a72ull},
    {0xb817b0c08c87ecb6ull, 0x83f96411ebbf6dc9ull, 0x865d4ea6ee6a7b17ull, 0xf74c2dc9f8e91026ull, 0xd2095e22f834357full, 0xd09e1461c1e7ef8cull, 0xf179de74117caf2full, 0xbe1ec5dfbc4cb552ull},
    {0xf99b22f7e866afc2ull, 0xd104b3767ab96441ull, 0x008d914b01fd4862ull, 0x01b30ae42e1e4dd5ull, 0xfcb14f388caeb45bull, 0x6c0ed81d7b02e82full, 0xb7c3dec3345c32c6ull, 0x138a39eb084146bbull},
    {0x78284f057de07198ull, 0xe4894b9a36037b04ull, 0x5e8f3520df294b7eull, 0x35fb9f62b3b645feull, 0xbeb799dbeea58f39ull, 0xdfdcba7122ab60b1ull, 0x131156d8880a58ddull, 0xabc081cc27722373ull},
    {0x584fb491e72591c0ull, 0xe512d6f85335f43cull, 0xe98c1a53b13b7d02ull, 0xfa52e99e1cc07e1bull, 0xc4dafb875c83a63full, 0x4fab009096486b40ull, 0xd69bf3cf050c4a4aull, 0x0a018d0ff5635161ull},
    {0x8797f11e16da5372ull, 0xa89790bf1cd5a217ull, 0x40ebbade165706dcull, 0x828f79138eb46f75ull, 0xdab51c0923747c5full, 0x283eb853eebbb9f5ull, 0xc9c7cabc9a917c58ull, 0xa82ebc55ea538c0full},
    {0xb2d6496297333e3eull, 0x7ad4300dcc2040d2ull, 0x58b7b483d76af8d5ull, 0x61f4d257b3795cccull, 0xd641420434fa025bull, 0x142c87cde34a6c48ull, 0x926895dabf182ad5ull, 0xea0e69117429978full},
    {0x4d1afef51859783cull, 0x479eeddbf9706155ull, 0x8bd33a38e90b19eeull, 0x371716e949116728ull, 0x5cc969f5efcf010dull, 0xfc5144ead2c6a4c2ull, 0xb8ea1acfb8ceacb5ull, 0xc0ae69ca4d475c8dull},
    {0x9951acd7ad8fb382ull, 0x65cbb8addb34def3ull, 0x0cd0ee59fcca42b7ull, 0xf8e6cdce489297c3ull, 0x4145402513bc402bull, 0x7a1f201a1128007cull, 0x9bacf1c8fc5841f0ull, 0xf05bebdb0b199b64ull},
};
}  // namespace p1w8
