//! Tests for the FRI fold schedule (`crate::fri::schedule`) and the generalised
//! `FriFoldLayout` (FRI.md §10 U1–U3).

use crate::fri::schedule::{
    FRI_SCHEDULE_DMAX, FriFormat, FriMode, fri_chain_start, fri_leaf_blocks, fri_path_cost_q,
    fri_schedule, fri_schedule_cost_q, fri_schedule_with_cost, legacy_fri_schedule, no_cap,
};
use crate::fri::terminal::FriFoldLayout;

const Q: u64 = 110;

// ---------------------------------------------------------------------------
// Cap-height functions (the DP takes the active cap policy as a parameter).
// ---------------------------------------------------------------------------

/// The cap rule FRI.md §2.2's table was computed with (PLAN §4):
/// `c = argmax_{0 ≤ c ≤ depth} (Q·c − (2^c − 1))`, ties to the smaller `c`.
fn cap_design_model(depth: u32) -> u32 {
    let (mut best, mut best_c) = (0i64, 0u32);
    for c in 0..=depth.min(62) {
        let v = Q as i64 * i64::from(c) - ((1i64 << c) - 1);
        if v > best {
            (best, best_c) = (v, c);
        }
    }
    best_c
}

/// CAP.md §2 `AUTO_WEIGHTS` (ns): compress, select, unpack, hint, compare.
const AUTO_WEIGHTS: (i64, i64, i64, i64, i64) = (2251, 567, 528, 460, 3789);

/// CAP.md §2 `CapPolicy::Auto.height(openings, depth)`, the policy adopted by
/// RULINGS.md 1. Implemented locally because the cap primitive commit (lane
/// I-CAP-S) is not yet on this branch; on rebase this becomes a call to
/// `CapPolicy::Auto.height` and `cap_auto_heights_match_cap_md` pins that the
/// two agree.
fn cap_auto_height(openings: u64, depth: u32) -> u32 {
    let (wc, ws, wu, wh, wq) = AUTO_WEIGHTS;
    let o = openings as i64;
    let gain = |c: u32| -> i64 {
        if c == 0 {
            return 0;
        }
        let p = 1i64 << c;
        o * (i64::from(c) * (wc + ws) - (p - 1) * ws - wu) - ((p - 1) * wc + p * wh + wq)
    };
    let (mut best, mut best_c) = (0i64, 0u32);
    for c in 0..=depth.min(16) {
        let g = gain(c);
        if g > best {
            (best, best_c) = (g, c);
        }
    }
    best_c
}

/// Every FRI tree is opened once per query, so the FRI cap function is
/// `Auto.height(Q, ·)`.
fn cap_auto(depth: u32) -> u32 {
    cap_auto_height(Q, depth)
}

#[test]
fn cap_auto_heights_match_cap_md() {
    // CAP.md §11 "CapPolicy pins", at a depth large enough not to clamp.
    for (openings, want) in [(1, 0), (3, 0), (4, 2), (19, 2), (20, 3), (110, 3), (224, 3)] {
        assert_eq!(cap_auto_height(openings, 20), want, "openings {openings}");
    }
    // Clamped to depth.
    for depth in 0..8 {
        assert_eq!(cap_auto_height(110, depth), depth.min(3), "depth {depth}");
    }
    // The design model's rule reaches 7 at Q = 110 (FRI.md §2.2 used it).
    assert_eq!(cap_design_model(20), 7);
    assert_eq!(cap_design_model(5), 5);
}

// ---------------------------------------------------------------------------
// Cost-model primitives.
// ---------------------------------------------------------------------------

#[test]
fn leaf_blocks_and_path_cost() {
    // ⌈3·2^d / 8⌉, at least 1.
    let want = [1u64, 1, 2, 3, 6, 12, 24];
    for (d, w) in want.iter().enumerate() {
        assert_eq!(fri_leaf_blocks(d as u32), *w, "d = {d}");
    }
    assert_eq!(fri_path_cost_q(9, Q, &no_cap), 990);
    // depth 9, c = 7: Q·2 + 127.
    assert_eq!(fri_path_cost_q(9, Q, &cap_design_model), 347);
    // A policy asking for more than the tree has is clamped to the depth.
    assert_eq!(fri_path_cost_q(2, Q, &|_| 40), 3);
    assert_eq!(fri_path_cost_q(0, Q, &|_| 40), 0);
}

#[test]
fn schedule_cost_rejects_malformed_schedules() {
    assert_eq!(fri_schedule_cost_q(10, &[], Q, &no_cap), Some(0));
    assert_eq!(fri_schedule_cost_q(10, &[0, 1], Q, &no_cap), None);
    assert_eq!(fri_schedule_cost_q(3, &[2, 2], Q, &no_cap), None);
    assert!(fri_schedule_cost_q(4, &[2, 2], Q, &no_cap).is_some());
}

// ---------------------------------------------------------------------------
// U1: the §2.2 table, pinned. The schedule is a format constant.
// ---------------------------------------------------------------------------

/// (B, today, S3 from B−1, S2+S3 from B); each entry = (cost·Q, schedule).
/// Generated by an independent Python reproduction of FRI.md §2.1 in exact
/// integer units (lane I-FRI-H scratch), and cross-checked against
/// `lanes/D-FRI/model_output.txt` for the OFF and MODEL caps (cost / 110).
type Row = (
    u32,
    (u64, &'static [u8]),
    (u64, &'static [u8]),
    (u64, &'static [u8]),
);

/// T = 9, cap = OFF: (B, today, S3, S2+S3), each (cost·Q, schedule).
const PIN_T9_CAP_OFF: &[Row] = &[
    (6, (0, &[]), (0, &[]), (0, &[])),
    (7, (0, &[]), (0, &[]), (0, &[])),
    (8, (0, &[]), (0, &[]), (0, &[])),
    (9, (0, &[]), (0, &[]), (0, &[])),
    (10, (0, &[]), (0, &[]), (1100, &[1])),
    (11, (1100, &[1]), (1100, &[1]), (1210, &[2])),
    (12, (2310, &[1, 1]), (1210, &[2]), (1320, &[3])),
    (13, (3630, &[1, 1, 1]), (1320, &[3]), (1650, &[4])),
    (14, (5060, &[1, 1, 1, 1]), (1650, &[4]), (2310, &[5])),
    (15, (6600, &[1, 1, 1, 1, 1]), (2310, &[5]), (2970, &[3, 3])),
    (
        16,
        (8250, &[1, 1, 1, 1, 1, 1]),
        (2970, &[3, 3]),
        (3300, &[4, 3]),
    ),
    (
        17,
        (10010, &[1, 1, 1, 1, 1, 1, 1]),
        (3300, &[4, 3]),
        (3740, &[4, 4]),
    ),
    (
        18,
        (11880, &[1, 1, 1, 1, 1, 1, 1, 1]),
        (3740, &[4, 4]),
        (4400, &[5, 4]),
    ),
    (
        19,
        (13860, &[1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4400, &[5, 4]),
        (5170, &[5, 5]),
    ),
    (
        20,
        (15950, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5170, &[5, 5]),
        (5720, &[4, 4, 3]),
    ),
    (
        21,
        (18150, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5720, &[4, 4, 3]),
        (6270, &[4, 4, 4]),
    ),
    (
        22,
        (20460, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (6270, &[4, 4, 4]),
        (6930, &[5, 4, 4]),
    ),
    (
        23,
        (22880, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (6930, &[5, 4, 4]),
        (7700, &[5, 5, 4]),
    ),
    (
        24,
        (25410, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (7700, &[5, 5, 4]),
        (8580, &[5, 5, 5]),
    ),
];
/// T = 10, cap = OFF: (B, today, S3, S2+S3), each (cost·Q, schedule).
const PIN_T10_CAP_OFF: &[Row] = &[
    (6, (0, &[]), (0, &[]), (0, &[])),
    (7, (0, &[]), (0, &[]), (0, &[])),
    (8, (0, &[]), (0, &[]), (0, &[])),
    (9, (0, &[]), (0, &[]), (0, &[])),
    (10, (0, &[]), (0, &[]), (0, &[])),
    (11, (0, &[]), (0, &[]), (1210, &[1])),
    (12, (1210, &[1]), (1210, &[1]), (1320, &[2])),
    (13, (2530, &[1, 1]), (1320, &[2]), (1430, &[3])),
    (14, (3960, &[1, 1, 1]), (1430, &[3]), (1760, &[4])),
    (15, (5500, &[1, 1, 1, 1]), (1760, &[4]), (2420, &[5])),
    (16, (7150, &[1, 1, 1, 1, 1]), (2420, &[5]), (3190, &[3, 3])),
    (
        17,
        (8910, &[1, 1, 1, 1, 1, 1]),
        (3190, &[3, 3]),
        (3520, &[4, 3]),
    ),
    (
        18,
        (10780, &[1, 1, 1, 1, 1, 1, 1]),
        (3520, &[4, 3]),
        (3960, &[4, 4]),
    ),
    (
        19,
        (12760, &[1, 1, 1, 1, 1, 1, 1, 1]),
        (3960, &[4, 4]),
        (4620, &[5, 4]),
    ),
    (
        20,
        (14850, &[1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4620, &[5, 4]),
        (5390, &[5, 5]),
    ),
    (
        21,
        (17050, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5390, &[5, 5]),
        (6050, &[4, 4, 3]),
    ),
    (
        22,
        (19360, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (6050, &[4, 4, 3]),
        (6600, &[4, 4, 4]),
    ),
    (
        23,
        (21780, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (6600, &[4, 4, 4]),
        (7260, &[5, 4, 4]),
    ),
    (
        24,
        (24310, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (7260, &[5, 4, 4]),
        (8030, &[5, 5, 4]),
    ),
];
/// T = 9, cap = MODEL: (B, today, S3, S2+S3), each (cost·Q, schedule).
const PIN_T9_CAP_MODEL: &[Row] = &[
    (6, (0, &[]), (0, &[]), (0, &[])),
    (7, (0, &[]), (0, &[]), (0, &[])),
    (8, (0, &[]), (0, &[]), (0, &[])),
    (9, (0, &[]), (0, &[]), (0, &[])),
    (10, (0, &[]), (0, &[]), (457, &[1])),
    (11, (457, &[1]), (457, &[1]), (567, &[2])),
    (12, (1024, &[1, 1]), (567, &[2]), (677, &[3])),
    (13, (1701, &[1, 1, 1]), (677, &[3]), (1007, &[4])),
    (14, (2488, &[1, 1, 1, 1]), (1007, &[4]), (1464, &[3, 2])),
    (
        15,
        (3385, &[1, 1, 1, 1, 1]),
        (1464, &[3, 2]),
        (1684, &[3, 3]),
    ),
    (
        16,
        (4392, &[1, 1, 1, 1, 1, 1]),
        (1684, &[3, 3]),
        (2014, &[4, 3]),
    ),
    (
        17,
        (5509, &[1, 1, 1, 1, 1, 1, 1]),
        (2014, &[4, 3]),
        (2454, &[4, 4]),
    ),
    (
        18,
        (6736, &[1, 1, 1, 1, 1, 1, 1, 1]),
        (2454, &[4, 4]),
        (3021, &[3, 3, 3]),
    ),
    (
        19,
        (8073, &[1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (3021, &[3, 3, 3]),
        (3351, &[4, 3, 3]),
    ),
    (
        20,
        (9520, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (3351, &[4, 3, 3]),
        (3791, &[4, 4, 3]),
    ),
    (
        21,
        (11077, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (3791, &[4, 4, 3]),
        (4341, &[4, 4, 4]),
    ),
    (
        22,
        (12744, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4341, &[4, 4, 4]),
        (5001, &[5, 4, 4]),
    ),
    (
        23,
        (14521, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5001, &[5, 4, 4]),
        (5458, &[4, 4, 3, 3]),
    ),
    (
        24,
        (16408, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5458, &[4, 4, 3, 3]),
        (6008, &[4, 4, 4, 3]),
    ),
];
/// T = 10, cap = MODEL: (B, today, S3, S2+S3), each (cost·Q, schedule).
const PIN_T10_CAP_MODEL: &[Row] = &[
    (6, (0, &[]), (0, &[]), (0, &[])),
    (7, (0, &[]), (0, &[]), (0, &[])),
    (8, (0, &[]), (0, &[]), (0, &[])),
    (9, (0, &[]), (0, &[]), (0, &[])),
    (10, (0, &[]), (0, &[]), (0, &[])),
    (11, (0, &[]), (0, &[]), (567, &[1])),
    (12, (567, &[1]), (567, &[1]), (677, &[2])),
    (13, (1244, &[1, 1]), (677, &[2]), (787, &[3])),
    (14, (2031, &[1, 1, 1]), (787, &[3]), (1117, &[4])),
    (15, (2928, &[1, 1, 1, 1]), (1117, &[4]), (1684, &[3, 2])),
    (
        16,
        (3935, &[1, 1, 1, 1, 1]),
        (1684, &[3, 2]),
        (1904, &[3, 3]),
    ),
    (
        17,
        (5052, &[1, 1, 1, 1, 1, 1]),
        (1904, &[3, 3]),
        (2234, &[4, 3]),
    ),
    (
        18,
        (6279, &[1, 1, 1, 1, 1, 1, 1]),
        (2234, &[4, 3]),
        (2674, &[4, 4]),
    ),
    (
        19,
        (7616, &[1, 1, 1, 1, 1, 1, 1, 1]),
        (2674, &[4, 4]),
        (3334, &[5, 4]),
    ),
    (
        20,
        (9063, &[1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (3334, &[5, 4]),
        (3681, &[4, 3, 3]),
    ),
    (
        21,
        (10620, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (3681, &[4, 3, 3]),
        (4121, &[4, 4, 3]),
    ),
    (
        22,
        (12287, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4121, &[4, 4, 3]),
        (4671, &[4, 4, 4]),
    ),
    (
        23,
        (14064, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4671, &[4, 4, 4]),
        (5331, &[5, 4, 4]),
    ),
    (
        24,
        (15951, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5331, &[5, 4, 4]),
        (5898, &[4, 4, 3, 3]),
    ),
];
/// T = 9, cap = AUTO: (B, today, S3, S2+S3), each (cost·Q, schedule).
const PIN_T9_CAP_AUTO: &[Row] = &[
    (6, (0, &[]), (0, &[]), (0, &[])),
    (7, (0, &[]), (0, &[]), (0, &[])),
    (8, (0, &[]), (0, &[]), (0, &[])),
    (9, (0, &[]), (0, &[]), (0, &[])),
    (10, (0, &[]), (0, &[]), (777, &[1])),
    (11, (777, &[1]), (777, &[1]), (887, &[2])),
    (12, (1664, &[1, 1]), (887, &[2]), (997, &[3])),
    (13, (2661, &[1, 1, 1]), (997, &[3]), (1327, &[4])),
    (14, (3768, &[1, 1, 1, 1]), (1327, &[4]), (1987, &[5])),
    (15, (4985, &[1, 1, 1, 1, 1]), (1987, &[5]), (2324, &[3, 3])),
    (
        16,
        (6312, &[1, 1, 1, 1, 1, 1]),
        (2324, &[3, 3]),
        (2654, &[4, 3]),
    ),
    (
        17,
        (7749, &[1, 1, 1, 1, 1, 1, 1]),
        (2654, &[4, 3]),
        (3094, &[4, 4]),
    ),
    (
        18,
        (9296, &[1, 1, 1, 1, 1, 1, 1, 1]),
        (3094, &[4, 4]),
        (3754, &[5, 4]),
    ),
    (
        19,
        (10953, &[1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (3754, &[5, 4]),
        (4311, &[4, 3, 3]),
    ),
    (
        20,
        (12720, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4311, &[4, 3, 3]),
        (4751, &[4, 4, 3]),
    ),
    (
        21,
        (14597, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4751, &[4, 4, 3]),
        (5301, &[4, 4, 4]),
    ),
    (
        22,
        (16584, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5301, &[4, 4, 4]),
        (5961, &[5, 4, 4]),
    ),
    (
        23,
        (18681, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5961, &[5, 4, 4]),
        (6731, &[5, 5, 4]),
    ),
    (
        24,
        (20888, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (6731, &[5, 5, 4]),
        (7288, &[4, 4, 4, 3]),
    ),
];
/// T = 10, cap = AUTO: (B, today, S3, S2+S3), each (cost·Q, schedule).
const PIN_T10_CAP_AUTO: &[Row] = &[
    (6, (0, &[]), (0, &[]), (0, &[])),
    (7, (0, &[]), (0, &[]), (0, &[])),
    (8, (0, &[]), (0, &[]), (0, &[])),
    (9, (0, &[]), (0, &[]), (0, &[])),
    (10, (0, &[]), (0, &[]), (0, &[])),
    (11, (0, &[]), (0, &[]), (887, &[1])),
    (12, (887, &[1]), (887, &[1]), (997, &[2])),
    (13, (1884, &[1, 1]), (997, &[2]), (1107, &[3])),
    (14, (2991, &[1, 1, 1]), (1107, &[3]), (1437, &[4])),
    (15, (4208, &[1, 1, 1, 1]), (1437, &[4]), (2097, &[5])),
    (16, (5535, &[1, 1, 1, 1, 1]), (2097, &[5]), (2544, &[3, 3])),
    (
        17,
        (6972, &[1, 1, 1, 1, 1, 1]),
        (2544, &[3, 3]),
        (2874, &[4, 3]),
    ),
    (
        18,
        (8519, &[1, 1, 1, 1, 1, 1, 1]),
        (2874, &[4, 3]),
        (3314, &[4, 4]),
    ),
    (
        19,
        (10176, &[1, 1, 1, 1, 1, 1, 1, 1]),
        (3314, &[4, 4]),
        (3974, &[5, 4]),
    ),
    (
        20,
        (11943, &[1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (3974, &[5, 4]),
        (4641, &[4, 3, 3]),
    ),
    (
        21,
        (13820, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (4641, &[4, 3, 3]),
        (5081, &[4, 4, 3]),
    ),
    (
        22,
        (15807, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5081, &[4, 4, 3]),
        (5631, &[4, 4, 4]),
    ),
    (
        23,
        (17904, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (5631, &[4, 4, 4]),
        (6291, &[5, 4, 4]),
    ),
    (
        24,
        (20111, &[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        (6291, &[5, 4, 4]),
        (7061, &[5, 5, 4]),
    ),
];

fn check_pin(name: &str, terminal_log: u32, cap: &dyn Fn(u32) -> u32, rows: &[Row]) {
    assert_eq!(rows.len(), 19, "{name}: B = 6..=24");
    for &(b, (today_q, today), (s3_q, s3), (s2_q, s2)) in rows {
        let ctx = format!("{name} B={b}");
        // today: the all-ones chain from B − 1 (no committed layer when B − 1 ≤ T).
        let b0 = fri_chain_start(b, false);
        assert_eq!(legacy_fri_schedule(b0, terminal_log), today, "{ctx} today");
        assert_eq!(
            fri_schedule_cost_q(b0, today, Q, cap),
            Some(today_q),
            "{ctx} today cost"
        );
        // S3: the DP from B − 1.
        let got = fri_schedule_with_cost(b0, terminal_log, Q, cap, FRI_SCHEDULE_DMAX);
        assert_eq!(got.schedule, s3, "{ctx} S3 schedule");
        assert_eq!(got.cost_q, s3_q, "{ctx} S3 cost");
        assert_eq!(got.trees as usize, s3.len(), "{ctx} S3 trees");
        // S2+S3: the DP from B (the DEEP codeword is committed).
        let b0 = fri_chain_start(b, true);
        let got = fri_schedule_with_cost(b0, terminal_log, Q, cap, FRI_SCHEDULE_DMAX);
        assert_eq!(got.schedule, s2, "{ctx} S2+S3 schedule");
        assert_eq!(got.cost_q, s2_q, "{ctx} S2+S3 cost");
        assert_eq!(
            fri_schedule(b0, terminal_log, Q, cap, FRI_SCHEDULE_DMAX),
            s2
        );
    }
}

#[test]
fn schedule_pinned_table() {
    check_pin("T9 cap off", 9, &no_cap, PIN_T9_CAP_OFF);
    check_pin("T10 cap off", 10, &no_cap, PIN_T10_CAP_OFF);
    check_pin("T9 cap model", 9, &cap_design_model, PIN_T9_CAP_MODEL);
    check_pin("T10 cap model", 10, &cap_design_model, PIN_T10_CAP_MODEL);
    check_pin("T9 cap auto", 9, &cap_auto, PIN_T9_CAP_AUTO);
    check_pin("T10 cap auto", 10, &cap_auto, PIN_T10_CAP_AUTO);
}

/// Spot checks tying the pins to the printed FRI.md §2.2 table (costs there are
/// per query, i.e. cost·Q / 110, rounded to two decimals).
#[test]
fn schedule_pins_match_fri_md_table() {
    let per_query = |cost_q: u64| (cost_q as f64 / Q as f64 * 100.0).round() / 100.0;
    let s3 = |b0: u32, t: u32, cap: &dyn Fn(u32) -> u32| {
        fri_schedule_with_cost(b0, t, Q, cap, FRI_SCHEDULE_DMAX)
    };
    // Base legs, T = 9, B = 21.
    let today = legacy_fri_schedule(20, 9);
    assert_eq!(
        per_query(fri_schedule_cost_q(20, &today, Q, &no_cap).unwrap()),
        165.0
    );
    assert_eq!(
        per_query(fri_schedule_cost_q(20, &today, Q, &cap_design_model).unwrap()),
        100.70
    );
    let c = s3(20, 9, &no_cap);
    assert_eq!((per_query(c.cost_q), c.schedule), (52.0, vec![4, 4, 3]));
    let c = s3(20, 9, &cap_design_model);
    assert_eq!((per_query(c.cost_q), c.schedule), (34.46, vec![4, 4, 3]));
    let c = s3(21, 9, &cap_design_model);
    assert_eq!((per_query(c.cost_q), c.schedule), (39.46, vec![4, 4, 4]));
    // B = 19, T = 9: the schedule depends on the cap policy (FRI.md §12.2).
    assert_eq!(s3(18, 9, &no_cap).schedule, vec![5, 4]);
    assert_eq!(s3(18, 9, &cap_design_model).schedule, vec![3, 3, 3]);
    // LFM proofs, T = 10: S3+cap at B = 21 is [4,3,3] 33.46, at B = 22 [4,4,3] 37.46.
    let c = s3(20, 10, &cap_design_model);
    assert_eq!((per_query(c.cost_q), c.schedule), (33.46, vec![4, 3, 3]));
    let c = s3(21, 10, &cap_design_model);
    assert_eq!((per_query(c.cost_q), c.schedule), (37.46, vec![4, 4, 3]));
}

// ---------------------------------------------------------------------------
// U2: brute-force optimality for b₀ ≤ 16.
// ---------------------------------------------------------------------------

/// Independent oracle for one layer's cost (FRI.md §2.1, written out again).
fn oracle_layer_q(d: u32, depth: u32, q: u64, cap: &dyn Fn(u32) -> u32) -> u64 {
    let leaf = (3u64 << d).div_ceil(8);
    let c = cap(depth).min(depth);
    q * leaf.max(1) + q * u64::from(depth - c) + (1u64 << c) - 1
}

/// Every composition of `b0 − t` into parts in `1..=dmax`, with its cost;
/// returns the minimum under (cost, trees, schedule) lexicographic order.
fn brute_force(b0: u32, t: u32, q: u64, cap: &dyn Fn(u32) -> u32, dmax: u32) -> (u64, Vec<u8>) {
    struct Search<'a> {
        t: u32,
        q: u64,
        cap: &'a dyn Fn(u32) -> u32,
        dmax: u32,
        prefix: Vec<u8>,
        best: Option<(u64, usize, Vec<u8>)>,
    }
    impl Search<'_> {
        fn walk(&mut self, b: u32, cost: u64) {
            if b == self.t {
                let cand = (cost, self.prefix.len(), self.prefix.clone());
                if self.best.as_ref().is_none_or(|cur| cand < *cur) {
                    self.best = Some(cand);
                }
                return;
            }
            for d in 1..=self.dmax.min(b - self.t) {
                self.prefix.push(d as u8);
                let c = cost + oracle_layer_q(d, b - d, self.q, self.cap);
                self.walk(b - d, c);
                self.prefix.pop();
            }
        }
    }
    let mut s = Search {
        t,
        q,
        cap,
        dmax,
        prefix: Vec::new(),
        best: None,
    };
    s.walk(b0, 0);
    let (cost, _, sched) = s.best.expect("at least the empty / all-ones composition");
    (cost, sched)
}

#[test]
fn dp_is_optimal() {
    let depth_mod_3 = |depth: u32| depth % 3; // an arbitrary, non-monotone policy
    let caps: [(&str, &dyn Fn(u32) -> u32); 4] = [
        ("off", &no_cap),
        ("model", &cap_design_model),
        ("auto", &cap_auto),
        ("depth%3", &depth_mod_3),
    ];
    let mut checked = 0u32;
    for (cap_name, cap) in caps {
        for q in [1u64, 3, 110] {
            for dmax in [1u32, 2, 3, FRI_SCHEDULE_DMAX] {
                for b0 in 0..=16u32 {
                    for t in 0..=b0 {
                        let got = fri_schedule_with_cost(b0, t, q, cap, dmax);
                        let (cost, sched) = brute_force(b0, t, q, cap, dmax);
                        let ctx = format!("cap={cap_name} q={q} dmax={dmax} b0={b0} t={t}");
                        assert_eq!(got.cost_q, cost, "{ctx}: cost");
                        // The tie rule makes the optimum unique: the smallest
                        // (trees, schedule) among the cost-optimal ones.
                        assert_eq!(got.schedule, sched, "{ctx}: schedule");
                        assert_eq!(got.trees as usize, sched.len(), "{ctx}: trees");
                        assert_eq!(
                            fri_schedule_cost_q(b0, &got.schedule, q, cap),
                            Some(got.cost_q),
                            "{ctx}: cost of the schedule"
                        );
                        let sum: u32 = got.schedule.iter().map(|&d| u32::from(d)).sum();
                        assert_eq!(sum, b0 - t, "{ctx}: lands on the terminal");
                        assert!(
                            got.schedule
                                .iter()
                                .all(|&d| (1..=dmax).contains(&u32::from(d)))
                        );
                        checked += 1;
                    }
                    // Above the terminal: nothing to commit.
                    for t in b0 + 1..=b0 + 2 {
                        assert!(fri_schedule(b0, t, q, cap, dmax).is_empty());
                    }
                }
            }
        }
    }
    assert_eq!(checked, 4 * 3 * 4 * (17 * 18 / 2));
}

#[test]
fn dmax_one_is_the_legacy_schedule() {
    for b0 in 0..=30u32 {
        for t in 0..=31u32 {
            for cap in [&no_cap as &dyn Fn(u32) -> u32, &cap_auto, &cap_design_model] {
                assert_eq!(fri_schedule(b0, t, Q, cap, 1), legacy_fri_schedule(b0, t));
                // dmax = 0 is treated as 1.
                assert_eq!(fri_schedule(b0, t, Q, cap, 0), legacy_fri_schedule(b0, t));
            }
        }
    }
}

// ---------------------------------------------------------------------------
// U3: the legacy constructor is unchanged.
// ---------------------------------------------------------------------------

/// `FriFoldLayout::new` as it was before the schedule existed (terminal.rs @
/// 5d0b0a41a), copied verbatim: (total_folds, num_committed, terminal_len,
/// effective_k).
fn old_layout(lde_log: u32, blowup_log: u32, k: u32) -> (u32, usize, usize, u32) {
    let terminal_log = (blowup_log + k).min(lde_log);
    let total_folds = lde_log - terminal_log;
    (
        total_folds,
        total_folds.saturating_sub(1) as usize,
        1usize << terminal_log,
        terminal_log - blowup_log,
    )
}

#[test]
fn legacy_layout_equals_old_layout() {
    let dp_formats: Vec<FriFormat<'static>> = [false, true]
        .into_iter()
        .flat_map(|one_row| {
            [&no_cap as &'static dyn Fn(u32) -> u32, &cap_auto].map(|cap_height| FriFormat {
                mode: FriMode::Dp,
                one_row,
                num_queries: Q,
                cap_height,
            })
        })
        .collect();
    let mut checked = 0u32;
    for blowup_log in 1..=4u32 {
        // The LDE is at least the blowup (trace length ≥ 1).
        for lde_log in blowup_log..=30u32 {
            for k in 0..=10u32 {
                let ctx = format!("lde_log={lde_log} blowup_log={blowup_log} k={k}");
                let (total_folds, num_committed, terminal_len, effective_k) =
                    old_layout(lde_log, blowup_log, k);
                let new = FriFoldLayout::new(lde_log, blowup_log, k);
                assert_eq!(new.total_folds, total_folds, "{ctx}");
                assert_eq!(new.num_committed, num_committed, "{ctx}");
                assert_eq!(new.terminal_len, terminal_len, "{ctx}");
                assert_eq!(new.effective_k, effective_k, "{ctx}");
                assert_eq!(new.schedule, vec![1u8; num_committed], "{ctx}");
                assert!(!new.one_row, "{ctx}");

                // Pair mode ignores the query count and the cap policy.
                for cap_height in [&no_cap as &dyn Fn(u32) -> u32, &cap_auto] {
                    let pair = FriFormat {
                        mode: FriMode::Pair,
                        one_row: false,
                        num_queries: Q,
                        cap_height,
                    };
                    assert_eq!(
                        FriFoldLayout::for_format(lde_log, blowup_log, k, &pair),
                        new,
                        "{ctx}"
                    );
                }
                assert_eq!(
                    FriFoldLayout::from_schedule(
                        lde_log,
                        blowup_log,
                        k,
                        false,
                        new.schedule.clone()
                    ),
                    Some(new.clone()),
                    "{ctx}"
                );

                // Any format moves only the split of the folds into committed layers.
                for fmt in &dp_formats {
                    let l = FriFoldLayout::for_format(lde_log, blowup_log, k, fmt);
                    assert_eq!(
                        (l.total_folds, l.terminal_len, l.effective_k, l.one_row),
                        (total_folds, terminal_len, effective_k, fmt.one_row),
                        "{ctx} {fmt:?}"
                    );
                    assert_eq!(l.num_committed, l.schedule.len(), "{ctx} {fmt:?}");
                    let covered: u32 = l.schedule.iter().map(|&d| u32::from(d)).sum();
                    let expected = match (total_folds, fmt.one_row) {
                        (0, _) => 0,
                        (n, true) => n,
                        (n, false) => n - 1,
                    };
                    assert_eq!(covered, expected, "{ctx} {fmt:?}");
                    assert_eq!(
                        FriFoldLayout::from_schedule(
                            lde_log,
                            blowup_log,
                            k,
                            fmt.one_row,
                            l.schedule.clone()
                        ),
                        Some(l),
                        "{ctx} {fmt:?}"
                    );
                }
                checked += 1;
            }
        }
    }
    assert_eq!(checked, 11 * (30 + 29 + 28 + 27));
}

#[test]
fn from_schedule_rejects_a_schedule_that_does_not_cover_the_folds() {
    // lde_log 20, blowup 2, k 7: total_folds 11, row-pair chain covers 10 bits.
    assert!(FriFoldLayout::from_schedule(20, 2, 7, false, vec![4, 4, 2]).is_some());
    assert!(FriFoldLayout::from_schedule(20, 2, 7, false, vec![4, 4, 3]).is_none());
    assert!(FriFoldLayout::from_schedule(20, 2, 7, false, vec![4, 4, 1]).is_none());
    // One-row: the chain covers all 11.
    assert!(FriFoldLayout::from_schedule(20, 2, 7, true, vec![4, 4, 3]).is_some());
    assert!(FriFoldLayout::from_schedule(20, 2, 7, true, vec![4, 4, 2]).is_none());
    // Zero and over-DMAX exponents.
    assert!(FriFoldLayout::from_schedule(20, 2, 7, false, vec![0, 5, 5]).is_none());
    assert!(FriFoldLayout::from_schedule(20, 2, 7, false, vec![7, 3]).is_none());
    // No fold: only the empty schedule.
    assert!(FriFoldLayout::from_schedule(8, 2, 7, false, vec![]).is_some());
    assert!(FriFoldLayout::from_schedule(8, 2, 7, true, vec![1]).is_none());
    // One fold, row pair: no committed layer.
    assert!(FriFoldLayout::from_schedule(10, 2, 7, false, vec![]).is_some());
    assert!(FriFoldLayout::from_schedule(10, 2, 7, false, vec![1]).is_none());
    assert!(FriFoldLayout::from_schedule(10, 2, 7, true, vec![1]).is_some());
}
