[package]
name = "crypto"
description = "Data structures and primitives for cryptography library"
version = "0.1.0"
edition = "2024"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
math = { path = "../math", features = ["alloc"] }
digest = "0.10.7"
sha3 = { version = "0.10.8", default-features = false }
# Optional
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "alloc",
], optional = true }
rayon = { version = "1.8.0", optional = true }
memmap2 = { version = "0.9", optional = true }
tempfile = { version = "3", optional = true }
libc = { version = "0.2", optional = true }
rkyv = { version = "0.8.10", default-features = false, features = [
    "alloc",
    "bytecheck",
    "aligned",
], optional = true }

[target.'cfg(target_arch = "riscv64")'.dependencies]
lambda-vm-syscalls = { path = "../../syscalls" }

[dev-dependencies]
math = { path = "../math", features = ["test-utils"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
sha2 = { version = "0.10", default-features = false }
bincode = "1"

[features]
default = ["asm", "std"]
asm = ["sha3/asm"]
std = ["math/std", "sha3/std", "serde?/std"]
serde = ["dep:serde"]
parallel = ["dep:rayon"]
disk-spill = ["std", "dep:memmap2", "dep:tempfile", "dep:libc"]
alloc = []
rkyv = ["dep:rkyv", "math/rkyv"]