[package]
name = "lambda-vm-prover"
version = "0.1.0"
edition = "2024"

[features]
default = ["std", "prove", "parallel"]
std = ["stark/std", "math/std", "crypto/std", "executor/std"]
prove = []
parallel = ["stark/parallel", "math/parallel", "crypto/parallel", "dep:rayon", "std"]
debug-checks = ["stark/debug-checks", "std"]
instruments = ["stark/instruments", "std"]

[dependencies]
stark = { path = "../crypto/stark", default-features = false }
crypto = { path = "../crypto/crypto", default-features = false, features = ["serde"] }
math = { path = "../crypto/math", default-features = false, features = ["alloc", "lambdaworks-serde-binary"] }
executor = { path = "../executor", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
hashbrown = { version = "0.14", default-features = false, features = ["inline-more", "ahash"] }
rayon = { version = "1.8.0", optional = true }

[dev-dependencies]
env_logger = "*"
criterion = { version = "0.5", default-features = false }
postcard = { version = "1.0", features = ["alloc"] }

[[bench]]
name = "vm_prover_benchmark"
harness = false

[[bench]]
name = "profile_vm_prover"
harness = false
