use alloc::{collections::BTreeMap, vec::Vec};
#[cfg(feature = "alloc")]
use math::traits::Serializable;
use math::{errors::DeserializationError, traits::Deserializable};

use super::{
    traits::IsMerkleTreeBackend,
    utils::{get_parent_pos, get_sibling_pos, parent_index_arity, total_nodes_arity},
};

/// Stores a merkle path to some leaf.
/// Internally, the necessary hashes are stored from root to leaf in the
/// `merkle_path` field, in such a way that, if the merkle tree is of height `n`, the
/// `i`-th element of `merkle_path` is the sibling node in the `n - 1 - i`-th check
/// when verifying.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Proof<T: PartialEq + Eq> {
    pub merkle_path: Vec<T>,
}

impl<T: PartialEq + Eq + Clone> Proof<T> {
    /// Verifies a Merkle inclusion proof for the value contained at leaf index.
    pub fn verify<B>(&self, root_hash: &B::Node, mut index: usize, value: &B::Data) -> bool
    where
        B: IsMerkleTreeBackend<Node = T>,
    {
        let arity = B::ARITY;
        let mut hashed_value = B::hash_data(value);

        if arity == 2 {
            for sibling_node in self.merkle_path.iter() {
                if index.is_multiple_of(2) {
                    hashed_value = B::hash_new_parent(&hashed_value, sibling_node);
                } else {
                    hashed_value = B::hash_new_parent(sibling_node, &hashed_value);
                }
                index >>= 1;
            }
        } else {
            // For arity A, consume A-1 siblings per level.
            let siblings_per_level = arity - 1;
            let mut path_iter = self.merkle_path.chunks_exact(siblings_per_level);
            for siblings in path_iter.by_ref() {
                // The position of self among siblings
                let pos = index % arity;
                // Reconstruct the full children array
                let mut children = Vec::with_capacity(arity);
                let mut sib_idx = 0;
                for i in 0..arity {
                    if i == pos {
                        children.push(hashed_value.clone());
                    } else {
                        children.push(siblings[sib_idx].clone());
                        sib_idx += 1;
                    }
                }
                hashed_value = B::hash_children(&children);
                index /= arity;
            }
        }

        root_hash == &hashed_value
    }
}

#[cfg(feature = "alloc")]
impl<T> Serializable for Proof<T>
where
    T: Serializable + PartialEq + Eq,
{
    fn serialize(&self) -> Vec<u8> {
        self.merkle_path
            .iter()
            .flat_map(|node| node.serialize())
            .collect()
    }
}

impl<T> Deserializable for Proof<T>
where
    T: Deserializable + PartialEq + Eq,
{
    fn deserialize(bytes: &[u8]) -> Result<Self, DeserializationError>
    where
        Self: Sized,
    {
        let mut merkle_path = Vec::new();
        for elem in bytes[0..].chunks(8) {
            let node = T::deserialize(elem)?;
            merkle_path.push(node);
        }
        Ok(Self { merkle_path })
    }
}

/// Stores all the nodes needed to prove the inclusion of multiple leaves.
///
/// # Proof Ordering
/// The `path` contains the nodes in **descending order by tree index**:
/// - Higher indices (closer to leaves) come first
/// - Lower indices (closer to root) come last
/// - Within the same level, nodes are ordered from right to left (higher index first)
///
/// This ordering is critical for verification, which consumes nodes in the same order
/// as they were generated by `get_batch_proof`.
#[derive(Debug, Clone)]
pub struct BatchProof<T: PartialEq + Eq> {
    pub path: Vec<T>,
}

impl<T: PartialEq + Eq + Clone> BatchProof<T> {
    /// Verifies a batch Merkle proof for multiple leaves.
    /// Mirrors the logic of `get_batch_auth_path_positions` exactly.
    ///
    /// # Arguments
    /// * `root_hash` - The expected Merkle root
    /// * `pos_list` - Leaf positions (0-indexed from left to right)
    /// * `values` - The leaf values at those positions (not hashed)
    /// * `num_leaves` - Total number of leaves in the tree (must be a power of 2)
    pub fn verify<B>(
        &self,
        root_hash: &B::Node,
        pos_list: &[usize],
        values: &[B::Data],
        num_leaves: usize,
    ) -> bool
    where
        B: IsMerkleTreeBackend<Node = T>,
    {
        if pos_list.len() != values.len() || pos_list.is_empty() {
            return false;
        }

        let arity = B::ARITY;

        // Index of the first leaf as it is ordered in the tree struct (from top to bottom).
        let total = total_nodes_arity(num_leaves, arity);
        let first_leaf_index = total - num_leaves;

        // Build map of `position → hashed value`, validating that duplicate positions have the same value.
        let mut current_level_known_nodes: BTreeMap<usize, T> = BTreeMap::new();
        for (&pos, value) in pos_list.iter().zip(values.iter()) {
            let tree_index = pos + first_leaf_index;
            let hashed_value = B::hash_data(value);

            if let Some(existing) = current_level_known_nodes.get(&tree_index) {
                if existing != &hashed_value {
                    return false;
                }
            } else {
                current_level_known_nodes.insert(tree_index, hashed_value);
            }
        }

        let mut proof_path_iter = self.path.iter();

        let num_levels = if arity == 2 {
            (2 * num_leaves).ilog2()
        } else {
            let mut levels = 0u32;
            let mut size = num_leaves;
            while size > 1 {
                size /= arity;
                levels += 1;
            }
            levels + 1
        };

        // Process level by level, from bottom to top.
        for _ in 0..num_levels - 1 {
            let mut next_level_known_nodes: BTreeMap<usize, T> = BTreeMap::new();

            // Process each known node from right to left to match the order of the proof.
            for (pos, value) in current_level_known_nodes.iter().rev() {
                let parent_pos = if arity == 2 {
                    get_parent_pos(*pos)
                } else {
                    parent_index_arity(*pos, arity)
                };

                // Skip if parent was already computed
                if next_level_known_nodes.contains_key(&parent_pos) {
                    continue;
                }

                if arity == 2 {
                    let Some(sibling_pos) = get_sibling_pos(*pos) else {
                        continue;
                    };

                    let sibling_hash =
                        if let Some(hash) = current_level_known_nodes.get(&sibling_pos) {
                            hash
                        } else {
                            match proof_path_iter.next() {
                                Some(h) => h,
                                None => return false,
                            }
                        };

                    let parent_hash = if pos % 2 == 1 {
                        B::hash_new_parent(value, sibling_hash)
                    } else {
                        B::hash_new_parent(sibling_hash, value)
                    };

                    next_level_known_nodes.insert(parent_pos, parent_hash);
                } else {
                    // For arity A: collect all A children of the parent.
                    // Consume proof nodes right-to-left (descending) to match proof ordering,
                    // then assemble in correct left-to-right order for hashing.
                    let first_child = parent_pos * arity + 1;
                    let mut children: Vec<Option<T>> = (0..arity).map(|_| None).collect();

                    // First pass: fill in known nodes
                    for (i, slot) in children.iter_mut().enumerate() {
                        let child_idx = first_child + i;
                        if let Some(hash) = current_level_known_nodes.get(&child_idx) {
                            *slot = Some(hash.clone());
                        }
                    }

                    // Second pass: consume proof nodes right-to-left (descending index)
                    for i in (0..arity).rev() {
                        if children[i].is_none() {
                            match proof_path_iter.next() {
                                Some(h) => children[i] = Some(h.clone()),
                                None => return false,
                            }
                        }
                    }

                    let children: Vec<T> = children.into_iter().map(|c| c.unwrap()).collect();
                    let parent_hash = B::hash_children(&children);
                    next_level_known_nodes.insert(parent_pos, parent_hash);
                }
            }
            current_level_known_nodes = next_level_known_nodes;
        }

        // Verify: root computed correctly and all proof nodes consumed.
        proof_path_iter.next().is_none()
            && current_level_known_nodes.len() == 1
            && (current_level_known_nodes.get(&0) == Some(root_hash))
    }
}
