use alloc::{collections::BTreeMap, vec::Vec};
use math::{errors::DeserializationError, traits::Deserializable};

use super::{
    traits::IsMerkleTreeBackend,
    utils::{get_parent_pos, get_sibling_pos},
};

/// Stores a merkle path to some leaf.
/// Internally, the necessary hashes are stored from root to leaf in the
/// `merkle_path` field, in such a way that, if the merkle tree is of height `n`, the
/// `i`-th element of `merkle_path` is the sibling node in the `n - 1 - i`-th check
/// when verifying.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Proof<T: PartialEq + Eq> {
    pub merkle_path: Vec<T>,
}

#[hax_lib::attributes]
impl<T: PartialEq + Eq> Proof<T> {
    /// Verifies a Merkle inclusion proof for the value contained at leaf index.
    // Panic-freedom contract: with no precondition, `verify` always returns a
    // value (no panic, no divergence). The loop is a bounded fold over the
    // finite `merkle_path`; the only fallible ops (`index % 2`, `index >> 1`)
    // are total for the constant operands. Proved in Lean via the generated
    // `Impl.verify` spec (see proofs/hax). hax-lib macros are no-ops in native
    // builds, so these annotations are unconditional (cf. hax examples).
    #[hax_lib::requires(true)]
    #[hax_lib::ensures(|_res| true)]
    #[hax_lib::lean::proof_method::grind]
    pub fn verify<B>(&self, root_hash: &B::Node, mut index: usize, value: &B::Data) -> bool
    where
        B: IsMerkleTreeBackend<Node = T>,
    {
        let mut hashed_value = B::hash_data(value);

        // Range loop (not `.iter()`) so the Rust->Lean extractors model it as a
        // bounded `fold_range` rather than an `Iterator::fold` over a slice
        // iterator, which the hax Lean proof-lib does not support. Equivalent:
        // visits each `merkle_path` node once, in order.
        for i in 0..self.merkle_path.len() {
            let sibling_node = &self.merkle_path[i];
            if index.is_multiple_of(2) {
                hashed_value = B::hash_new_parent(&hashed_value, sibling_node);
            } else {
                hashed_value = B::hash_new_parent(sibling_node, &hashed_value);
            }

            index >>= 1;
        }

        root_hash == &hashed_value
    }
}

impl<T> Deserializable for Proof<T>
where
    T: Deserializable + PartialEq + Eq,
{
    fn deserialize(bytes: &[u8]) -> Result<Self, DeserializationError>
    where
        Self: Sized,
    {
        let mut merkle_path = Vec::new();
        for elem in bytes[0..].chunks(8) {
            let node = T::deserialize(elem)?;
            merkle_path.push(node);
        }
        Ok(Self { merkle_path })
    }
}

/// Stores all the nodes needed to prove the inclusion of multiple leaves.
///
/// # Proof Ordering
/// The `path` contains the nodes in **descending order by tree index**:
/// - Higher indices (closer to leaves) come first
/// - Lower indices (closer to root) come last
/// - Within the same level, nodes are ordered from right to left (higher index first)
///
/// This ordering is critical for verification, which consumes nodes in the same order
/// as they were generated by `get_batch_proof`.
#[derive(Debug, Clone)]
pub struct BatchProof<T: PartialEq + Eq> {
    pub path: Vec<T>,
}

impl<T: PartialEq + Eq + Clone> BatchProof<T> {
    /// Verifies a batch Merkle proof for multiple leaves.
    /// Mirrors the logic of `get_batch_auth_path_positions` exactly.
    ///
    /// # Arguments
    /// * `root_hash` - The expected Merkle root
    /// * `pos_list` - Leaf positions (0-indexed from left to right)
    /// * `values` - The leaf values at those positions (not hashed)
    /// * `num_leaves` - Total number of leaves in the tree (must be a power of 2)
    pub fn verify<B>(
        &self,
        root_hash: &B::Node,
        pos_list: &[usize],
        values: &[B::Data],
        num_leaves: usize,
    ) -> bool
    where
        B: IsMerkleTreeBackend<Node = T>,
    {
        if pos_list.len() != values.len() || pos_list.is_empty() {
            return false;
        }

        // Index of the first leaf as it is ordered in the tree struct (from top to bottom).
        let first_leaf_index = num_leaves - 1;

        // Build map of `position → hashed value`, validating that duplicate positions have the same value.
        // Since the nodes in the tree are indexed from the root to the leaves, we need to redefine the
        // given indices of the leaves.
        // We also need to hash all the given leaf values.
        // BTreeMap always maintains elements in ascending order, so here the leaves are ordered from
        // left (smaller index) to right (larger index).
        let mut current_level_known_nodes: BTreeMap<usize, T> = BTreeMap::new();
        for (&pos, value) in pos_list.iter().zip(values.iter()) {
            let tree_index = pos + first_leaf_index;
            let hashed_value = B::hash_data(value);

            if let Some(existing) = current_level_known_nodes.get(&tree_index) {
                // Duplicate position: values must be the same
                if existing != &hashed_value {
                    return false;
                }
                // Same value, skip (deduplicate)
            } else {
                current_level_known_nodes.insert(tree_index, hashed_value);
            }
        }

        let mut proof_path_iter = self.path.iter();

        let num_levels = (2 * num_leaves).ilog2();
        // Process level by level, from bottom to top, same as `get_batch_auth_path_positions`.
        for _ in 0..num_levels - 1 {
            let mut next_level_known_nodes: BTreeMap<usize, T> = BTreeMap::new();

            // Process each known node from right to left to match the order of the proof.
            // Since in `current_level_known_nodes` the nodes are ordered from left to right we take `.rev()`.
            for (pos, value) in current_level_known_nodes.iter().rev() {
                let parent_pos = get_parent_pos(*pos);

                // Skip if parent was already computed (i.e. sibling was processed first).
                if next_level_known_nodes.contains_key(&parent_pos) {
                    continue;
                }

                // Get sibling position (None only for root, which shouldn't appear here)
                let Some(sibling_pos) = get_sibling_pos(*pos) else {
                    continue;
                };

                // Get sibling value: from known nodes or from proof path.
                let sibling_hash = if let Some(hash) = current_level_known_nodes.get(&sibling_pos) {
                    hash
                } else {
                    match proof_path_iter.next() {
                        Some(h) => h,
                        None => return false,
                    }
                };

                // Compute parent hash.
                let parent_hash = if pos % 2 == 1 {
                    B::hash_new_parent(value, sibling_hash)
                } else {
                    B::hash_new_parent(sibling_hash, value)
                };

                next_level_known_nodes.insert(parent_pos, parent_hash);
            }
            current_level_known_nodes = next_level_known_nodes;
        }

        // Verify: root computed correctly and all proof nodes consumed.
        proof_path_iter.next().is_none()
            && current_level_known_nodes.len() == 1
            && (current_level_known_nodes.get(&0) == Some(root_hash))
    }
}
