#import "/book.typ": book-page

#show: book-page("stark.typ")

#set heading(numbering: "I.1.a.")

= Notation

== General notation

#let BaseField = math.FF
#let ExtensionField = math.GG

=== Sets

- $NN$: the set of non-zero natural integers.
- $[n]$ for $n in NN$: the set of integers ${0, dots, n - 1}$.
- $BaseField$: the base finite field used by the arithmetisation.
- $ExtensionField$: a finite extension of $BaseField$ of cryptographic size.

=== Tuples

- $X[i]$ for tuple $X$: the $i$-th element of $X$, starting at $0$.

== Arithmetisation notation

=== Tables

#let numTables = $sans(t)$
#let Table = $T$
#let TableSet = ${Table_i}_(i in [t])$
#let numColumns = $sans(m)$
#let numRows = $sans(n)$
#let maxNumRows = $numRows_sans("max")$

- $numTables in NN$: number of tables $Table_i$ in the arithmetisation of the VM.
- $Table_i in BaseField^(numRows_i times numColumns_i)$: a table in the arithmetisation of the VM; $TableSet$ denotes set of all tables.
- $numColumns_i in NN$: number of _columns_ in table $Table_i$ (not the number of variables).
- $numRows_i in NN$: number of _rows_ in table $Table_i$.

=== Constraints

#let indX = $cal(X)$
#let indY = $cal(Y)$
#let indTuple = $arrow(indX)$
#let numConstraints = $sans(c)$
#let ConstraintSet = $scr(C)$
#let Constraint = $cal(C)$
#let constraintDegree = $sans(d)$
#let EnforcementDom = $scr(H)$

- $indTuple_i = (indX_(i,1), dots, indX_(i, numColumns_i), indY_(i,1), dots, indY_(i, numColumns_i))$: _tuple of $2 numColumns_i$ indeterminates_, two for each column of a table: one $indX$ for the current row, and one $indY$ for the following row.
- $numConstraints_i in NN$: _number of constraints_ for table $Table_i$.
- $ConstraintSet_i subset BaseField[indTuple_i]$: _set of constraints_ for table $Table_i$, of size $numConstraints_i$.
- $Constraint_(i,j) in BaseField[indTuple_i]$: $j$-th _constraint polynomial_ for $Table_i$, for $j in [numConstraints_i]$.
- $EnforcementDom_(i,j) subset [numRows_i]$: _enforcement domain_ for the $j$-th constraint of table $Table_i$, selecting the rows for which the $j$-th constraint equation is expecting to hold.
- $j$-th _constraint equation_ for table $Table_i$: $ forall k in EnforcementDom_(i,j), quad Constraint_(i,j)(Table_i [k] || Table_i [k+1]) = 0_BaseField. $

= STARK Protocol

== Initial Commitment

=== Interpolation

#let traceColPoly = $cal(t)$
#let BasePolyRing = $BaseField[indX]$
#let multGen = $g$

When the $i$-th trace table $Table_i$ is successfully _padded_ to its length $numRows_i$, the Prover interpolates its $numColumns_i$ columns into univariate _(trace) column polynomials_ $traceColPoly_(i,j) in BasePolyRing^(< numRows_i)$, for $j in [numColumns_i]$.

Interpolation requires a set of interpolation points, chosen to be a subgroup of the multiplicative group $(BaseField, ast)$ generated by a primitive $numRows_i$-th root of unity $multGen_i in BaseField$.
With this set chosen, it then holds that $traceColPoly_(i,j)(multGen_i^k) = Table_i [k, j]$ for $k in [numRows_i], j in [numColumns_i]$.

*Output:* for each table $Table_i$, $numColumns_i$ column polynomials $traceColPoly_(i,j)$.

=== Codeword Evaluation

#let FRIDomain = $D$
#let FRIDomainMax = $D_(sans("max"))$
#let FRIRate = $rho$
#let FRICodeword = $arrow(c)$

To use the FRI protocol, each column polynomial has to be encoded as a Reed--Solomon codeword.
Since the codewords are evaluations of the polynomials, this requires an evaluation set, called the FRI (evaluation) domain.
Let the initial domain be denoted $FRIDomainMax$.

The soundness of the FRI protocol requires that the length of the codeword be a small expansion factor larger than the maximum degree of the polynomials that are to be encoded.
This therefore implies $abs(FRIDomainMax) = 2^(- log(FRIRate)) dot maxNumRows$ for some expansion factor $1 / FRIRate > 1$.
By this construction, $abs(FRIDomainMax)$ is also a power of two which allows for efficient NTT-based evaluations of the column polynomials over it.

Each column polynomial $traceColPoly_(i,j)$ is encoded as $FRICodeword_(i,j) in BaseField^abs(FRIDomain_i)$, where, looking ahead, $FRIDomain_i$ with $abs(FRIDomain_i) = 2^(- log(FRIRate)) dot numColumns_i$ is chosen for table $Table_i$ such that it is suitable for FRI pipelining.

*Output:* for each table $Table_i$, $numColumns_i$ codewords $FRICodeword_(i,j)$.

=== Codeword Commitment

#let MerkleRoot = $sans("rt")$

Before the protocol can continue, the column polynomials are committed to.
This is achieved by committing to their encodings using a _Merkle commitment scheme_.
Naïvely, each codeword would have its own Merkle tree, where the leaves contain the symbols of the codeword (or their hash with a salt for the hiding variant).

However, looking ahead once more, the folding factor in the configuration of the FRI protocol will require the opening of more than one symbol of each codeword for every query point.
Several symbols (selected by a fixed offset determined by the folding factor) can therefore be concatenated into the same leaf of the codeword's Merkle tree.

Furthermore, all commitments to codewords of the same length will be opened in the same location.
Therefore the leaves can be instead set to be concatenations of the set of symbols at the same position across different codewords.

*Output:* for each table $Table_i$, a Merkle commitment $MerkleRoot_i$.

== Claim Re-interpretation

#let Zerofier = $cal(Z)$
#let zerofierDegree = $sans(z)$
#let ComposedConstraint = $hat(Constraint)$

By committing to the $sum_i numColumns_i$ trace column polynomials across all $numTables$ tables, the Prover is implicitly making the claim "the set $ConstraintSet_i$ of constraint equations is satisfied by the expected values in table $Table_i$".
This set of $sum_i numConstraints_i$ claims is not very algebraically "nice" so it needs to be re-interpreted.

For a given constraint polynomial $Constraint_(i,j)$, first let $Zerofier_(i,j)(indX) = product_(k in EnforcementDom_(i,j)) (indX - x_(i,j,k))$ denote the _zerofier polynomial_ which equals $0$ for every interpolation point $x_(i,j,k)$ indexing a row for which $Constraint_(i,j)$ is expected to be satisfied, and let $zerofierDegree_(i,j)$ denote its degree.
The claim that "the constraint equation is satisfied at every expected row" can now be rewritten as $ Constraint(i,j) compose arrow(traceColPoly)_i "is divisible by" Zerofier_(i,j) $ where $arrow(traceColPoly)_i = (traceColPoly_(i,1)(indX), dots, traceColPoly_(i, numColumns_i)(indX), traceColPoly_(i,1)(multGen dot indX), dots, traceColPoly_(i, numColumns_i)(multGen dot indX))$ denotes the variable substitution of each $indX_(i,j)$ and $indY_(i,j)$ in $indTuple$ with $traceColPoly_(i,j)(indX)$ and $traceColPoly_(i,j)(multGen dot indX)$ respectively, and $compose$ denotes function composition of the multivariate polynomial $Constraint_(i,j)$ with the univariate vector $arrow(traceColPoly)_i$, yielding a univariate polynomial.

Polynomial divisibility is a difficult claim to prove in this initial form, but it can be re-interpreted as a low-degree claim with the observation that if one polynomial divides another, then the quotient is itself a polynomial, and it has a predictable degree.
In our case, the constraint polynomial $Constraint_(i,j)$ has constraint degree $constraintDegree_(i,j)$, the column polynomials $traceColPoly_(i,j)$ all have degree strictly less than $numRows_i$, and the zerofier polynomial $Zerofier_(i,j)$ has degree $zerofierDegree_(i,j)$.
This implies that the univariate _composed constraint polynomial_ $ComposedConstraint_(i,j) = (Constraint_(i,j) compose arrow(traceColPoly)_i) / Zerofier_(i,j)$ is expected to have degree strictly less than $constraintDegree_(i,j) dot numRows_i - zerofierDegree_(i,j)$.

In conclusion, the $sum_(i in [numTables]) numConstraints_i$ claims that the constraint equation sets are satisfied by the table values can be re-interpreted as the equivalent claims that $ ComposedConstraint_(i,j)(indX) = (Constraint_(i,j) compose arrow(traceColPoly)_i (indX)) / (Zerofier_(i,j)(indX)) "has degree" < constraintDegree_(i,j) dot numRows_i - zerofierDegree_(i,j), $ for $i in [numTables]$ and $j in [numConstraints_i]$.

== Verifier Challenge for Degree Correction and Constraint Claim Batching

#let degreeGap = $sans(g)$
#let batchingChallenge = $alpha$
#let degreeChallenge = $beta$

When multiple claims are expected to hold simultaneously, the standard trick in cryptography is to compute a single claim, constructed as a random linear combination of the multiples ones, and verify that this batched claim holds.
However, to apply this batching technique, the multiple claims need to be homogeneous, which is not necessarily the case of the low-degree claims the composed constraint polynomials $ComposedConstraint_(i, j)$ since each might have a different degree bound.

To homogenise these claims, the protocol must first apply _degree correction_ with the help of randomisers provided by the verifier.
First, let $constraintDegree in NN$ such that $ log_2(constraintDegree) = ceil(log_2 max_(i,j){constraintDegree_(i,j) dot numRows_i - zerofierDegree_(i,j)}) $ denote the next power-of-two degree bound on the composed constraint polynomials. That is, $constraintDegree$ is the smallest power of two that is greater than or equal to the degree of any composed constraint polynomial.
Then let $ degreeGap_(i, j) = constraintDegree - (constraintDegree_(i, j) dot numRows_i - zerofierDegree_(i, j)) $ denote the _degree gap_ for the composed constraint polynomial $ComposedConstraint_(i,j)$ with respect to $constraintDegree$.

Degree correction works by receiving two random extension field challenges $batchingChallenge_(i,j)$ and $degreeChallenge_(i,j)$ from the verifier for each low-degree claim and transforming each claim into $ ComposedConstraint_(i,j)(indX) dot (batchingChallenge_(i,j) + degreeChallenge_(i,j) dot indX^(degreeGap_(i,j))) "has degree" < constraintDegree. $
This introduces a small soundness loss as there is the possibility that an invalid claim gets degree-corrected into a valid one.

Now that every claim is corrected to be of the same degree, they can all be batched into the single claim $ ComposedConstraint(indX) = sum_(i,j) ComposedConstraint_(i,j)(indX) dot (batchingChallenge_(i,j) + degreeChallenge_(i,j) dot indX^(degreeGap_(i,j))) "has degree" < constraintDegree. $

Note that the prover is implicitly committed to this claim by virtue of being committed to the column polynomials and having received the verifier challenges, so it does not need to send another commitment to make this claim.
