#import "/book.typ": book-page

#show: book-page("stark.typ")

#set heading(numbering: "I.1.a.")

= Notation

== General notation

#let BaseField = math.FF
#let ExtensionField = math.GG

=== Sets

- $NN$: the set of non-zero natural integers.
- $[n]$ for $n in NN$: the set of integers ${0, dots, n - 1}$.
- $BaseField$: the base finite field used by the arithmetisation.
- $ExtensionField$: a finite extension of $BaseField$ of cryptographic size.

=== Tuples

- $X[i]$ for tuple $X$: the $i$-th element of $X$, starting at $0$.

== Arithmetisation notation

=== Tables

#let numTables = $sans(t)$
#let Table = $T$
#let TableSet = ${Table_i}_(i in [t])$
#let numColumns = $sans(m)$
#let numRows = $sans(n)$
#let maxNumRows = $numRows_sans("max")$

- $numTables in NN$: number of tables $Table_i$ in the arithmetisation of the VM.
- $Table_i in BaseField^(numRows_i times numColumns_i)$: a table in the arithmetisation of the VM; $TableSet$ denotes set of all tables.
- $numColumns_i in NN$: number of _columns_ in table $Table_i$ (not the number of variables).
- $numRows_i in NN$: number of _rows_ in table $Table_i$.

=== Constraints

#let indX = $cal(X)$
#let indY = $cal(Y)$
#let indTuple = $arrow(indX)$
#let numConstraints = $sans(c)$
#let ConstraintSet = $scr(C)$
#let Constraint = $cal(C)$
#let EnforcementDom = $scr(H)$

- $indTuple_i = (indX_(i,1), dots, indX_(i, numColumns_i), indY_(i,1), dots, indY_(i, numColumns_i))$: _tuple of $2 numColumns_i$ indeterminates_, two for each column of a table: one $indX$ for the current row, and one $indY$ for the following row.
- $numConstraints_i in NN$: _number of constraints_ for table $Table_i$.
- $ConstraintSet_i subset BaseField[indTuple_i]$: _set of constraints_ for table $Table_i$, of size $numConstraints_i$.
- $Constraint_(i,j) in BaseField[indTuple_i]$: $j$-th _constraint polynomial_ for $Table_i$, for $j in [numConstraints_i]$.
- $EnforcementDom_(i,j) subset [numRows_i]$: _enforcement domain_ for the $j$-th constraint of table $Table_i$, selecting the rows for which the $j$-th constraint equation is expecting to hold.
- $j$-th _constraint equation_ for table $Table_i$: $ forall k in EnforcementDom_(i,j), quad Constraint_(i,j)(Table_i [k] || Table_i [k+1]) = 0_BaseField. $

= STARK Protocol

== Initial Commitment

=== Interpolation

#let traceColPoly = $cal(t)$
#let BasePolyRing = $BaseField[indX]$
#let multGen = $g$

When the $i$-th trace table $Table_i$ is successfully _padded_ to its length $numRows_i$, the Prover interpolates its $numColumns_i$ columns into univariate _(trace) column polynomials_ $traceColPoly_(i,j) in BasePolyRing^(< numRows_i)$, for $j in [numColumns_i]$.

Interpolation requires a set of interpolation points, chosen to be a subgroup of the multiplicative group $(BaseField, ast)$ generated by a primitive $numRows_i$-th root of unity $multGen_i in BaseField$.
With this set chosen, it then holds that $traceColPoly_(i,j)(multGen_i^k) = Table_i [k, j]$ for $k in [numRows_i], j in [numColumns_i]$.

*Output:* for each table $Table_i$, $numColumns_i$ column polynomials $traceColPoly_(i,j)$.

=== Codeword Evaluation

#let FRIDomain = $D$
#let FRIDomainMax = $D_(sans("max"))$
#let FRIRate = $rho$
#let FRICodeword = $arrow(c)$

To use the FRI protocol, each column polynomial has to be encoded as a Reed--Solomon codeword.
Since the codewords are evaluations of the polynomials, this requires an evaluation set, called the FRI (evaluation) domain.
Let the initial domain be denoted $FRIDomainMax$.

The soundness of the FRI protocol requires that the length of the codeword be a small expansion factor larger than the maximum degree of the polynomials that are to be encoded.
This therefore implies $abs(FRIDomainMax) = 2^(- log(FRIRate)) dot maxNumRows$ for some expansion factor $1 / FRIRate > 1$.
By this construction, $abs(FRIDomainMax)$ is also a power of two which allows for efficient NTT-based evaluations of the column polynomials over it.

Each column polynomial $traceColPoly_(i,j)$ is encoded as $FRICodeword_(i,j) in BaseField^abs(FRIDomain_i)$, where, looking ahead, $FRIDomain_i$ with $abs(FRIDomain_i) = 2^(- log(FRIRate)) dot numColumns_i$ is chosen for table $Table_i$ such that it is suitable for FRI pipelining.

*Output:* for each table $Table_i$, $numColumns_i$ codewords $FRICodeword_(i,j)$.

=== Codeword Commitment

#let MerkleRoot = $sans("rt")$

Before the protocol can continue, the column polynomials are committed to.
This is achieved by committing to their encodings using a _Merkle commitment scheme_.
Naïvely, each codeword would have its own Merkle tree, where the leaves contain the symbols of the codeword (or their hash with a salt for the hiding variant).

However, looking ahead once more, the folding factor in the configuration of the FRI protocol will require the opening of more than one symbol of each codeword for every query point.
Several symbols (selected by a fixed offset determined by the folding factor) can therefore be concatenated into the same leaf of the codeword's Merkle tree.

Furthermore, all commitments to codewords of the same length will be opened in the same location.
Therefore the leaves can be instead set to be concatenations of the set of symbols at the same position across different codewords.

*Output:* for each table $Table_i$, a Merkle commitment $MerkleRoot_i$.
