-- AUTO-GENERATED by proofs/scripts/carve_merkle_verify.py — DO NOT EDIT.
-- The single-leaf Merkle `Proof::verify` subset, carved from the aeneas
-- output by dependency closure so it compiles standalone (the full
-- Crypto/Funs.lean does not, due to out-of-scope upstream-blocked code).
-- Re-run the carve script after regenerating; no manual maintenance.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

-- Missing Aeneas Std model: `usize::is_multiple_of` (Rust 1.87) is
-- referenced by the generated code but not provided by this aeneas
-- version's Std. Defined here computably (mirrors the Rust semantics)
-- so the carved module is self-contained and the predicate is provable.
def core.num.Usize.is_multiple_of (x : Std.Usize) (n : Std.Usize) :
    Result Bool := ok (x.val % n.val == 0)

-- `merkle_tree.merkle.ROOT = 0`. The generated def is an inline-attr
-- one-liner (`@[global_simps, irreducible] def ROOT := 0#usize`) that the
-- block-carver does not split cleanly, so it is supplied here verbatim.
def merkle_tree.merkle.ROOT : Std.Usize := 0#usize

-- Missing Aeneas Std model: `usize::ilog2` (-> u32). Used ONLY by
-- `build_merkle_path` to size a `Vec::with_capacity` hint — the value has
-- no effect on the result (capacity, not length), so it is modelled as the
-- total constant `0` to keep the carve self-contained and panic-free.
def core.num.Usize.ilog2 (_x : Std.Usize) : Result Std.U32 := ok 0#u32

noncomputable section


/-- Trait declaration: [crypto::merkle_tree::traits::IsMerkleTreeBackend]
    Source: 'crypto/crypto/src/merkle_tree/traits.rs', lines 8:0-29:1
    Visibility: public -/
structure merkle_tree.traits.IsMerkleTreeBackend (Self : Type) (Self_Node :
  Type) (Self_Data : Type) where
  corecmpPartialEqInst : core.cmp.PartialEq Self_Node Self_Node
  corecmpEqInst : core.cmp.Eq Self_Node
  corecloneCloneInst : core.clone.Clone Self_Node
  hash_data : Self_Data → Result Self_Node
  hash_leaves : Slice Self_Data → Result (alloc.vec.Vec Self_Node)
  hash_new_parent : Self_Node → Self_Node → Result Self_Node


/-- [crypto::merkle_tree::merkle::Error]
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 11:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive merkle_tree.merkle.Error where
| OutOfBounds : merkle_tree.merkle.Error
| EmptyPositionList : merkle_tree.merkle.Error


/-- [crypto::merkle_tree::merkle::MerkleTree]
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 55:0-61:1
    Visibility: public -/
structure merkle_tree.merkle.MerkleTree (B : Type) (Clause0_Node : Type)
  (Clause0_Data : Type) where
  root : Clause0_Node
  nodes : alloc.vec.Vec Clause0_Node


/-- [crypto::merkle_tree::proof::Proof]
    Source: 'crypto/crypto/src/merkle_tree/proof.rs', lines 16:0-18:1
    Visibility: public -/
structure merkle_tree.proof.Proof (T : Type) where
  merkle_path : alloc.vec.Vec T


/-- [crypto::merkle_tree::utils::is_power_of_two]:
    Source: 'crypto/crypto/src/merkle_tree/utils.rs', lines 61:0-63:1 -/
def merkle_tree.utils.is_power_of_two (x : Std.Usize) : Result Bool := do
  let i ← x - 1#usize
  let i1 ← lift (x &&& i)
  ok (i1 = 0#usize)


/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::node_count]:
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 203:4-209:5 -/
def merkle_tree.merkle.MerkleTree.node_count
  {B : Type} {Clause0_Node : Type} {Clause0_Data : Type}
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B
  Clause0_Node Clause0_Data)
  (self : merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data) :
  Result Std.Usize
  := do
  ok (alloc.vec.Vec.len self.nodes)


/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::node_get]:
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 214:4-233:5 -/
def merkle_tree.merkle.MerkleTree.node_get
  {B : Type} {Clause0_Node : Type} {Clause0_Data : Type}
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B
  Clause0_Node Clause0_Data)
  (self : merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data)
  (idx : Std.Usize) :
  Result (Option Clause0_Node)
  := do
  let s := alloc.vec.Vec.deref self.nodes
  core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Clause0_Node) s
    idx


/-- [crypto::merkle_tree::utils::parent_index]:
    Source: 'crypto/crypto/src/merkle_tree/utils.rs', lines 15:0-21:1
    Visibility: public -/
def merkle_tree.utils.parent_index
  (node_index : Std.Usize) : Result Std.Usize := do
  let b ← core.num.Usize.is_multiple_of node_index 2#usize
  if b
  then let i ← node_index - 1#usize
       i / 2#usize
  else node_index / 2#usize


/-- [crypto::merkle_tree::utils::sibling_index]:
    Source: 'crypto/crypto/src/merkle_tree/utils.rs', lines 7:0-13:1
    Visibility: public -/
def merkle_tree.utils.sibling_index
  (node_index : Std.Usize) : Result Std.Usize := do
  let b ← core.num.Usize.is_multiple_of node_index 2#usize
  if b
  then node_index - 1#usize
  else node_index + 1#usize


/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::build_merkle_path]: loop body 0:
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 266:8-277:5 -/
@[rust_loop_body]
def merkle_tree.merkle.MerkleTree.build_merkle_path_loop.body
  {B : Type} {Clause0_Node : Type} {Clause0_Data : Type}
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B
  Clause0_Node Clause0_Data)
  (self : merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data)
  (merkle_path : alloc.vec.Vec Clause0_Node) (pos : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Clause0_Node) × Std.Usize)
    (core.result.Result (alloc.vec.Vec Clause0_Node) merkle_tree.merkle.Error))
  := do
  if pos != merkle_tree.merkle.ROOT
  then
    let i ← merkle_tree.utils.sibling_index pos
    let o ←
      merkle_tree.merkle.MerkleTree.node_get traitsIsMerkleTreeBackendInst self
        i
    match o with
    | none =>
      ok (done (core.result.Result.Err merkle_tree.merkle.Error.OutOfBounds))
    | some node =>
      let t ← traitsIsMerkleTreeBackendInst.corecloneCloneInst.clone node
      let merkle_path1 ← alloc.vec.Vec.push merkle_path t
      let pos1 ← merkle_tree.utils.parent_index pos
      ok (cont (merkle_path1, pos1))
  else ok (done (core.result.Result.Ok merkle_path))


/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::build_merkle_path]: loop 0:
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 266:8-277:5 -/
@[rust_loop]
def merkle_tree.merkle.MerkleTree.build_merkle_path_loop
  {B : Type} {Clause0_Node : Type} {Clause0_Data : Type}
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B
  Clause0_Node Clause0_Data)
  (self : merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data)
  (merkle_path : alloc.vec.Vec Clause0_Node) (pos : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec Clause0_Node)
    merkle_tree.merkle.Error)
  := do
  loop
    (fun (merkle_path1, pos1) =>
      merkle_tree.merkle.MerkleTree.build_merkle_path_loop.body
      traitsIsMerkleTreeBackendInst self merkle_path1 pos1)
    (merkle_path, pos)


/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::build_merkle_path]:
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 260:4-277:5 -/
def merkle_tree.merkle.MerkleTree.build_merkle_path
  {B : Type} {Clause0_Node : Type} {Clause0_Data : Type}
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B
  Clause0_Node Clause0_Data)
  (self : merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data)
  (pos : Std.Usize) :
  Result (core.result.Result (alloc.vec.Vec Clause0_Node)
    merkle_tree.merkle.Error)
  := do
  let i ←
    merkle_tree.merkle.MerkleTree.node_count traitsIsMerkleTreeBackendInst self
  let i1 ← i + 1#usize
  let i2 ← core.num.Usize.ilog2 i1
  let tree_depth ← lift (UScalar.cast .Usize i2)
  let merkle_path := alloc.vec.Vec.with_capacity Clause0_Node tree_depth
  merkle_tree.merkle.MerkleTree.build_merkle_path_loop
    traitsIsMerkleTreeBackendInst self merkle_path pos


/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::create_proof]:
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 255:4-257:5 -/
def merkle_tree.merkle.MerkleTree.create_proof
  {B : Type} {Clause0_Node : Type} {Clause0_Data : Type}
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B
  Clause0_Node Clause0_Data)
  (self : merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data)
  (merkle_path : alloc.vec.Vec Clause0_Node) :
  Result (Option (merkle_tree.proof.Proof Clause0_Node))
  := do
  ok (some { merkle_path })


/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::get_proof_by_pos]:
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 245:4-252:5
    Visibility: public -/
def merkle_tree.merkle.MerkleTree.get_proof_by_pos
  {B : Type} {Clause0_Node : Type} {Clause0_Data : Type}
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B
  Clause0_Node Clause0_Data)
  (self : merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data)
  (pos : Std.Usize) :
  Result (Option (merkle_tree.proof.Proof Clause0_Node))
  := do
  let i ←
    merkle_tree.merkle.MerkleTree.node_count traitsIsMerkleTreeBackendInst self
  let i1 ← i / 2#usize
  let pos1 ← pos + i1
  let r ←
    merkle_tree.merkle.MerkleTree.build_merkle_path
      traitsIsMerkleTreeBackendInst self pos1
  match r with
  | core.result.Result.Ok merkle_path =>
    merkle_tree.merkle.MerkleTree.create_proof traitsIsMerkleTreeBackendInst
      self merkle_path
  | core.result.Result.Err _ => ok none


/-- [crypto::merkle_tree::utils::get_parent_pos]:
    Source: 'crypto/crypto/src/merkle_tree/utils.rs', lines 36:0-46:1
    Visibility: public -/
def merkle_tree.utils.get_parent_pos
  (node_index : Std.Usize) : Result Std.Usize := do
  if node_index = 0#usize
  then ok node_index
  else
    let b ← core.num.Usize.is_multiple_of node_index 2#usize
    if b
    then let i ← node_index - 1#usize
         i / 2#usize
    else node_index / 2#usize


/-- [crypto::merkle_tree::utils::get_sibling_pos]:
    Source: 'crypto/crypto/src/merkle_tree/utils.rs', lines 25:0-34:1
    Visibility: public -/
def merkle_tree.utils.get_sibling_pos
  (node_index : Std.Usize) : Result (Option Std.Usize) := do
  if node_index = 0#usize
  then ok none
  else
    let b ← core.num.Usize.is_multiple_of node_index 2#usize
    if b
    then let i ← node_index - 1#usize
         ok (some i)
    else let i ← node_index + 1#usize
         ok (some i)


/-- [crypto::merkle_tree::proof::{crypto::merkle_tree::proof::Proof<T>}::verify]: loop body 0:
    Source: 'crypto/crypto/src/merkle_tree/proof.rs', lines 42:8-51:9
    Visibility: public -/
@[rust_loop_body]
def merkle_tree.proof.Proof.verify_loop.body
  {T : Type} {B : Type} {Clause2_Data : Type} (traitsIsMerkleTreeBackendInst :
  merkle_tree.traits.IsMerkleTreeBackend B T Clause2_Data)
  (v : alloc.vec.Vec T) (iter : core.ops.range.Range Std.Usize)
  (index : Std.Usize) (hashed_value : T) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.Usize × T) T)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done hashed_value)
  | some i =>
    let sibling_node ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice T) v i
    let b ← core.num.Usize.is_multiple_of index 2#usize
    let hashed_value1 ←
      if b
      then
        traitsIsMerkleTreeBackendInst.hash_new_parent hashed_value sibling_node
      else
        traitsIsMerkleTreeBackendInst.hash_new_parent sibling_node hashed_value
    let index1 ← index >>> 1#i32
    ok (cont (iter1, index1, hashed_value1))


/-- [crypto::merkle_tree::proof::{crypto::merkle_tree::proof::Proof<T>}::verify]: loop 0:
    Source: 'crypto/crypto/src/merkle_tree/proof.rs', lines 42:8-51:9
    Visibility: public -/
@[rust_loop]
def merkle_tree.proof.Proof.verify_loop
  {T : Type} {B : Type} {Clause2_Data : Type} (traitsIsMerkleTreeBackendInst :
  merkle_tree.traits.IsMerkleTreeBackend B T Clause2_Data)
  (iter : core.ops.range.Range Std.Usize) (v : alloc.vec.Vec T)
  (index : Std.Usize) (hashed_value : T) :
  Result T
  := do
  loop
    (fun (iter1, index1, hashed_value1) =>
      merkle_tree.proof.Proof.verify_loop.body traitsIsMerkleTreeBackendInst v
      iter1 index1 hashed_value1)
    (iter, index, hashed_value)


/-- [crypto::merkle_tree::proof::{crypto::merkle_tree::proof::Proof<T>}::verify]:
    Source: 'crypto/crypto/src/merkle_tree/proof.rs', lines 32:4-54:5
    Visibility: public -/
def merkle_tree.proof.Proof.verify
  {T : Type} {B : Type} {Clause2_Data : Type} (corecmpPartialEqInst :
  core.cmp.PartialEq T T) (corecmpEqInst : core.cmp.Eq T)
  (traitsIsMerkleTreeBackendInst : merkle_tree.traits.IsMerkleTreeBackend B T
  Clause2_Data) (self : merkle_tree.proof.Proof T) (root_hash : T)
  (index : Std.Usize) (value : Clause2_Data) :
  Result Bool
  := do
  let hashed_value ← traitsIsMerkleTreeBackendInst.hash_data value
  let i := alloc.vec.Vec.len self.merkle_path
  let hashed_value1 ←
    merkle_tree.proof.Proof.verify_loop traitsIsMerkleTreeBackendInst
      { start := 0#usize, «end» := i } self.merkle_path index hashed_value
  core.cmp.impls.PartialEqShared.eq corecmpPartialEqInst root_hash
    hashed_value1

end
