-- [patched by patch_aeneas_crypto_types.py]
-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [crypto]: type definitions
import Aeneas
import Crypto.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace crypto

/-- Trait declaration: [core::convert::AsRef]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 219:0-219:52
    Name pattern: [core::convert::AsRef]
    Visibility: public -/
@[rust_trait "core::convert::AsRef"]
structure core.convert.AsRef (Self : Type) (T : Type) where
  as_ref : Self → Result T

/-- Trait declaration: [core::borrow::Borrow]
    Source: '/rustc/library/core/src/borrow.rs', lines 158:0-158:40
    Name pattern: [core::borrow::Borrow]
    Visibility: public -/
@[rust_trait "core::borrow::Borrow"]
structure core.borrow.Borrow (Self : Type) (Borrowed : Type) where
  borrow : Self → Result Borrowed

/-- Trait declaration: [core::fmt::UpperHex]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 1432:0-1432:32
    Name pattern: [core::fmt::UpperHex]
    Visibility: public -/
@[rust_trait "core::fmt::UpperHex"]
structure core.fmt.UpperHex (Self : Type) where
  fmt : Self → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- [core::marker::PhantomData]
    Source: '/rustc/library/core/src/marker.rs', lines 811:0-811:39
    Name pattern: [core::marker::PhantomData]
    Visibility: public -/
@[reducible, rust_type "core::marker::PhantomData"]
def core.marker.PhantomData (T : Type) := Unit

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31
    Name pattern: [core::ops::arith::Add]
    Visibility: public -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::bit::Shr]
    Source: '/rustc/library/core/src/ops/bit.rs', lines 584:0-584:31
    Name pattern: [core::ops::bit::Shr]
    Visibility: public -/
@[rust_trait "core::ops::bit::Shr"]
structure core.ops.bit.Shr (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  shr : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::bit::ShrAssign]
    Source: '/rustc/library/core/src/ops/bit.rs', lines 1026:0-1026:37
    Name pattern: [core::ops::bit::ShrAssign]
    Visibility: public -/
@[rust_trait "core::ops::bit::ShrAssign"]
structure core.ops.bit.ShrAssign (Self : Type) (Rhs : Type) where
  shr_assign : Self → Rhs → Result Self

/-- Trait declaration: [alloc::slice::Concat]
    Source: '/rustc/library/alloc/src/slice.rs', lines 702:0-702:30
    Name pattern: [alloc::slice::Concat]
    Visibility: public -/
@[rust_trait "alloc::slice::Concat"]
structure alloc.slice.Concat (Self : Type) (Item : Type) (Self_Output : Type)
  where
  concat : Self → Result Self_Output

/-- Trait declaration: [typenum::sealed::Sealed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 154:4-154:20
    Name pattern: [typenum::sealed::Sealed]
    Visibility: public -/
@[rust_trait "typenum::sealed::Sealed"]
structure typenum.sealed.Sealed (Self : Type) where

/-- Trait declaration: [typenum::marker_traits::Unsigned]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 59:0-59:53
    Name pattern: [typenum::marker_traits::Unsigned]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Unsigned"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "U16", "U32", "U64", "USIZE", "I8", "I16", "I32", "I64", "ISIZE"])]
structure typenum.marker_traits.Unsigned (Self : Type) where
  U8 : Result Std.U8
  U16 : Result Std.U16
  U32 : Result Std.U32
  U64 : Result Std.U64
  USIZE : Result Std.Usize
  I8 : Result Std.I8
  I16 : Result Std.I16
  I32 : Result Std.I32
  I64 : Result Std.I64
  ISIZE : Result Std.Isize
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  to_u8 : Result Std.U8
  to_u16 : Result Std.U16
  to_u32 : Result Std.U32
  to_u64 : Result Std.U64
  to_usize : Result Std.Usize
  to_i8 : Result Std.I8
  to_i16 : Result Std.I16
  to_i32 : Result Std.I32
  to_i64 : Result Std.I64
  to_isize : Result Std.Isize

/-- Trait declaration: [generic_array::ArrayLength]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 112:0-112:41
    Name pattern: [generic_array::ArrayLength]
    Visibility: public -/
@[rust_trait "generic_array::ArrayLength"
  (parentClauses := ["typenummarker_traitsUnsignedInst"])]
structure generic_array.ArrayLength (Self : Type) (T : Type) (Self_ArrayType :
  Type) where
  typenummarker_traitsUnsignedInst : typenum.marker_traits.Unsigned Self

/-- Trait declaration: [block_buffer::sealed::Sealed]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/block-buffer-0.10.4/src/sealed.rs', lines 5:0-5:16
    Name pattern: [block_buffer::sealed::Sealed]
    Visibility: public -/
@[rust_trait "block_buffer::sealed::Sealed"]
structure block_buffer.sealed.Sealed (Self : Type) where
  invariant : Std.Usize → Std.Usize → Result Bool
  split_blocks : forall {N : Type} {Clause0_ArrayType : Type}
    (generic_arrayArrayLengthPU8PInst : generic_array.ArrayLength N Std.U8
    Clause0_ArrayType), Slice Std.U8 → Result ((Slice
    (generic_array.GenericArray Std.U8 N Clause0_ArrayType)) × (Slice Std.U8))

/-- Trait declaration: [block_buffer::BufferKind]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/block-buffer-0.10.4/src/lib.rs', lines 23:0-23:36
    Name pattern: [block_buffer::BufferKind]
    Visibility: public -/
@[rust_trait "block_buffer::BufferKind"
  (parentClauses := ["sealedSealedInst"])]
structure block_buffer.BufferKind (Self : Type) where
  sealedSealedInst : block_buffer.sealed.Sealed Self

/-- [block_buffer::Eager]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/block-buffer-0.10.4/src/lib.rs', lines 28:0-28:16
    Name pattern: [block_buffer::Eager]
    Visibility: public -/
@[reducible, rust_type "block_buffer::Eager"]
def block_buffer.Eager := Unit

/-- Trait declaration: [crypto_common::BlockSizeUser]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 42:0-42:23
    Name pattern: [crypto_common::BlockSizeUser]
    Visibility: public -/
@[rust_trait "crypto_common::BlockSizeUser"
  (parentClauses := ["generic_arrayArrayLengthSelf_BlockSizeU8Self_Clause0_ArrayTypeInst"])]
structure crypto_common.BlockSizeUser (Self : Type) (Self_BlockSize : Type)
  (Self_Clause0_ArrayType : Type) where
  generic_arrayArrayLengthSelf_BlockSizeU8Self_Clause0_ArrayTypeInst :
    generic_array.ArrayLength Self_BlockSize Std.U8 Self_Clause0_ArrayType

/-- Trait declaration: [crypto_common::OutputSizeUser]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 67:0-67:24
    Name pattern: [crypto_common::OutputSizeUser]
    Visibility: public -/
@[rust_trait "crypto_common::OutputSizeUser"
  (parentClauses := ["generic_arrayArrayLengthSelf_OutputSizeU8Self_Clause0_ArrayTypeInst"])]
structure crypto_common.OutputSizeUser (Self : Type) (Self_OutputSize : Type)
  (Self_Clause0_ArrayType : Type) where
  generic_arrayArrayLengthSelf_OutputSizeU8Self_Clause0_ArrayTypeInst :
    generic_array.ArrayLength Self_OutputSize Std.U8 Self_Clause0_ArrayType

/-- Trait declaration: [crypto_common::Reset]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-common-0.1.7/src/lib.rs', lines 112:0-112:15
    Name pattern: [crypto_common::Reset]
    Visibility: public -/
@[rust_trait "crypto_common::Reset"]
structure crypto_common.Reset (Self : Type) where
  reset : Self → Result Self

/-- [typenum::uint::UTerm]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 50:0-50:16
    Name pattern: [typenum::uint::UTerm]
    Visibility: public -/
@[reducible, rust_type "typenum::uint::UTerm"]
def typenum.uint.UTerm := Unit

/-- Trait declaration: [typenum::marker_traits::Bit]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 35:0-35:48
    Name pattern: [typenum::marker_traits::Bit]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Bit"
  (parentClauses := ["sealedSealedInst", "coremarkerCopyInst", "coredefaultDefaultInst"])
  (consts := ["U8", "BOOL"])]
structure typenum.marker_traits.Bit (Self : Type) where
  U8 : Result Std.U8
  BOOL : Result Bool
  sealedSealedInst : typenum.sealed.Sealed Self
  coremarkerCopyInst : core.marker.Copy Self
  coredefaultDefaultInst : core.default.Default Self
  new : Result Self
  to_u8 : Result Std.U8
  to_bool : Result Bool

/-- Trait declaration: [typenum::type_operators::IsLess]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/type_operators.rs', lines 374:0-374:28
    Name pattern: [typenum::type_operators::IsLess]
    Visibility: public -/
@[rust_trait "typenum::type_operators::IsLess"
  (parentClauses := ["marker_traitsBitInst"])]
structure typenum.type_operators.IsLess (Self : Type) (Rhs : Type) (Self_Output
  : Type) where
  marker_traitsBitInst : typenum.marker_traits.Bit Self_Output
  is_less : Self → Rhs → Result Self_Output

/-- Trait declaration: [typenum::marker_traits::NonZero]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 22:0-22:25
    Name pattern: [typenum::marker_traits::NonZero]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::NonZero"
  (parentClauses := ["sealedSealedInst"])]
structure typenum.marker_traits.NonZero (Self : Type) where
  sealedSealedInst : typenum.sealed.Sealed Self

/-- [typenum::bit::B1]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 33:0-33:13
    Name pattern: [typenum::bit::B1]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B1"]
def typenum.bit.B1 := Unit

/-- [typenum::bit::B0]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/bit.rs', lines 20:0-20:13
    Name pattern: [typenum::bit::B0]
    Visibility: public -/
@[reducible, rust_type "typenum::bit::B0"]
def typenum.bit.B0 := Unit

/-- Trait declaration: [digest::core_api::BufferKindUser]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/core_api.rs', lines 37:0-37:39
    Name pattern: [digest::core_api::BufferKindUser]
    Visibility: public -/
@[rust_trait "digest::core_api::BufferKindUser"
  (parentClauses := ["crypto_commonBlockSizeUserInst", "block_bufferBufferKindInst"])]
structure digest.core_api.BufferKindUser (Self : Type) (Self_BufferKind : Type)
  (Self_Clause0_BlockSize : Type) (Self_Clause0_Clause0_ArrayType : Type) where
  crypto_commonBlockSizeUserInst : crypto_common.BlockSizeUser Self
    Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType
  block_bufferBufferKindInst : block_buffer.BufferKind Self_BufferKind

/-- Trait declaration: [digest::digest::HashMarker]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/digest.rs', lines 8:0-8:20
    Name pattern: [digest::digest::HashMarker]
    Visibility: public -/
@[rust_trait "digest::digest::HashMarker"]
structure digest.digest.HashMarker (Self : Type) where

/-- Trait declaration: [digest::Update]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/lib.rs', lines 77:0-77:16
    Name pattern: [digest::Update]
    Visibility: public -/
@[rust_trait "digest::Update"]
structure digest.Update (Self : Type) where
  update : Self → Slice Std.U8 → Result Self

/-- Trait declaration: [digest::core_api::UpdateCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/core_api.rs', lines 31:0-31:35
    Name pattern: [digest::core_api::UpdateCore]
    Visibility: public -/
@[rust_trait "digest::core_api::UpdateCore"
  (parentClauses := ["crypto_commonBlockSizeUserInst"])]
structure digest.core_api.UpdateCore (Self : Type) (Self_Clause0_BlockSize :
  Type) (Self_Clause0_Clause0_ArrayType : Type) where
  crypto_commonBlockSizeUserInst : crypto_common.BlockSizeUser Self
    Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType
  update_blocks : Self → Slice (generic_array.GenericArray Std.U8
    Self_Clause0_BlockSize Self_Clause0_Clause0_ArrayType) → Result Self

/-- Trait declaration: [digest::FixedOutput]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/lib.rs', lines 93:0-93:54
    Name pattern: [digest::FixedOutput]
    Visibility: public -/
@[rust_trait "digest::FixedOutput"
  (parentClauses := ["UpdateInst", "crypto_commonOutputSizeUserInst"])]
structure digest.FixedOutput (Self : Type) (Self_Clause1_OutputSize : Type)
  (Self_Clause1_Clause0_ArrayType : Type) where
  UpdateInst : digest.Update Self
  crypto_commonOutputSizeUserInst : crypto_common.OutputSizeUser Self
    Self_Clause1_OutputSize Self_Clause1_Clause0_ArrayType
  finalize_into : Self → generic_array.GenericArray Std.U8
    Self_Clause1_OutputSize Self_Clause1_Clause0_ArrayType → Result
    (generic_array.GenericArray Std.U8 Self_Clause1_OutputSize
    Self_Clause1_Clause0_ArrayType)

/-- Trait declaration: [digest::core_api::FixedOutputCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/core_api.rs', lines 43:0-43:71
    Name pattern: [digest::core_api::FixedOutputCore]
    Visibility: public -/
@[rust_trait "digest::core_api::FixedOutputCore"
  (parentClauses := ["UpdateCoreInst", "BufferKindUserInst", "crypto_commonOutputSizeUserInst", "typenumtype_operatorsIsLessSelf_Clause0_Clause0_BlockSizeUIntUIntUIntUIntUIntUIntUIntUIntUIntUTermB1B0B0B0B0B0B0B0B0Self_Clause3_OutputInst", "typenummarker_traitsNonZeroInst"])]
structure digest.core_api.FixedOutputCore (Self : Type)
  (Self_Clause0_Clause0_BlockSize : Type)
  (Self_Clause0_Clause0_Clause0_ArrayType : Type) (Self_Clause1_BufferKind :
  Type) (Self_Clause1_Clause0_BlockSize : Type)
  (Self_Clause1_Clause0_Clause0_ArrayType : Type) (Self_Clause2_OutputSize :
  Type) (Self_Clause2_Clause0_ArrayType : Type) (Self_Clause3_Output : Type)
  where
  UpdateCoreInst : digest.core_api.UpdateCore Self
    Self_Clause0_Clause0_BlockSize Self_Clause0_Clause0_Clause0_ArrayType
  BufferKindUserInst : digest.core_api.BufferKindUser Self
    Self_Clause1_BufferKind Self_Clause1_Clause0_BlockSize
    Self_Clause1_Clause0_Clause0_ArrayType
  crypto_commonOutputSizeUserInst : crypto_common.OutputSizeUser Self
    Self_Clause2_OutputSize Self_Clause2_Clause0_ArrayType
  typenumtype_operatorsIsLessSelf_Clause0_Clause0_BlockSizeUIntUIntUIntUIntUIntUIntUIntUIntUIntUTermB1B0B0B0B0B0B0B0B0Self_Clause3_OutputInst
    : typenum.type_operators.IsLess Self_Clause0_Clause0_BlockSize
    (typenum.uint.UInt (typenum.uint.UInt (typenum.uint.UInt (typenum.uint.UInt
    (typenum.uint.UInt (typenum.uint.UInt (typenum.uint.UInt (typenum.uint.UInt
    (typenum.uint.UInt typenum.uint.UTerm typenum.bit.B1) typenum.bit.B0)
    typenum.bit.B0) typenum.bit.B0) typenum.bit.B0) typenum.bit.B0)
    typenum.bit.B0) typenum.bit.B0) typenum.bit.B0) Self_Clause3_Output
  typenummarker_traitsNonZeroInst : typenum.marker_traits.NonZero
    Self_Clause3_Output
  finalize_fixed_core : Self → block_buffer.BlockBuffer
    Self_Clause0_Clause0_BlockSize Self_Clause1_BufferKind
    Self_Clause0_Clause0_Clause0_ArrayType Self_Clause3_Output →
    generic_array.GenericArray Std.U8 Self_Clause2_OutputSize
    Self_Clause2_Clause0_ArrayType → Result (Self ×
    (block_buffer.BlockBuffer Self_Clause0_Clause0_BlockSize
    Self_Clause1_BufferKind Self_Clause0_Clause0_Clause0_ArrayType
    Self_Clause3_Output) × (generic_array.GenericArray Std.U8
    Self_Clause2_OutputSize Self_Clause2_Clause0_ArrayType))

/-- Trait declaration: [digest::FixedOutputReset]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/lib.rs', lines 107:0-107:47
    Name pattern: [digest::FixedOutputReset]
    Visibility: public -/
@[rust_trait "digest::FixedOutputReset"
  (parentClauses := ["FixedOutputInst", "crypto_commonResetInst"])]
structure digest.FixedOutputReset (Self : Type)
  (Self_Clause0_Clause1_OutputSize : Type)
  (Self_Clause0_Clause1_Clause0_ArrayType : Type) where
  FixedOutputInst : digest.FixedOutput Self Self_Clause0_Clause1_OutputSize
    Self_Clause0_Clause1_Clause0_ArrayType
  crypto_commonResetInst : crypto_common.Reset Self
  finalize_into_reset : Self → generic_array.GenericArray Std.U8
    Self_Clause0_Clause1_OutputSize Self_Clause0_Clause1_Clause0_ArrayType →
    Result (Self × (generic_array.GenericArray Std.U8
    Self_Clause0_Clause1_OutputSize Self_Clause0_Clause1_Clause0_ArrayType))

/-- Trait declaration: [digest::digest::Digest]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/digest.rs', lines 15:0-15:32
    Name pattern: [digest::digest::Digest]
    Visibility: public -/
@[rust_trait "digest::digest::Digest"
  (parentClauses := ["crypto_commonOutputSizeUserInst"])]
structure digest.digest.Digest (Self : Type) (Self_Clause0_OutputSize : Type)
  (Self_Clause0_Clause0_ArrayType : Type) where
  crypto_commonOutputSizeUserInst : crypto_common.OutputSizeUser Self
    Self_Clause0_OutputSize Self_Clause0_Clause0_ArrayType
  new : Result Self
  new_with_prefix : forall {T1 : Type} (coreconvertAsRefPSliceU8Inst :
    core.convert.AsRef T1 (Slice Std.U8)), T1 → Result Self
  update : forall {T1 : Type} (coreconvertAsRefPSliceU8Inst :
    core.convert.AsRef T1 (Slice Std.U8)), Self → T1 → Result Self
  chain_update : forall {T1 : Type} (coreconvertAsRefPSliceU8Inst :
    core.convert.AsRef T1 (Slice Std.U8)), Self → T1 → Result Self
  finalize : Self → Result (generic_array.GenericArray Std.U8
    Self_Clause0_OutputSize Self_Clause0_Clause0_ArrayType)
  finalize_into : Self → generic_array.GenericArray Std.U8
    Self_Clause0_OutputSize Self_Clause0_Clause0_ArrayType → Result
    (generic_array.GenericArray Std.U8 Self_Clause0_OutputSize
    Self_Clause0_Clause0_ArrayType)
  finalize_reset : forall {Clause0_Clause0_Clause1_OutputSize : Type}
    {Clause0_Clause0_Clause1_Clause0_ArrayType : Type} (FixedOutputResetInst :
    digest.FixedOutputReset Self Clause0_Clause0_Clause1_OutputSize
    Clause0_Clause0_Clause1_Clause0_ArrayType), Self → Result
    ((generic_array.GenericArray Std.U8 Self_Clause0_OutputSize
    Self_Clause0_Clause0_ArrayType) × Self)
  finalize_into_reset : forall {Clause0_Clause0_Clause1_OutputSize : Type}
    {Clause0_Clause0_Clause1_Clause0_ArrayType : Type} (FixedOutputResetInst :
    digest.FixedOutputReset Self Clause0_Clause0_Clause1_OutputSize
    Clause0_Clause0_Clause1_Clause0_ArrayType), Self →
    generic_array.GenericArray Std.U8 Self_Clause0_OutputSize
    Self_Clause0_Clause0_ArrayType → Result (Self ×
    (generic_array.GenericArray Std.U8 Self_Clause0_OutputSize
    Self_Clause0_Clause0_ArrayType))
  reset : forall (crypto_commonResetInst : crypto_common.Reset Self), Self →
    Result Self
  output_size : Result Std.Usize
  digest : forall {T1 : Type} (coreconvertAsRefPSliceU8Inst :
    core.convert.AsRef T1 (Slice Std.U8)), T1 → Result
    (generic_array.GenericArray Std.U8 Self_Clause0_OutputSize
    Self_Clause0_Clause0_ArrayType)

/-- [math::errors::ByteConversionError]
    Source: 'crypto/math/src/errors.rs', lines 2:0-2:28
    Name pattern: [math::errors::ByteConversionError]
    Visibility: public -/
@[discriminant isize, rust_type "math::errors::ByteConversionError"]
inductive math.errors.ByteConversionError where
| FromBEBytesError : math.errors.ByteConversionError
| FromLEBytesError : math.errors.ByteConversionError
| ValueNotReduced : math.errors.ByteConversionError

/-- [math::errors::CreationError]
    Source: 'crypto/math/src/errors.rs', lines 9:0-9:22
    Name pattern: [math::errors::CreationError]
    Visibility: public -/
@[discriminant isize, rust_type "math::errors::CreationError"]
inductive math.errors.CreationError where
| InvalidHexString : math.errors.CreationError
| HexStringIsTooBig : math.errors.CreationError
| CanonicalOutOfRange : math.errors.CreationError
| EmptyString : math.errors.CreationError

/-- [math::errors::DeserializationError]
    Source: 'crypto/math/src/errors.rs', lines 17:0-17:29
    Name pattern: [math::errors::DeserializationError]
    Visibility: public -/
@[discriminant isize, rust_type "math::errors::DeserializationError"]
inductive math.errors.DeserializationError where
| InvalidAmountOfBytes : math.errors.DeserializationError
| FieldFromBytesError : math.errors.DeserializationError
| PointerSizeError : math.errors.DeserializationError
| InvalidValue : math.errors.DeserializationError

/-- Trait declaration: [math::traits::ByteConversion]
    Source: 'crypto/math/src/traits.rs', lines 5:0-5:24
    Name pattern: [math::traits::ByteConversion]
    Visibility: public -/
@[rust_trait "math::traits::ByteConversion" (consts := ["BYTE_LEN"])]
structure math.traits.ByteConversion (Self : Type) where
  BYTE_LEN : Result Std.Usize
  to_bytes_be : Self → Result (alloc.vec.Vec Std.U8)
  to_bytes_le : Self → Result (alloc.vec.Vec Std.U8)
  from_bytes_be : Slice Std.U8 → Result (core.result.Result Self
    math.errors.ByteConversionError)
  from_bytes_le : Slice Std.U8 → Result (core.result.Result Self
    math.errors.ByteConversionError)

/-- [math::field::errors::FieldError]
    Source: 'crypto/math/src/field/errors.rs', lines 2:0-2:19
    Name pattern: [math::field::errors::FieldError]
    Visibility: public -/
@[discriminant isize, rust_type "math::field::errors::FieldError"]
inductive math.field.errors.FieldError where
| DivisionByZero : math.field.errors.FieldError
| RootOfUnityError : Std.U64 → math.field.errors.FieldError
| InvZeroError : math.field.errors.FieldError

/-- Trait declaration: [math::field::traits::IsField]
    Source: 'crypto/math/src/field/traits.rs', lines 99:0-99:32
    Name pattern: [math::field::traits::IsField]
    Visibility: public -/
@[rust_trait "math::field::traits::IsField"
  (parentClauses := ["corefmtDebugInst", "corecloneCloneInst", "corecloneCloneInst", "corefmtDebugInst", "traitsByteConversionInst", "coredefaultDefaultInst"])]
structure math.field.traits.IsField (Self : Type) (Self_BaseType : Type) where
  corefmtDebugInst : core.fmt.Debug Self
  corecloneCloneInst : core.clone.Clone Self
  corecloneCloneBaseTypeInst : core.clone.Clone Self_BaseType
  corefmtDebugBaseTypeInst : core.fmt.Debug Self_BaseType
  traitsByteConversionInst : math.traits.ByteConversion Self_BaseType
  coredefaultDefaultInst : core.default.Default Self_BaseType
  add : Self_BaseType → Self_BaseType → Result Self_BaseType
  mul : Self_BaseType → Self_BaseType → Result Self_BaseType
  sub : Self_BaseType → Self_BaseType → Result Self_BaseType
  neg : Self_BaseType → Result Self_BaseType
  inv : Self_BaseType → Result (core.result.Result Self_BaseType
    math.field.errors.FieldError)
  div : Self_BaseType → Self_BaseType → Result (core.result.Result
    Self_BaseType math.field.errors.FieldError)
  eq : Self_BaseType → Self_BaseType → Result Bool
  one : Result Self_BaseType
  from_u64 : Std.U64 → Result Self_BaseType
  from_base_type : Self_BaseType → Result Self_BaseType

/-- Trait declaration: [math::field::traits::IsSubFieldOf]
    Source: 'crypto/math/src/field/traits.rs', lines 17:0-17:43
    Name pattern: [math::field::traits::IsSubFieldOf]
    Visibility: public -/
@[rust_trait "math::field::traits::IsSubFieldOf"
  (parentClauses := ["IsFieldInst", "IsFieldInst"])]
structure math.field.traits.IsSubFieldOf (Self : Type) (F : Type)
  (Self_Clause0_BaseType : Type) (Self_Clause1_BaseType : Type) where
  IsFieldInst : math.field.traits.IsField Self Self_Clause0_BaseType
  IsFieldClause1Inst : math.field.traits.IsField F Self_Clause1_BaseType
  mul : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    Self_Clause1_BaseType
  add : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    Self_Clause1_BaseType
  div : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    (core.result.Result Self_Clause1_BaseType math.field.errors.FieldError)
  sub : Self_Clause0_BaseType → Self_Clause1_BaseType → Result
    Self_Clause1_BaseType
  embed : Self_Clause0_BaseType → Result Self_Clause1_BaseType
  to_subfield_vec : Self_Clause1_BaseType → Result (alloc.vec.Vec
    Self_Clause0_BaseType)

/-- Trait declaration: [math::unsigned_integer::traits::IsUnsignedInteger]
    Source: 'crypto/math/src/unsigned_integer/traits.rs', lines 6:0-17:30
    Name pattern: [math::unsigned_integer::traits::IsUnsignedInteger]
    Visibility: public -/
@[rust_trait "math::unsigned_integer::traits::IsUnsignedInteger"
  (parentClauses := ["coreopsbitShrSelfUsizeSelfInst", "coreopsbitShrAssignSelfUsizeInst", "coreopsbitBitAndInst", "corecmpEqInst", "corecmpOrdInst", "coreconvertFromSelfU16Inst", "coremarkerCopyInst", "corefmtDisplayInst", "corefmtLowerHexInst", "corefmtUpperHexInst", "coreopsarithAddInst"])]
structure math.unsigned_integer.traits.IsUnsignedInteger (Self : Type) where
  coreopsbitShrSelfUsizeSelfInst : core.ops.bit.Shr Self Std.Usize Self
  coreopsbitShrAssignSelfUsizeInst : core.ops.bit.ShrAssign Self Std.Usize
  coreopsbitBitAndInst : core.ops.bit.BitAnd Self Self Self
  corecmpEqInst : core.cmp.Eq Self
  corecmpOrdInst : core.cmp.Ord Self
  coreconvertFromSelfU16Inst : core.convert.From Self Std.U16
  coremarkerCopyInst : core.marker.Copy Self
  corefmtDisplayInst : core.fmt.Display Self
  corefmtLowerHexInst : core.fmt.LowerHex Self
  corefmtUpperHexInst : core.fmt.UpperHex Self
  coreopsarithAddInst : core.ops.arith.Add Self Self Self

/-- Trait declaration: [math::field::traits::IsPrimeField]
    Source: 'crypto/math/src/field/traits.rs', lines 204:0-204:31
    Name pattern: [math::field::traits::IsPrimeField]
    Visibility: public -/
@[rust_trait "math::field::traits::IsPrimeField"
  (parentClauses := ["IsFieldInst", "unsigned_integertraitsIsUnsignedIntegerInst"])]
structure math.field.traits.IsPrimeField (Self : Type) (Self_CanonicalType :
  Type) (Self_Clause0_BaseType : Type) where
  IsFieldInst : math.field.traits.IsField Self Self_Clause0_BaseType
  unsigned_integertraitsIsUnsignedIntegerInst :
    math.unsigned_integer.traits.IsUnsignedInteger Self_CanonicalType
  canonical : Self_Clause0_BaseType → Result Self_CanonicalType
  from_hex : Str → Result (core.result.Result Self_Clause0_BaseType
    math.errors.CreationError)
  to_hex : Self_Clause0_BaseType → Result String
  field_bit_size : Result Std.Usize

/-- Trait declaration: [rand_core::RngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.6.4/src/lib.rs', lines 142:0-142:17
    Name pattern: [rand_core::RngCore]
    Visibility: public -/
@[rust_trait "rand_core::RngCore"]
structure rand_core.RngCore (Self : Type) where
  next_u32 : Self → Result (Std.U32 × Self)
  next_u64 : Self → Result (Std.U64 × Self)
  fill_bytes : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))
  try_fill_bytes : Self → Slice Std.U8 → Result ((core.result.Result Unit
    rand_core.error.Error) × Self × (Slice Std.U8))

/-- Trait declaration: [rand::rng::Rng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.8.5/src/rng.rs', lines 55:0-55:22
    Name pattern: [rand::rng::Rng]
    Visibility: public -/
@[rust_trait "rand::rng::Rng" (parentClauses := ["rand_coreRngCoreInst"])]
structure rand.rng.Rng (Self : Type) where
  rand_coreRngCoreInst : rand_core.RngCore Self

/-- Trait declaration: [math::field::traits::HasDefaultTranscript]
    Source: 'crypto/math/src/field/traits.rs', lines 300:0-300:39
    Name pattern: [math::field::traits::HasDefaultTranscript]
    Visibility: public -/
@[rust_trait "math::field::traits::HasDefaultTranscript"
  (parentClauses := ["IsFieldInst"])]
structure math.field.traits.HasDefaultTranscript (Self : Type)
  (Self_Clause0_BaseType : Type) where
  IsFieldInst : math.field.traits.IsField Self Self_Clause0_BaseType
  get_random_field_element_from_rng : forall {T1 : Type} (randrngRngInst :
    rand.rng.Rng T1), T1 → Result ((math.field.element.FieldElement Self
    Self_Clause0_BaseType) × T1)

/-- Trait declaration: [math::traits::AsBytes]
    Source: 'crypto/math/src/traits.rs', lines 39:0-39:17
    Name pattern: [math::traits::AsBytes]
    Visibility: public -/
@[rust_trait "math::traits::AsBytes"]
structure math.traits.AsBytes (Self : Type) where
  as_bytes : Self → Result (alloc.vec.Vec Std.U8)

/-- Trait declaration: [math::traits::Deserializable]
    Source: 'crypto/math/src/traits.rs', lines 101:0-101:24
    Name pattern: [math::traits::Deserializable]
    Visibility: public -/
@[rust_trait "math::traits::Deserializable"]
structure math.traits.Deserializable (Self : Type) where
  deserialize : Slice Std.U8 → Result (core.result.Result Self
    math.errors.DeserializationError)

/-- Trait declaration: [typenum::marker_traits::Ord]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/marker_traits.rs', lines 29:0-29:21
    Name pattern: [typenum::marker_traits::Ord]
    Visibility: public -/
@[rust_trait "typenum::marker_traits::Ord"
  (parentClauses := ["sealedSealedInst"])]
structure typenum.marker_traits.Ord (Self : Type) where
  sealedSealedInst : typenum.sealed.Sealed Self
  to_ordering : Result Ordering

/-- [typenum::Less]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 98:0-98:15
    Name pattern: [typenum::Less]
    Visibility: public -/
@[reducible, rust_type "typenum::Less"]
def typenum.Less := Unit

/-- Trait declaration: [typenum::private::PrivateCmp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 320:0-320:32
    Name pattern: [typenum::private::PrivateCmp]
    Visibility: public -/
@[rust_trait "typenum::private::PrivateCmp"]
structure typenum.private.PrivateCmp (Self : Type) (Rhs : Type) (SoFar : Type)
  (Self_Output : Type) where
  private_cmp : Self → Rhs → SoFar → Result Self_Output

/-- [typenum::Greater]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 92:0-92:18
    Name pattern: [typenum::Greater]
    Visibility: public -/
@[reducible, rust_type "typenum::Greater"]
def typenum.Greater := Unit

/-- Trait declaration: [typenum::private::InternalMarker]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 31:0-31:24
    Name pattern: [typenum::private::InternalMarker]
    Visibility: public -/
@[rust_trait "typenum::private::InternalMarker"]
structure typenum.private.InternalMarker (Self : Type) where

/-- [typenum::Equal]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/lib.rs', lines 104:0-104:16
    Name pattern: [typenum::Equal]
    Visibility: public -/
@[reducible, rust_type "typenum::Equal"]
def typenum.Equal := Unit

/-- Trait declaration: [typenum::type_operators::Cmp]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/type_operators.rs', lines 310:0-310:25
    Name pattern: [typenum::type_operators::Cmp]
    Visibility: public -/
@[rust_trait "typenum::type_operators::Cmp"]
structure typenum.type_operators.Cmp (Self : Type) (Rhs : Type) (Self_Output :
  Type) where
  compare : forall {IM : Type} (privateInternalMarkerInst :
    typenum.private.InternalMarker IM), Self → Rhs → Result Self_Output

/-- Trait declaration: [typenum::private::IsLessPrivate]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/private.rs', lines 394:0-394:33
    Name pattern: [typenum::private::IsLessPrivate]
    Visibility: public -/
@[rust_trait "typenum::private::IsLessPrivate"
  (parentClauses := ["marker_traitsBitInst"])]
structure typenum.private.IsLessPrivate (Self : Type) (Rhs : Type) (Cmp : Type)
  (Self_Output : Type) where
  marker_traitsBitInst : typenum.marker_traits.Bit Self_Output
  is_less_private : Self → Rhs → Cmp → Result Self_Output

/-- [crypto::fiat_shamir::default_transcript::DefaultTranscript]
    Source: 'crypto/crypto/src/fiat_shamir/default_transcript.rs', lines 14:0-17:1
    Visibility: public -/
structure fiat_shamir.default_transcript.DefaultTranscript (F : Type)
  (Clause0_Clause0_BaseType : Type) where
  hasher : digest.core_api.wrapper.CoreWrapper sha3.Keccak256Core
    block_buffer.Eager (typenum.uint.UInt (typenum.uint.UInt (typenum.uint.UInt
    (typenum.uint.UInt (typenum.uint.UInt (typenum.uint.UInt (typenum.uint.UInt
    (typenum.uint.UInt typenum.uint.UTerm typenum.bit.B1) typenum.bit.B0)
    typenum.bit.B0) typenum.bit.B0) typenum.bit.B1) typenum.bit.B0)
    typenum.bit.B0) typenum.bit.B0) (generic_array.GenericArrayImplEven Std.U8
    (generic_array.GenericArrayImplEven Std.U8
    (generic_array.GenericArrayImplEven Std.U8
    (generic_array.GenericArrayImplOdd Std.U8
    (generic_array.GenericArrayImplEven Std.U8
    (generic_array.GenericArrayImplEven Std.U8
    (generic_array.GenericArrayImplEven Std.U8
    (generic_array.GenericArrayImplOdd Std.U8 (Array Std.U8 0#usize)))))))))
    typenum.bit.B1
  phantom : core.marker.PhantomData F

/-- Trait declaration: [crypto::fiat_shamir::is_transcript::IsTranscript]
    Source: 'crypto/crypto/src/fiat_shamir/is_transcript.rs', lines 7:0-18:1
    Visibility: public -/
structure fiat_shamir.is_transcript.IsTranscript (Self : Type) (F : Type)
  (Self_Clause0_BaseType : Type) where
  mathfieldtraitsIsFieldInst : math.field.traits.IsField F
    Self_Clause0_BaseType
  append_field_element : Self → math.field.element.FieldElement F
    Self_Clause0_BaseType → Result Self
  append_bytes : Self → Slice Std.U8 → Result Self
  state : Self → Result (Array Std.U8 32#usize)
  sample_field_element : Self → Result ((math.field.element.FieldElement F
    Self_Clause0_BaseType) × Self)
  sample_u64 : Self → Std.U64 → Result (Std.U64 × Self)

/-- Trait declaration: [crypto::fiat_shamir::is_transcript::IsStarkTranscript]
    Source: 'crypto/crypto/src/fiat_shamir/is_transcript.rs', lines 20:0-82:1
    Visibility: public -/
structure fiat_shamir.is_transcript.IsStarkTranscript (Self : Type) (F : Type)
  (S : Type) (Self_Clause0_Clause0_BaseType : Type) (Self_Clause1_BaseType :
  Type) (Self_Clause2_BaseType : Type) (Self_Clause3_Clause0_BaseType : Type)
  (Self_Clause3_Clause1_BaseType : Type) where
  IsTranscriptInst : fiat_shamir.is_transcript.IsTranscript Self F
    Self_Clause0_Clause0_BaseType
  mathfieldtraitsIsFieldInst : math.field.traits.IsField F
    Self_Clause1_BaseType
  mathfieldtraitsIsFieldSInst : math.field.traits.IsField S
    Self_Clause2_BaseType
  mathfieldtraitsIsSubFieldOfInst : math.field.traits.IsSubFieldOf S F
    Self_Clause3_Clause0_BaseType Self_Clause3_Clause1_BaseType
  sample_z_ood_with_domain_params : Self → Std.Usize → Std.Usize →
    math.field.element.FieldElement S Self_Clause2_BaseType → Result
    ((math.field.element.FieldElement F Self_Clause1_BaseType) × Self)
  sample_z_ood : Self → Slice (math.field.element.FieldElement S
    Self_Clause2_BaseType) → Slice (math.field.element.FieldElement S
    Self_Clause2_BaseType) → Result ((math.field.element.FieldElement F
    Self_Clause1_BaseType) × Self)

/-- Trait declaration: [crypto::hash::poseidon::private::Sealed]
    Source: 'crypto/crypto/src/hash/poseidon/mod.rs', lines 11:4-11:23
    Visibility: public -/
structure hash.poseidon.private.Sealed (Self : Type) where

/-- Trait declaration: [crypto::hash::poseidon::parameters::PermutationParameters]
    Source: 'crypto/crypto/src/hash/poseidon/parameters.rs', lines 11:0-45:1
    Visibility: public -/
structure hash.poseidon.parameters.PermutationParameters (Self : Type) (Self_F
  : Type) (Self_Clause0_CanonicalType : Type) (Self_Clause0_Clause0_BaseType :
  Type) where
  RATE : Result Std.Usize
  CAPACITY : Result Std.Usize
  ALPHA : Result Std.U32
  N_FULL_ROUNDS : Result Std.Usize
  N_PARTIAL_ROUNDS : Result Std.Usize
  STATE_SIZE : Result Std.Usize
  MDS_MATRIX : Result (Slice (math.field.element.FieldElement Self_F
    Self_Clause0_Clause0_BaseType))
  N_MDS_MATRIX_ROWS : Result Std.Usize
  N_MDS_MATRIX_COLS : Result Std.Usize
  ROUND_CONSTANTS : Result (Slice (math.field.element.FieldElement Self_F
    Self_Clause0_Clause0_BaseType))
  N_ROUND_CONSTANTS_ROWS : Result Std.Usize
  N_ROUND_CONSTANTS_COLS : Result Std.Usize
  mathfieldtraitsIsPrimeFieldInst : math.field.traits.IsPrimeField Self_F
    Self_Clause0_CanonicalType Self_Clause0_Clause0_BaseType
  mix : Slice (math.field.element.FieldElement Self_F
    Self_Clause0_Clause0_BaseType) → Result (Slice
    (math.field.element.FieldElement Self_F Self_Clause0_Clause0_BaseType))

/-- Trait declaration: [crypto::hash::poseidon::Poseidon]
    Source: 'crypto/crypto/src/hash/poseidon/mod.rs', lines 16:0-23:1
    Visibility: public -/
structure hash.poseidon.Poseidon (Self : Type) (Self_Clause0_F : Type)
  (Self_Clause0_Clause0_CanonicalType : Type)
  (Self_Clause0_Clause0_Clause0_BaseType : Type) where
  parametersPermutationParametersInst :
    hash.poseidon.parameters.PermutationParameters Self Self_Clause0_F
    Self_Clause0_Clause0_CanonicalType Self_Clause0_Clause0_Clause0_BaseType
  privateSealedInst : hash.poseidon.private.Sealed Self
  hades_permutation : Slice (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType) → Result (Slice
    (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType))
  full_round : Slice (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType) → Std.Usize → Result (Slice
    (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType))
  partial_round : Slice (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType) → Std.Usize → Result (Slice
    (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType))
  hash : math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType → math.field.element.FieldElement
    Self_Clause0_F Self_Clause0_Clause0_Clause0_BaseType → Result
    (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType)
  hash_single : math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType → Result
    (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType)
  hash_many : Slice (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType) → Result
    (math.field.element.FieldElement Self_Clause0_F
    Self_Clause0_Clause0_Clause0_BaseType)

/-- [crypto::hash::poseidon::{impl crypto::hash::poseidon::Poseidon<Clause0_F, Clause0_Clause0_CanonicalType, Clause0_Clause0_Clause0_BaseType> for P}::hash_many::closure]
    Source: 'crypto/crypto/src/hash/poseidon/mod.rs', lines 87:50-87:64 -/
@[reducible]
def hash.poseidon.Poseidon.hash_many.closure (P : Type) (Clause0_F : Type)
  (Clause0_Clause0_CanonicalType : Type) (Clause0_Clause0_Clause0_BaseType :
  Type) :=
Unit

/-- [crypto::hash::sha3::Sha3Hasher]
    Source: 'crypto/crypto/src/hash/sha3/mod.rs', lines 7:0-7:22
    Visibility: public -/
@[reducible]
def hash.sha3.Sha3Hasher := Unit

/-- [crypto::hash::sha3::{crypto::hash::sha3::Sha3Hasher}::strxor::closure]
    Source: 'crypto/crypto/src/hash/sha3/mod.rs', lines 66:28-66:42 -/
@[reducible]
def hash.sha3.Sha3Hasher.strxor.closure := Unit

/-- [crypto::merkle_tree::backends::field_element::FieldElementBackend]
    Source: 'crypto/crypto/src/merkle_tree/backends/field_element.rs', lines 11:0-14:1
    Visibility: public -/
structure merkle_tree.backends.field_element.FieldElementBackend (F : Type) (D
  : Type) (Clause0_Clause0_OutputSize : Type)
  (Clause0_Clause0_Clause0_ArrayType : Type) (NUM_BYTES : Std.Usize) where
  phantom1 : core.marker.PhantomData F
  phantom2 : core.marker.PhantomData D

/-- Trait declaration: [crypto::merkle_tree::traits::IsMerkleTreeBackend]
    Source: 'crypto/crypto/src/merkle_tree/traits.rs', lines 8:0-29:1
    Visibility: public -/
structure merkle_tree.traits.IsMerkleTreeBackend (Self : Type) (Self_Node :
  Type) (Self_Data : Type) where
  corecmpPartialEqInst : core.cmp.PartialEq Self_Node Self_Node
  corecmpEqInst : core.cmp.Eq Self_Node
  corecloneCloneInst : core.clone.Clone Self_Node
  hash_data : Self_Data → Result Self_Node
  hash_leaves : Slice Self_Data → Result (alloc.vec.Vec Self_Node)
  hash_new_parent : Self_Node → Self_Node → Result Self_Node

/-- [crypto::merkle_tree::traits::IsMerkleTreeBackend::hash_leaves::closure]
    Source: 'crypto/crypto/src/merkle_tree/traits.rs', lines 23:17-23:45 -/
@[reducible]
def merkle_tree.traits.IsMerkleTreeBackend.hash_leaves.closure (Self : Type)
  (Clause0_Node : Type) (Clause0_Data : Type) :=
Unit

/-- [crypto::merkle_tree::backends::field_element::TreePoseidon]
    Source: 'crypto/crypto/src/merkle_tree/backends/field_element.rs', lines 50:0-52:1
    Visibility: public -/
structure merkle_tree.backends.field_element.TreePoseidon (P : Type)
  (Clause0_Clause0_F : Type) (Clause0_Clause0_Clause0_CanonicalType : Type)
  (Clause0_Clause0_Clause0_Clause0_BaseType : Type) where
  _poseidon : core.marker.PhantomData P

/-- [crypto::merkle_tree::backends::field_element_vector::FieldElementPairBackend]
    Source: 'crypto/crypto/src/merkle_tree/backends/field_element_vector.rs', lines 16:0-19:1
    Visibility: public -/
structure merkle_tree.backends.field_element_vector.FieldElementPairBackend (F
  : Type) (D : Type) (Clause0_Clause0_OutputSize : Type)
  (Clause0_Clause0_Clause0_ArrayType : Type) (NUM_BYTES : Std.Usize) where
  phantom1 : core.marker.PhantomData F
  phantom2 : core.marker.PhantomData D

/-- [crypto::merkle_tree::backends::field_element_vector::FieldElementVectorBackend]
    Source: 'crypto/crypto/src/merkle_tree/backends/field_element_vector.rs', lines 60:0-63:1
    Visibility: public -/
structure merkle_tree.backends.field_element_vector.FieldElementVectorBackend
  (F : Type) (D : Type) (Clause0_Clause0_OutputSize : Type)
  (Clause0_Clause0_Clause0_ArrayType : Type) (NUM_BYTES : Std.Usize) where
  phantom1 : core.marker.PhantomData F
  phantom2 : core.marker.PhantomData D

/-- [crypto::merkle_tree::backends::field_element_vector::BatchPoseidonTree]
    Source: 'crypto/crypto/src/merkle_tree/backends/field_element_vector.rs', lines 123:0-125:1
    Visibility: public -/
structure merkle_tree.backends.field_element_vector.BatchPoseidonTree (P :
  Type) (Clause0_Clause0_F : Type) (Clause0_Clause0_Clause0_CanonicalType :
  Type) (Clause0_Clause0_Clause0_Clause0_BaseType : Type) where
  _poseidon : core.marker.PhantomData P

/-- [crypto::merkle_tree::merkle::Error]
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 11:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive merkle_tree.merkle.Error where
| OutOfBounds : merkle_tree.merkle.Error
| EmptyPositionList : merkle_tree.merkle.Error

/-- [crypto::merkle_tree::merkle::MerkleTree]
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 55:0-61:1
    Visibility: public -/
structure merkle_tree.merkle.MerkleTree (B : Type) (Clause0_Node : Type)
  (Clause0_Data : Type) where
  root : Clause0_Node
  nodes : alloc.vec.Vec Clause0_Node

/-- [crypto::merkle_tree::proof::Proof]
    Source: 'crypto/crypto/src/merkle_tree/proof.rs', lines 16:0-18:1
    Visibility: public -/
structure merkle_tree.proof.Proof (T : Type) where
  merkle_path : alloc.vec.Vec T

/-- [crypto::merkle_tree::proof::BatchProof]
    Source: 'crypto/crypto/src/merkle_tree/proof.rs', lines 85:0-87:1
    Visibility: public -/
structure merkle_tree.proof.BatchProof (T : Type) where
  path : alloc.vec.Vec T

/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::get_batch_proof::closure#1]
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 323:17-327:13 -/
@[reducible]
def merkle_tree.merkle.MerkleTree.get_batch_proof.closure_1 (B : Type)
  (Clause0_Node : Type) (Clause0_Data : Type) :=
  merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data

/-- [crypto::merkle_tree::merkle::{crypto::merkle_tree::merkle::MerkleTree<B, Clause0_Node, Clause0_Data>}::get_batch_proof::closure]
    Source: 'crypto/crypto/src/merkle_tree/merkle.rs', lines 315:17-315:50 -/
@[reducible]
def merkle_tree.merkle.MerkleTree.get_batch_proof.closure (B : Type)
  (Clause0_Node : Type) (Clause0_Data : Type) :=
  merkle_tree.merkle.MerkleTree B Clause0_Node Clause0_Data

end crypto
