-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [crypto]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [core::iter::adapters::cloned::Cloned]
    Source: '/rustc/library/core/src/iter/adapters/cloned.rs', lines 18:0-18:20
    Name pattern: [core::iter::adapters::cloned::Cloned]
    Visibility: public -/
@[rust_type "core::iter::adapters::cloned::Cloned"]
axiom core.iter.adapters.cloned.Cloned (I : Type) : Type

/-- [core::iter::adapters::zip::Zip]
    Source: '/rustc/library/core/src/iter/adapters/zip.rs', lines 13:0-13:20
    Name pattern: [core::iter::adapters::zip::Zip]
    Visibility: public -/
@[rust_type "core::iter::adapters::zip::Zip"]
axiom core.iter.adapters.zip.Zip (A : Type) (B : Type) : Type

/-- [core::slice::iter::Chunks]
    Source: '/rustc/library/core/src/slice/iter.rs', lines 1478:0-1478:28
    Name pattern: [core::slice::iter::Chunks]
    Visibility: public -/
@[rust_type "core::slice::iter::Chunks"]
axiom core.slice.iter.Chunks (T : Type) : Type

/-- [alloc::collections::btree::map::BTreeMap]
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 189:0-193:1
    Name pattern: [alloc::collections::btree::map::BTreeMap]
    Visibility: public -/
@[rust_type "alloc::collections::btree::map::BTreeMap"]
axiom alloc.collections.btree.map.BTreeMap (K : Type) (V : Type) (A : Type) :
  Type

/-- [alloc::collections::btree::map::Iter]
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 372:0-372:33
    Name pattern: [alloc::collections::btree::map::Iter]
    Visibility: public -/
@[rust_type "alloc::collections::btree::map::Iter"]
axiom alloc.collections.btree.map.Iter (K : Type) (V : Type) : Type

/-- [alloc::collections::btree::set::BTreeSet]
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 78:0-81:1
    Name pattern: [alloc::collections::btree::set::BTreeSet]
    Visibility: public -/
@[rust_type "alloc::collections::btree::set::BTreeSet"]
axiom alloc.collections.btree.set.BTreeSet (T : Type) (A : Type) : Type

/-- [alloc::collections::btree::set::Iter]
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 135:0-135:26
    Name pattern: [alloc::collections::btree::set::Iter]
    Visibility: public -/
@[rust_type "alloc::collections::btree::set::Iter"]
axiom alloc.collections.btree.set.Iter (T : Type) : Type

/-- [alloc::collections::btree::set::IntoIter]
    Source: '/rustc/library/alloc/src/collections/btree/set.rs', lines 154:0-157:1
    Name pattern: [alloc::collections::btree::set::IntoIter]
    Visibility: public -/
@[rust_type "alloc::collections::btree::set::IntoIter"]
axiom alloc.collections.btree.set.IntoIter (T : Type) (A : Type) : Type

/-- [generic_array::GenericArray]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 179:0-179:45
    Name pattern: [generic_array::GenericArray]
    Visibility: public -/
@[rust_type "generic_array::GenericArray"]
axiom generic_array.GenericArray (T : Type) (U : Type) (Clause0_ArrayType :
  Type) : Type

/-- [block_buffer::BlockBuffer]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/block-buffer-0.10.4/src/lib.rs', lines 55:0-55:39
    Name pattern: [block_buffer::BlockBuffer]
    Visibility: public -/
@[rust_type "block_buffer::BlockBuffer"]
axiom block_buffer.BlockBuffer (BlockSize : Type) (Kind : Type)
  (Clause0_ArrayType : Type) (Clause1_Output : Type) : Type

/-- [typenum::uint::UInt]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/typenum-1.19.0/src/uint.rs', lines 148:0-148:21
    Name pattern: [typenum::uint::UInt]
    Visibility: public -/
@[rust_type "typenum::uint::UInt"]
axiom typenum.uint.UInt (U : Type) (B : Type) : Type

/-- [digest::core_api::wrapper::CoreWrapper]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/digest-0.10.7/src/core_api/wrapper.rs', lines 24:0-24:25
    Name pattern: [digest::core_api::wrapper::CoreWrapper]
    Visibility: public -/
@[rust_type "digest::core_api::wrapper::CoreWrapper"]
axiom digest.core_api.wrapper.CoreWrapper (T : Type) (Clause0_BufferKind :
  Type) (Clause0_Clause0_BlockSize : Type) (Clause0_Clause0_Clause0_ArrayType :
  Type) (Clause1_Output : Type) : Type

/-- [generic_array::GenericArrayImplOdd]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 148:0-148:36
    Name pattern: [generic_array::GenericArrayImplOdd]
    Visibility: public -/
@[rust_type "generic_array::GenericArrayImplOdd"]
axiom generic_array.GenericArrayImplOdd (T : Type) (U : Type) : Type

/-- [generic_array::GenericArrayImplEven]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/generic-array-0.14.7/src/lib.rs', lines 126:0-126:37
    Name pattern: [generic_array::GenericArrayImplEven]
    Visibility: public -/
@[rust_type "generic_array::GenericArrayImplEven"]
axiom generic_array.GenericArrayImplEven (T : Type) (U : Type) : Type

/-- [math::field::element::FieldElement]
    Source: 'crypto/math/src/field/element.rs', lines 50:0-50:35
    Name pattern: [math::field::element::FieldElement]
    Visibility: public -/
@[rust_type "math::field::element::FieldElement"]
axiom math.field.element.FieldElement (F : Type) (Clause0_BaseType : Type) :
  Type

/-- [rand_core::error::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.6.4/src/error.rs', lines 21:0-21:16
    Name pattern: [rand_core::error::Error]
    Visibility: public -/
@[rust_type "rand_core::error::Error"]
axiom rand_core.error.Error : Type

/-- [rand_chacha::chacha::ChaCha20Rng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_chacha-0.3.1/src/chacha.rs', lines 149:8-151:9
    Name pattern: [rand_chacha::chacha::ChaCha20Rng]
    Visibility: public -/
@[rust_type "rand_chacha::chacha::ChaCha20Rng"]
axiom rand_chacha.chacha.ChaCha20Rng : Type

/-- [sha3::Keccak256Core]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sha3-0.10.8/src/macros.rs', lines 11:8-13:9
    Name pattern: [sha3::Keccak256Core]
    Visibility: public -/
@[rust_type "sha3::Keccak256Core"]
axiom sha3.Keccak256Core : Type

/-- [sha3::Sha3_256Core]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sha3-0.10.8/src/macros.rs', lines 11:8-13:9
    Name pattern: [sha3::Sha3_256Core]
    Visibility: public -/
@[rust_type "sha3::Sha3_256Core"]
axiom sha3.Sha3_256Core : Type

