[package]
name = "executor"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { version = "2.0", default-features = false }
rustc-demangle = { version = "0.1", optional = true }
hashbrown = { version = "0.14", default-features = false, features = ["inline-more", "ahash"] }

[features]
default = ["std"]
std = ["thiserror/std", "dep:rustc-demangle"]

[[bin]]
name = "executor"
required-features = ["std"]

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny-keccak = { version = "2.0", features = ["keccak"] }
rkyv = { version = "0.8.10", features = ["std", "unaligned"] }
guest-program = { git = "https://github.com/lambdaclass/ethrex.git", package="guest_program", default-features = false, branch = "crypto-default-features" }
