#import "/meta.typ": et, aside

// Spaces and instances
#let (programSpace, program) = ($cal(F)$, $f$)
#let (inputSpace, input) = ($II$, $bb(i)$)
#let (instanceSpace, instance, instance2) = ($XX$, $bb(x)$, $bb(y)$)
#let (witnessSpace, witness) = ($WW$, $bb(w)$)
#let (proofSpace, proof) = ($bb(Pi)$, $pi$)

#let (commitmentSpace, commitment) = ($cal(C)$, $bb(c)$)
#let commit(x) = $overline(#x)$
#let comm(x) = $commit(#x)$

#let hash = $H$

#let relation = $cal(R)$
#let language = $cal(L)$

#let verifierSpace = $cal(V)$
#let (prove, verify) = ($italic("p")$, $italic("v")$)

// Mathematical symbols
#let (zero, one) = ($0$, $1$)
#let iff = $arrow.double.l.r$
#let implies = $arrow.double.r$
#let prob = $PP$
#let to = math.arrow.r

#show math.equation.where(block: false): box

#set list(marker: [---])

= Proof recursion <proof-recursion>
Let $BB := { zero, one }$ denote the boolean set and let 
$programSpace := {program: inputSpace times witnessSpace to BB}$ denote 
the set of functions mapping the (public) input space $inputSpace$ and (private) 
witness space $witnessSpace$ to this set.
We define instance space $instanceSpace := programSpace times inputSpace = {program: witnessSpace to BB}$;
program-input pairs $(program, input) in instanceSpace$ 
are henceforth referred to as _function instances_, or simply _instances_.
Where the individual components of the pair are irrelevant, an instance is 
denoted as $instance in instanceSpace$.

We define relation $relation subset instanceSpace times witnessSpace$ where $((program, input), witness) in relation$ if $program(input, witness) = 1$.
This relation induces the language $language subset instanceSpace$ of _solvable instances_,
where $instance in language$ if there exists a witness $witness$ for which $(instance, witness)in relation$.

Lastly, we introduce the instance commitment function $c: instanceSpace to commitmentSpace$.
Note that this commitment scheme does not involve randomness; it is a _determistic_ scheme.
Randomness is typically required to make a commitment _hiding_.
For the purposes of this discussion, we are not concerned with this property, 
as the function will only be used for committing to public information. 
To simplify notation, we henceforth use $commit(instance)$ to represent the commitment $c(instance)$ of $instance$.

We now assume the existence of _proof system_ $(prove, verify)$ with 
prover $prove: instanceSpace times witnessSpace to proofSpace$ and 
verifier $verify: commitmentSpace times proofSpace to BB$ that is both
_complete_ --- i.e., $verify$ accepts all valid proofs generated by $prove$ --- 
and _sound_ --- i.e., one cannot create an acceptable proof for an unsolvable instance.

Translating this to the purposes of this VM, a prover wishes to convince the verifier 
that for some agreed upon program ($program in programSpace$) and specified public input ($input in inputSpace$),
they know a private input ($witness in witnessSpace$) such that the program terminates successfully 
(i.e., $(program, input) in language$).
To this end, the prover uses $prove(program(input; dot); witness)$ 
to construct some proof $proof in proofSpace$ and sends this to the verifier.
They then use $verify(comm(program(input; dot)), proof)$ to check that the proof is valid, 
convincing them of the prover's claim.

== Recursively proving proof verification
Now observe that the verifier $verify$ is itself a function in 
$verifierSpace := {hat(f): commitmentSpace times proofSpace to BB} subset.eq programSpace$.
This means that we can use $prove$ to prove that the verification of a proof $proof$ 
for a given instance $instance$ succeeds:
$
  &prove(verify(comm(instance), dot); proof) = proof', text("and")
  &verify(comm(verify(comm(instance), dot)), proof') = one.
$
This new proof $proof'$ thus attests to _the existence of a proof $proof$ that 
satisfies the verifier on the given instance $instance$_.

This concept, colloquially known as _proof recursion_, can be applied repeatedly.
The technique is specifically beneficial for _succinct_ proving systems where proof size
typically shrinks (and verification time reduces) as the level of recursion increases.
The technique is mostly useful in settings where the extra time spent by the prover
is outweighed by the time saved by the verifier(s), 
e.g., a computationally constrained verifier, or multiple verifiers.

== Resolving growing instance complexity
While recursive proving leads to a decrease in proof size, this is naively traded off
against an increase in instance complexity.
Looking at a depth-two recursive proof,
$
  prove(verify(comm(verify(comm(instance), dot)), dot); proof') = proof'', text("and")
  verify(comm(verify(comm(verify(comm(instance), dot)), dot)), proof'') = one
$
we see that the verifier first has to derive the commitment
$comm(verify(comm(verify(comm(instance), dot)), dot))$
from the given base instance $instance$ before verifying the proof.
This increase in verifier computation is undesirable and should be avoided.

A solution to this, is to leverage the following variation to the verification algorithm:
$
  verify': commitmentSpace^2 times proofSpace: ([comm(x), comm(y)], proof) mapsto
  verify(comm(x), proof) or verify(comm(y([comm(x), comm(y)], dot)), proof)
$
where it is assumed that $comm(y([comm(x), comm(y)], dot)) in commitmentSpace$ can be constructed efficiently from $comm(x), comm(y) in commitmentSpace$.
Now observe that setting $(comm(x), comm(y)) = (commit(instance), commit(verify'))$ yields
$
  verify'([comm(instance), comm(verify')],  proof) 
  = verify(comm(instance), proof) or verify(comm(verify'([comm(instance), comm(verify')], dot)), proof).
$
In words, $verify'([comm(instance), comm(verify')], dot)$ only accepts $proof$ if it is either
a) proof of $instance in language$, or
b) proof of the existence of a (different) proof that satisfies $verify'([comm(instance), comm(verify')], dot)$.
We can now recursively expand the expression, yielding
$
  verify'(commit(instance), commit(verify'), proof)
  &= verify(comm(instance), proof) or verify(comm(verify'([comm(instance), comm(verify')], dot)), proof)\
  &= verify(comm(instance), proof) or verify(comm(verify(comm(instance), dot) or verify(comm(verify'([comm(instance), comm(verify')]; dot)), dot)), proof)\
  &= verify(comm(instance), proof) or verify(comm(verify(comm(instance), dot) or verify(comm(verify(comm(instance), dot) or verify(comm(verify'([comm(instance), comm(verify')], dot)), dot)), dot)), proof)\
  &= verify(comm(instance), proof) or verify(comm(verify(comm(instance), dot) or verify(comm(verify(comm(instance), dot) or verify(comm(verify(comm(instance), dot) or verify(comm(verify'([comm(instance), comm(verify')], dot)), dot)), dot)), dot)), proof),\
  &&text(italic("etc."))
$
This shows us that a prover can use $verify'$ to shrink a proof $proof$ attesting 
to $instance in language$ recursively any number of times, such that the ultimate 
verification will still pass; verification is _complete_.
Secondly, note that the size of the verification input 
$(comm(instance), comm(verify'))$ is _constant_ in the depth of the recursion.
In fact, the size of the verification instance is typically fully determined by 
$comm(instance)$, since $comm(verify')$ can often be precomputed.

It is important to note that we have not proven soundness of this construction.
Specifically, there may exist proofs that _attest to the existence of itself_ in a finite number of recursion steps.
Such a proof would be accepted by $verify'$ even if $instance in.not language$.
In practice, one might be able to prevent this problem by including a recursion-level counter in the proof.

#aside([$comm(verify')$ absorption])[
  Note that $commit(verify')$ must be provided to $verify'$ as a _parameter_;
  absorbing it into $verify'$ would imply an object containing a cryptographic 
  commitment of itself at a static location, which is practically impossible.
]

= Split verification <split-verification>
#let (record, recordSpace) = ($bb(r)$, $Re$)

Proof recursion involves executing the verification algorithm _inside_ the VM.
In practice, we find that the set of operations utilized for verification differs vastly from
those typically performed by guest programs.
Specifically, verification primarily involves hashing and (extension) field arithmetic, 
where especially the second is absent in typical guest programs.

Emulating field arithmetic on a binary arithmetic-oriented VM typically
incurs significant computational overhead.
With the aim of avoiding a performance penalty on this front, we show how one 
might split the verification process in two halves,
such that either half can be executed on a VM with an instruction set tailored to its needs.

== Communication
As a result of executing the two verification-algorithm halves on distinct VMs,
no direct communication between both algorithms is possible.
Yet, practice shows that effective algorithm splits requires some form of communication
between both halves: typically one half performs a verification step to a certain
point, after which the other half continues verification starting from this
intermediate state.

To achieve communication between two programs running on different VMs, 
we introduce the concept of a prover-hinted _communication record_ $record$ 
provided as _input_ to both processes.
All values that are to be communicated from one part to another, are stated on this record.
For each value on the record, the "sending" half _verifies_ that it is as expected, 
whilst the "receiving" half _assumes_ its correctness and resumes verification under this assumption.
One can now conclude that the proof satisfies the instance
when both algorithm-halves produce the same record for this input.

#aside("Coupling")[
  As observed, both verification halves must be synchronized to correctly verify a proof.
  This implies that some coupling between both halves must exist.
  This design utilizes little coupling in the VM design, instead forcing 
  the guest programs to solve synchronization, as a result introducing the coupling there. 
  
  This no-coupling VM design permits one of the two halves to transition to a 
  different proof system (e.g., moving to Flock 
  #footnote(link(
    "https://eprint.iacr.org/2026/1329", 
    "Flock: Fast Proving for Batch Boolean Computations. src: https://eprint.iacr.org/2026/1329"
  )) 
  to accelerate hash-verification) while incurring as little design overhead as possible.
]

More formally, we define
$v_0, v_1: instanceSpace times proofSpace to recordSpace$ as a valid _split_ of verifier $v in verifierSpace$ if
$
  forall (instance, proof) in instanceSpace times proofSpace: v(comm(instance), proof) = 1 iff v_0(comm(instance), proof) = v_1(comm(instance), proof),
$
where $recordSpace$ denotes the communication record space.
That is, the two halves agree if and only if the instance-proof verifies succesfully.
By applying the Kronecker delta function $delta$ #footnote("https://en.wikipedia.org/wiki/Kronecker_delta"),
we can transform both halves into members of $programSpace$:
$
  tilde(v)_0(comm(instance), [proof, record]) := delta_(v_0(comm(instance), proof),record), #h(3em)
  tilde(v)_1(comm(instance), [proof, record]) := delta_(v_1(comm(instance), proof),record).
$
That is, $tilde(v)_0, tilde(v)_1$ indicate whether the provided record $record in recordSpace$
would indeed be produced by $v_0$ respectively $v_1$ when provided $instance$ and $proof$.
With this transformation in place, one can express 
$
	v(comm(instance), proof) 
	= tilde(v)_0(comm(instance), [proof, d(comm(instance), proof)]) 
		dot tilde(v)_1(comm(instance), [proof, d(comm(instance), proof)]).
$
where $d(comm(instance), proof) := v_0(comm(instance), proof)$ denotes the
record deriviation function.
We introduce the function product $(f || g)(input, witness) := f(input, witness) dot g(input, witness)$ for $f, g in programSpace$.
This then allows us to express
$
	prove(verify(comm(instance), dot); proof)
	&= prove((tilde(v)_0 || tilde(v)_1)(comm(instance), dot); [proof, record])
	&= proof',
$
with $record := d(comm(instance), proof)$.

Summarizing, we have now expressed recursive verification in terms of a 
split verifier, where the same instance-proof-record triple was provided to 
both verification halves.
The produced proof $proof'$ now attests to $instance in language$ when
$verify(comm((tilde(v)_0 || tilde(v)_1)(comm(instance), dot)), proof') = 1$.

= Split proving
#et("todo")

= Split-recursion
With proof recursion and split verification formalized, we now combine both concepts into a unified system.
To this end, we first introduce the selector function
$
  &Delta_cal(A): cal(A)^2 times BB to cal(A): (x, y, b) mapsto cases(x & text("if") b=0, y & text("if") b=1),
$
which, given a bit $b in BB$ and two elements $x,y$ of some space $cal(A)$, selects 
an element based on the value of $b$.
We can now use this selector to define $verify^*$ --- a variation to $verify'$ --- as follows:
$
  verify^*([comm(x), comm(y)], [proof, b])
  :&= Delta_BB (verify(comm(x), proof), verify(comm(y([comm(x), comm(y)], dot)), proof), b)\
  &= verify(Delta_C (comm(x), comm(y([comm(x), comm(y)], dot)), b), proof).
$
Note here that one can reconstruct $verify'$ from $verify^*$ as
$
	sum_(b in BB) verify^*([comm(x), comm(y)], [proof, b])
	&=^((triangle)) or.big_(b in BB) verify^*([comm(x), comm(y)], [proof, b])\
	&= verify(Delta_C (comm(x), comm(y([comm(x), comm(y)], dot)), 0), proof) or verify(Delta_C (comm(x), comm(y([comm(x), comm(y)], dot)), 1), proof)\
	&= verify(comm(x), proof) or verify(comm(y([comm(x), comm(y)], dot)), proof)\
	&= verify'(comm(x), comm(y), proof),\
$
where $(triangle)$ holds under the assumption that a single proof $proof$ cannot 
attest to two distinct instances.
This makes the `OR` operation ($or$) effectively equivalent to the `XOR` operation,
which is equivalent to addition in $BB$.
Hence, $verify^*$ and $verify'$ are effectively equivalent, except that $verify^*$
has the proof include a bit $b$ indicating whether it is verifying a base proof or recursion proof.

We now observe that
$
	tilde(verify)^*_0([comm(x), comm(y)], [[proof, b], r]) 
	&:= tilde(v)_0(Delta_C (comm(x), comm(y([comm(x), comm(y)], dot)), b), [proof, r]),\
	tilde(verify)^*_1([comm(x), comm(y)], [[proof, b], r]) 
	&:= tilde(v)_1(Delta_C (comm(x), comm(y([comm(x), comm(y)], dot)), b), [proof, r])
$
jointly form a valid split of $verify^*$, since
$
	verify^*([comm(x), comm(y)], [proof, b])
	&= verify(Delta_C (comm(x), comm(y([comm(x), comm(y)], dot)), b), proof)\
	&= (tilde(verify)_0 || tilde(verify)_1)(Delta_C (comm(x), comm(y([comm(x), comm(y)], dot)), b), [proof, r])\
	&= (tilde(verify)^*_0 || tilde(verify)^*_1)([comm(x), comm(y)], [[proof, b], r]),\
$
when
$r = g([comm(x), comm(y([comm(x), comm(y)], dot))], [proof, b])$.
By selecting $(comm(x), comm(y)) = (comm(instance), comm(tilde(v)^*_0 || tilde(v)^*_1))$, 
we now obtain
$
	(tilde(verify)^*_0 || tilde(verify)^*_1)([comm(instance), comm(tilde(verify)^*_0 || tilde(verify)^*_1)], [[proof, b], r])
	// &= tilde(verify)^*_0([comm(instance), comm(tilde(verify)^*_0 || tilde(verify)^*_1)], [[proof, b], r]) dot tilde(verify)^*_1([comm(instance), comm(tilde(verify)^*_0 || tilde(verify)^*_1)], [[proof, b], r])\
	&= verify^*([comm(instance), comm(tilde(verify)^*_0 || tilde(verify)^*_1)], [proof, b])\
	&= verify(Delta_commitmentSpace (comm(instance), comm((tilde(verify)^*_0 || tilde(verify)^*_1)([comm(instance),comm(tilde(verify)^*_0 || tilde(verify)^*_1)], dot)), b), proof)\
	&= Delta_BB (verify(comm(instance), proof), verify(comm((tilde(verify)^*_0 || tilde(verify)^*_1)([comm(instance),comm(tilde(verify)^*_0 || tilde(verify)^*_1)], dot)), proof), b)\
	&= verify(comm(instance), proof) dot (1-b) + verify(comm((tilde(verify)^*_0 || tilde(verify)^*_1)([comm(instance),comm(tilde(verify)^*_0 || tilde(verify)^*_1)], dot)), proof) dot b.
$
i.e., a split verification algorithm that checks whether $proof$ attests a) to $instance in language$ when $b=0$ or b) to the existence of a proof that does when $b=1$.
Importantly, this can be achieved recursively, as
$
	#h(8em) // alignment purposes
	&prove(instance; witness) &&to proof_(0),\
	&prove((tilde(verify)^*_0||tilde(verify)^*_1)([comm(instance), comm(tilde(verify)^*_0||tilde(verify)^*_1)], dot); [[proof_(0), 0], r_(0)]) &&to [proof_(1), 1],\
	&prove((tilde(verify)^*_0||tilde(verify)^*_1)([comm(instance), comm(tilde(verify)^*_0||tilde(verify)^*_1)], dot); [[proof_(1), 1], r_(1)]) &&to [proof_(2), 1],\
	&prove((tilde(verify)^*_0||tilde(verify)^*_1)([comm(instance), comm(tilde(verify)^*_0||tilde(verify)^*_1)], dot); [[proof_(2), 1], r_(2)]) &&to [proof_(3), 1],
  &&#h(8em)text(italic("etc."))
$
with
$
	r_i :&= g(comm((tilde(verify)^*_0||tilde(verify)^*_1)([comm(instance), comm(tilde(verify)^*_0||tilde(verify)^*_1)], dot)), [proof_i, 1-delta_(i,0)]).
$

= Applied to lambda VM


When both VMs are proven using the same proof system, the inner product argument is excessive.
Here, the same commitment to $comm((proof, record))$ can be interpreted by both VMs.
It therefore suffices for the verifier to verify both partial proofs against
the same public proof-record commitment.

base level:
- input: instance, verifier
- witness: proof, record
- output: proof

$
  verify': commitmentSpace^2 times proofSpace: (comm(x), comm(y), proof) mapsto
  verify(comm(x), proof) or verify(comm(y(comm(x), comm(y); dot)), proof)
$

how to split $verify'$ into $verify'_0$ and $verify'_1$

$
  verify': commitmentSpace^2 times proofSpace: (comm(x), comm(y), proof) mapsto
  verify(comm(x), proof) or verify(comm(y(comm(x), comm(y); dot)), proof)
$

$
  &verify'_0: (comm(x), comm(y), proof) mapsto
  verify_0(comm(x), proof) or verify_0(comm(y(comm(x), comm(y); dot)), proof)\
  &verify'_1: (comm(x), comm(y), proof) mapsto
  verify_1(comm(x), proof) or verify_1(comm(y(comm(x), comm(y); dot)), proof)\
$

$
  &verify_0(comm(x), proof)\
  &verify_1(comm(x), proof)
$

recursion level:

$
  &verify'_0\
  &verify'_1\
$


$
  verify
$

TODO: 
We assume that these VMs are proven using the same proof system, 
yielding a unified proof of the combined execution as a result.


= Combining recursive proving and split processing

= Applied to LambdaVM
We lastly provide some notes on applying the recursive proving and split processing to
the verification of a proof in the context of this VM.

First, we note that in any scenario, the prover has to commit to the program $program$
being exeucted and the public input $input$ that is provided.
In a non-recursive proof, this is trivially done by committing to the `DECODE` table
representing $program$, and the `PAGE` tables storing the public $input$.
Since these commitments are deterministic, the verifier can locally reconstruct
the commitments and verify any opening proofs against its own version of the commitment.
Note that in this case, the prover may exclude the opened value from any proof strings
pertaining to the `DECODE` and `PAGE` tables, as these are already known to the verifier.

When recursing on this process, the prover provides the verifier with this commitment.
We thus have to demonstrate the commitments the prover provides are as expected.
This is achieved by having the verification  algorithm `COMMIT` (see @commit)
to the public input it is provided.
This act produces an imbalance in the LogUp-component of the proof-of-verification, 
which must be balanced during verification in the _next_ recursion layer.
In later recursions, the verifier must consistently `COMMIT` to its public input
and use the _same_ public input to balance out the LogUp-component of the proof
it is provided.
This solution effectively kicks the can down the road; the final verifier has to
provide the initial input to the program as input to verify the recursive proof.

Denoted as pseudo-algorithms, we find:

= Applied to LambdaVM


In theory, any division of tasks between the two VMs would work.
Moreover, it is unclear what division will lead to optimal performance.
Yet, it is expected that divisions adhering to these high-level guidelines will 
be a good first step towards a performant verifier:
+ have the field-VM perform all verification steps involving field arithmetic,
+ include all verifier-issued challenges required by these verification steps 
  in the communication record $record$ as field-elements, so that the field-VM does not have to derive them,
+ use the binary-VM to verify the challenges hinted by the communication record are indeed correct.

*Communication record overview:*
- the data required according to the chosen verification split,
- if $b=1$, reconstructed commitment $comm(verify'(comm(instance), comm(verify'); dot))$

*$verify'_b\(comm(instance), (comm(verify'_b), comm(verify'_f)), proof, record)$:*
- `COMMIT` to $comm(instance)$, $comm(verify'_b),$ and $comm(verify'_f)$ 
- verify proof:
  - if $b=0$: execute $verify_b (comm(instance), proof)$
  - if $b=1$:
    + construct $comm(verify'(comm(instance), comm(verify'); dot))$ from $(comm(instance), (comm(verify'_b), comm(verify'_f)))$
    + execute $verify_b (comm(verify'(comm(instance), comm(verify'); dot)), proof)$

*$verify'_f\(comm(instance), (comm(verify'_b), comm(verify'_f)), b, proof, record)$:*
- verify proof: $verify_b (comm(verify'(comm(instance), comm(verify'); dot)), proof)$
  - if $b=1$, use $comm(instance), comm(verify'_b), comm(verify'_f)$ to complete the `COMMIT` LogUp-balance.

*Prover:*
$
  proof &arrow.l prove(instance, witness)\
  proof' &arrow.l prove(verify'_b || verify'_f, (commit(instance), (commit(verify'_b), commit(verify'_f)), 0, proof, record))\
  proof^((i)) &arrow.l prove(verify'_b || verify'_f, (commit(instance), (commit(verify'_b), commit(verify'_f)), 1, proof^((i-1)), record))
$

*Final verification.*
$verify'(commit(instance), (commit(verify'_b), commit(verify'_f)), 1, proof^((n))) =^? one$
