//! A run's traces built window by window, with the big tables' full chunks
//! handed out as soon as their rows exist.
//!
//! A whole-run build ([`Traces::from_elf_and_logs`]) collects every op before it
//! generates any table, so nothing downstream can start until the last cycle is
//! collected. This builder takes the run's logs a window at a time, carries the
//! memory and register state across windows exactly as the whole-run walk
//! carries it across cycles, and emits every FULL chunk of the tables whose op
//! lists grow in execution order — CPU, MEMW_R, MEMW_A, MEMW, LOAD, LT, SHIFT,
//! STORE — the moment it is complete ([`StreamedChunk`]). [`finish`] then runs the
//! whole-run table phase over the same op lists, generating everything that was
//! not streamed.
//!
//! # ★ The same tables as a whole-run build
//!
//! A chunk is streamed only when it is the op slice `[k·max, (k+1)·max)` of its
//! table's FINAL op list, and that list is the whole-run one:
//! - the CPU ops carry the run's timestamps (`collect_cpu_ops_from`), and the walk
//!   is a per-op fold over carried state, so its per-window outputs concatenate
//!   to the whole-run outputs;
//! - the routing's lists are concatenations of segments (a filter over the CPU
//!   ops, then CPU32's dispatch, then what DVRM implies), and each segment is
//!   accumulated on its own ([`RoutedSegments`]) and concatenated in the
//!   whole-run order at the end;
//! - a table is streamed only from its FIRST segment (for LT and SHIFT: the walk's
//!   part, which the whole-run list starts with), so no later op can land in a
//!   streamed chunk;
//! - the chunks are generated by the same functions the table phase uses.
//!
//! Everything that needs the whole run — BITWISE and DECODE multiplicities, the
//! CPU padding count, HALT finalization, PAGE and REGISTER from the final state,
//! the accelerators — is left to [`finish`], which is the whole-run table phase
//! with the streamed chunks' slots skipped ([`StreamSkip`]). So a windowed build is
//! a SCHEDULE, not a different trace: `windowed_builds_the_whole_run_tables`
//! checks every table against [`Traces::from_elf_and_logs`].
//!
//! Row order inside the tables that deduplicate through a `HashMap` (EQ,
//! BYTEWISE, BRANCH, DVRM, LT, MUL) is not reproducible between ANY two builds;
//! their chunks hold the same ops, so the same rows.
//!
//! [`finish`]: WindowedTraceBuilder::finish

use std::collections::HashMap;

use executor::elf::Elf;
use executor::vm::logs::Log;
#[cfg(feature = "parallel")]
use rayon::prelude::*;
use stark::trace::TraceTable;

use super::super::types::{GoldilocksExtension, GoldilocksField};
use super::{
    CollectedOps, DecodeArtifacts, MemoryState, MemwBuckets, PreCounted, RegisterState,
    RoutedSegments, StreamSkip, Traces, WalkOutputs, bitwise, build_initial_image, build_traces,
    collect_halt_ops, collect_ops_from_cpu_into, route_ops,
};
use crate::Error;
use crate::tables::{cpu, load, lt, memw, memw_aligned, memw_register, register, shift, store};

type Table = TraceTable<GoldilocksField, GoldilocksExtension>;

/// The tables a windowed build streams: those whose op lists grow in
/// execution order from their first element.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum StreamTable {
    Cpu,
    MemwRegister,
    MemwAligned,
    Memw,
    Load,
    Lt,
    Shift,
    Store,
}

impl StreamTable {
    pub const ALL: [StreamTable; 8] = [
        StreamTable::Cpu,
        StreamTable::MemwRegister,
        StreamTable::MemwAligned,
        StreamTable::Memw,
        StreamTable::Load,
        StreamTable::Lt,
        StreamTable::Shift,
        StreamTable::Store,
    ];
}

/// One full chunk of a streamed table: chunk `index` of that table, the same
/// table a whole-run build puts at `Traces::<field>[index]`.
pub struct StreamedChunk {
    pub table: StreamTable,
    pub index: usize,
    pub trace: Table,
}

/// A run's traces, built window by window. See the module docs.
pub struct WindowedTraceBuilder<'a> {
    artifacts: DecodeArtifacts,
    image: HashMap<u64, u8>,
    register_init: Vec<u32>,
    max_rows: crate::tables::MaxRowsConfig,
    private_input: &'a [u8],
    memory_state: MemoryState,
    register_state: RegisterState,
    /// Cycles collected so far: the next window's first cycle.
    cycles: usize,
    /// The walked windows, in run order, kept as they were walked: moved here,
    /// never copied. `finish` concatenates them once, list by list.
    windows: Vec<WalkedWindow>,
    /// The routing's segments (smaller lists), appended per window.
    segments: RoutedSegments,
    emitted: StreamSkip,
    /// The BITWISE lookups of the walked windows' in-walk lookups and MEMW_R
    /// rows, counted as the windows arrive.
    counted: PreCounted,
    stamps: WindowStamps,
}

/// Where a windowed build spent its time, seconds summed over the windows:
/// the walk, the routing (with the window's bookkeeping), and handing the
/// streamed chunks out (`finish` is timed by its caller).
#[derive(Clone, Copy, Debug, Default)]
pub struct WindowStamps {
    pub windows: usize,
    pub walk: f64,
    pub route: f64,
    pub generate: f64,
}

impl<'a> WindowedTraceBuilder<'a> {
    /// A builder for a run of `elf` on `private_input`, chunked at `max_rows`
    /// — the state [`Traces::from_elf_and_logs`] starts from.
    pub fn new(
        elf: &Elf,
        private_input: &'a [u8],
        max_rows: &crate::tables::MaxRowsConfig,
    ) -> Result<Self, Error> {
        let image = build_initial_image(elf, private_input);
        let register_init = register::register_init_from_entry_point(elf.entry_point);
        let memory_state = MemoryState::from_image(&image);
        let register_state = RegisterState::from_init(&register_init);
        Ok(Self {
            artifacts: DecodeArtifacts::from_elf(elf)?,
            image,
            register_init,
            max_rows: max_rows.clone(),
            private_input,
            memory_state,
            register_state,
            cycles: 0,
            windows: Vec::new(),
            segments: RoutedSegments::default(),
            emitted: StreamSkip::default(),
            counted: PreCounted {
                histogram: bitwise::BitwiseHistogram::new(),
                bitwise_ops: 0,
                memw_register_rows: 0,
            },
            stamps: WindowStamps::default(),
        })
    }

    /// Collects the next window of the run's logs (not the last one: that is
    /// [`finish`](Self::finish)'s) and returns the full chunks it completed.
    ///
    /// A window may be any length; the chunks do not depend on where the
    /// windows fall.
    pub fn push(&mut self, logs: &[Log]) -> Result<Vec<StreamedChunk>, Error> {
        let jobs = self.push_jobs(logs)?;
        #[cfg(feature = "parallel")]
        let jobs = jobs.into_par_iter();
        #[cfg(not(feature = "parallel"))]
        let jobs = jobs.into_iter();
        Ok(jobs.map(ChunkJob::generate).collect())
    }

    /// Like [`push`](Self::push), but hands back each completed chunk as a
    /// [`ChunkJob`] — its ops, copied out — instead of generating it here, so
    /// the caller can generate it on another thread while this one walks the
    /// next window. The chunks are the same.
    pub fn push_jobs(&mut self, logs: &[Log]) -> Result<Vec<ChunkJob>, Error> {
        let (mut walker, mut accumulator) = self.split();
        let walked = walker.walk(logs)?;
        Ok(accumulator.absorb(walked))
    }

    /// The time the windows took so far.
    pub fn stamps(&self) -> WindowStamps {
        self.stamps
    }

    /// How many chunks of each streamed table have been handed out.
    pub fn streamed(&self) -> StreamSkip {
        self.emitted
    }

    /// Collects the run's last window and builds every table the windows did
    /// not stream. The streamed chunks' slots hold empty placeholders;
    /// [`Traces::insert_streamed`] puts the chunks back.
    pub fn finish(mut self, logs: &[Log]) -> Result<Traces, Error> {
        // The last window may halt: it is walked here, not by the `Walker`.
        let cpu_ops = super::collect_cpu_ops_from(logs, &self.artifacts.instructions, self.cycles)?;
        self.cycles += logs.len();
        let mut walk = WalkOutputs::with_capacity(cpu_ops.len());
        collect_ops_from_cpu_into(
            &cpu_ops,
            &mut self.memory_state,
            &mut self.register_state,
            &mut walk,
        );
        self.segments.append(route_ops(&cpu_ops, &walk.cpu32_ops));
        self.windows.push(WalkedWindow { cpu_ops, walk });
        let Self {
            artifacts,
            image,
            register_init,
            max_rows,
            private_input,
            memory_state,
            mut register_state,
            windows,
            segments,
            emitted,
            counted,
            ..
        } = self;
        let (cpu_ops, walk) = concatenate(windows);
        let ops = assemble(cpu_ops, walk, segments, &mut register_state);
        build_traces(
            ops,
            Some(&image),
            &memory_state,
            &register_init,
            artifacts.decode_trace.clone(),
            &artifacts.decode_pc_to_row,
            register_state,
            &max_rows,
            #[cfg(feature = "disk-spill")]
            stark::storage_mode::StorageMode::Ram,
            private_input,
            true,
            false,
            &emitted,
            Some(counted),
        )
    }

    /// The builder in its two halves, to run on two threads: the [`Walker`]
    /// walks each window (the state it carries is the walk's), the
    /// [`Accumulator`] keeps each walked window, routes it and hands out the
    /// chunks it completed. Fed the windows in order, the two build exactly
    /// what [`push_jobs`](Self::push_jobs) builds; afterwards
    /// [`finish`](Self::finish) takes the last window as usual.
    pub fn split(&mut self) -> (Walker<'_>, Accumulator<'_>) {
        (
            Walker {
                artifacts: &self.artifacts,
                memory_state: &mut self.memory_state,
                register_state: &mut self.register_state,
                cycles: &mut self.cycles,
                windows: &mut self.stamps.windows,
                walk_secs: &mut self.stamps.walk,
            },
            Accumulator {
                max_rows: &self.max_rows,
                windows: &mut self.windows,
                segments: &mut self.segments,
                emitted: &mut self.emitted,
                counted: &mut self.counted,
                route_secs: &mut self.stamps.route,
                handout_secs: &mut self.stamps.generate,
            },
        )
    }
}

/// One window, walked: its CPU ops and what the walk emitted for them.
pub struct WalkedWindow {
    cpu_ops: Vec<super::CpuOperation>,
    walk: WalkOutputs,
}

/// The walk half of a split builder ([`WindowedTraceBuilder::split`]).
pub struct Walker<'b> {
    artifacts: &'b DecodeArtifacts,
    memory_state: &'b mut MemoryState,
    register_state: &'b mut RegisterState,
    cycles: &'b mut usize,
    windows: &'b mut usize,
    walk_secs: &'b mut f64,
}

impl Walker<'_> {
    /// Walks the next window (not the run's last) into fresh lists.
    pub fn walk(&mut self, logs: &[Log]) -> Result<WalkedWindow, Error> {
        // As a whole-run build: only the last cycle may halt.
        if logs.iter().any(|log| log.next_pc == 0) {
            return Err(Error::HaltInNonFinalEpoch);
        }
        let t = std::time::Instant::now();
        let cpu_ops =
            super::collect_cpu_ops_from(logs, &self.artifacts.instructions, *self.cycles)?;
        *self.cycles += logs.len();
        let mut walk = WalkOutputs::with_capacity(cpu_ops.len());
        collect_ops_from_cpu_into(&cpu_ops, self.memory_state, self.register_state, &mut walk);
        *self.walk_secs += t.elapsed().as_secs_f64();
        *self.windows += 1;
        Ok(WalkedWindow { cpu_ops, walk })
    }
}

/// The accumulating half of a split builder ([`WindowedTraceBuilder::split`]).
pub struct Accumulator<'b> {
    max_rows: &'b crate::tables::MaxRowsConfig,
    windows: &'b mut Vec<WalkedWindow>,
    segments: &'b mut RoutedSegments,
    emitted: &'b mut StreamSkip,
    counted: &'b mut PreCounted,
    route_secs: &'b mut f64,
    handout_secs: &'b mut f64,
}

impl Accumulator<'_> {
    /// Routes a walked window, keeps it, and hands out the chunks the run's
    /// lists now complete. Windows must come in run order.
    pub fn absorb(&mut self, window: WalkedWindow) -> Vec<ChunkJob> {
        let t = std::time::Instant::now();
        self.segments
            .append(route_ops(&window.cpu_ops, &window.walk.cpu32_ops));
        // The table phase's two dominant BITWISE sources, counted now.
        self.counted.histogram.add_ops(&window.walk.bitwise_ops);
        super::memw_register::collect_bitwise_from_memw_register(
            &window.walk.memw.register_rows,
            &mut self.counted.histogram,
        );
        self.counted.bitwise_ops += window.walk.bitwise_ops.len();
        self.counted.memw_register_rows += window.walk.memw.register_rows.len();
        self.windows.push(window);
        *self.route_secs += t.elapsed().as_secs_f64();
        let t = std::time::Instant::now();
        let jobs = chunk_jobs(self.max_rows, self.windows, self.segments, self.emitted);
        *self.handout_secs += t.elapsed().as_secs_f64();
        jobs
    }
}

/// `range` of the run's list that `list` picks out of each window, gathered
/// into one vector (the windows' lists concatenate to the run's).
fn gather<T: Clone>(
    windows: &[WalkedWindow],
    list: impl Fn(&WalkedWindow) -> &[T],
    range: std::ops::Range<usize>,
) -> Vec<T> {
    let mut out = Vec::with_capacity(range.len());
    let mut at = 0usize;
    for window in windows {
        let part = list(window);
        let (lo, hi) = (at, at + part.len());
        if hi > range.start && lo < range.end {
            let from = range.start.max(lo) - lo;
            let to = range.end.min(hi) - lo;
            out.extend_from_slice(&part[from..to]);
        }
        at = hi;
        if at >= range.end {
            break;
        }
    }
    out
}

// The run's lists, as each window holds its part.
fn list_cpu(w: &WalkedWindow) -> &[super::CpuOperation] {
    &w.cpu_ops
}
fn list_register_rows(w: &WalkedWindow) -> &[super::RegRow] {
    &w.walk.memw.register_rows
}
fn list_aligned(w: &WalkedWindow) -> &[super::MemwOperation] {
    &w.walk.memw.aligned
}
fn list_general(w: &WalkedWindow) -> &[super::MemwOperation] {
    &w.walk.memw.general
}
fn list_load(w: &WalkedWindow) -> &[super::LoadOperation] {
    &w.walk.load_ops
}
fn list_lt(w: &WalkedWindow) -> &[super::LtOperation] {
    &w.walk.lt_ops
}
fn list_shift(w: &WalkedWindow) -> &[super::ShiftOperation] {
    &w.walk.shift_ops
}

/// Every full chunk the run's lists hold that was not handed out yet, its ops
/// gathered out of the windows.
fn chunk_jobs(
    m: &crate::tables::MaxRowsConfig,
    windows: &[WalkedWindow],
    segments: &RoutedSegments,
    e: &mut StreamSkip,
) -> Vec<ChunkJob> {
    let mut jobs = Vec::new();
    macro_rules! full_chunks {
        ($table:expr, $variant:ident, $list:expr, $max:expr, $done:expr) => {{
            let list = $list;
            let len: usize = windows.iter().map(|w| list(w).len()).sum();
            let max = $max;
            while ($done + 1) * max <= len {
                let index = $done;
                jobs.push(ChunkJob {
                    table: $table,
                    index,
                    ops: ChunkOps::$variant(gather(windows, list, index * max..(index + 1) * max)),
                });
                $done += 1;
            }
        }};
    }
    full_chunks!(StreamTable::Cpu, Cpu, list_cpu, m.cpu, e.cpu);
    full_chunks!(
        StreamTable::MemwRegister,
        MemwRegister,
        list_register_rows,
        m.memw_register,
        e.memw_register
    );
    full_chunks!(
        StreamTable::MemwAligned,
        MemwAligned,
        list_aligned,
        m.memw_aligned,
        e.memw_aligned
    );
    full_chunks!(StreamTable::Memw, Memw, list_general, m.memw, e.memw);
    full_chunks!(StreamTable::Load, Load, list_load, m.load, e.load);
    full_chunks!(StreamTable::Lt, Lt, list_lt, m.lt, e.lt);
    full_chunks!(StreamTable::Shift, Shift, list_shift, m.shift, e.shift);
    // STORE's ops are a routing segment, already one list.
    let store = &segments.store_ops;
    while (e.store + 1) * m.store <= store.len() {
        let index = e.store;
        jobs.push(ChunkJob {
            table: StreamTable::Store,
            index,
            ops: ChunkOps::Store(store[index * m.store..(index + 1) * m.store].to_vec()),
        });
        e.store += 1;
    }
    jobs
}

/// `rayon::join`, or the two calls in turn without the `parallel` feature (the
/// recursion ELFs build this crate without it).
fn join<A: Send, B: Send>(a: impl FnOnce() -> A + Send, b: impl FnOnce() -> B + Send) -> (A, B) {
    #[cfg(feature = "parallel")]
    return rayon::join(a, b);
    #[cfg(not(feature = "parallel"))]
    (a(), b())
}

/// The windows' lists concatenated into the run's, once: list by list in
/// parallel, each window's list freed as it is copied.
fn concatenate(windows: Vec<WalkedWindow>) -> (Vec<super::CpuOperation>, WalkOutputs) {
    fn cat<T: Send>(parts: Vec<Vec<T>>) -> Vec<T> {
        let total = parts.iter().map(Vec::len).sum();
        let mut out = Vec::with_capacity(total);
        for part in parts {
            out.extend(part);
        }
        out
    }
    let n = windows.len();
    let mut cpu = Vec::with_capacity(n);
    let mut register_rows = Vec::with_capacity(n);
    let mut aligned = Vec::with_capacity(n);
    let mut general = Vec::with_capacity(n);
    let mut load = Vec::with_capacity(n);
    let mut lt = Vec::with_capacity(n);
    let mut shift = Vec::with_capacity(n);
    let mut bitwise = Vec::with_capacity(n);
    let mut commit = Vec::with_capacity(n);
    let mut keccak = Vec::with_capacity(n);
    let mut blake3 = Vec::with_capacity(n);
    let mut blake3_absorb = Vec::with_capacity(n);
    let mut cpu32 = Vec::with_capacity(n);
    let mut ecsm = Vec::with_capacity(n);
    let mut ecdas = Vec::with_capacity(n);
    let mut hint = Vec::with_capacity(n);
    for WalkedWindow { cpu_ops, walk } in windows {
        cpu.push(cpu_ops);
        register_rows.push(walk.memw.register_rows);
        aligned.push(walk.memw.aligned);
        general.push(walk.memw.general);
        load.push(walk.load_ops);
        lt.push(walk.lt_ops);
        shift.push(walk.shift_ops);
        bitwise.push(walk.bitwise_ops);
        commit.push(walk.commit_ops);
        keccak.push(walk.keccak_ops);
        blake3.push(walk.blake3_ops);
        blake3_absorb.push(walk.blake3_absorb_ops);
        cpu32.push(walk.cpu32_ops);
        ecsm.push(walk.ecsm_ops);
        ecdas.push(walk.ecdas_ops);
        hint.push(walk.hint_ops);
    }
    let ((cpu, (register_rows, aligned)), ((general, bitwise), (load, (lt, shift)))) = join(
        || (cat(cpu), join(|| cat(register_rows), || cat(aligned))),
        || {
            join(
                || join(|| cat(general), || cat(bitwise)),
                || join(|| cat(load), || join(|| cat(lt), || cat(shift))),
            )
        },
    );
    let walk = WalkOutputs {
        memw: MemwBuckets {
            register_rows,
            aligned,
            general,
        },
        load_ops: load,
        lt_ops: lt,
        shift_ops: shift,
        bitwise_ops: bitwise,
        commit_ops: cat(commit),
        keccak_ops: cat(keccak),
        blake3_ops: cat(blake3),
        blake3_absorb_ops: cat(blake3_absorb),
        cpu32_ops: cat(cpu32),
        ecsm_ops: cat(ecsm),
        ecdas_ops: cat(ecdas),
        hint_ops: cat(hint),
    };
    (cpu, walk)
}

/// A completed chunk not generated yet: which chunk it is, and its ops.
/// [`generate`](Self::generate) builds the table a whole-run build puts in that
/// slot, with the same function.
pub struct ChunkJob {
    pub table: StreamTable,
    pub index: usize,
    ops: ChunkOps,
}

enum ChunkOps {
    Cpu(Vec<super::CpuOperation>),
    MemwRegister(Vec<super::RegRow>),
    MemwAligned(Vec<super::MemwOperation>),
    Memw(Vec<super::MemwOperation>),
    Load(Vec<super::LoadOperation>),
    Lt(Vec<super::LtOperation>),
    Shift(Vec<super::ShiftOperation>),
    Store(Vec<store::StoreOperation>),
}

impl ChunkJob {
    pub fn generate(self) -> StreamedChunk {
        let trace = match &self.ops {
            ChunkOps::Cpu(ops) => cpu::generate_cpu_trace(ops),
            ChunkOps::MemwRegister(ops) => {
                memw_register::generate_memw_register_trace_from_rows(ops)
            }
            ChunkOps::MemwAligned(ops) => memw_aligned::generate_memw_aligned_trace(ops),
            ChunkOps::Memw(ops) => memw::generate_memw_trace(ops),
            ChunkOps::Load(ops) => load::generate_load_trace(ops),
            ChunkOps::Lt(ops) => lt::generate_lt_trace(ops),
            ChunkOps::Shift(ops) => shift::generate_shift_trace(ops),
            ChunkOps::Store(ops) => store::generate_store_trace(ops),
        };
        StreamedChunk {
            table: self.table,
            index: self.index,
            trace,
        }
    }
}

/// The walk's lists and the routing's segments as the whole-run
/// [`collect_all_ops`](super::collect_all_ops) returns them, HALT finalization
/// included (the run's end).
fn assemble(
    cpu_ops: Vec<super::CpuOperation>,
    walk: WalkOutputs,
    segments: RoutedSegments,
    register_state: &mut RegisterState,
) -> CollectedOps {
    let WalkOutputs {
        memw,
        load_ops,
        mut lt_ops,
        mut shift_ops,
        mut bitwise_ops,
        commit_ops,
        keccak_ops,
        blake3_ops,
        blake3_absorb_ops,
        cpu32_ops,
        ecsm_ops,
        ecdas_ops,
        hint_ops,
    } = walk;
    let MemwBuckets {
        register_rows: mut memw_register_rows,
        aligned: mut memw_aligned_ops,
        general: mut memw_ops,
    } = memw;
    // HALT's register ops land at the end of their buckets, as in
    // `collect_all_ops`.
    let mut halt = MemwBuckets::with_register_capacity(0);
    halt.extend_ops(collect_halt_ops(register_state));
    memw_register_rows.extend(halt.register_rows);
    memw_aligned_ops.extend(halt.aligned);
    memw_ops.extend(halt.general);

    let RoutedSegments {
        branch_ops,
        mul_filter,
        dvrm_filter,
        eq_ops,
        bytewise_ops,
        store_ops,
        shift_cpu32,
        mul_cpu32,
        dvrm_cpu32,
        bitwise_cpu32,
        lt_dvrm_filter,
        lt_dvrm_cpu32,
        mul_dvrm_filter,
        mul_dvrm_cpu32,
    } = segments;
    shift_ops.extend(shift_cpu32);
    bitwise_ops.extend(bitwise_cpu32);
    let mut mul_ops = mul_filter;
    mul_ops.extend(mul_cpu32);
    mul_ops.extend(mul_dvrm_filter);
    mul_ops.extend(mul_dvrm_cpu32);
    let mut dvrm_ops = dvrm_filter;
    dvrm_ops.extend(dvrm_cpu32);
    lt_ops.extend(lt_dvrm_filter);
    lt_ops.extend(lt_dvrm_cpu32);

    CollectedOps {
        cpu_ops,
        memw_ops,
        memw_aligned_ops,
        memw_register_rows,
        load_ops,
        lt_ops,
        shift_ops,
        bitwise_ops,
        branch_ops,
        mul_ops,
        dvrm_ops,
        commit_ops,
        keccak_ops,
        blake3_ops,
        blake3_absorb_ops,
        eq_ops,
        bytewise_ops,
        store_ops,
        cpu32_ops,
        ecsm_ops,
        ecdas_ops,
        hint_ops,
    }
}

impl Traces {
    /// Puts streamed chunks back into the placeholder slots a windowed build's
    /// [`finish`](WindowedTraceBuilder::finish) left — which makes the traces
    /// the whole-run build's. Refuses a chunk for a slot that is not a
    /// placeholder.
    pub fn insert_streamed(&mut self, chunks: Vec<StreamedChunk>) -> Result<(), Error> {
        for chunk in chunks {
            let slots = match chunk.table {
                StreamTable::Cpu => &mut self.cpus,
                StreamTable::MemwRegister => &mut self.memw_registers,
                StreamTable::MemwAligned => &mut self.memw_aligneds,
                StreamTable::Memw => &mut self.memws,
                StreamTable::Load => &mut self.loads,
                StreamTable::Lt => &mut self.lts,
                StreamTable::Shift => &mut self.shifts,
                StreamTable::Store => &mut self.stores,
            };
            let len = slots.len();
            let slot = slots.get_mut(chunk.index).ok_or_else(|| {
                Error::Prover(format!(
                    "{:?} chunk {} has no slot ({len} tables)",
                    chunk.table, chunk.index,
                ))
            })?;
            if slot.main_table.width != 0 {
                return Err(Error::Prover(format!(
                    "{:?} chunk {} lands on a slot that is not a placeholder",
                    chunk.table, chunk.index
                )));
            }
            *slot = chunk.trace;
        }
        Ok(())
    }
}
