//! A run's traces built window by window, with the big tables' full chunks
//! handed out as soon as their rows exist.
//!
//! A whole-run build ([`Traces::from_elf_and_logs`]) collects every op before it
//! generates any table, so nothing downstream can start until the last cycle is
//! collected. This builder takes the run's logs a window at a time, carries the
//! memory and register state across windows exactly as the whole-run walk
//! carries it across cycles, and emits every FULL chunk of the tables whose op
//! lists grow in execution order — CPU, MEMW_R, MEMW_A, MEMW, LOAD, LT, SHIFT,
//! STORE — the moment it is complete ([`StreamedChunk`]). [`finish`] then runs the
//! whole-run table phase over the same op lists, generating everything that was
//! not streamed.
//!
//! # ★ The same tables as a whole-run build
//!
//! A chunk is streamed only when it is the op slice `[k·max, (k+1)·max)` of its
//! table's FINAL op list, and that list is the whole-run one:
//! - the CPU ops carry the run's timestamps (`collect_cpu_ops_from`), and the walk
//!   is a per-op fold over carried state, so its per-window outputs concatenate
//!   to the whole-run outputs;
//! - the routing's lists are concatenations of segments (a filter over the CPU
//!   ops, then CPU32's dispatch, then what DVRM implies), and each segment is
//!   accumulated on its own ([`RoutedSegments`]) and concatenated in the
//!   whole-run order at the end;
//! - a table is streamed only from its FIRST segment (for LT and SHIFT: the walk's
//!   part, which the whole-run list starts with), so no later op can land in a
//!   streamed chunk;
//! - the chunks are generated by the same functions the table phase uses.
//!
//! Everything that needs the whole run — BITWISE and DECODE multiplicities, the
//! CPU padding count, HALT finalization, PAGE and REGISTER from the final state,
//! the accelerators — is left to [`finish`], which is the whole-run table phase
//! with the streamed chunks' slots skipped ([`StreamSkip`]). So a windowed build is
//! a SCHEDULE, not a different trace: `windowed_builds_the_whole_run_tables`
//! checks every table against [`Traces::from_elf_and_logs`].
//!
//! # Dropping the streamed ops
//!
//! By default the builder keeps every walked window until [`finish`], so the
//! run's op lists are all resident at the end of the run (≈ 300 B per cycle).
//! With [`WindowedTraceBuilder::drop_streamed_ops`] it keeps, per streamed
//! table, only the ops not yet in a handed-out chunk ([`Tail`]), and takes what
//! the table phase would have read from a chunk's ops as the chunk leaves:
//! BITWISE's lookups from LT, SHIFT, STORE, MEMW_A and MEMW_R, DECODE's lookups
//! and the last ECALL from CPU are counted; the phase-3 LT ops of MEMW and
//! MEMW_A are derived and kept (unless [`stream_memw_lt`] already put them in
//! the windows' LT lists). The other walk lists are appended window by window;
//! the in-walk BITWISE lookups are counted and dropped. [`finish`] then runs
//! the table phase over the tails ([`StreamSkip::tails`]). The tables are the
//! same as without it.
//!
//! [`stream_memw_lt`]: WindowedTraceBuilder::stream_memw_lt
//!
//! Row order inside the tables that deduplicate through a `HashMap` (EQ,
//! BYTEWISE, BRANCH, DVRM, LT, MUL) is not reproducible between ANY two builds;
//! their chunks hold the same ops, so the same rows.
//!
//! [`finish`]: WindowedTraceBuilder::finish

use std::collections::{HashMap, VecDeque};

use executor::elf::Elf;
use executor::vm::logs::Log;
#[cfg(feature = "parallel")]
use rayon::prelude::*;
use stark::trace::TraceTable;

use super::super::types::{GoldilocksExtension, GoldilocksField};
use super::{
    CollectedOps, DecodeArtifacts, DecodeTable, InWalk, MemoryState, MemwBuckets, PreCounted,
    RegisterState, RoutedSegments, StreamSkip, Traces, WalkLean, WalkOutputs, bitwise,
    build_initial_image, build_traces, collect_halt_ops, collect_ops_from_cpu_into, route_ops,
    route_ops_one_pass,
};
use crate::Error;
use crate::tables::{
    cpu, decode, keccak_rnd, load, lt, memw, memw_aligned, memw_register, register, shift, store,
};

#[cfg(test)]
mod producer_harness;

type Table = TraceTable<GoldilocksField, GoldilocksExtension>;

/// The tables a windowed build streams: those whose op lists grow in
/// execution order from their first element.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum StreamTable {
    Cpu,
    MemwRegister,
    MemwAligned,
    Memw,
    Load,
    Lt,
    Shift,
    Store,
    /// Only when the builder cuts KECCAK_RND into chunks
    /// ([`WindowedTraceBuilder::keccak_rnd_chunks`]).
    KeccakRnd,
}

impl StreamTable {
    pub const ALL: [StreamTable; 9] = [
        StreamTable::Cpu,
        StreamTable::MemwRegister,
        StreamTable::MemwAligned,
        StreamTable::Memw,
        StreamTable::Load,
        StreamTable::Lt,
        StreamTable::Shift,
        StreamTable::Store,
        StreamTable::KeccakRnd,
    ];
}

/// One full chunk of a streamed table: chunk `index` of that table, the same
/// table a whole-run build puts at `Traces::<field>[index]`.
pub struct StreamedChunk {
    pub table: StreamTable,
    pub index: usize,
    pub trace: Table,
}

/// A run's traces, built window by window. See the module docs.
pub struct WindowedTraceBuilder<'a> {
    artifacts: DecodeArtifacts,
    image: HashMap<u64, u8>,
    register_init: Vec<u32>,
    max_rows: crate::tables::MaxRowsConfig,
    private_input: &'a [u8],
    memory_state: MemoryState,
    register_state: RegisterState,
    /// Cycles collected so far: the next window's first cycle.
    cycles: usize,
    /// The walked windows, in run order, kept as they were walked: moved here,
    /// never copied. `finish` concatenates them once, list by list.
    windows: Vec<WalkedWindow>,
    /// The routing's segments (smaller lists), appended per window.
    segments: RoutedSegments,
    emitted: StreamSkip,
    /// The BITWISE lookups of the walked windows' in-walk lookups and MEMW_R
    /// rows, counted as the windows arrive.
    counted: PreCounted,
    stamps: WindowStamps,
    /// [`Self::stream_memw_lt`].
    stream_memw_lt: bool,
    /// [`Self::drop_streamed_ops`]: the run so far, without the handed-out ops
    /// (`windows` stays empty).
    kept: Option<Kept>,
    /// The parts of the lean walk this build uses.
    lean: WalkLean,
    /// With [`WalkLean::decode`], the walk reads each cycle's decode from here,
    /// from the instruction map otherwise.
    decode: Option<DecodeTable>,
    /// With [`WalkLean::walk_counts`], the walker counts the walked windows'
    /// in-walk lookups here; `finish` adds them to the run's.
    walk_counted: Option<Box<bitwise::BitwiseHistogram>>,
}

/// Where a windowed build spent its time, seconds summed over the windows:
/// the walk, the routing (with the window's bookkeeping), and handing the
/// streamed chunks out (`finish` is timed by its caller).
#[derive(Clone, Copy, Debug, Default)]
pub struct WindowStamps {
    pub windows: usize,
    pub walk: f64,
    pub route: f64,
    pub generate: f64,
}

impl<'a> WindowedTraceBuilder<'a> {
    /// A builder for a run of `elf` on `private_input`, chunked at `max_rows`
    /// — the state [`Traces::from_elf_and_logs`] starts from.
    pub fn new(
        elf: &Elf,
        private_input: &'a [u8],
        max_rows: &crate::tables::MaxRowsConfig,
    ) -> Result<Self, Error> {
        let image = build_initial_image(elf, private_input);
        let register_init = register::register_init_from_entry_point(elf.entry_point);
        let mut memory_state = MemoryState::from_image(&image);
        let register_state = RegisterState::from_init(&register_init);
        let artifacts = DecodeArtifacts::from_elf(elf)?;
        let lean = WalkLean::from_env()?;
        let decode = lean
            .decode
            .then(|| DecodeTable::from_instructions(&artifacts.instructions));
        memory_state.lean = lean.memory;
        let walk_counted = lean
            .walk_counts
            .then(|| Box::new(bitwise::BitwiseHistogram::new()));
        Ok(Self {
            artifacts,
            image,
            register_init,
            max_rows: max_rows.clone(),
            private_input,
            memory_state,
            register_state,
            cycles: 0,
            windows: Vec::new(),
            segments: RoutedSegments::default(),
            emitted: StreamSkip::default(),
            counted: PreCounted {
                histogram: bitwise::BitwiseHistogram::new(),
                bitwise_ops: 0,
                memw_register_rows: 0,
                last_ecall: None,
                memw_lt: Vec::new(),
                memw_aligned_lt: Vec::new(),
            },
            stamps: WindowStamps::default(),
            stream_memw_lt: false,
            kept: None,
            lean,
            decode,
            walk_counted,
        })
    }

    /// Walk with these lean parts, whatever `LAMBDA_VM_WALK_LEAN` says (the
    /// tables are the same). Before the first window only.
    #[cfg(test)]
    pub(crate) fn walk_lean(mut self, lean: WalkLean) -> Self {
        assert_eq!(self.cycles, 0, "walk_lean after a window was walked");
        self.decode = lean
            .decode
            .then(|| DecodeTable::from_instructions(&self.artifacts.instructions));
        self.memory_state.lean = lean.memory;
        self.walk_counted = lean
            .walk_counts
            .then(|| Box::new(bitwise::BitwiseHistogram::new()));
        self.lean = lean;
        self
    }

    /// Collects the next window of the run's logs (not the last one: that is
    /// [`finish`](Self::finish)'s) and returns the full chunks it completed.
    ///
    /// A window may be any length; the chunks do not depend on where the
    /// windows fall.
    pub fn push(&mut self, logs: &[Log]) -> Result<Vec<StreamedChunk>, Error> {
        let jobs = self.push_jobs(logs)?;
        #[cfg(feature = "parallel")]
        let jobs = jobs.into_par_iter();
        #[cfg(not(feature = "parallel"))]
        let jobs = jobs.into_iter();
        Ok(jobs.map(ChunkJob::generate).collect())
    }

    /// Like [`push`](Self::push), but hands back each completed chunk as a
    /// [`ChunkJob`] — its ops, copied out — instead of generating it here, so
    /// the caller can generate it on another thread while this one walks the
    /// next window. The chunks are the same.
    pub fn push_jobs(&mut self, logs: &[Log]) -> Result<Vec<ChunkJob>, Error> {
        let (mut walker, mut accumulator) = self.split();
        let walked = walker.walk(logs)?;
        Ok(accumulator.absorb(walked))
    }

    /// Cut KECCAK_RND into tables of `rows` rows — the split a block proof makes
    /// — and hand each full one out as its ops arrive (24 rows an op; the rows
    /// of an op depend on that op alone). `rows` is a power of two, at least 32.
    /// Without this call KECCAK_RND is one table, built by `finish`.
    pub fn keccak_rnd_chunks(mut self, rows: usize) -> Result<Self, Error> {
        if !rows.is_power_of_two() || rows < 32 {
            return Err(Error::Prover(format!(
                "KECCAK_RND chunks of {rows} rows: a power of two of at least 32 is needed"
            )));
        }
        self.emitted.keccak_rnd_rows = rows;
        Ok(self)
    }

    /// Derive each window's phase-3 LT ops (from its MEMW and MEMW_A ops) as the
    /// window arrives, into the window's LT list, so LT's full chunks stream with
    /// them instead of waiting for the run's end.
    ///
    /// ⚠ BLOCK PATH ONLY. The LT ops are the whole-run build's, but in another
    /// order — each window's MEMW-derived ops follow its walk's — so a chunk
    /// holds other ops than the whole-run build's chunk at that index, and LT
    /// deduplicates per chunk. Every LT op is in exactly one chunk with its
    /// whole-run multiplicity summed over the chunks, which is what LT's
    /// constraints and the bus see; the whole-run order (and so every epoch
    /// proof) is untouched. The chunks are a function of the run and the window
    /// length.
    pub fn stream_memw_lt(mut self) -> Self {
        self.stream_memw_lt = true;
        self
    }

    /// Drop each streamed chunk's ops once the chunk is handed out, instead of
    /// keeping every walked window to the run's end (see the module docs): the
    /// builder then holds less than a chunk of each streamed table's ops, plus
    /// the other tables' lists and (without [`Self::stream_memw_lt`]) the
    /// phase-3 LT ops of the MEMW ops it dropped. The tables are the same.
    /// Before the first window only.
    pub fn drop_streamed_ops(mut self) -> Result<Self, Error> {
        if self.cycles > 0 {
            return Err(Error::Prover(
                "drop_streamed_ops after a window was walked".to_string(),
            ));
        }
        self.kept = Some(Kept::new(self.artifacts.decode_trace.clone()));
        Ok(self)
    }

    /// Per streamed table (CPU, MEMW_R, MEMW_A, MEMW, LOAD, LT, SHIFT, STORE),
    /// the ops the builder holds that were not handed out in a chunk, and the
    /// ops its held lists take room for (those plus a part's handed-out head):
    /// under [`Self::drop_streamed_ops`] only; `None` otherwise.
    pub fn held_streamed_ops(&self) -> Option<[(usize, usize); 8]> {
        let kept = self.kept.as_ref()?;
        let store = self.segments.store_ops.len();
        Some([
            kept.cpu.held(),
            kept.register_rows.held(),
            kept.aligned.held(),
            kept.general.held(),
            kept.load.held(),
            kept.lt.held(),
            kept.shift.held(),
            (store, store),
        ])
    }

    /// The time the windows took so far.
    pub fn stamps(&self) -> WindowStamps {
        self.stamps
    }

    /// How many chunks of each streamed table have been handed out.
    pub fn streamed(&self) -> StreamSkip {
        self.emitted
    }

    /// Collects the run's last window and builds every table the windows did
    /// not stream. The streamed chunks' slots hold empty placeholders;
    /// [`Traces::insert_streamed`] puts the chunks back.
    pub fn finish(mut self, logs: &[Log]) -> Result<Traces, Error> {
        // The last window may halt: it is walked here, not by the `Walker`.
        let cpu_ops = match &self.decode {
            Some(table) => super::collect_cpu_ops_from_table(logs, table, self.cycles)?,
            None => super::collect_cpu_ops_from(logs, &self.artifacts.instructions, self.cycles)?,
        };
        self.cycles += logs.len();
        let mut walk = WalkOutputs::with_capacity(cpu_ops.len());
        // The last window's in-walk lookups are listed and counted by the
        // table phase, lean or not.
        collect_ops_from_cpu_into(
            &cpu_ops,
            &mut self.memory_state,
            &mut self.register_state,
            &mut walk,
            InWalk::List,
            None,
        );
        let route = if self.lean.route {
            route_ops_one_pass
        } else {
            route_ops
        };
        self.segments.append(route(&cpu_ops, &walk.cpu32_ops));
        let last = WalkedWindow { cpu_ops, walk };
        super::build_stamps::mark("p0 last window");
        let Self {
            artifacts,
            image,
            register_init,
            max_rows,
            private_input,
            memory_state,
            mut register_state,
            mut windows,
            segments,
            emitted,
            mut counted,
            kept,
            stream_memw_lt,
            walk_counted,
            ..
        } = self;
        // The lookups the walker counted, with the rest.
        if let Some(walk_counted) = walk_counted {
            counted.histogram.merge(&walk_counted);
        }
        let (ops, decode_trace, skip, pre) = match kept {
            None => {
                windows.push(last);
                let (cpu_ops, walk) = concatenate(windows);
                super::build_stamps::mark("p0 concatenate");
                let ops = assemble(cpu_ops, walk, segments, &mut register_state);
                super::build_stamps::mark("p0 assemble");
                (ops, artifacts.decode_trace.clone(), emitted, counted)
            }
            Some(mut kept) => {
                // The last window's ops, its in-walk lookups and its MEMW
                // ops' LT ops are all still to count, as the tails are.
                kept.append(last);
                let (cpu_ops, walk, decode_trace) = kept.into_run();
                super::build_stamps::mark("p0 concatenate");
                let ops = assemble(cpu_ops, walk, segments, &mut register_state);
                super::build_stamps::mark("p0 assemble");
                // With the MEMW-derived LT ops streamed, `memw_lt_done` counts
                // the dropped ops too; without, it is zero and the dropped
                // ops' LT ops are in `counted`.
                let converted = |done: usize, chunks: usize, max: usize| {
                    if !stream_memw_lt {
                        return Ok(done);
                    }
                    done.checked_sub(chunks * max).ok_or_else(|| {
                        Error::Prover(format!(
                            "{chunks} MEMW chunks of {max} were dropped but only {done} ops' LT ops \
                             were derived"
                        ))
                    })
                };
                let skip = StreamSkip {
                    tails: true,
                    memw_lt_done: converted(emitted.memw_lt_done, emitted.memw, max_rows.memw)?,
                    memw_aligned_lt_done: converted(
                        emitted.memw_aligned_lt_done,
                        emitted.memw_aligned,
                        max_rows.memw_aligned,
                    )?,
                    ..emitted
                };
                let pre = PreCounted {
                    bitwise_ops: 0,
                    memw_register_rows: 0,
                    ..counted
                };
                (ops, decode_trace, skip, pre)
            }
        };
        build_traces(
            ops,
            Some(&image),
            &memory_state,
            &register_init,
            decode_trace,
            &artifacts.decode_pc_to_row,
            register_state,
            &max_rows,
            #[cfg(feature = "disk-spill")]
            stark::storage_mode::StorageMode::Ram,
            private_input,
            true,
            false,
            &skip,
            Some(pre),
        )
    }

    /// The builder in its two halves, to run on two threads: the [`Walker`]
    /// walks each window (the state it carries is the walk's), the
    /// [`Accumulator`] keeps each walked window, routes it and hands out the
    /// chunks it completed. Fed the windows in order, the two build exactly
    /// what [`push_jobs`](Self::push_jobs) builds; afterwards
    /// [`finish`](Self::finish) takes the last window as usual.
    pub fn split(&mut self) -> (Walker<'_>, Accumulator<'_>) {
        (
            Walker {
                artifacts: &self.artifacts,
                decode: self.decode.as_ref(),
                in_walk: self.lean.in_walk(),
                counted: self.walk_counted.as_deref_mut(),
                memory_state: &mut self.memory_state,
                register_state: &mut self.register_state,
                cycles: &mut self.cycles,
                windows: &mut self.stamps.windows,
                walk_secs: &mut self.stamps.walk,
            },
            Accumulator {
                lean: self.lean,
                stream_memw_lt: self.stream_memw_lt,
                max_rows: &self.max_rows,
                pc_to_row: &self.artifacts.decode_pc_to_row,
                kept: self.kept.as_mut(),
                windows: &mut self.windows,
                segments: &mut self.segments,
                emitted: &mut self.emitted,
                counted: &mut self.counted,
                route_secs: &mut self.stamps.route,
                handout_secs: &mut self.stamps.generate,
            },
        )
    }
}

/// One window, walked: its CPU ops and what the walk emitted for them.
pub struct WalkedWindow {
    cpu_ops: Vec<super::CpuOperation>,
    walk: WalkOutputs,
}

/// The walk half of a split builder ([`WindowedTraceBuilder::split`]).
pub struct Walker<'b> {
    artifacts: &'b DecodeArtifacts,
    decode: Option<&'b DecodeTable>,
    /// What the walk does with the in-walk lookups ([`WalkLean::in_walk`]);
    /// with [`InWalk::Count`] it counts them into `counted`.
    in_walk: InWalk,
    counted: Option<&'b mut bitwise::BitwiseHistogram>,
    memory_state: &'b mut MemoryState,
    register_state: &'b mut RegisterState,
    cycles: &'b mut usize,
    windows: &'b mut usize,
    walk_secs: &'b mut f64,
}

impl Walker<'_> {
    /// Walks the next window (not the run's last) into fresh lists.
    pub fn walk(&mut self, logs: &[Log]) -> Result<WalkedWindow, Error> {
        // As a whole-run build: only the last cycle may halt.
        if logs.iter().any(|log| log.next_pc == 0) {
            return Err(Error::HaltInNonFinalEpoch);
        }
        let t = std::time::Instant::now();
        let cpu_ops = match self.decode {
            Some(table) => super::collect_cpu_ops_from_table(logs, table, *self.cycles)?,
            None => super::collect_cpu_ops_from(logs, &self.artifacts.instructions, *self.cycles)?,
        };
        *self.cycles += logs.len();
        // Left out, the accumulator counts them (`absorb`).
        let mut walk = WalkOutputs::for_walk(cpu_ops.len(), self.in_walk == InWalk::List);
        collect_ops_from_cpu_into(
            &cpu_ops,
            self.memory_state,
            self.register_state,
            &mut walk,
            self.in_walk,
            self.counted.as_deref_mut(),
        );
        *self.walk_secs += t.elapsed().as_secs_f64();
        *self.windows += 1;
        Ok(WalkedWindow { cpu_ops, walk })
    }
}

/// The accumulating half of a split builder ([`WindowedTraceBuilder::split`]).
pub struct Accumulator<'b> {
    /// The lean parts the builder uses: with [`InWalk::Leave`] the walker left
    /// each window's in-walk lookups out, with `route` the routing is one pass.
    lean: WalkLean,
    stream_memw_lt: bool,
    max_rows: &'b crate::tables::MaxRowsConfig,
    pc_to_row: &'b decode::PcToRow,
    kept: Option<&'b mut Kept>,
    windows: &'b mut Vec<WalkedWindow>,
    segments: &'b mut RoutedSegments,
    emitted: &'b mut StreamSkip,
    counted: &'b mut PreCounted,
    route_secs: &'b mut f64,
    handout_secs: &'b mut f64,
}

impl Accumulator<'_> {
    /// Routes a walked window, keeps it, and hands out the chunks the run's
    /// lists now complete. Windows must come in run order.
    pub fn absorb(&mut self, mut window: WalkedWindow) -> Vec<ChunkJob> {
        let t = std::time::Instant::now();
        if self.stream_memw_lt {
            let walk = &mut window.walk;
            walk.lt_ops
                .extend(super::collect_lt_from_memw(&walk.memw.general));
            walk.lt_ops
                .extend(super::collect_lt_from_memw_aligned(&walk.memw.aligned));
            self.emitted.memw_lt_done += walk.memw.general.len();
            self.emitted.memw_aligned_lt_done += walk.memw.aligned.len();
        }
        let route = if self.lean.route {
            route_ops_one_pass
        } else {
            route_ops
        };
        self.segments
            .append(route(&window.cpu_ops, &window.walk.cpu32_ops));
        // The table phase's dominant BITWISE source, counted now: from the CPU
        // and LOAD ops when the walk left the lookups out (the list is then
        // empty), from the list otherwise.
        if self.lean.in_walk() == InWalk::Leave {
            let histogram = &mut self.counted.histogram;
            window
                .cpu_ops
                .iter()
                .for_each(|op| op.count_bitwise_into(histogram));
            window
                .walk
                .load_ops
                .iter()
                .for_each(|op| op.count_bitwise_into(histogram));
        }
        self.counted.histogram.add_ops(&window.walk.bitwise_ops);
        self.counted.bitwise_ops += window.walk.bitwise_ops.len();
        if let Some(kept) = self.kept.as_deref_mut() {
            // Nothing else reads the in-walk lookups; MEMW_R's rows are
            // counted as their chunks leave.
            drop(std::mem::take(&mut window.walk.bitwise_ops));
            kept.append(window);
            *self.route_secs += t.elapsed().as_secs_f64();
            let t = std::time::Instant::now();
            let jobs = tail_jobs(
                self.max_rows,
                self.stream_memw_lt,
                self.pc_to_row,
                kept,
                self.segments,
                self.emitted,
                self.counted,
            );
            *self.handout_secs += t.elapsed().as_secs_f64();
            jobs
        } else {
            // And the second, MEMW_R.
            super::memw_register::collect_bitwise_from_memw_register(
                &window.walk.memw.register_rows,
                &mut self.counted.histogram,
            );
            self.counted.memw_register_rows += window.walk.memw.register_rows.len();
            self.windows.push(window);
            *self.route_secs += t.elapsed().as_secs_f64();
            let t = std::time::Instant::now();
            let jobs = chunk_jobs(self.max_rows, self.windows, self.segments, self.emitted);
            *self.handout_secs += t.elapsed().as_secs_f64();
            jobs
        }
    }
}

/// `range` of the run's list that `list` picks out of each window, gathered
/// into one vector (the windows' lists concatenate to the run's).
fn gather<T: Clone>(
    windows: &[WalkedWindow],
    list: impl Fn(&WalkedWindow) -> &[T],
    range: std::ops::Range<usize>,
) -> Vec<T> {
    let mut out = Vec::with_capacity(range.len());
    let mut at = 0usize;
    for window in windows {
        let part = list(window);
        let (lo, hi) = (at, at + part.len());
        if hi > range.start && lo < range.end {
            let from = range.start.max(lo) - lo;
            let to = range.end.min(hi) - lo;
            out.extend_from_slice(&part[from..to]);
        }
        at = hi;
        if at >= range.end {
            break;
        }
    }
    out
}

// The run's lists, as each window holds its part.
fn list_cpu(w: &WalkedWindow) -> &[super::CpuOperation] {
    &w.cpu_ops
}
fn list_register_rows(w: &WalkedWindow) -> &[super::RegRow] {
    &w.walk.memw.register_rows
}
fn list_aligned(w: &WalkedWindow) -> &[super::MemwOperation] {
    &w.walk.memw.aligned
}
fn list_general(w: &WalkedWindow) -> &[super::MemwOperation] {
    &w.walk.memw.general
}
fn list_load(w: &WalkedWindow) -> &[super::LoadOperation] {
    &w.walk.load_ops
}
fn list_lt(w: &WalkedWindow) -> &[super::LtOperation] {
    &w.walk.lt_ops
}
fn list_shift(w: &WalkedWindow) -> &[super::ShiftOperation] {
    &w.walk.shift_ops
}
fn list_keccak(w: &WalkedWindow) -> &[super::keccak::KeccakOperation] {
    &w.walk.keccak_ops
}

/// Every full chunk the run's lists hold that was not handed out yet, its ops
/// gathered out of the windows.
fn chunk_jobs(
    m: &crate::tables::MaxRowsConfig,
    windows: &[WalkedWindow],
    segments: &RoutedSegments,
    e: &mut StreamSkip,
) -> Vec<ChunkJob> {
    let mut jobs = Vec::new();
    macro_rules! full_chunks {
        ($table:expr, $variant:ident, $list:expr, $max:expr, $done:expr) => {{
            let list = $list;
            let len: usize = windows.iter().map(|w| list(w).len()).sum();
            let max = $max;
            while ($done + 1) * max <= len {
                let index = $done;
                jobs.push(ChunkJob {
                    table: $table,
                    index,
                    ops: ChunkOps::$variant(gather(windows, list, index * max..(index + 1) * max)),
                });
                $done += 1;
            }
        }};
    }
    full_chunks!(StreamTable::Cpu, Cpu, list_cpu, m.cpu, e.cpu);
    full_chunks!(
        StreamTable::MemwRegister,
        MemwRegister,
        list_register_rows,
        m.memw_register,
        e.memw_register
    );
    full_chunks!(
        StreamTable::MemwAligned,
        MemwAligned,
        list_aligned,
        m.memw_aligned,
        e.memw_aligned
    );
    full_chunks!(StreamTable::Memw, Memw, list_general, m.memw, e.memw);
    full_chunks!(StreamTable::Load, Load, list_load, m.load, e.load);
    full_chunks!(StreamTable::Lt, Lt, list_lt, m.lt, e.lt);
    full_chunks!(StreamTable::Shift, Shift, list_shift, m.shift, e.shift);
    // KECCAK_RND, cut at `keccak_rnd_rows` rows: a chunk is out once the ops so
    // far cover all of its rows (the run's padding rows only reach its last).
    if e.keccak_rnd_rows > 0 {
        let rows = e.keccak_rnd_rows;
        let len: usize = windows.iter().map(|w| list_keccak(w).len()).sum();
        while (e.keccak_rnd + 1) * rows <= len * 24 {
            let index = e.keccak_rnd;
            let (first, end) = super::keccak_rnd_op_range(index, rows, len);
            jobs.push(ChunkJob {
                table: StreamTable::KeccakRnd,
                index,
                ops: ChunkOps::KeccakRnd {
                    ops: gather(windows, list_keccak, first..end),
                    skip: index * rows - first * 24,
                    rows,
                },
            });
            e.keccak_rnd += 1;
        }
    }
    // STORE's ops are a routing segment, already one list.
    let store = &segments.store_ops;
    while (e.store + 1) * m.store <= store.len() {
        let index = e.store;
        jobs.push(ChunkJob {
            table: StreamTable::Store,
            index,
            ops: ChunkOps::Store(store[index * m.store..(index + 1) * m.store].to_vec()),
        });
        e.store += 1;
    }
    jobs
}

/// A streamed table's ops not yet in a handed-out chunk
/// ([`WindowedTraceBuilder::drop_streamed_ops`]): the windows' lists, moved in
/// whole, of which the first `start` ops of the first have left.
struct Tail<T> {
    parts: VecDeque<Vec<T>>,
    start: usize,
    len: usize,
}

impl<T: Clone> Tail<T> {
    fn new() -> Self {
        Self {
            parts: VecDeque::new(),
            start: 0,
            len: 0,
        }
    }

    fn push(&mut self, part: Vec<T>) {
        if !part.is_empty() {
            self.len += part.len();
            self.parts.push_back(part);
        }
    }

    /// The first `n` ops (at most `len`). A part that is exactly the chunk
    /// moves out whole; a part the chunk uses up is freed.
    fn take(&mut self, n: usize) -> Vec<T> {
        let n = n.min(self.len);
        self.len -= n;
        if self.start == 0 && self.parts.front().is_some_and(|part| part.len() == n) {
            return self.parts.pop_front().unwrap_or_default();
        }
        let mut out = Vec::with_capacity(n);
        while out.len() < n {
            let Some(front) = self.parts.front() else {
                break;
            };
            let want = n - out.len();
            if front.len() - self.start <= want {
                out.extend_from_slice(&front[self.start..]);
                self.parts.pop_front();
                self.start = 0;
            } else {
                out.extend_from_slice(&front[self.start..self.start + want]);
                self.start += want;
            }
        }
        out
    }

    /// (ops not handed out, ops the parts hold).
    fn held(&self) -> (usize, usize) {
        (self.len, self.len + self.start)
    }

    /// The ops not handed out, as one list.
    fn into_vec(mut self) -> Vec<T> {
        if self.start == 0 && self.parts.len() == 1 {
            return self.parts.pop_front().unwrap_or_default();
        }
        let mut out = Vec::with_capacity(self.len);
        for (i, part) in self.parts.into_iter().enumerate() {
            out.extend_from_slice(&part[if i == 0 { self.start } else { 0 }..]);
        }
        out
    }
}

/// The run so far under [`WindowedTraceBuilder::drop_streamed_ops`].
struct Kept {
    cpu: Tail<super::CpuOperation>,
    register_rows: Tail<super::RegRow>,
    aligned: Tail<super::MemwOperation>,
    general: Tail<super::MemwOperation>,
    load: Tail<super::LoadOperation>,
    lt: Tail<super::LtOperation>,
    shift: Tail<super::ShiftOperation>,
    /// Every other walk list, the run so far (the streamed lists' fields stay
    /// empty; the in-walk lookups only hold what is left to count).
    rest: WalkOutputs,
    /// DECODE with the lookups of the CPU ops handed out counted.
    decode: Table,
}

impl Kept {
    fn new(decode: Table) -> Self {
        Self {
            cpu: Tail::new(),
            register_rows: Tail::new(),
            aligned: Tail::new(),
            general: Tail::new(),
            load: Tail::new(),
            lt: Tail::new(),
            shift: Tail::new(),
            rest: WalkOutputs::with_capacity(0),
            decode,
        }
    }

    /// A walked window's lists, appended in run order.
    fn append(&mut self, window: WalkedWindow) {
        let WalkedWindow { cpu_ops, walk } = window;
        let WalkOutputs {
            memw,
            load_ops,
            lt_ops,
            shift_ops,
            bitwise_ops,
            commit_ops,
            keccak_ops,
            blake3_ops,
            blake3_absorb_ops,
            cpu32_ops,
            ecsm_ops,
            ecdas_ops,
            hint_ops,
        } = walk;
        self.cpu.push(cpu_ops);
        self.register_rows.push(memw.register_rows);
        self.aligned.push(memw.aligned);
        self.general.push(memw.general);
        self.load.push(load_ops);
        self.lt.push(lt_ops);
        self.shift.push(shift_ops);
        let rest = &mut self.rest;
        rest.bitwise_ops.extend(bitwise_ops);
        rest.commit_ops.extend(commit_ops);
        rest.keccak_ops.extend(keccak_ops);
        rest.blake3_ops.extend(blake3_ops);
        rest.blake3_absorb_ops.extend(blake3_absorb_ops);
        rest.cpu32_ops.extend(cpu32_ops);
        rest.ecsm_ops.extend(ecsm_ops);
        rest.ecdas_ops.extend(ecdas_ops);
        rest.hint_ops.extend(hint_ops);
    }

    /// The run's lists with the handed-out ops left out, and DECODE.
    fn into_run(self) -> (Vec<super::CpuOperation>, WalkOutputs, Table) {
        let Kept {
            cpu,
            register_rows,
            aligned,
            general,
            load,
            lt,
            shift,
            mut rest,
            decode,
        } = self;
        rest.memw = MemwBuckets {
            register_rows: register_rows.into_vec(),
            aligned: aligned.into_vec(),
            general: general.into_vec(),
        };
        rest.load_ops = load.into_vec();
        rest.lt_ops = lt.into_vec();
        rest.shift_ops = shift.into_vec();
        (cpu.into_vec(), rest, decode)
    }
}

/// [`chunk_jobs`] under [`WindowedTraceBuilder::drop_streamed_ops`]: every full
/// chunk taken out of the tails, and what the table phase reads from its ops
/// counted as it leaves (`counted`, and DECODE in `kept`).
fn tail_jobs(
    m: &crate::tables::MaxRowsConfig,
    stream_memw_lt: bool,
    pc_to_row: &decode::PcToRow,
    kept: &mut Kept,
    segments: &mut RoutedSegments,
    e: &mut StreamSkip,
    counted: &mut PreCounted,
) -> Vec<ChunkJob> {
    let mut jobs = Vec::new();
    macro_rules! take_chunks {
        ($table:expr, $variant:ident, $tail:expr, $max:expr, $done:expr) => {
            take_chunks!($table, $variant, $tail, $max, $done, |ops| {})
        };
        ($table:expr, $variant:ident, $tail:expr, $max:expr, $done:expr, |$ops:ident| $count:block) => {{
            let max = $max;
            while $tail.len >= max {
                let $ops = $tail.take(max);
                $count
                jobs.push(ChunkJob {
                    table: $table,
                    index: $done,
                    ops: ChunkOps::$variant($ops),
                });
                $done += 1;
            }
        }};
    }
    take_chunks!(StreamTable::Cpu, Cpu, kept.cpu, m.cpu, e.cpu, |ops| {
        let pcs: Vec<u64> = ops.iter().map(|op| op.decode.pc).collect();
        decode::update_multiplicities(&mut kept.decode, pc_to_row, &pcs);
        if let Some(op) = ops.iter().rev().find(|op| op.decode.fields.ecall) {
            counted.last_ecall = Some((op.timestamp, op.next_pc));
        }
    });
    take_chunks!(
        StreamTable::MemwRegister,
        MemwRegister,
        kept.register_rows,
        m.memw_register,
        e.memw_register,
        |ops| {
            super::memw_register::collect_bitwise_from_memw_register(&ops, &mut counted.histogram)
        }
    );
    take_chunks!(
        StreamTable::MemwAligned,
        MemwAligned,
        kept.aligned,
        m.memw_aligned,
        e.memw_aligned,
        |ops| {
            let lookups = super::collect_bitwise_from_memw_aligned(&ops);
            counted.histogram.add_ops(&lookups);
            if !stream_memw_lt {
                let lt = super::collect_lt_from_memw_aligned(&ops);
                counted.memw_aligned_lt.extend(lt);
            }
        }
    );
    take_chunks!(
        StreamTable::Memw,
        Memw,
        kept.general,
        m.memw,
        e.memw,
        |ops| {
            if !stream_memw_lt {
                counted.memw_lt.extend(super::collect_lt_from_memw(&ops));
            }
        }
    );
    take_chunks!(StreamTable::Load, Load, kept.load, m.load, e.load);
    take_chunks!(StreamTable::Lt, Lt, kept.lt, m.lt, e.lt, |ops| {
        counted
            .histogram
            .add_ops(&super::collect_bitwise_from_lt(&ops))
    });
    take_chunks!(
        StreamTable::Shift,
        Shift,
        kept.shift,
        m.shift,
        e.shift,
        |ops| {
            counted
                .histogram
                .add_ops(&shift::collect_bitwise_from_shift(&ops))
        }
    );
    // KECCAK_RND's ops stay: KECCAK needs them all.
    if e.keccak_rnd_rows > 0 {
        let rows = e.keccak_rnd_rows;
        let keccak = &kept.rest.keccak_ops;
        while (e.keccak_rnd + 1) * rows <= keccak.len() * 24 {
            let index = e.keccak_rnd;
            let (first, end) = super::keccak_rnd_op_range(index, rows, keccak.len());
            jobs.push(ChunkJob {
                table: StreamTable::KeccakRnd,
                index,
                ops: ChunkOps::KeccakRnd {
                    ops: keccak[first..end].to_vec(),
                    skip: index * rows - first * 24,
                    rows,
                },
            });
            e.keccak_rnd += 1;
        }
    }
    // STORE's ops are a routing segment: its own tail.
    let store = &mut segments.store_ops;
    while store.len() >= m.store {
        let ops: Vec<store::StoreOperation> = store.drain(..m.store).collect();
        for op in &ops {
            counted.histogram.add_ops(&op.collect_bitwise_ops());
        }
        jobs.push(ChunkJob {
            table: StreamTable::Store,
            index: e.store,
            ops: ChunkOps::Store(ops),
        });
        e.store += 1;
    }
    jobs
}

/// `rayon::join` under the `parallel` feature, the two calls in order without
/// it (the prover's guests take it without rayon).
fn join<A: Send, B: Send>(a: impl FnOnce() -> A + Send, b: impl FnOnce() -> B + Send) -> (A, B) {
    #[cfg(feature = "parallel")]
    {
        rayon::join(a, b)
    }
    #[cfg(not(feature = "parallel"))]
    {
        (a(), b())
    }
}

/// The windows' lists concatenated into the run's, once: list by list in
/// parallel, each window's list freed as it is copied.
/// Whether [`concatenate`] copies each list's windows one after another on one
/// thread (`LAMBDA_VM_BUILDER_CONCAT=serial`), the control for the parallel copy
/// that is the default: on block 25368371 it read −0.52 s of base (FAST 417) and
/// replicated in its re-registered band at −0.21 s (FAST 419). Read once. The
/// two give the same lists.
#[cfg(feature = "parallel")]
fn serial_concat() -> bool {
    static SERIAL: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *SERIAL.get_or_init(|| {
        std::env::var("LAMBDA_VM_BUILDER_CONCAT").is_ok_and(|v| v.trim() == "serial")
    })
}

fn concatenate(windows: Vec<WalkedWindow>) -> (Vec<super::CpuOperation>, WalkOutputs) {
    /// The windows' lists one after another, in window order. Under `parallel`
    /// each window's part is moved into its own disjoint slice of the output
    /// on a thread of its own: the copy and the first touch of a list of
    /// several GiB are spread over the pool instead of one thread.
    fn cat<T: Send>(parts: Vec<Vec<T>>) -> Vec<T> {
        let total = parts.iter().map(Vec::len).sum();
        let mut out = Vec::with_capacity(total);
        #[cfg(feature = "parallel")]
        if !serial_concat() && parts.len() > 1 {
            let mut slots: Vec<&mut [std::mem::MaybeUninit<T>]> = Vec::with_capacity(parts.len());
            let mut rest = &mut out.spare_capacity_mut()[..total];
            for part in &parts {
                let (head, tail) = rest.split_at_mut(part.len());
                slots.push(head);
                rest = tail;
            }
            parts
                .into_par_iter()
                .zip(slots.into_par_iter())
                .for_each(|(part, slot)| {
                    for (dst, src) in slot.iter_mut().zip(part) {
                        dst.write(src);
                    }
                });
            // SAFETY: the slots tile `0..total` of the spare capacity, and each
            // was written element for element by its part, whose length it has.
            unsafe { out.set_len(total) };
            return out;
        }
        for part in parts {
            out.extend(part);
        }
        out
    }
    let n = windows.len();
    let mut cpu = Vec::with_capacity(n);
    let mut register_rows = Vec::with_capacity(n);
    let mut aligned = Vec::with_capacity(n);
    let mut general = Vec::with_capacity(n);
    let mut load = Vec::with_capacity(n);
    let mut lt = Vec::with_capacity(n);
    let mut shift = Vec::with_capacity(n);
    let mut bitwise = Vec::with_capacity(n);
    let mut commit = Vec::with_capacity(n);
    let mut keccak = Vec::with_capacity(n);
    let mut blake3 = Vec::with_capacity(n);
    let mut blake3_absorb = Vec::with_capacity(n);
    let mut cpu32 = Vec::with_capacity(n);
    let mut ecsm = Vec::with_capacity(n);
    let mut ecdas = Vec::with_capacity(n);
    let mut hint = Vec::with_capacity(n);
    for WalkedWindow { cpu_ops, walk } in windows {
        cpu.push(cpu_ops);
        register_rows.push(walk.memw.register_rows);
        aligned.push(walk.memw.aligned);
        general.push(walk.memw.general);
        load.push(walk.load_ops);
        lt.push(walk.lt_ops);
        shift.push(walk.shift_ops);
        bitwise.push(walk.bitwise_ops);
        commit.push(walk.commit_ops);
        keccak.push(walk.keccak_ops);
        blake3.push(walk.blake3_ops);
        blake3_absorb.push(walk.blake3_absorb_ops);
        cpu32.push(walk.cpu32_ops);
        ecsm.push(walk.ecsm_ops);
        ecdas.push(walk.ecdas_ops);
        hint.push(walk.hint_ops);
    }
    let ((cpu, (register_rows, aligned)), ((general, bitwise), (load, (lt, shift)))) = join(
        || (cat(cpu), join(|| cat(register_rows), || cat(aligned))),
        || {
            join(
                || join(|| cat(general), || cat(bitwise)),
                || join(|| cat(load), || join(|| cat(lt), || cat(shift))),
            )
        },
    );
    let walk = WalkOutputs {
        memw: MemwBuckets {
            register_rows,
            aligned,
            general,
        },
        load_ops: load,
        lt_ops: lt,
        shift_ops: shift,
        bitwise_ops: bitwise,
        commit_ops: cat(commit),
        keccak_ops: cat(keccak),
        blake3_ops: cat(blake3),
        blake3_absorb_ops: cat(blake3_absorb),
        cpu32_ops: cat(cpu32),
        ecsm_ops: cat(ecsm),
        ecdas_ops: cat(ecdas),
        hint_ops: cat(hint),
    };
    (cpu, walk)
}

/// A completed chunk not generated yet: which chunk it is, and its ops.
/// [`generate`](Self::generate) builds the table a whole-run build puts in that
/// slot, with the same function.
pub struct ChunkJob {
    pub table: StreamTable,
    pub index: usize,
    ops: ChunkOps,
}

enum ChunkOps {
    Cpu(Vec<super::CpuOperation>),
    MemwRegister(Vec<super::RegRow>),
    MemwAligned(Vec<super::MemwOperation>),
    Memw(Vec<super::MemwOperation>),
    Load(Vec<super::LoadOperation>),
    Lt(Vec<super::LtOperation>),
    Shift(Vec<super::ShiftOperation>),
    Store(Vec<store::StoreOperation>),
    KeccakRnd {
        ops: Vec<super::keccak::KeccakOperation>,
        skip: usize,
        rows: usize,
    },
}

impl ChunkJob {
    pub fn generate(self) -> StreamedChunk {
        let trace = match &self.ops {
            ChunkOps::Cpu(ops) => cpu::generate_cpu_trace(ops),
            ChunkOps::MemwRegister(ops) => {
                memw_register::generate_memw_register_trace_from_rows(ops)
            }
            ChunkOps::MemwAligned(ops) => memw_aligned::generate_memw_aligned_trace(ops),
            ChunkOps::Memw(ops) => memw::generate_memw_trace(ops),
            ChunkOps::Load(ops) => load::generate_load_trace(ops),
            ChunkOps::Lt(ops) => lt::generate_lt_trace(ops),
            ChunkOps::Shift(ops) => shift::generate_shift_trace(ops),
            ChunkOps::Store(ops) => store::generate_store_trace(ops),
            ChunkOps::KeccakRnd { ops, skip, rows } => {
                let ops: Vec<keccak_rnd::KeccakRoundOperation> = ops
                    .iter()
                    .map(|op| keccak_rnd::KeccakRoundOperation {
                        timestamp: op.timestamp,
                        input: op.input,
                        output: op.output,
                    })
                    .collect();
                keccak_rnd::generate_keccak_rnd_rows(&ops, *skip, *rows)
            }
        };
        StreamedChunk {
            table: self.table,
            index: self.index,
            trace,
        }
    }
}

/// The walk's lists and the routing's segments as the whole-run
/// [`collect_all_ops`](super::collect_all_ops) returns them, HALT finalization
/// included (the run's end).
fn assemble(
    cpu_ops: Vec<super::CpuOperation>,
    walk: WalkOutputs,
    segments: RoutedSegments,
    register_state: &mut RegisterState,
) -> CollectedOps {
    let WalkOutputs {
        memw,
        load_ops,
        mut lt_ops,
        mut shift_ops,
        mut bitwise_ops,
        commit_ops,
        keccak_ops,
        blake3_ops,
        blake3_absorb_ops,
        cpu32_ops,
        ecsm_ops,
        ecdas_ops,
        hint_ops,
    } = walk;
    let MemwBuckets {
        register_rows: mut memw_register_rows,
        aligned: mut memw_aligned_ops,
        general: mut memw_ops,
    } = memw;
    // HALT's register ops land at the end of their buckets, as in
    // `collect_all_ops`.
    let mut halt = MemwBuckets::with_register_capacity(0);
    halt.extend_ops(collect_halt_ops(register_state));
    memw_register_rows.extend(halt.register_rows);
    memw_aligned_ops.extend(halt.aligned);
    memw_ops.extend(halt.general);

    let RoutedSegments {
        branch_ops,
        mul_filter,
        dvrm_filter,
        eq_ops,
        bytewise_ops,
        store_ops,
        shift_cpu32,
        mul_cpu32,
        dvrm_cpu32,
        bitwise_cpu32,
        lt_dvrm_filter,
        lt_dvrm_cpu32,
        mul_dvrm_filter,
        mul_dvrm_cpu32,
    } = segments;
    shift_ops.extend(shift_cpu32);
    bitwise_ops.extend(bitwise_cpu32);
    let mut mul_ops = mul_filter;
    mul_ops.extend(mul_cpu32);
    mul_ops.extend(mul_dvrm_filter);
    mul_ops.extend(mul_dvrm_cpu32);
    let mut dvrm_ops = dvrm_filter;
    dvrm_ops.extend(dvrm_cpu32);
    lt_ops.extend(lt_dvrm_filter);
    lt_ops.extend(lt_dvrm_cpu32);

    CollectedOps {
        cpu_ops,
        memw_ops,
        memw_aligned_ops,
        memw_register_rows,
        load_ops,
        lt_ops,
        shift_ops,
        bitwise_ops,
        branch_ops,
        mul_ops,
        dvrm_ops,
        commit_ops,
        keccak_ops,
        blake3_ops,
        blake3_absorb_ops,
        eq_ops,
        bytewise_ops,
        store_ops,
        cpu32_ops,
        ecsm_ops,
        ecdas_ops,
        hint_ops,
    }
}

impl Traces {
    /// Puts streamed chunks back into the placeholder slots a windowed build's
    /// [`finish`](WindowedTraceBuilder::finish) left — which makes the traces
    /// the whole-run build's. Refuses a chunk for a slot that is not a
    /// placeholder.
    pub fn insert_streamed(&mut self, chunks: Vec<StreamedChunk>) -> Result<(), Error> {
        for chunk in chunks {
            let slots = match chunk.table {
                StreamTable::Cpu => &mut self.cpus,
                StreamTable::MemwRegister => &mut self.memw_registers,
                StreamTable::MemwAligned => &mut self.memw_aligneds,
                StreamTable::Memw => &mut self.memws,
                StreamTable::Load => &mut self.loads,
                StreamTable::Lt => &mut self.lts,
                StreamTable::Shift => &mut self.shifts,
                StreamTable::Store => &mut self.stores,
                StreamTable::KeccakRnd => &mut self.keccak_rnds,
            };
            let len = slots.len();
            let slot = slots.get_mut(chunk.index).ok_or_else(|| {
                Error::Prover(format!(
                    "{:?} chunk {} has no slot ({len} tables)",
                    chunk.table, chunk.index,
                ))
            })?;
            if slot.main_table.width != 0 {
                return Err(Error::Prover(format!(
                    "{:?} chunk {} lands on a slot that is not a placeholder",
                    chunk.table, chunk.index
                )));
            }
            *slot = chunk.trace;
        }
        Ok(())
    }
}
