// Known answers for the ZisK-instance device kernels (`kernels/p1w16.cu`), computed by
// ZisK's own Rust implementation (`proofman-fields`, pil2-proofman v1.3.0-alpha, d485fac2,
// MIT OR Apache-2.0). GENERATED by `scripts/poseidon1/zisk_crosscheck` (`-- c`); do not edit.
// Leaf inputs are the LCG stream `zk_felts(ZK_SEED_LEAF, n)`.
#pragma once
#include <cstdint>
static const uint64_t ZK_PERM8_IN[4][8] = {
    {0x0000000000000000ull, 0x0000000000000001ull, 0x0000000000000002ull, 0x0000000000000003ull, 0x0000000000000004ull, 0x0000000000000005ull, 0x0000000000000006ull, 0x0000000000000007ull},
    {0x0000000000000000ull, 0x0000000000000000ull, 0x0000000000000000ull, 0x0000000000000000ull, 0x0000000000000000ull, 0x0000000000000000ull, 0x0000000000000000ull, 0x0000000000000000ull},
    {0xffffffff00000000ull, 0xffffffff00000000ull, 0xffffffff00000000ull, 0xffffffff00000000ull, 0xffffffff00000000ull, 0xffffffff00000000ull, 0xffffffff00000000ull, 0xffffffff00000000ull},
    {0x2ceaee21bf46bc00ull, 0xaa80754d1a1a8d4full, 0xb3c4904a6d278932ull, 0xbc69cf4276846d19ull, 0x377b2fd56a5b15b4ull, 0x64d815deeaf29df3ull, 0xf66e100db2d7d206ull, 0x1069e6a57e06665dull},
};
static const uint64_t ZK_PERM8_OUT[4][8] = {
    {0x21bd740749dd30d7ull, 0x82d56e9f77070d02ull, 0x5ec0547e3dbc8dccull, 0xeaa429642119fae9ull, 0x8c9b30f79af9b031ull, 0xf224d564607084bdull, 0x7dd2af74636e87d6ull, 0xa7daeb4dc21c22d7ull},
    {0x967b858fdabc48f5ull, 0xad350bc2b4a0e728ull, 0x2df1898fef94687aull, 0x03615aabe4616577ull, 0x964840faf7231998ull, 0x2c23d347f3c7cddbull, 0xc3c52c0cb7d2776cull, 0xa1021e181fe6ea58ull},
    {0x00f79505ba6ae588ull, 0xa94c3a530e38c062ull, 0xc33cd2c7bad60fa5ull, 0x9eab666a9418b97cull, 0xba59588e735134f7ull, 0xe20003ce19565758ull, 0xdd6e988c7e479219ull, 0xa7f53d8b009dd2e7ull},
    {0x6f4b8bcff6c46360ull, 0x55fa4e327ba9a074ull, 0x64f61d05b00bb015ull, 0x503249cfdf8949a2ull, 0xee0c105d8e205184ull, 0xa296e0f105460d27ull, 0x2a1dd0e592a7148bull, 0x3796cef45525bcecull},
};
static const uint64_t ZK_SEED_LEAF = 0x1eafull;
static const uint64_t ZK_LEAF_N[15] = {1, 3, 4, 5, 8, 11, 12, 13, 23, 24, 25, 36, 64, 100, 245};
static const uint64_t ZK_LEAF_DIGEST[15][4] = {
    {0x7d03e575421c5b23ull, 0xe7205b8b16d02caeull, 0xe7403af7b190c9b8ull, 0x33dce167235a4161ull},
    {0x6640aacb19b99fefull, 0x8cfa8c6eded38947ull, 0x983df120f9673f0eull, 0x1310238c565b68c3ull},
    {0x5bbe522545759068ull, 0x8be0c21c95272122ull, 0x4c1d411056f08119ull, 0xfd4884cefaae238eull},
    {0xf9e35072a2cbb968ull, 0x00eecaa4551e4bc6ull, 0x2967536c85b1e981ull, 0xcc0e4f974a68a925ull},
    {0x37699b63c7c41ff8ull, 0x9b77ac0ed9cfa6baull, 0xe8e79112528274faull, 0x0c97bd2a1719f7a9ull},
    {0x2fb335f8ba81a625ull, 0xc60103e3cd048002ull, 0x6ad161bff910fe7full, 0xda3990535144a065ull},
    {0x56d3b861d55fd314ull, 0xa5a31a15748ecf02ull, 0x7b8a70ffc050b14aull, 0x1ea870b034c04761ull},
    {0x970e5d8788b6ff13ull, 0x662a81f429cf5db9ull, 0x4b0b0ab73c68d61dull, 0x9f39ab57a883f85aull},
    {0xb24ab0a82ce7788full, 0x01e278923e6f556aull, 0x1d5fcb3b6c26b2dfull, 0xb854b08d821532a7ull},
    {0x94f5a3dd9e653ad2ull, 0x3170c14426de671bull, 0x2b2be28f1e5de7e6ull, 0x121dc669632d4af2ull},
    {0x92f4915f35848d9full, 0x23d820916e1a5313ull, 0xde776805d1a21bf7ull, 0x9e2ecd73e3fcced1ull},
    {0x042694abd8c60e18ull, 0x64e6ea0ecb0e3dacull, 0x089c1f4d45e9b9b7ull, 0xa13674c9fe4c3eedull},
    {0x8794e906c2322944ull, 0x0e3e180c1411cf2aull, 0xd4f728e29cf2838full, 0x5972df3e1ef71b06ull},
    {0x61ca36b7bf6d6dd3ull, 0x54822101148cfe34ull, 0x019fda1d3ba125c2ull, 0xff29312691d434ebull},
    {0x7c9f951fe2d785d0ull, 0x1a234f39f5f1997dull, 0xfa9e991c9153c45cull, 0x17e9375cff057d09ull},
};
static const uint64_t ZK_GRIND_CHALLENGE[3] = {0x9e2dc8d5767b6c68ull, 0x600b7718fe692797ull, 0xc430fd99b96a5fdaull};
static const uint64_t ZK_GRIND_LANE0[4] = {0xc82edce9946878a9ull, 0xa97fc9da5e04914eull, 0x4d160560aa29bea0ull, 0x03007779902fd6ebull};
static const uint64_t ZK_GRIND_BITS = 10;
static const uint64_t ZK_GRIND_SMALLEST_NONCE = 2408;
