//! ⚠ TEMPORARY measurement knobs of the gap campaign's HASH lane — K3, K4, K5.
//!
//! Each fix ships behind its own variable, default OFF, so one binary runs an
//! A/B with the fix off and on. The variables are removed (the fix becomes the
//! code's only path) when a fix is integrated.
//!
//! - `LAMBDA_VM_GAP_K3=1` — Merkle narrow levels and tails through the
//!   half-warp permutation (`rpx_merkle_level_warp`, `rpx_merkle_tail_warp`).
//! - `LAMBDA_VM_GAP_K4=1` — the RPX grind through the work-queue kernel
//!   (`rpx_grind_search_queue`) on a grid that fills the card.
//! - `LAMBDA_VM_GAP_K5=<V>` — every RPX kernel from `rpx_k5_v<V>.cubin`, the
//!   same source compiled at permutation variant `V`, one of [`K5_VARIANTS`]
//!   (a bit set: limb multiply 1, limb square 2, unrolled `square_n` 4).
//!   `1` is the limb multiply alone.
//!
//! None of them moves a byte of a proof: the nodes, roots and grind nonces are
//! the shipped kernels' (the parity tests pin each against the shipped path).
//!
//! Read once per process and printed as ONE line, `★ GAP HASH KNOBS: …`, on
//! first use, so every log that reached an RPX device path says which arms ran.
//! A value the knob does not accept aborts at startup, the way the grind knobs
//! do: a typo that silently read as "off" would turn a B arm into an A arm.

use std::sync::OnceLock;

pub const K3_ENV: &str = "LAMBDA_VM_GAP_K3";
pub const K4_ENV: &str = "LAMBDA_VM_GAP_K4";
pub const K5_ENV: &str = "LAMBDA_VM_GAP_K5";

// `K5_VARIANTS`: the permutation variants compiled as `rpx_k5_v<V>.cubin`.
// Generated by build.rs from the list it compiles, so the knob can only name a
// cubin that exists.
include!(concat!(env!("OUT_DIR"), "/rpx_k5_consts.rs"));

/// The three knobs as this process read them.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HashKnobs {
    pub k3: bool,
    pub k4: bool,
    /// The K5 permutation variant whose cubin replaces `rpx.cubin`, if any.
    pub k5: Option<u32>,
}

/// The knobs for this process, read once and cached; prints the banner on the
/// first call.
pub fn knobs() -> HashKnobs {
    static KNOBS: OnceLock<HashKnobs> = OnceLock::new();
    *KNOBS.get_or_init(|| {
        let knobs = HashKnobs {
            k3: read(K3_ENV, &[1]).is_some(),
            k4: read(K4_ENV, &[1]).is_some(),
            k5: read(K5_ENV, &K5_VARIANTS),
        };
        println!(
            "★ GAP HASH KNOBS: K3 {} · K4 {} · K5 {}",
            on_off(knobs.k3),
            on_off(knobs.k4),
            match knobs.k5 {
                Some(v) => format!("variant {v} (rpx_k5_v{v}.cubin)"),
                None => "off (rpx.cubin)".to_string(),
            },
        );
        knobs
    })
}

fn on_off(on: bool) -> &'static str {
    if on { "on" } else { "off" }
}

/// `None` when unset or `0`; `Some(v)` for a value in `accepted`; abort on
/// anything else, naming what is accepted.
fn read(env: &str, accepted: &[u32]) -> Option<u32> {
    match std::env::var(env) {
        Err(_) => None,
        Ok(raw) => parse(raw.trim(), accepted).unwrap_or_else(|| {
            eprintln!(
                "{env}={raw:?} is not a value this knob accepts. Accepted: 0 (off) or one of {accepted:?}."
            );
            std::process::abort()
        }),
    }
}

/// `Some(None)` = off, `Some(Some(v))` = on at `v`, `None` = refused.
fn parse(raw: &str, accepted: &[u32]) -> Option<Option<u32>> {
    if raw == "0" {
        return Some(None);
    }
    // Plain decimal digits only: no sign, no spaces, no leading zero.
    if raw.is_empty() || raw.starts_with('0') || !raw.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    let v: u32 = raw.parse().ok()?;
    accepted.contains(&v).then_some(Some(v))
}

#[cfg(test)]
mod tests {
    use super::{K5_VARIANTS, parse};

    #[test]
    fn on_off_knobs_accept_only_zero_and_one() {
        assert_eq!(parse("1", &[1]), Some(Some(1)));
        assert_eq!(parse("0", &[1]), Some(None));
        for raw in ["", "on", "true", "2", "01", " 1", "yes", "-1", "+1"] {
            assert_eq!(
                parse(raw, &[1]),
                None,
                "{raw:?} must be refused, not read as off"
            );
        }
    }

    #[test]
    fn the_k5_knob_accepts_exactly_the_compiled_variants() {
        assert_eq!(K5_VARIANTS, [1, 3, 5, 7], "the variants build.rs compiles");
        for v in K5_VARIANTS {
            assert_eq!(parse(&v.to_string(), &K5_VARIANTS), Some(Some(v)));
        }
        for raw in ["2", "4", "8", "9", "03", "x"] {
            assert_eq!(
                parse(raw, &K5_VARIANTS),
                None,
                "{raw:?} names no compiled cubin"
            );
        }
        assert_eq!(parse("0", &K5_VARIANTS), Some(None), "0 is off");
    }
}
