//! Which RPX device path each of three switches takes: the Merkle tree tops,
//! the proof-of-work grind, and the permutation's field multiply.
//!
//! Each switch has its default stated ONCE, as a `*_DEFAULT` constant below,
//! and one variable that overrides it (`1` on, `0` off, unset = the default),
//! read once per process. A pipeline that needs one of them off by default
//! flips that constant, one line, the way `lfm::chunking`'s
//! `HASH_SPLIT_DEFAULT` differs between the two pipelines.
//!
//! Every setting produces the same bytes: the nodes, roots, grind nonces and
//! digests are the other path's, which `prover/tests/rpx_device_paths.rs` pins
//! path against path and against the host oracle. These switch speed, never
//! the proof: a block proved either way has the same program ids.
//!
//! Each prints one line the first time it is read, so every log says which
//! paths it ran — on, then off:
//!
//! - `LAMBDA_VM_RPX_WARP_MERKLE`:
//!   `[gpu] RPX Merkle: a half-warp per parent up to 16384 pairs, then one
//!   1024-thread tail block (…)` /
//!   `[gpu] RPX Merkle: a thread per parent, then one 128-thread tail block (…)`
//! - `LAMBDA_VM_RPX_GRIND_QUEUE`:
//!   `[gpu] RPX grind: the work-queue kernel on a card-filling grid (…)` /
//!   `[gpu] RPX grind: the stride kernel on LAMBDA_VM_GRIND_GRID blocks (…)`
//! - `LAMBDA_VM_RPX_LIMB_PERMUTE`:
//!   `[gpu] RPX permutation: variant 5, 32-bit limb multiplies, squarings
//!   unrolled by four (rpx_v5.cubin) (…)` /
//!   `[gpu] RPX permutation: variant 0, the 64-bit multiply (rpx_v0.cubin) (…)`
//!
//! `(…)` reads `the pipeline default` when the variable is unset, else the
//! variable and its value. The grind queue adds its grid once it has read it
//! (`[gpu] RPX grind queue: grid …`). Any value other than `0` or `1` aborts
//! and names what is accepted: a typo read as "unset" would turn one arm of an
//! A/B into the other.

use std::env::VarError;
use std::sync::OnceLock;

// `LIMB_PERMUTE_VARIANT`: the permutation variant of the default RPX cubin.
// Generated by build.rs from the variant it compiles, so the two cannot drift.
include!(concat!(env!("OUT_DIR"), "/rpx_variants.rs"));

/// The Merkle tops: levels of up to 16,384 pairs through
/// `rpx_merkle_level_warp` (a half-warp per parent) and the last 64 pairs
/// through one `rpx_merkle_tail_warp` block, in every RPX tree walk (the STARK
/// trace, aux, composition and FRI trees, the WHIR trees and their query-time
/// rebuilds). Off: `rpx_merkle_level` at every level and `rpx_merkle_tail`
/// from 128 pairs up.
pub const WARP_MERKLE_DEFAULT: bool = true;

/// The RPX grind: `rpx_grind_search_queue`, warps claiming 32 nonces at a time
/// from a queue head, on a grid of multiprocessors × the kernel's occupancy.
/// Off: `rpx_grind_search`'s stride walk on `LAMBDA_VM_GRIND_GRID` blocks. The
/// same smallest nonce either way.
pub const GRIND_QUEUE_DEFAULT: bool = true;

/// The permutation's field multiply: every RPX kernel from
/// `rpx_v<LIMB_PERMUTE_VARIANT>.cubin` (32-bit limb multiplies with carry
/// chains, `square_n` unrolled by four). Off: `rpx_v0.cubin`, the 64-bit
/// multiply. Both cubins are always built, so flipping this is one line.
pub const LIMB_PERMUTE_DEFAULT: bool = true;

pub const WARP_MERKLE_ENV: &str = "LAMBDA_VM_RPX_WARP_MERKLE";
pub const GRIND_QUEUE_ENV: &str = "LAMBDA_VM_RPX_GRIND_QUEUE";
pub const LIMB_PERMUTE_ENV: &str = "LAMBDA_VM_RPX_LIMB_PERMUTE";

/// Whether RPX Merkle walks take the half-warp levels and the one-block tail.
pub fn warp_merkle() -> bool {
    static ON: OnceLock<bool> = OnceLock::new();
    *ON.get_or_init(|| {
        read(
            WARP_MERKLE_ENV,
            WARP_MERKLE_DEFAULT,
            "RPX Merkle: a half-warp per parent up to 16384 pairs, then one 1024-thread tail block",
            "RPX Merkle: a thread per parent, then one 128-thread tail block",
        )
    })
}

/// Whether the RPX grind takes the work-queue kernel.
pub fn grind_queue() -> bool {
    static ON: OnceLock<bool> = OnceLock::new();
    *ON.get_or_init(|| {
        read(
            GRIND_QUEUE_ENV,
            GRIND_QUEUE_DEFAULT,
            "RPX grind: the work-queue kernel on a card-filling grid",
            "RPX grind: the stride kernel on LAMBDA_VM_GRIND_GRID blocks",
        )
    })
}

/// Whether the RPX module loads at [`LIMB_PERMUTE_VARIANT`] rather than at
/// variant 0. Read once, when the backend loads its modules.
pub fn limb_permute() -> bool {
    static ON: OnceLock<bool> = OnceLock::new();
    *ON.get_or_init(|| {
        read(
            LIMB_PERMUTE_ENV,
            LIMB_PERMUTE_DEFAULT,
            &format!(
                "RPX permutation: variant {LIMB_PERMUTE_VARIANT}, 32-bit limb multiplies, \
                 squarings unrolled by four (rpx_v{LIMB_PERMUTE_VARIANT}.cubin)"
            ),
            "RPX permutation: variant 0, the 64-bit multiply (rpx_v0.cubin)",
        )
    })
}

/// One switch resolved and printed: the variable if it is set, else the
/// default. A value the switch does not accept aborts. The WHIR retention's
/// switch (`whir::keep_futile`) reads through here too.
pub(crate) fn read(env: &str, default: bool, on: &str, off: &str) -> bool {
    let (value, source) = match std::env::var(env) {
        Err(VarError::NotPresent) => (default, "the pipeline default".to_string()),
        Ok(raw) => match parse(raw.trim()) {
            Some(value) => (value, format!("{env}={}", u8::from(value))),
            None => refuse(env, &format!("{raw:?}"), default),
        },
        Err(VarError::NotUnicode(raw)) => refuse(env, &format!("{raw:?}"), default),
    };
    eprintln!("[gpu] {} ({source})", if value { on } else { off });
    value
}

/// eprintln then abort, as the grind knobs do: a configuration error at
/// startup needs the accepted values, not a backtrace.
fn refuse(env: &str, raw: &str, default: bool) -> ! {
    eprintln!(
        "{env}={raw} is not a value this switch accepts. Accepted: 1 (on) or 0 (off); unset \
         is the pipeline default ({}).",
        u8::from(default)
    );
    std::process::abort()
}

/// `1` is on and `0` is off; anything else is refused.
fn parse(raw: &str) -> Option<bool> {
    match raw {
        "1" => Some(true),
        "0" => Some(false),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::{LIMB_PERMUTE_VARIANT, parse};

    #[test]
    fn a_switch_accepts_only_zero_and_one() {
        assert_eq!(parse("1"), Some(true));
        assert_eq!(parse("0"), Some(false));
        for raw in ["", "on", "off", "true", "2", "01", "yes", "-1", "+1"] {
            assert_eq!(parse(raw), None, "{raw:?} must be refused, not read");
        }
    }

    /// The variant the limb cubin is built at is the one the bench measured
    /// fastest (0.8128 of variant 0 per permutation on the 5090): limb
    /// multiply (1) plus `square_n` unrolled by four (4). Another variant is
    /// another measurement, not a rename.
    #[test]
    fn the_limb_permutation_is_variant_five() {
        assert_eq!(LIMB_PERMUTE_VARIANT, 5);
    }
}
