name = "ADD"

# Variables

[[variables.condition]]
name = "cond"
type = "BaseField"
desc = "Whether the relation should be enforced ($eq.not 0$) or not ($0$)."

[[variables.input]]
name = "lhs"
type = "DWordWL"
desc = "left-hand operator"

[[variables.input]]
name = "rhs"
type = "DWordWL"
desc = "right-hand operator"

[[variables.output]]
name = "sum"
type = "DWordWL"
desc = "$#`lhs` + #`rhs`$"

[[variables.virtual]]
name = "carry"
desc = "Carry values used to constrain the addition"
type = ["Bit", 4]
def = {idx="i", polys=[
    {range=0, poly=["*", ["^", 2, -32], ["-", ["+", ["idx", "lhs", 0], ["idx", "rhs", 0]], ["idx", "sum", 0]]]},
    {range=[1, 3], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", "lhs", "i"], ["idx", "rhs", "i"], ["idx", "carry", ["-", "i", 1]]], ["idx", "sum", "i"]]]},
]}


# Assumptions

[[assumptions]]
desc = "`IS_WORD[lhs[i]]`"
range = ["i", 0, 3]
ref = "add:a:lhs"

[[assumptions]]
desc = "`IS_WORD[rhs[i]]`"
range = ["i", 0, 3]
ref = "add:a:rhs"

[[assumptions]]
desc = "`IS_WORD[sum[i]]`"
range = ["i", 0, 3]
ref = "add:a:sum"

# Constraints

[[constraint_groups]]
name = "all"

[[constraints.all]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "carry", "i"]]
range = ["i", 0, 3]
cond = "cond"
ref = "add:c:carry"

