name = "BRANCH"


# Input

[[variables.input]]
name = "pc"
type = "DWordWL"
desc = "The current pc, used as base address when `!JALR`"
pad = 0

[[variables.input]]
name = "offset"
type = "DWordWL"
desc = "The offset from the base address to jump to"
pad = 0

[[variables.input]]
name = "register"
type = "DWordWL"
desc = "The base address to use when `JALR`"
pad = 0

[[variables.input]]
name = "JALR"
type = "Bit"
desc = "Selects between `pc` and `register` as base address, needed for the `JALR` instruction"
pad = 0


# Output

[[variables.output]]
name = "next_pc_high"
type = ["Half", 3]
desc = "The upper part of the next pc"
pad = ["arr", 0, 0, 0]

[[variables.output]]
name = "next_pc_low"
type = ["Byte", 2]
desc = "The lower part of the next pc"
pad = 0


# Auxiliary

[[variables.auxiliary]]
name = "unmasked_low_byte"
type = "Byte"
desc = "The low byte of the next pc, before masking the LSB. Used to constraint the raw addition."
pad = 0


# Virtual

[[variables.virtual]]
name = "next_pc_unmasked"
type = "DWordWL"
desc = "The combination of `next_pc_high`, `next_pc_low[1]` and `unmasked_low_byte` to constrain the addition. This is the computed value for the next pc, before masking off the LSB as required by the ISA."
def = {idx = "i", polys = [
  {iter = 0, poly = ["+", ["*", ["^", 2, 16], ["idx", "next_pc_high", 0]], ["*", ["^", 2, 8], ["idx", "next_pc_low", 1]], "unmasked_low_byte"]},
  {iter = 1, poly = ["+", ["*", ["^", 2, 16], ["idx", "next_pc_high", 2]], ["idx", "next_pc_high", 1]]},
]}

[[variables.virtual]]
name = "next_pc"
type = "DWordWL"
desc = "The computed next pc, after masking off the LSB as required by the ISA."
def = {idx = "i", polys = [
  {iter = 0, poly = ["+", ["*", ["^", 2, 16], ["idx", "next_pc_high", 0]], ["*", ["^", 2, 8], ["idx", "next_pc_low", 1]], ["idx", "next_pc_low", 0]]},
  {iter = 1, poly = ["+", ["*", ["^", 2, 16], ["idx", "next_pc_high", 2]], ["idx", "next_pc_high", 1]]},
]}


# Multiplicity

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""
pad = 0


[[assumptions]]
desc = "`pc` is range checked, `IS_WORD[pc[i]]`"
iter = ["i", 0, 1]

[[assumptions]]
desc = "`offset` is range checked, `IS_WORD[offset]`"

[[assumptions]]
desc = "`register` is range checked, `IS_WORD[register[i]]`"
iter = ["i", 0, 1]

[[assumptions]]
desc = "`IS_BIT<JALR>`"


[[constraint_groups]]
name = "assumptions"

[[constraints.assumptions]]
kind = "template"
tag = "IS_BIT"
input = ["JALR"]

[[constraint_groups]]
name = "all"

[[constraints.all]]
kind = "template"
tag = "ADD"
input = ["pc", ["cast", "offset", "DWordWL"]]
output = "next_pc_unmasked"
cond = ["not", "JALR"]

[[constraints.all]]
kind = "template"
tag = "ADD"
input = ["register", ["cast", "offset", "DWordWL"]]
output = "next_pc_unmasked"
cond = "JALR"

[[constraints.all]]
kind = "template"
tag = "IS_BYTE"
input = [["idx", "next_pc_low", 1]]
cond = "μ"

[[constraints.all]]
kind = "interaction"
tag = "BYTE_ALU"
input = [["opsel", "AND"], "unmasked_low_byte", 254]
output = ["idx", "next_pc_low", 0]
multiplicity = "μ"

[[constraints.all]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "next_pc_high", "i"]]
iter = ["i", 0, 2]
multiplicity = "μ"


[[constraint_groups]]
name = "output"
desc = "Each row contributes the following to the LogUp sum"

[[constraints.output]]
kind = "interaction"
tag = "BRANCH"
input = ["pc", "offset", "register", "JALR"]
output = "next_pc"
multiplicity = ["-", "μ"]
