name = "COMMIT"
code = "CMT"

# Variables

[[variables.input]]
name = "timestamp"
type = "Word"
desc = "timestamp at which to commit"
pad = 0

[[variables.auxiliary]]
name = "index"
type = "BaseField"
desc = "Index of the first value being committed by this sequence"
pad = 0

[[variables.auxiliary]]
name = "address"
type = "DWordWL"
desc = "Address of first byte to commit"
pad = 0

[[variables.auxiliary]]
name = "count"
type = "DWordWL"
desc = "number of bytes to commit"
pad = 0

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""
pad = 0

# Assumptions


# Constraints

[[constraint_groups]]
name = "incoming"

[[constraints.incoming]]
kind = "interaction"
tag = "ECALL"
input = ["timestamp", ["cast", 64, "DWordWL"]]
multiplicity = ["-", "μ"]
ref = "commit:c:receive_ecall"

[[constraint_groups]]
name = "read_input"

[[constraints.read_input]]
kind = "template"
tag = "REG"
input = [11, "address", "timestamp"]
output = "address"
cond = "μ"
ref = "commit:c:read_address"

[[constraints.read_input]]
kind = "template"
tag = "REG"
input = [12, "count", "timestamp"]
output = "count"
cond = "μ"
ref = "commit:c:read_count"

[[constraints.read_input]]
kind = "template"
tag = "REG"
input = [10, "count", "timestamp"]
output = ["cast", 1, "DWordWL"]
cond = "μ"
ref = "commit:c:read_fd_write_count"

[[constraints.read_input]]
kind = "template"
tag = "REG"
input = [254, ["arr", ["+", "index", ["cast", "count", "BaseField"]], 0], "timestamp"]
output = ["arr", "index", 0]
cond = "μ"
ref = "commit:c:read_index"

[[constraint_groups]]
name = "defer"

[[constraints.defer]]
kind = "interaction"
tag = "COMMIT_DEFER"
input = ["timestamp", "address", ["arr", "index", 0], "count"]
multiplicity = "μ"
ref = "commit:c:defer_to_memmove"

[[constraint_groups]]
name = "bits"

[[constraints.bits]]
kind = "template"
tag = "IS_BIT"
input = ["μ"]
ref = "commit:c:range_mu"
