[metadata]
version = 1

[[variables.types]]
label = "BaseField"
subtypes = ["BaseField"]
range = [0, "18446744069414584320"]
desc = "Variable that can assume any value in the base field."

[[variables.types]]
label = "Bit"
subtypes = ["BaseField"]
range = [0, 1]
desc = "Variable that can only assume values in the set ${0,1}$."

[[variables.types]]
label = "B4"
subtypes = ["BaseField"]
range = [0, 15]
desc = "Variable that can only assume values in the range $[0, 2^4)$."

[[variables.types]]
label = "Byte"
subtypes = ["BaseField"]
range = [0, 255]
desc = "Variable that can only assume values in the range $[0, 2^8)$."

[[variables.types]]
label = "Half"
subtypes = ["BaseField"]
range = [0, 65535]
desc = "Variable that can only assume values in the range $[0, 2^16)$."

[[variables.types]]
label = "B20"
subtypes = ["BaseField"]
range = [0, 1048575]
desc = "Variable that can only assume values in the range $[0, 2^20)$."

[[variables.types]]
label = "Word"
subtypes = ["BaseField"]
range = [0, 4294967295]
desc = "Variable that can only assume values in the range $[0, 2^32)$."

[[variables.types]]
label = "B51"
subtypes = ["BaseField"]
range = [0, 2251799813685247]
desc = "Variable that can only assume values in the range $[0, 2^51)$."

[[variables.types]]
label = "DWordBL"
subtypes = ["Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as an array of eight `Byte` variables.\
       """

[[variables.types]]
label = "DWordHL"
subtypes = ["Half", "Half", "Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as an array of four `Half` variables.\
       """

[[variables.types]]
label = "DWordWL"
subtypes = ["Word", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as an array of two `Word` variables.\
       """

[[variables.types]]
label = "DWordHHW"
subtypes = ["Word", "Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as a `Word` and two `Half` variables. \
       The `Word` is the *least* significant digit.
       """

[[variables.types]]
label = "DWordWHH"
subtypes = ["Half", "Half", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as a `Word` and two `Half` variables. \
       The `Word` is the *most* significant digit.
       """

[[variables.types]]
label = "DWordWHBB"
subtypes = ["Byte", "Byte", "Half", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as a `Word`, a `Half` and two `Byte` variables. \
       The `Word` is the *most* significant digit.
       """

[[variables.types]]
label = "WordBL"
subtypes = ["Byte", "Byte", "Byte", "Byte"]
desc = """\
       Variable that can only assume values in the range $[0, 2^32)$. \\
       Represented as an array of four `Byte` variables.\
       """

[[variables.types]]
label = "WordHL"
subtypes = ["Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^32)$. \\
       Represented as an array of two `Half` variables.\
       """

[[variables.types]]
label = "QuadHL"
subtypes = ["Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^128)$. \\
       Represented as an array of eight `Half` variables.\
       """

[[variables.types]]
label = "QuadWL"
subtypes = ["Word", "Word", "Word", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^128)$. \\
       Represented as an array of four `Word` variables.\
       """

[[variables.types]]
label = "U256BL"
subtypes = ["Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte"]
desc = """\
       Variable that can only assume values in the range $[0, 2^256)$. \\
       Represented as an array of thirty-two `Byte` variables.\
       """

[[variables.types]]
label = "U256HL"
subtypes = ["Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^256)$. \\
       Represented as an array of sixteen `Half` variables.\
       """

[[variables.types]]
label = "U256WL"
subtypes = ["Word", "Word", "Word", "Word", "Word", "Word", "Word", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^256)$. \\
       Represented as an array of eight `Word` variables.\
       """

[[variables.types]]
label = "U512BL"
subtypes = ["Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte"]
desc = """\
       Variable that can only assume values in the range $[0, 2^512)$. \\
       Represented as an array of sixty-four `Byte` variables.\
       """

[[variables.types]]
label = "Timestamp"
subtypes = ["Word"]
desc = "A preprocessed column holding timestamps as `Word`. Row `i` of the column contains the value $2^2 dot (i + 1)$. Used in the CPU chip (@cpu), see there for more details about the magic number."
preprocessed = true

[[variables.types]]
label = "RowIndex"
subtypes = ["Word"]
desc = "A preprocessed column holding the row index (zero-indexed)."
preprocessed = true

[variables.categories]
all = ["constant", "input", "output", "auxiliary", "virtual", "multiplicity", "condition"]
instantiated = ["input", "output", "auxiliary", "multiplicity"]
