[metadata]
version = 1

[[variables.types]]
label = "BaseField"
subtypes = ["BaseField"]
desc = "Variable that can assume any value in the base field."

[[variables.types]]
label = "Bit"
subtypes = ["BaseField"]
desc = "Variable that can only assume values in the set ${0,1}$."

[[variables.types]]
label = "B4"
subtypes = ["BaseField"]
desc = "Variable that can only assume values in the range $[0, 2^4)$."

[[variables.types]]
label = "Byte"
subtypes = ["BaseField"]
count = 1
desc = "Variable that can only assume values in the range $[0, 2^8)$."

[[variables.types]]
label = "Half"
subtypes = ["BaseField"]
desc = "Variable that can only assume values in the range $[0, 2^16)$."

[[variables.types]]
label = "B20"
subtypes = ["BaseField"]
desc = "Variable that can only assume values in the range $[0, 2^20)$."

[[variables.types]]
label = "Word"
subtypes = ["BaseField"]
desc = "Variable that can only assume values in the range $[0, 2^32)$."

[[variables.types]]
label = "WordHL"
subtypes = ["Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^32)$. \\
       Represented as an array of two `Half` variables.\
       """

[[variables.types]]
label = "WordBL"
subtypes = ["Byte", "Byte", "Byte", "Byte"]
desc = """\
       Variable that can only assume values in the range $[0, 2^32)$. \\
       Represented as an array of four `Byte` variables.\
       """

[[variables.types]]
label = "B35"
subtypes = ["BaseField"]
desc = "Variable that can only assume values in the range $[0, 2^35)$."

[[variables.types]]
label = "B51"
subtypes = ["BaseField"]
desc = "Variable that can only assume values in the range $[0, 2^51)$."

[[variables.types]]
label = "DWordBL"
subtypes = ["Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte", "Byte"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as an array of eight `Byte` variables.\
       """

[[variables.types]]
label = "DWordHL"
subtypes = ["Half", "Half", "Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as an array of four `Half` variables.\
       """

[[variables.types]]
label = "DWordWL"
subtypes = ["Word", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as an array of two `Word` variables.\
       """

[[variables.types]]
label = "DWordHHW"
subtypes = ["Word", "Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as a `Word` and two `Half` variables.\
       The `Word` is the *least* significant digit.
       """

[[variables.types]]
label = "QuadHL"
subtypes = ["Half", "Half", "Half", "Half", "Half", "Half", "Half", "Half"]
desc = """\
       Variable that can only assume values in the range $[0, 2^128)$. \\
       Represented as an array of eight `Half` variables.\
       """

[[variables.types]]
label = "QuadWL"
subtypes = ["Word", "Word", "Word", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^128)$. \\
       Represented as an array of four `Word` variables.\
       """

[[variables.types]]
label = "DWordWHH"
subtypes = ["Half", "Half", "Word"]
desc = """\
       Variable that can only assume values in the range $[0, 2^64)$. \\
       Represented as a `Word` and two `Half` variables.\
       The `Word` is the *most* significant digit.
       """

[[variables.types]]
label = "Timestamp"
subtypes = ["DWordWL"]
desc = "A preprocessed column holding timestamps as `DWordWL`. Row `i` of the column contains the value $2^2 dot (i + 1)$. Used in the CPU chip, see there for more details about the magic number."

[variables.categories]
all = ["input", "output", "auxiliary", "virtual", "multiplicity", "condition"]
instantiated = ["input", "output", "auxiliary", "multiplicity"]
