name = "CPU"


# Input
# Let's call the variables coming from DECODE input

[[variables.input]]
name = "timestamp"
type = "Timestamp"
desc = "A preprocessed timestamp to coordinate the memory argument. Since we have at most 3 non-disjoint memory accesses (`(rs1, rs2, rd)`, `(rs1, pc, pc)`, `MEMORY`) a maximum of 4 slots is enough."

[[variables.input]]
name = "pc"
type = "DWordWL"
desc = "The program counter"
pad = 1

[[variables.input]]
name = "rs1"
type = "Byte"
desc = "Source register 1 index"
pad = 0

[[variables.input]]
name = "rs2"
type = "Byte"
desc = "Source register 2 index"
pad = 0

[[variables.input]]
name = "rd"
type = "Byte"
desc = "Destination register index"
pad = 0

[[variables.input]]
name = "read_register1"
type = "Bit"
desc = "Whether to read from `rs1` (1) or to place a 0 in `rv1` (0)"
pad = 0

[[variables.input]]
name = "read_register2"
type = "Bit"
desc = "Whether to read from `rs2` (1) or to place a 0 in `rv2` (0)"
pad = 0

[[variables.input]]
name = "write_register"
type = "Bit"
desc = "Whether to write back to the destination register"
pad = 0

[[variables.input]]
name = "imm"
type = "DWordWL"
desc = "The fully extended 64-bit version of the immediate"
pad = 0

# We encode C-type instructions with a length of 2, as this generality allows fusing common instruction combos
[[variables.input]]
name = "half_instruction_length"
type = "Byte"
desc = "Half the number of bytes consumed by this instruction, commonly used to indicate whether the instruction is of C type, i.e., whether it is 2 bytes long (= 1) instead of 4 (= 2)"
pad = 2

[[variables.input]]
name = "word_instr"
type = "Bit"
desc = "Whether the instruction is a \\*W instruction, requiring the inputs and outputs to be (sign) extended"
pad = 0

[[variables.input]]
name = "ALU"
type = "Bit"
desc = "Whether to use the ALU for this instruction"
pad = 0

[[variables.input]]
name = "alu_flags"
type = "Byte"
desc = "The ALU operation + flags (interpreting things as signed/unsigned, choosing the MUL/DVRM output, ...) to pass to the ALU"
pad = 0

[[variables.input]]
name = "ADD"
type = "Bit"
desc = "Addition fast-path bypassing the ALU"
pad = 0

[[variables.input]]
name = "SUB"
type = "Bit"
desc = "Subtraction fast-path bypassing the ALU"
pad = 0

[[variables.input]]
name = "MEMORY"
type = "Bit"
desc = "Whether this instruction touches memory (LOAD/STORE)"
pad = 0

[[variables.input]]
name = "mem_flags"
type = "Byte"
desc = "The flags to pass for MEMORY operations (LOAD vs STORE, number of bytes touched, signed)"
pad = 0

[[variables.input]]
name = "BRANCH"
type = "Bit"
desc = "Whether this instruction is a conditional branch (BLT, BEQ)"
pad = 0

[[variables.input]]
name = "ECALL"
type = "Bit"
desc = "Whether this instruction is an ECALL"
pad = 0

# Output
[[variables.output]]
name = "next_pc"
type = "DWordWL"
desc = "The program counter for the next instruction"
pad = 1

[[variables.output]]
name = "rvd"
type = "DWordWL"
desc = "The value to (maybe) be written back to rvd"
pad = 0

# Auxiliary
[[variables.auxiliary]]
name = "prev_pc_timestamp_borrow"
type = "Bit"
desc = "The borrow bit for computing the previous timestamp the PC was accessed"
pad = 0

[[variables.auxiliary]]
name = "pc_double_read"
type = "Bit"
desc = "Whether the PC is being read as a general purpose register (`rs1`) this cycle"
pad = 0

[[variables.auxiliary]]
name = "rv1"
type = "DWordWL"
desc = "The value of register `rs1`"
pad = 0

[[variables.auxiliary]]
name = "rv2"
type = "DWordWL"
desc = "The value of register `rs2`"
pad = 0

[[variables.auxiliary]]
name = "arg2"
type = "DWordWL"
desc = "A multiplexed version of `rv2` and `imm`, to be used as second argument to ALU calls"
pad = 0

[[variables.auxiliary]]
name = "res"
type = "DWordHL"
desc = "The ALU result"
pad = 0

[[variables.auxiliary]]
name = "branch_cond"
type = "Bit"
desc = "Whether a branch is taken: the branch condition evaluates to true, or we are doing an unconditional jump"
pad = 0

# Virtual
[[variables.virtual]]
name = "JALR"
type = "Bit"
desc = "Read whether our BRANCH corresponds to a JAL(R) instruction from `mem_flags`, as `MEMORY` and `BRANCH` are mutually exclusive"
def = "mem_flags"

[[variables.virtual]]
name = "packed_decode"
type = "BaseField"
desc = "A packed representation of all bit flags and register indices obtained from the decoding"
def = ["+",
    ["*", ["^", 2, 0], "read_register1"],
    ["*", ["^", 2, 1], "read_register2"],
    ["*", ["^", 2, 2], "write_register"],
    ["*", ["^", 2, 3], "word_instr"],
    ["*", ["^", 2, 4], "ALU"],
    ["*", ["^", 2, 5], "ADD"],
    ["*", ["^", 2, 6], "SUB"],
    ["*", ["^", 2, 7], "MEMORY"],
    ["*", ["^", 2, 8], "BRANCH"],
    ["*", ["^", 2, 9], "ECALL"],
    ["*", ["^", 2, 10], "rs1"],
    ["*", ["^", 2, 18], "rs2"],
    ["*", ["^", 2, 26], "rd"],
    ["*", ["^", 2, 34], "half_instruction_length"],
    ["*", ["^", 2, 42], "alu_flags"],
    ["*", ["^", 2, 50], "mem_flags"],
]


[[assumptions]]
desc = "`MEMORY` and `BRANCH` are mutually exclusive"
ref = "cpu:a:mem-branch-mutex"

[[assumptions]]
desc = "When `MEMORY + BRANCH = 0`, either `read_register2 = 0` or `imm = 0` should be enforced by the decoding. This is needed for `arg2`."
ref = "cpu:a:arg2-multiplex"

[[assumptions]]
desc = "$#`!MEMORY` => #`IS_BIT<mem_flags>`$"

[[constraint_groups]]
name = "assumptions"

[[constraints.assumptions]]
kind = "arith"
constraint = "$not (#`MEMORY` and #`BRANCH`)$"
poly = ["*", "MEMORY", "BRANCH"]

[[constraints.assumptions]]
kind = "arith"
constraint = "$(1 - #`MEMORY` - #`BRANCH`) => (#`read_register2` = 0 or #`imm[i]` = 0)$"
poly = ["*", ["-", 1, "MEMORY", "BRANCH"], "read_register2", ["+", ["idx", "imm", 0], ["idx", "imm", 1]]]

[[constraints.assumptions]]
kind = "template"
tag = "IS_BIT"
input = ["mem_flags"]
cond = ["not", "MEMORY"]


[[constraint_groups]]
name = "decode"

[[constraints.decode]]
kind = "interaction"
tag = "DECODE"
input = ["pc", "imm", "packed_decode"]
multiplicity = ["not", "word_instr"]

[[constraints.decode]]
kind = "arith"
constraint = "$#`word_instr` => #`MEMORY = 0`$"
poly = ["*", "word_instr", "MEMORY"]

[[constraints.decode]]
kind = "arith"
constraint = "$#`word_instr` => #`BRANCH = 0`$"
poly = ["*", "word_instr", "BRANCH"]

[[constraints.decode]]
kind = "arith"
constraint = "$#`word_instr` => #`ECALL = 0`$"
poly = ["*", "word_instr", "ECALL"]

[[constraints.decode]]
kind = "arith"
constraint = "$#`word_instr` => #`read_register1 = 0`$"
poly = ["*", "word_instr", "read_register1"]

[[constraints.decode]]
kind = "arith"
constraint = "$#`word_instr` => #`read_register2 = 0`$"
poly = ["*", "word_instr", "read_register2"]

[[constraints.decode]]
kind = "arith"
constraint = "$#`word_instr` => #`write_register = 0`$"
poly = ["*", "word_instr", "write_register"]

[[constraints.decode]]
kind = "interaction"
tag = "CPU32"
input = ["timestamp", "pc"]
output = "half_instruction_length"
multiplicity = "word_instr"


[[constraint_groups]]
name = "range"
prefix = "R"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["read_register1"]
ref = "cpu:c:range_read_register1"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["read_register2"]
ref = "cpu:c:range_read_register2"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["write_register"]
ref = "cpu:c:range_write_register"

[[constraints.range]]
kind = "template"
tag = "IS_BYTE"
input = ["half_instruction_length"]
ref = "cpu:c:range_c_type_instruction"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["word_instr"]
ref = "cpu:c:range_word_instr"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["ALU"]
ref = "cpu:c:range_ALU"

[[constraints.range]]
kind = "template"
tag = "IS_BYTE"
input = ["alu_flags"]
ref = "cpu:c:range_alu_flags"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["ADD"]
ref = "cpu:c:range_ADD"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["SUB"]
ref = "cpu:c:range_SUB"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["MEMORY"]
ref = "cpu:c:range_MEMORY"

[[constraints.range]]
kind = "template"
tag = "IS_BYTE"
input = ["mem_flags"]
ref = "cpu:c:range_mem_flags"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["BRANCH"]
ref = "cpu:c:range_BRANCH"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["ECALL"]
ref = "cpu:c:range_ECALL"

[[constraints.range]]
kind = "template"
tag = "IS_BYTE"
input = ["rs1"]

[[constraints.range]]
kind = "template"
tag = "IS_BYTE"
input = ["rs2"]

[[constraints.range]]
kind = "template"
tag = "IS_BYTE"
input = ["rd"]

[[constraints.range]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "res", "i"]]
multiplicity = 1
iter = ["i", 0, 3]


[[constraint_groups]]
name = "alu"
prefix = "A"

[[constraints.alu]]
kind = "arith"
constraint = "$#`arg2` = #`MEMORY` dot #`imm` + #`BRANCH` dot #`rv2` + (1 - #`MEMORY` - #`BRANCH`) dot (#`rv2` + #`imm`)$"
poly = ["-", ["idx", "arg2", "i"],
    ["*", "MEMORY", ["idx", "imm", "i"]],
    ["*", "BRANCH", ["idx", "rv2", "i"]],
    ["*", ["-", 1, "MEMORY", "BRANCH"], ["idx", ["+", "rv2", "imm"], "i"]]
]
iter = ["i", 0, 1]

[[constraints.alu]]
kind = "template"
tag = "ADD"
cond = "ADD"
input = ["rv1", "arg2"]
output = ["cast", "res", "DWordWL"]

[[constraints.alu]]
kind = "template"
tag = "SUB"
cond = "SUB"
input = ["rv1", "arg2"]
output = ["cast", "res", "DWordWL"]
ref = "cpu:c:sub"

[[constraints.alu]]
kind = "interaction"
tag = "ALU"
input = ["rv1", "arg2", "alu_flags"]
output = ["cast", "res", "DWordWL"]
multiplicity = "ALU"


[[constraint_groups]]
name = "mem"
prefix = "M"

[[constraints.mem]]
kind = "interaction"
tag = "MEMW"
input = [1, ["*", ["cast", 2, "DWordWL"], "rs1"], ["arr", ["idx", "rv1", 0], ["idx", "rv1", 1], 0, 0, 0, 0, 0, 0], ["+", "timestamp", ["cast", 0, "DWordWL"]], 1, 0, 0]
output = ["arr", ["idx", "rv1", 0], ["idx", "rv1", 1], 0, 0, 0, 0, 0, 0]
multiplicity = "read_register1"
ref = "cpu:c:read_rv1"

[[constraints.mem]]
kind = "arith"
constraint = "$#`!read_register1` => #`rv1[i]` = 0$"
poly = ["*", ["not", "read_register1"], ["idx", "rv1", "i"]]
iter = ["i", 0, 1]

[[constraints.mem]]
kind = "interaction"
tag = "MEMW"
input = [1, ["*", ["cast", 2, "DWordWL"], "rs2"], ["arr", ["idx", "rv2", 0], ["idx", "rv2", 1], 0, 0, 0, 0, 0, 0], ["+", "timestamp", ["cast", 1, "DWordWL"]], 1, 0, 0]
output = ["arr", ["idx", "rv2", 0], ["idx", "rv2", 1], 0, 0, 0, 0, 0, 0]
multiplicity = "read_register2"

[[constraints.mem]]
kind = "arith"
constraint = "$#`!read_register2` => #`rv2[i]` = 0$"
poly = ["*", ["not", "read_register2"], ["idx", "rv2", "i"]]
iter = ["i", 0, 1]

[[constraints.mem]]
kind = "interaction"
tag = "MEMW"
input = [1, ["*", ["cast", 2, "DWordWL"], "rd"], ["arr", ["idx", "rvd", 0], ["idx", "rvd", 1], 0, 0, 0, 0, 0, 0], ["+", "timestamp", ["cast", 2, "DWordWL"]], 1, 0, 0]
multiplicity = "write_register"

[[constraints.mem]]
kind = "interaction"
tag = "MEMOP"
input = ["timestamp", ["cast", "res", "DWordWL"], "rv2", "mem_flags"]
output = "rvd"
multiplicity = "MEMORY"

[[constraints.mem]]
kind = "arith"
constraint = "$#`!MEMORY` and #`!BRANCH` => #`rvd` = #`res`$"
poly = ["*", ["-", 1, "MEMORY", "BRANCH"], ["-", ["idx", "rvd", "i"], ["idx", ["cast", "res", "DWordWL"], "i"]]]
iter = ["i", 0, 1]

[[constraints.mem]]
kind = "template"
tag = "IS_BIT"
input = ["pc_double_read"]

[[constraints.mem]]
kind = "template"
tag = "IS_BIT"
input = ["prev_pc_timestamp_borrow"]

[[constraints.mem]]
kind = "interaction"
tag = "memory"
input = [1, ["arr", ["+", ["*", 2, 255], "i"], 0], ["arr", ["+", ["-", ["idx", "timestamp", 0], ["*", 3, ["not", "pc_double_read"]]], ["*", ["^", 2, 32], "prev_pc_timestamp_borrow"]], ["-", ["idx", "timestamp", 1], "prev_pc_timestamp_borrow"]], ["idx", "pc", "i"]]
iter = ["i", 0, 1]
multiplicity = 1

[[constraints.mem]]
kind = "interaction"
tag = "memory"
input = [1, ["arr", ["+", ["*", 2, 255], "i"], 0], ["+", "timestamp", ["cast", 1, "DWordWL"]], ["idx", "next_pc", "i"]]
iter = ["i", 0, 1]
multiplicity = -1

[[constraint_groups]]
name = "branch"
prefix = "B"

[[constraints.branch]]
kind = "arith"
constraint = "$#`branch_cond` = #`BRANCH` and (#`JALR` or #`res`)$"
poly = ["-",
        "branch_cond",
        ["*", "BRANCH", "JALR"],
        ["*", "BRANCH", ["-", 1, "JALR"], ["idx", "res", 0]]
    ]

[[constraints.branch]]
kind = "interaction"
tag = "BRANCH"
input = ["pc", "imm", "rv1", "JALR"]
output = "next_pc"
multiplicity = "branch_cond"

[[constraints.branch]]
kind = "template"
tag = "ADD"
input = ["pc", ["arr", ["*", 2, "half_instruction_length"], 0]]
output = "next_pc"
cond = ["not", "branch_cond"]
desc = "Increment `pc` to `next_pc` if we're not branching"

[[constraints.branch]]
kind = "template"
tag = "ADD"
input = ["pc", ["arr", ["*", 2, "half_instruction_length"], 0]]
output = "rvd"
cond = "BRANCH"
desc = "Compute the next instruction address in `rvd` when BRANCH is active to enable JALR"


[[constraint_groups]]
name = "sys"
prefix = "S"

[[constraints.sys]]
kind = "interaction"
tag = "ECALL"
input = ["timestamp", "rv1"]
multiplicity = "ECALL"
