name = "DECODE"

[[variables.output]]
name = "pc"
type = "DWordWL"
desc = "value of the program counter this instruction is associated with."
pad = 1

[[variables.output]]
name = "packed_decode"
type = "BaseField"
desc = """Ordered concatenation of several small variables.
The `decode (uncompressed)` section explains the purpose of each variable.\\
A list of each variable and the bit(-range) in which it is located:\\
[0] `read_register1`, \\
[1] `read_register2`, \\
[2] `write_register`, \\
[3] `word_instr`, \\
[4] `ALU`, \\
[5] `ADD`, \\
[6] `SUB`, \\
[7] `MEMORY`, \\
[8] `BRANCH`, \\
[9] `ECALL`, \\
[10:17] `rs1`, \\
[18:25] `rs2`, \\
[26:33] `rd`, \\
[34:41] `half_instruction_length`, \\
[42:49] `alu_flags`, \\
[50:57] `mem_flags`, \\
the remaining bits are set to zero.
"""
pad = 0

[[variables.output]]
name = "imm"
type = "DWordWL"
desc = "the *fully extended (!)* 64-bit version of the immediate."
pad = 0

[[variables.multiplicity]]
name = "μ"
type = "BaseField"
desc = "The multiplicity with which this instruction is looked up in the `CPU` table."
pad = 0
