name = "DECODE"

[[variables.output]]
name = "pc"
type = "DWordWL"
desc = "value of the program counter this instruction is associated with."
pad = 0

[[variables.output]]
name = "packed_decode"
type = "BaseField"
desc = """Ordered concatenation of several small variables.
The `decode (uncompressed)` section explains the purpose of each variable.\\
A list of each variable and the bit(-range) in which it is located:\\
[0] `write_register`, \\
[1] `memory_2bytes`, \\
[2] `memory_4bytes`, \\
[3] `memory_8bytes`, \\
[4] `c_type`, \\
[5] `signed`, \\
[6] `mp_selector`, \\
[7] `muldiv_selector`, \\
[8] `word_instr`, \\
[9] `ADD`, \\
[10] `SUB`, \\
[11] `SLT`, \\
[12] `AND`, \\
[13] `OR`, \\
[14] `XOR`, \\
[15] `SHIFT`, \\
[16] `JALR`, \\
[17] `BEQ`, \\
[18] `BLT`, \\
[19] `LOAD`, \\
[20] `STORE`, \\
[21] `MUL`, \\
[22] `DIVREM`, \\
[23] `ECALL`, \\
[24] `EBREAK`; \\
[25:33] `rs1`, \\
[33:41] `rs2`, \\
[41:49] `rd`, \\
the remaining bits are set to zero.
"""
pad = ["^", 2, 24]

[[variables.output]]
name = "imm"
type = "DWordWL"
desc = "the *fully extended (!)* 64-bit version of the immediate."
pad = 0

[[variables.multiplicity]]
name = "μ"
type = "BaseField"
desc = "The multiplicity with which this instruction is looked up in the `CPU` table."
pad = 0
