name = "DVRM"

# Input

[[variables.input]]
name = "n"
type = "DWordHL"
desc = "The numerator"
pad = 0

[[variables.input]]
name = "d"
type = "DWordHL"
desc = "The denominator"
pad = 0

[[variables.input]]
name = "signed"
type = "Bit"
desc = "Whether to interpret the input as signed (1) or unsigned (0) integers."
pad = 0


# Output

[[variables.output]]
name = "q"
type = "DWordHL"
desc = "The quotient; $#`n` / #`d`$ rounded towards zero."
pad = 0

[[variables.output]]
name = "r"
type = "DWordHL"
desc = "The remainder; $#`n` - #`q` #`d`$."
pad = 0

# Auxiliary

[[variables.auxiliary]]
name = "div_by_zero"
type = "Bit"
desc = "Whether $#`d`=0$."
pad = 1

[[variables.auxiliary]]
name = "overflow"
type = "Bit"
desc = "Whether $#`n` = -2^63$ and $#`d`=-1$."
pad = 0

[[variables.auxiliary]]
name = "abs_r"
type = "DWordWL"
desc = "Absolute value of `r`."
pad = 0

[[variables.auxiliary]]
name = "abs_d"
type = "DWordWL"
desc = "Absolute value of `d`."
pad = 0

[[variables.auxiliary]]
name = "n_sub_r"
type = "DWordHL"
desc = "$#`n`-#`r`$."
pad = 0

[[variables.auxiliary]]
name = "sign_n_sub_r"
type = "Bit"
desc = "Sign of `n_sub_r`."
pad = 0

[[variables.auxiliary]]
name = "sign_n"
type = "Bit"
desc = "Sign of `n`."
pad = 0

[[variables.auxiliary]]
name = "sign_d"
type = "Bit"
desc = "Sign of `d`."
pad = 0

[[variables.auxiliary]]
name = "sign_q"
type = "Bit"
desc = "Sign of `q`."
pad = 0

[[variables.auxiliary]]
name = "sign_r"
type = "Bit"
desc = "Sign of `r`."
pad = 0

# Virtual

[[variables.virtual]]
name = "extended_n"
type = "QuadHL"
desc = "sign-extended value of `n`."
def = {idx="i", polys = [
  {iter=[0, 3], poly=["idx", "n", "i"]},
  {iter=[4, 7], poly=["*", 0xFFFF, "sign_n"]}
]}

[[variables.virtual]]
name = "extended_r"
type = "QuadHL"
desc = "sign-extended value of `r`."
def = {idx="i", polys = [
  {iter=[0, 3], poly=["idx", "r", "i"]},
  {iter=[4, 7], poly=["*", 0xFFFF, "sign_r"]}
]}

[[variables.virtual]]
name = "extension_n_sub_r"
type = "DWordHL"
desc = "sign-extension limbs of `n_sub_r`."
def = {idx="i", iter=[0, 3], poly=["*", 0xFFFF, "sign_n_sub_r"]}

[[variables.virtual]]
name = "extended_n_sub_r"
type = "QuadHL"
desc = "sign-extended value of `n_sub_r`."
def = {idx="i", polys = [
  {iter=[0, 3], poly=["idx", "n_sub_r", "i"]},
  {iter=[4, 7], poly=["idx", "extension_n_sub_r", ["-", "i", 4]]}
]}

[[variables.virtual]]
name = "carry"
type = ["Bit", 4]
desc = "carries for adding `extended_n_sub_r` to `extended_r`, forming `extended_n`."
def = {idx="i", polys = [
    {iter=0, poly=["*", 
        ["^", 2, -32], 
        ["-", 
            ["+", 
                ["idx", ["cast", "extended_n_sub_r", "QuadWL"], "i"], 
                ["idx", ["cast", "extended_r", "QuadWL"], "i"]
            ], 
            ["idx", ["cast", "extended_n", "QuadWL"], "i"]
        ]
    ]},
    {iter=[1, 3], poly=["*", 
        ["^", 2, -32], 
        ["-", 
            ["+", 
                ["idx", ["cast", "extended_n_sub_r", "QuadWL"], "i"], 
                ["idx", ["cast", "extended_r", "QuadWL"], "i"],
                ["idx", "carry", ["-", "i", 1]],
            ], 
            ["idx", ["cast", "extended_n", "QuadWL"], "i"]
        ]
    ]},
]}

[[variables.virtual]]
name = "μ_sum"
type = "BaseField"
desc = "sum of multiplicities"
def = ["+", "μ_q", "μ_r"]


# Multiplicities

[[variables.multiplicity]]
name = "μ_q"
type = "BaseField"
desc = ""
pad = 0

[[variables.multiplicity]]
name = "μ_r"
type = "BaseField"
desc = ""
pad = 0


# Constraints

[[constraint_groups]]
name = "range"

[[constraints.range]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "n", "i"]]
iter = ["i", 0, 3]
multiplicity = "μ_sum"
ref = "lt:c:range_n"

[[constraints.range]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "d", "i"]]
iter = ["i", 0, 3]
multiplicity = "μ_sum"
ref = "lt:c:range_d"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["signed"]
ref = "lt:c:range_signed"

[[constraint_groups]]
name = "sign_equality"

[[constraints.sign_equality]]
kind = "arith"
constraint = "$#`r` eq.not 0 => #`sign_r` = #`sign_n`$"
poly = ["*", ["sum", ["=", "i", 0], 3, ["idx", "r", "i"]], ["-", "sign_r", "sign_n"]]
ref = "dvrm:c:sign_r_equals_sign_n"

[[constraint_groups]]
name = "abs_diff"

[[constraints.abs_diff]]
kind = "interaction"
tag = "ALU"
input = ["abs_r", "abs_d", ["opsel", "LT"]]
output = ["arr", ["not", "div_by_zero"], 0]
multiplicity = "μ_sum"
ref ="dvrm:c:abs_r_lt_abs_d"

[[constraints.abs_diff]]
kind = "template"
tag = "NEG"
input = ["r"]
output = "abs_r"
cond = "sign_r"
ref = "dvrm:c:abs_r_if_negative"

[[constraints.abs_diff]]
kind = "arith"
constraint = "$not#`sign_r` => #`abs_r` = #`r`$"
poly = ["*", ["not", "sign_r"], ["-", ["idx", "abs_r", "i"], ["idx", ["cast", "r", "DWordWL"], "i"]]]
iter = ["i", 0, 1]
ref = "dvrm:c:abs_r_if_nonnegative"

[[constraints.abs_diff]]
kind = "template"
tag = "NEG"
input = ["d"]
output = "abs_d"
cond = "sign_d"
ref = "dvrm:c:abs_d_if_negative"

[[constraints.abs_diff]]
kind = "arith"
constraint = "$not#`sign_d` => #`abs_d` = #`d`$"
iter = ["i", 0, 1]
poly = ["*", ["not", "sign_d"], ["-", ["idx", "abs_d", "i"], ["idx", ["cast", "d", "DWordWL"], "i"]]]
ref = "dvrm:c:abs_d_if_nonnegative"

[[constraint_groups]]
name = "overflow"

[[constraints.overflow]]
kind = "arith"
constraint = "$#`sign_q` = #`signed` dot (1- #`overflow`)$"
poly = ["-", ["*", "signed", ["-", 1, "overflow"]], "sign_q"]
ref = "dvrm:c:sign_q"

[[constraints.overflow]]
kind = "interaction"
tag = "ZERO"
input = [["+", ["idx", "n", 0], ["idx", "n", 1], ["idx", "n", 2], ["-", ["idx", "n", 3], ["*", ["^", 2, 15], "sign_n"]], ["-", 1, "sign_n"], ["-", 65535, ["idx", "d", 0]], ["-", 65535, ["idx", "d", 1]], ["-", 65535, ["idx", "d", 2]], ["-", 65535, ["idx", "d", 3]]]]
output = "overflow"
multiplicity = "μ_sum"
ref = "dvrm:c:overflow"

[[constraint_groups]]
name = "n_sub_r"

[[constraints.n_sub_r]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "carry", "i"]]
iter = ["i", 0, 3]
ref = "dvrm:c:n_sub_r"

[[constraints.n_sub_r]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "r", "i"]]
iter = ["i", 0, 3]
multiplicity = "μ_sum"
ref = "dvrm:c:r_range"

[[constraints.n_sub_r]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "n_sub_r", "i"]]
iter = ["i", 0, 3]
multiplicity = "μ_sum"
ref = "dvrm:c:n_sub_r_range"

[[constraints.n_sub_r]]
kind = "template"
tag = "IS_BIT"
input = ["sign_n_sub_r"]
ref = "dvrm:c:sign_n_sub_r_is_bit"

[[constraint_groups]]
name = "equality"

[[constraints.equality]]
kind = "interaction"
tag = "ALU"
input = [["cast", "d", "DWordWL"], ["cast", "q", "DWordWL"], ["+", ["opsel", "MUL"], ["*", 32, "signed"], ["*", 64, "sign_q"]]]
output = ["cast", "n_sub_r", "DWordWL"]
multiplicity = "μ_sum"
ref = "dvrm:c:mul_lower"

[[constraints.equality]]
kind = "interaction"
tag = "ALU"
input = [["cast", "d", "DWordWL"], ["cast", "q", "DWordWL"], ["+", ["opsel", "MUL"], ["*", 32, "signed"], ["*", 64, "sign_q"], 128]]
output = ["cast", "extension_n_sub_r", "DWordWL"]
multiplicity = "μ_sum"
ref = "dvrm:c:mul_upper"

[[constraints.equality]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "q", "i"]]
iter = ["i", 0, 3]
multiplicity = "μ_sum"
ref = "dvrm:c:q_range"


[[constraint_groups]]
name = "defs"

[[constraints.defs]]
kind = "template"
tag = "SIGN"
input = [["idx", "n", 3], "signed"]
output = "sign_n"
ref = "dvrm:c:sign_n"

[[constraints.defs]]
kind = "template"
tag = "SIGN"
input = [["idx", "r", 3], "signed"]
output = "sign_r"
ref = "dvrm:c:sign_r"

[[constraints.defs]]
kind = "template"
tag = "SIGN"
input = [["idx", "d", 3], "signed"]
output = "sign_d"
ref = "dvrm:c:sign_d"

[[constraint_groups]]
name = "div_by_zero"

[[constraints.div_by_zero]]
kind = "arith"
iter = ["i", 0, 3]
constraint = "$#`div_by_zero` => #`q[i]` = 65535$"
poly = ["*", "div_by_zero", ["-", ["idx", "q", "i"], 65535]]
ref = "dvrm:c:q_if_div_by_zero"

[[constraints.div_by_zero]]
kind = "interaction"
tag = "ZERO"
input = [["+", ["idx", "d", 0], ["idx", "d", 1], ["idx", "d", 2], ["idx", "d", 3]]]
output = "div_by_zero"
ref = "dvrm:c:div_by_zero"
multiplicity = "μ_sum"

[[constraint_groups]]
name = "output"
desc = "Each row contributes the following to the LogUp sum"

[[constraints.output]]
kind = "interaction"
tag = "ALU"
input = [["cast", "n", "DWordWL"], ["cast", "d", "DWordWL"], ["+", ["opsel", "DIVREM"], ["*", 32, "signed"]]]
output = ["cast", "q", "DWordWL"]
multiplicity = ["-", "μ_q"]

[[constraints.output]]
kind = "interaction"
tag = "ALU"
input = [["cast", "n", "DWordWL"], ["cast", "d", "DWordWL"], ["+", ["opsel", "DIVREM"], ["*", 32, "signed"], 128]]
output = ["cast", "r", "DWordWL"]
multiplicity = ["-", "μ_r"]
