name = "EC_SCALAR"

[[variables.input]]
name = "timestamp"
type = "DWordWL"
desc = "timestamp at which to read the constant"

[[variables.input]]
name = "addr"
type = "DWordWL"
desc = "address at which the current limb is stored"

[[variables.input]]
name = "len"
type = "Byte"
desc = "the number of bytes to read after this one"

[[variables.auxiliary]]
name = "limb_bits"
type = ["Bit", 8]
desc = "bit-decomposition of the limb being read"

[[variables.auxiliary]]
name = "last_limb"
type = "Bit"
desc = "whether this is the last limb to read"

[[variables.virtual]]
name = "next_addr"
type = "DWordWL"
desc = "address storing the next byte limb of the scalar"
def = {polys=[
    {iter=["i", 0], poly=["-", ["idx", "addr", 0], 1]},
    {iter=["i", 1], poly=["idx", "addr", 1]},
]}

[[variables.virtual]]
name = "limb"
type = "Byte"
desc = "limb being read"
def = {poly=["+",
        ["*", ["^", 2, 0], ["idx", "limb_bits", 0]],
        ["*", ["^", 2, 1], ["idx", "limb_bits", 1]],
        ["*", ["^", 2, 2], ["idx", "limb_bits", 2]],
        ["*", ["^", 2, 3], ["idx", "limb_bits", 3]],
        ["*", ["^", 2, 4], ["idx", "limb_bits", 4]],
        ["*", ["^", 2, 5], ["idx", "limb_bits", 5]],
        ["*", ["^", 2, 6], ["idx", "limb_bits", 6]],
        ["*", ["^", 2, 7], ["idx", "limb_bits", 7]],
]}

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""




[[constraint_groups]]
name = "all"

[[constraints.all]]
kind = "template"
tag = "IS_BIT"
input = ["μ"]

[[constraints.all]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "limb_bits", "i"]]
iter = ["i", 0, 7]

[[constraints.all]]
kind = "arith"
constraint = "$#`limb_bits`_i = 1 => #`μ` = 1$"
poly = ["*", ["idx", "limb_bits", "i"], ["not", "μ"]]
iter = ["i", 0, 7]

[[constraints.all]]
kind = "interaction"
tag = "MEMW"
input = [0, "addr", ["arr", "limb", 0, 0, 0, 0, 0, 0, 0], "timestamp", 0, 0, 0]
output = ["arr", "limb", 0, 0, 0, 0, 0, 0, 0]
multiplicity = "μ"

[[constraints.all]]
kind = "interaction"
tag = "BIT"
input = ["timestamp", ["+", ["*", 8, "len"], "i"]]
iter = ["i", 0, 7]
multiplicity = ["idx", "limb_bits", "i"]

[[constraints.all]]
kind = "arith"
constraint = "$#`last_limb` = 1 => #`μ` = 1$"
poly = ["*", "last_limb", ["not", "μ"]]

[[constraints.all]]
kind = "arith"
constraint = "$#`last_limb` = 1 => #`len` = 0$"
poly = ["*", "last_limb", "len"]

[[constraints.all]]
kind = "interaction"
tag = "SERVE_K"
input = ["timestamp", "addr", "len"]
multiplicity = ["-", "μ"]

[[constraints.all]]
kind = "interaction"
tag = "SERVE_K"
input = ["timestamp", "next_addr", ["-", "len", 1]]
multiplicity = ["not", "last_limb"]