name = "EC_SCALAR"

[[variables.input]]
name = "timestamp"
type = "DWordWL"
desc = "timestamp at which to read the constant"

[[variables.input]]
name = "ptr"
type = "DWordWL"
desc = "pointer to the first byte of the scalar"

[[variables.input]]
name = "offset"
type = "Byte"
desc = "index of limb"

[[variables.auxiliary]]
name = "limb_bits"
type = ["Bit", 8]
desc = "bit-decomposition of the limb being read"

[[variables.auxiliary]]
name = "last_limb"
type = "Bit"
desc = "whether this is the last limb to read"

[[variables.virtual]]
name = "limb"
type = "Byte"
desc = "limb being read"
def = {poly=["sum", ["=", "i", 0], 7, ["*", ["^", 2, "i"], ["idx", "limb_bits", "i"]]]}

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""

[[assumptions]]
desc = "$#`ptr` + #`offset`$ does not overflow the bottom limb"

[[constraint_groups]]
name = "recv"

[[constraints.recv]]
kind = "interaction"
tag = "SERVE_K"
input = ["timestamp", "ptr", "offset"]
multiplicity = ["-", "μ"]

[[constraints.recv]]
kind = "template"
tag = "IS_BIT"
input = ["μ"]

[[constraint_groups]]
name = "read"

[[constraints.read]]
kind = "interaction"
tag = "MEMW"
input = [0, ["+", "ptr", ["cast", "offset", "DWordWL"]], ["arr", "limb", 0, 0, 0, 0, 0, 0, 0], "timestamp", 0, 0, 0]
output = ["arr", "limb", 0, 0, 0, 0, 0, 0, 0]
multiplicity = "μ"

[[constraints.read]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "limb_bits", "i"]]
iter = ["i", 0, 7]


[[constraint_groups]]
name = "serve"

[[constraints.serve]]
kind = "interaction"
tag = "BIT"
input = ["timestamp", ["+", ["*", 8, "offset"], "i"]]
iter = ["i", 0, 7]
multiplicity = ["idx", "limb_bits", "i"]

[[constraints.serve]]
kind = "arith"
constraint = "$#`limb_bits`_i = 1 => #`μ` = 1$"
poly = ["*", ["idx", "limb_bits", "i"], ["not", "μ"]]
iter = ["i", 0, 7]

[[constraint_groups]]
name = "recurse"

[[constraints.recurse]]
kind = "template"
tag = "IS_BIT"
input = ["last_limb"]

[[constraints.recurse]]
kind = "arith"
constraint = "$#`last_limb` = 1 => #`μ` = 1$"
poly = ["*", "last_limb", ["not", "μ"]]

[[constraints.recurse]]
kind = "arith"
constraint = "$#`last_limb` = 1 => #`offset` = 0$"
poly = ["*", "last_limb", "offset"]

[[constraints.recurse]]
kind = "interaction"
tag = "SERVE_K"
input = ["timestamp", "next_addr", ["-", "offset", 1]]
multiplicity = ["not", "last_limb"]