name = "ECSM"

[[variables.input]]
name = "timestamp"
type = "DWordWL"
desc = "timestamp at which this operation is executed"
pad = 0

[[variables.input]]
name = "addr_xG"
type = ["DWordHL", 4]
desc = "address at which `x`-coordinate of start point `G` is stored"
pad = 0

[[variables.input]]
name = "addr_k"
type = ["DWordHL", 4]
desc = "address at which scalar `k` is stored"
pad = 0

[[variables.input]]
name = "addr_xR"
type = ["DWordHL", 4]
desc = "address to which the `x`-coordinate of result point `R` is to be written"
pad = 0

[[variables.output]]
name = "xR"
type = "U256BL"
desc = "$(#`k` times #`G`)_x$"
pad = 0

[[variables.auxiliary]]
name = "yR"
type = "U256BL"
desc = "$(#`k` times #`G`)_y$"
pad = 0

[[variables.auxiliary]]
name = "k"
type = ["Bit", 256]
desc = "`k`"
pad = 0

[[variables.auxiliary]]
name = "idx_k"
type = "Byte"
desc = "Zero-based index of `k`'s most significant 1-bit"
pad = 0

[[variables.auxiliary]]
name = "xG"
type = "U256BL"
desc = "$x_G$"
pad = 0

[[variables.auxiliary]]
name = "yG"
type = "U256BL"
desc = "$y_G$"
pad = 0

[[variables.auxiliary]]
name = "x2"
type = "U256BL"
desc = "$x_G^2$"
pad = 0

[[variables.auxiliary]]
name = "q0"
type = "U256BL"
desc = "quotient for computing `x2`"
pad = 0

[[variables.auxiliary]]
name = "c0"
type = ["BaseField", 64]
desc = "carries for computing `x2`"
pad = 0

[[variables.auxiliary]]
name = "q1"
type = ["Byte", 33]
desc = "quotient for computing `yG`"
pad = "p"

[[variables.auxiliary]]
name = "c1"
type = ["BaseField", 64]
desc = "carries for computing `yG`"
pad = 0

[[variables.auxiliary]]
name = "xG_sub_p"
type = "U256HL"
desc = "$x_G - #`p` mod 2^256$"
pad = 0

[[variables.auxiliary]]
name = "k_sub_N"
type = "U256HL"
desc = "$#`k`- #`N` mod 2^256$"
pad = 0

[[variables.auxiliary]]
name = "xR_sub_p"
type = "U256HL"
desc = "$x_R - #`p` mod 2^256$"
pad = 0

[[variables.virtual]]
name = "byte_k"
type = "U256BL"
desc = "`k`, as bytes"
def = {polys=[
    {iter=["i", 0, 31], poly=["sum",["=", "j", 0], 7, ["*", ["^", 2, "j"], ["idx", "k", ["+", ["*", 8, "i"], "j"]]]]}
]}

[[variables.virtual]]
name = "c2"
type = ["Bit", 8]
desc = "carries for computing $#`P` + #`xG_sub_p`$"
def = {polys=[
    {iter=["i", 0], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", ["cast", "p", "U256WL"], "i"], ["idx", ["cast", "xG_sub_p", "U256WL"], "i"]], ["idx", ["cast", "xG", "U256WL"], "i"]]]},
    {iter=["i", 1, 7], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", ["cast", "p", "U256WL"], "i"], ["idx", ["cast", "xG_sub_p", "U256WL"], "i"], ["idx", "c2", ["-", "i", 1]]], ["idx", ["cast", "xG", "U256WL"], "i"]]]},
]}

[[variables.virtual]]
name = "c3"
type = ["Bit", 8]
desc = "carries for computing $#`N` + #`k_sub_N`$"
def = {polys=[
    {iter=["i", 0], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", ["cast", "N", "U256WL"], "i"], ["idx", ["cast", "k_sub_N", "U256WL"], "i"]], ["idx", ["cast", "byte_k", "U256WL"], "i"]]]},
    {iter=["i", 1, 7], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", ["cast", "N", "U256WL"], "i"], ["idx", ["cast", "k_sub_N", "U256WL"], "i"], ["idx", "c3", ["-", "i", 1]]], ["idx", ["cast", "byte_k", "U256WL"], "i"]]]},
]}

[[variables.virtual]]
name = "c4"
type = ["Bit", 8]
desc = "carries for computing $#`p` + #`xR_sub_p`$"
def = {polys=[
    {iter=["i", 0], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", ["cast", "p", "U256WL"], "i"], ["idx", ["cast", "xR_sub_p", "U256WL"], "i"]], ["idx", ["cast", "xR", "U256WL"], "i"]]]},
    {iter=["i", 1, 7], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", ["cast", "p", "U256WL"], "i"], ["idx", ["cast", "xR_sub_p", "U256WL"], "i"], ["idx", "c4", ["-", "i", 1]]], ["idx", ["cast", "xR", "U256WL"], "i"]]]},
]}

[[variables.virtual]]
name = "XG"
type = ["Byte", 64]
desc = "zero-extension of `xG`"
def = {polys=[
    {iter=["i", 0, 31], poly=["idx", "xG", "i"]},
    {iter=["i", 32, 63], poly=0},
]}

[[variables.virtual]]
name = "YG"
type = ["Byte", 64]
desc = "zero-extension of `yG`"
def = {polys=[
    {iter=["i", 0, 31], poly=["idx", "yG", "i"]},
    {iter=["i", 32, 63], poly=0},
]}

[[variables.virtual]]
name = "X2"
type = ["Byte", 64]
desc = "zero-extension of `x2`"
def = {polys=[
    {iter=["i", 0, 31], poly=["idx", "x2", "i"]},
    {iter=["i", 32, 63], poly=0},
]}

[[variables.virtual]]
name = "Q0"
type = ["Byte", 64]
desc = "zero-extension of `q`"
def = {polys=[
    {iter=["i", 0, 31], poly=["idx", "q0", "i"]},
    {iter=["i", 32, 63], poly=0},
]}

[[variables.virtual]]
name = "Q1"
type = ["Byte", 64]
desc = "zero-extension of `q1`"
def = {polys=[
    {iter=["i", 0, 32], poly=["idx", "q1", "i"]},
    {iter=["i", 33, 63], poly=0},
]}

[[variables.virtual]]
name = "B"
type = ["Byte", 64]
desc = "zero-extension of `b`"
def = {polys=[
    {iter=["i", 0, 31], poly=["idx", "b", "i"]},
    {iter=["i", 32, 63], poly=0},
]}

[[variables.virtual]]
name = "P"
type = ["Byte", 64]
desc = "zero-extension of `p`"
def = {polys=[
    {iter=["i", 0, 31], poly=["idx", "p", "i"]},
    {iter=["i", 32, 63], poly=0},
]}

[[variables.constant]]
name = "b"
type = "U256BL"
desc = "`b`-coefficient of the elliptic curve"

[[variables.constant]]
name = "p"
type = "U256BL"
desc = "Prime field modulus"

[[variables.constant]]
name = "N"
type = "U256BL"
desc = "Curve order"

[[variables.constant]]
name = "offsets"
type = ["Half", 2]
desc = "Offsets for the range of carries `c0` and `c1`."

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""
pad = 0

# Load xG from memory

[[constraint_groups]]
name = "read_xG"

[[constraints.read_xG]]
kind = "interaction"
tag = "MEMW"
input = [
    1, 
    ["cast", ["*", 2, 11], "DWordWL"],
    ["arr", ["idx", ["cast", ["idx", "addr_xG", 0], "DWordWL"], 0], ["idx", ["cast", ["idx", "addr_xG", 0], "DWordWL"], 1], 0, 0, 0, 0, 0, 0],
    "timestamp", 
    1, 0, 0]
output = ["arr", ["idx", ["cast", ["idx", "addr_xG", 0], "DWordWL"], 0], ["idx", ["cast", ["idx", "addr_xG", 0], "DWordWL"], 1], 0, 0, 0, 0, 0, 0]
multiplicity = "μ"
ref = "ec:c:read_addr_xG"

[[constraints.read_xG]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", ["idx", "addr_xG", "i"], "j"]]
iters = [["i", 0, 3], ["j", 0, 3]]
multiplicity = "μ"
ref = "ec:c:range_addr_xG"

[[constraints.read_xG]]
kind = "template"
tag = "ADD"
input = [["cast", ["idx", "addr_xG", 0], "DWordWL"], ["cast", ["*", 8, "i"], "DWordWL"]]
output = ["cast", ["idx", "addr_xG", "i"], "DWordWL"]
iter = ["i", 1, 3]
cond = "μ"
ref = "ec:c:extrapolate_addr_xG"

[[constraints.read_xG]]
kind = "interaction"
tag = "MEMW"
input = [
    0,
    ["cast", ["idx", "addr_xG", "i"], "DWordWL"],
    ["arr",
        ["idx", "xG", ["+", ["*", 8, "i"], 0]],
        ["idx", "xG", ["+", ["*", 8, "i"], 1]],
        ["idx", "xG", ["+", ["*", 8, "i"], 2]],
        ["idx", "xG", ["+", ["*", 8, "i"], 3]],
        ["idx", "xG", ["+", ["*", 8, "i"], 4]],
        ["idx", "xG", ["+", ["*", 8, "i"], 5]],
        ["idx", "xG", ["+", ["*", 8, "i"], 6]],
        ["idx", "xG", ["+", ["*", 8, "i"], 7]],
    ],
    "timestamp",
    0, 0, 1
]
output = ["arr",
    ["idx", "xG", ["+", ["*", 8, "i"], 0]],
    ["idx", "xG", ["+", ["*", 8, "i"], 1]],
    ["idx", "xG", ["+", ["*", 8, "i"], 2]],
    ["idx", "xG", ["+", ["*", 8, "i"], 3]],
    ["idx", "xG", ["+", ["*", 8, "i"], 4]],
    ["idx", "xG", ["+", ["*", 8, "i"], 5]],
    ["idx", "xG", ["+", ["*", 8, "i"], 6]],
    ["idx", "xG", ["+", ["*", 8, "i"], 7]],
]
iter = ["i", 0, 3]
multiplicity = "μ"
ref = "ec:c:read_xG"

# Range check xG

[[constraint_groups]]
name = "range_xG"

[[constraints.range_xG]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "xG_sub_p", "i"]]
iter = ["i", 0, 15]
multiplicity = "μ"
ref = "ec:c:range_xG_sub_p"

[[constraints.range_xG]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "c2", "i"]]
iter = ["i", 0, 6]
cond = "μ"
ref = "ec:c:range_c2"

[[constraints.range_xG]]
kind = "arith"
constraint = "$#`μ` => #`c2`_7 = 1$"
poly = ["*", "μ", ["not", ["idx", "c2", 7]]]
ref = "ec:c:xG_addition_overflows"

# Computing xG^2

[[constraint_groups]]
name = "xG2"

[[constraints.xG2]]
kind = "template"
tag = "IS_BYTE"
input = [["idx", "x2", "i"]]
iter = ["i", 0, 31]
cond = "μ"
ref = "ec:c:range_x2"

[[constraints.xG2]]
kind = "template"
tag = "IS_BYTE"
input = [["idx", "q0", "i"]]
iter = ["i", 0, 31]
cond = "μ"
ref = "ec:c:range_q0"

[[constraints.xG2]]
kind = "arith"
constraint = "$2^8 dot #`c0`_0 = #`XG`_0 dot #`XG`_0 - #`X2`_0 - #`Q0`_0 dot #`P`_0$"
poly = ["-", ["*", ["idx", "XG", 0], ["idx", "XG", 0]], ["idx", "X2", 0], ["*", ["idx", "Q0", 0], ["idx", "P", 0]], ["*", ["^", 2, 8], ["idx", "c0", 0]]]
ref = "ec:c:c0_0"

[[constraints.xG2]]
kind = "arith"
constraint = "$2^8 dot #`c0`_i = #`c0`_(i-1) - #`X2`_i + sum_(j=0)^i #`XG`_j dot #`XG`_(i-j) - #`Q0`_j dot #`P`_(i-j)$"
poly = ["+", ["-", ["idx", "c0", ["-", "i", 1]], ["*", ["^", 2, 8], ["idx", "c0", "i"]], ["idx", "X2", "i"]], ["sum", ["=", "j", 0], "i", ["-", ["*", ["idx", "XG", "j"], ["idx", "XG", ["-", "i", "j"]]], ["*", ["idx", "Q0", "j"], ["idx", "P", ["-", "i", "j"]]]]]]
iter = ["i", 1, 63]
ref = "ec:c:c0_i"

[[constraints.xG2]]
kind = "arith"
constraint = "$#`c0`_63 = 0$"
poly = ["idx", "c0", 63]
ref = "ec:c:c0_63_is_zero"

[[constraints.xG2]]
kind = "interaction"
tag = "IS_HALF"
input = [["+", ["idx", "c0", "i"], ["idx", "offsets", 0]]]
iter = ["i", 0, 62]
multiplicity = "μ"
ref = "ec:c:range_c0"


# Computing yG

[[constraint_groups]]
name = "yG"

[[constraints.yG]]
kind = "template"
tag = "IS_BYTE"
input = [["idx", "yG", "i"]]
iter = ["i", 0, 31]
cond = "μ"
ref = "ec:c:range_yG"

[[constraints.yG]]
kind = "template"
tag = "IS_BYTE"
input = [["idx", "q1", "i"]]
iter = ["i", 0, 31]
cond = "μ"
ref = "ec:c:range_q1"

[[constraints.yG]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "q1", 32]]
ref = "ec:c:q1_257"

[[constraints.yG]]
kind = "arith"
constraint = "$2^8 dot #`c1`_0 = #`YG`_0 dot #`YG`_0 - #`X2`_0 dot #`XG`_0 - #`μ` dot #`B`_0 + #`P`_0 dot #`P`_0 - #`Q1`_0 dot #`P`_0$"
poly = ["-", 
    ["+", 
        ["*", ["idx", "YG", 0], ["idx", "YG", 0]], 
        ["*", ["idx", "P", 0], ["idx", "P", 0]], 
    ], 
    ["*", ["idx", "X2", 0], ["idx", "XG", 0]], 
    ["*", "μ", ["idx", "B", 0]], 
    ["*", ["idx", "Q1", 0], ["idx", "P", 0]], 
    ["*", ["^", 2, 8], ["idx", "c1", 0]]
]
ref = "ec:c:c1_0"

[[constraints.yG]]
kind = "arith"
constraint = "$2^8 dot #`c1`_i = #`c1`_(i-1) - #`μ` dot #`B`_i + sum_(j=0)^i (#`YG`_j dot #`YG`_(i-j) + #`P`_j dot #`P`_(i-j) - #`X2`_j dot #`XG`_(i-j) - #`Q1`_j dot #`P`_(i-j))$"
poly = ["+", 
    ["-", 
        ["idx", "c1", ["-", "i", 1]], 
        ["*", ["^", 2, 8], ["idx", "c1", "i"]],
        ["*", "μ", ["idx", "B", "i"]]
    ], 
    ["sum", ["=", "j", 0], "i", 
        ["-", 
            ["+", 
                ["*", ["idx", "YG", "j"], ["idx", "YG", ["-", "i", "j"]]],
                ["*", ["idx", "P", "j"], ["idx", "P", ["-", "i", "j"]]]
            ], 
            ["*", ["idx", "X2", "j"], ["idx", "XG", ["-", "i", "j"]]], 
            ["*", ["idx", "Q1", "j"], ["idx", "P", ["-", "i", "j"]]]
        ]
    ]
]
iter = ["i", 1, 63]
ref = "ec:c:c1_i"

[[constraints.yG]]
kind = "arith"
constraint = "$#`c1`_63 = 0$"
poly = ["idx", "c1", 63]
ref = "ec:c:c1_63_is_zero"

[[constraints.yG]]
kind = "interaction"
tag = "IS_HALF"
input = [["+", ["idx", "c1", "i"], ["idx", "offsets", 1]]]
iter = ["i", 0, 62]
multiplicity = "μ"
ref = "ec:c:range_c1"


# Verifying k

[[constraint_groups]]
name = "verify_k"

[[constraints.verify_k]]
kind = "interaction"
tag = "MEMW"
input = [
    1, 
    ["cast", ["*", 2, 12], "DWordWL"],
    ["arr", ["idx", ["cast", ["idx", "addr_k", 0], "DWordWL"], 0], ["idx", ["cast", ["idx", "addr_k", 0], "DWordWL"], 1], 0, 0, 0, 0, 0, 0],
    ["+", "timestamp", ["cast", 1, "DWordWL"]],
    1, 0, 0]
output = ["arr", ["idx", ["cast", ["idx", "addr_k", 0], "DWordWL"], 0], ["idx", ["cast", ["idx", "addr_k", 0], "DWordWL"], 1], 0, 0, 0, 0, 0, 0]
multiplicity = "μ"
ref = "ec:c:read_addr_k"

[[constraints.verify_k]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", ["idx", "addr_k", "i"], "j"]]
iters = [["i", 0, 3], ["j", 0, 3]]
multiplicity = "μ"
ref = "ec:c:range_addr_k"

[[constraints.verify_k]]
kind = "template"
tag = "ADD"
input = [["cast", ["idx", "addr_k", 0], "DWordWL"], ["cast", ["*", 8, "i"], "DWordWL"]]
output = ["cast", ["idx", "addr_k", "i"], "DWordWL"]
iter = ["i", 1, 3]
cond = "μ"
ref = "ec:c:extrapolate_addr_k"

[[constraints.verify_k]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "k", "i"]]
iter = ["i", 0, 255]
ref = "ec:c:range_k"

[[constraints.verify_k]]
kind = "interaction"
tag = "MEMW"
input = [
    0,
    ["cast", ["idx", "addr_k", "i"], "DWordWL"],
    ["arr",
        ["idx", "byte_k", ["+", ["*", 8, "i"], 0]],
        ["idx", "byte_k", ["+", ["*", 8, "i"], 1]],
        ["idx", "byte_k", ["+", ["*", 8, "i"], 2]],
        ["idx", "byte_k", ["+", ["*", 8, "i"], 3]],
        ["idx", "byte_k", ["+", ["*", 8, "i"], 4]],
        ["idx", "byte_k", ["+", ["*", 8, "i"], 5]],
        ["idx", "byte_k", ["+", ["*", 8, "i"], 6]],
        ["idx", "byte_k", ["+", ["*", 8, "i"], 7]],
    ],
    ["+", "timestamp", ["cast", 1, "DWordWL"]],
    0, 0, 1
]
output = ["arr",
    ["idx", "byte_k", ["+", ["*", 8, "i"], 0]],
    ["idx", "byte_k", ["+", ["*", 8, "i"], 1]],
    ["idx", "byte_k", ["+", ["*", 8, "i"], 2]],
    ["idx", "byte_k", ["+", ["*", 8, "i"], 3]],
    ["idx", "byte_k", ["+", ["*", 8, "i"], 4]],
    ["idx", "byte_k", ["+", ["*", 8, "i"], 5]],
    ["idx", "byte_k", ["+", ["*", 8, "i"], 6]],
    ["idx", "byte_k", ["+", ["*", 8, "i"], 7]],
]
iter = ["i", 0, 3]
multiplicity = "μ"
ref = "ec:c:load_k"

[[constraints.verify_k]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "k_sub_N", "i"]]
iter = ["i", 0, 15]
multiplicity = "μ"
ref = "ec:c:range_k_sub_N"

[[constraints.verify_k]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "c3", "i"]]
iter = ["i", 0, 6]
cond = "μ"
ref = "ec:c:range_c3"

[[constraints.verify_k]]
kind = "arith"
constraint = "$#`μ` => #`c3`_7 = 1$"
poly = ["*", "μ", ["not", ["idx", "c3", 7]]]
ref = "ec:c:k_lt_N"

[[constraints.verify_k]]
kind = "interaction"
tag = "ZERO"
input = [["+", 
    ["idx", "byte_k", 0],
    ["idx", "byte_k", 1],
    ["idx", "byte_k", 2],
    ["idx", "byte_k", 3],
    ["idx", "byte_k", 4],
    ["idx", "byte_k", 5],
    ["idx", "byte_k", 6],
    ["idx", "byte_k", 7],
    ["idx", "byte_k", 8],
    ["idx", "byte_k", 9],
    ["idx", "byte_k", 10],
    ["idx", "byte_k", 11],
    ["idx", "byte_k", 12],
    ["idx", "byte_k", 13],
    ["idx", "byte_k", 14],
    ["idx", "byte_k", 15],
    ["idx", "byte_k", 16],
    ["idx", "byte_k", 17],
    ["idx", "byte_k", 18],
    ["idx", "byte_k", 19],
    ["idx", "byte_k", 20],
    ["idx", "byte_k", 21],
    ["idx", "byte_k", 22],
    ["idx", "byte_k", 23],
    ["idx", "byte_k", 24],
    ["idx", "byte_k", 25],
    ["idx", "byte_k", 26],
    ["idx", "byte_k", 27],
    ["idx", "byte_k", 28],
    ["idx", "byte_k", 29],
    ["idx", "byte_k", 30],
    ["idx", "byte_k", 31]
]]
output = 0
multiplicity = "μ"
ref = "ec:c:k_gt_0"

# Range check xR

[[constraint_groups]]
name = "range_xR"

[[constraints.range_xR]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "xR_sub_p", "i"]]
iter = ["i", 0, 15]
multiplicity = "μ"
ref = "ec:c:range_xR_sub_p"

[[constraints.range_xR]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "c4", "i"]]
iter = ["i", 0, 6]
cond = "μ"
ref = "ec:c:range_c4"

[[constraints.range_xR]]
kind = "arith"
constraint = "$#`μ` => #`c4`_7 = 1$"
poly = ["*", "μ", ["not", ["idx", "c4", 7]]]
ref = "ec:c:xR_addition_overflows"


# Write R to memory

[[constraint_groups]]
name = "write_xR"

[[constraints.write_xR]]
kind = "interaction"
tag = "MEMW"
input = [
    1, 
    ["cast", ["*", 2, 10], "DWordWL"],
    ["arr", ["idx", ["cast", ["idx", "addr_xR", 0], "DWordWL"], 0], ["idx", ["cast", ["idx", "addr_xR", 0], "DWordWL"], 1], 0, 0, 0, 0, 0, 0],
    ["+", "timestamp", ["cast", 2, "DWordWL"]],
    1, 0, 0]
output = ["arr", ["idx", ["cast", ["idx", "addr_xR", 0], "DWordWL"], 0], ["idx", ["cast", ["idx", "addr_xR", 0], "DWordWL"], 1], 0, 0, 0, 0, 0, 0]
multiplicity = "μ"
ref = "ec:c:load_addr_xR"

[[constraints.write_xR]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", ["idx", "addr_xR", "i"], "j"]]
iters = [["i", 0, 3], ["j", 0, 3]]
multiplicity = "μ"
ref = "ec:c:range_addr_xR"

[[constraints.write_xR]]
kind = "template"
tag = "ADD"
input = [["cast", ["idx", "addr_xR", 0], "DWordWL"], ["cast", ["*", 8, "i"], "DWordWL"]]
output = ["cast", ["idx", "addr_xR", "i"], "DWordWL"]
iter = ["i", 0, 3]
cond = "μ"
ref = "ec:c:extrapolate_addr_xR"

[[constraints.write_xR]]
kind = "interaction"
tag = "MEMW"
input = [
    0,
    ["cast", ["idx", "addr_xR", "i"], "DWordWL"],
    ["arr",
        ["idx", "xR", ["+", ["*", 8, "i"], 0]],
        ["idx", "xR", ["+", ["*", 8, "i"], 1]],
        ["idx", "xR", ["+", ["*", 8, "i"], 2]],
        ["idx", "xR", ["+", ["*", 8, "i"], 3]],
        ["idx", "xR", ["+", ["*", 8, "i"], 4]],
        ["idx", "xR", ["+", ["*", 8, "i"], 5]],
        ["idx", "xR", ["+", ["*", 8, "i"], 6]],
        ["idx", "xR", ["+", ["*", 8, "i"], 7]],
    ],
    ["+", "timestamp", ["cast", 2, "DWordWL"]],
    0, 0, 1
]
iter = ["i", 0, 3]
multiplicity = "μ"
ref = "ec:c:write_xR"


[[constraint_groups]]
name = "ecall"

[[constraints.ecall]]
kind = "template"
tag = "IS_BIT"
input = ["μ"]
ref = "ec:c:mu_isbit"

[[constraints.ecall]]
kind = "interaction"
tag = "ECALL"
input = ["timestamp", ["cast", ["-", ["^", 2, 64], 11], "DWordWL"]]
multiplicity = ["-", "μ"]

[[constraint_groups]]
name = "delegate"

[[constraints.delegate]]
kind = "interaction"
tag = "BIT"
input = ["timestamp", "i"]
iter = ["i", 0, 255]
multiplicity = ["idx", "k", "i"]

[[constraints.delegate]]
kind = "arith"
constraint = "$#`k` != 0 => #`μ` != 0$"
poly = ["*", ["sum", ["=", "i", 0], 255, ["idx", "k", "i"]], ["not", "μ"]]

[[constraints.delegate]]
kind = "interaction"
tag = "BIT"
input = ["timestamp", "idx_k"]
multiplicity = "μ"

[[constraints.delegate]]
kind = "interaction"
tag = "ECDAS"
input = ["timestamp", "xG", "yG", "xG", "yG", ["-", "idx_k", 1], 0]
multiplicity = "μ"
ref = "ec:c:start_double_add"

[[constraints.delegate]]
kind = "interaction"
tag = "ECDAS"
input = ["timestamp", "xR", "yR", "xG", "yG", -1, 0]
multiplicity = ["-", "μ"]
ref = "ec:c:receive_double_add"
