name = "FIELD_VM"
code = "FVM"

[[variables.input]]
name = "pc"
type = "BaseField"
desc = "The program counter"

[[variables.input]]
name = "argument_registers"
type = ["BaseField", 4]
desc = "The register numbers of the arguments `o`, `a`, `b`, `c`, in that order"

[[variables.input]]
name = "argument_scalars"
type = ["BaseField", 4]
desc = "The `imm_0` scalars for the arguments `o`, `a`, `b`, `c`, in that order"

[[variables.input]]
name = "argument_offsets"
type = ["BaseField", 4]
desc = "The `imm_1` offsets for the arguments `o`, `a`, `b`, `c`, in that order"

[[variables.input]]
name = "mem_flags"
type = ["Bit", 4]
desc = "Whether the argument (`o`, `a`, `b`, `c`, in that order) comes from a memory lookup"

[[variables.input]]
name = "hint_input"
type = ["Bit", 5] # PARAM: ["Bit", N]
desc = "Whether each input register is hinted this cycle"

[[variables.input]]
name = "hint_output"
type = "Bit"
desc = "Whether the output register is hinted this cycle"

[[variables.auxiliary]]
name = "registers"
type = ["ExtField", 5] # PARAM: ["ExtField", N]
desc = "The general purpose registers"

[[variables.auxiliary]]
name = "ZERO"
type = "Bit"
desc = "Whether the output of the previous instruction was zero"

[[variables.auxiliary]]
name = "out_inverse"
type = "ExtField"
desc = "The multiplicative inverse of the output, used to check `ZERO`"

[[variables.auxiliary]]
name = "arg_reg_pows_computed"
type = [["BaseField", 1], 4] # PARAM: [["BaseField", T], 4]
desc = "Powers of the argument register indices to split the MUX polynomials into lower degree parts"

[[variables.auxiliary]]
name = "args_premem"
type = ["ExtField", 4]
desc = "The argument values, before a potential memory lookup"

[[variables.auxiliary]]
name = "args"
type = ["ExtField", 4]
desc = "The argument values, after a potential memory lookup"

[[variables.virtual]]
name = "all_regs"
type = ["ExtField", 7] # PARAM: ["ExtField", N + 2]
desc = "All general purpose registers, followed by `pc` and `ZERO`, matching the decoding indices"
def = {polys = [
  {iter = ["i", 0], poly = "ZERO"},
  {iter = ["i", 1], poly = "pc"},
  {iter = ["i", 2, 6], poly = ["idx", "registers", ["-", "i", 2]]}, # PARAM: iter = ["i", 2, N + 1]
]}

[[variables.virtual]]
name = "arg_register_powers"
type = [["BaseField", 2], 4] # PARAM: [["BaseField", T + 1], 4]
desc = "A virtual wrapper aroung `arg_reg_pows_computed` to have a 1 at index 0"
def = {polys = [
    {iters = [["i", 0, 3], ["j", 0]], poly = 1},
    {iters = [["i", 0, 3], ["j", 1, 1]], poly = ["idx", ["idx", "arg_reg_pows_computed", "i"], ["-", "j", 1]]} # PARAM: iters = ["i", 0, 3], ["j", 1, T]]
  ]}

[[variables.constant]]
name = "MUX"
type = [[["BaseField", 4], 2], 6] # PARAM: [[["BaseField", d - 1], t + 1], N + 1]
desc = "The MUX polynomial coefficients"

[[constraint_groups]]
name = "decode"

[[constraints.decode]]
kind = "interaction"
tag = "FIELD_VM_DECODE"
input = ["pc", "argument_registers", "argument_scalars", "argument_offsets", "mem_flags", "hint_input", "hint_output"]
multiplicity = 1

[[constraint_groups]]
name = "mux"

[[constraints.mux]]
kind = "arith"
constraint = "$#`arg_reg_pows_computed`_(i,0) = #`arg_registers`_i^4$" # PARAM: power = d - 1
poly = ["-", ["idx", ["idx", "arg_reg_pows_computed", "i"], 0],
  ["*",
    ["idx", "arg_registers", "i"],
    ["idx", "arg_registers", "i"],
    ["idx", "arg_registers", "i"],
    ["idx", "arg_registers", "i"]]]
iter = ["i", 0, 3]

# PARAM: If T > 1, we need to populate arg_reg_pows_computed[i][j], j > 0, too, with power j * (d - 2) + (d - 1)

[[constraints.mux]]
kind = "arith"
# PARAM: $#`args_premem`_i = #`argument_offsets`_i + #`argument_scalars`_i dot limits(sum)_(j = 0)^(N + 1) #`all_regs`_j dot (limits(sum)_(k = 0)^T #`arg_register_powers`_(i,k) dot (limits(sum_(l = 0)^(d - 2) #`argument_registers`_i^l dot #`MUX`_(j,k,l)))$
constraint = "$#`args_premem`_i = #`argument_offsets`_i + #`argument_scalars`_i dot limits(sum)_(j = 0)^6 #`all_regs`_j dot (limits(sum)_(k = 0)^1 #`arg_register_powers`_(i,k) dot (limits(sum)_(l = 0)^3 #`argument_registers`_i^l dot #`MUX`_(j,k,l)))$"
# PARAM: ["-", ["idx", "args_premem", "i"], ["idx", "argument_offsets", "i"], ["*", ["idx", "argument_scalars", "i"], ["sum", ["=", "j", 0], ["+", "N", 1], ["*", ["idx", "all_regs", "j"], ["sum", ["=", "k", 0], "T", ["*", ["idx", ["idx", "arg_register_powers", "k"], "i"], ["sum", ["=", "l", 0], ["-", "d", 2], ["*", ["^", ["idx", "argument_registers", "i"], "l"], ["idx", ["idx", ["idx", "MUX", "l"], "k"], "j"]]]]]]]]]
poly = ["-", ["idx", "args_premem", "i"], ["idx", "argument_offsets", "i"], ["*", ["idx", "argument_scalars", "i"], ["sum", ["=", "j", 0], 6, ["*", ["idx", "all_regs", "j"], ["sum", ["=", "k", 0], 1, ["*", ["idx", ["idx", "arg_register_powers", "i"], "k"], ["sum", ["=", "l", 0], 3, ["*", ["^", ["idx", "argument_registers", "i"], "l"], ["idx", ["idx", ["idx", "MUX", "j"], "k"], "l"]]]]]]]]]
iter = ["i", 1, 3]

[[constraints.mux]]
kind = "arith"
# PARAM: $#`args_premem`_0 = #`argument_offsets`_0 + #`argument_scalars`_0 dot limits(sum)_(j = 0)^(N + 1) #`all_regs`_j dot (limits(sum)_(k = 0)^T #`arg_register_powers`_(i,k) dot (limits(sum_(l = 0)^(d - 2) #`argument_registers`_0^l dot #`MUX`_(j,k,l)))$
constraint = "$#`args_premem`_0 = #`argument_offsets`_0 + #`argument_scalars`_0 dot limits(sum)_(j = 0)^6 #`all_regs`'_j dot (limits(sum)_(k = 0)^1 #`arg_register_powers`_(i,k) dot (limits(sum)_(l = 0)^3 #`argument_registers`_0^l dot #`MUX`_(j,k,l)))$"
# PARAM: ["-", ["idx", "args_premem", 0], ["idx", "argument_offsets", 0], ["*", ["idx", "argument_scalars", 0], ["sum", ["=", "j", 0], ["+", "N", 1], ["*", ["idx", ["next", "all_regs"], "j"], ["sum", ["=", "k", 0], "T", ["*", ["idx", ["idx", "arg_register_powers", "k"], 0], ["sum", ["=", "l", 0], ["-", "d", 2], ["*", ["^", ["idx", "argument_registers", 0], "l"], ["idx", ["idx", ["idx", "MUX", "l"], "k"], "j"]]]]]]]]]
poly = ["-", ["idx", "args_premem", 0], ["idx", "argument_offsets", 0], ["*", ["idx", "argument_scalars", 0], ["sum", ["=", "j", 0], 6, ["*", ["idx", ["next", "all_regs"], "j"], ["sum", ["=", "k", 0], 1, ["*", ["idx", ["idx", "arg_register_powers", 0], "k"], ["sum", ["=", "l", 0], 3, ["*", ["^", ["idx", "argument_registers", 0], "l"], ["idx", ["idx", ["idx", "MUX", "j"], "k"], "l"]]]]]]]]]

[[constraint_groups]]
name = "memory"

[[constraints.memory]]
kind = "arith"
constraint = "$!#`mem_flags[i]` => #`args[i]` = #`args_premem[i]`$"
poly = ["*", ["not", ["idx", "mem_flags", "i"]], ["-", ["idx", "args", "i"], ["idx", "args_premem", "i"]]]
iter = ["i", 0, 3]

[[constraints.memory]]
kind = "interaction"
tag = "MEMORY"
input = [["idx", "args_premem", "i"]]
output = ["idx", "args", "i"]
multiplicity = ["idx", "mem_flags", "i"]
iter = ["i", 0, 3]

[[constraint_groups]]
name = "fma"

[[constraints.fma]]
kind = "arith"
constraint = "$#`args[0]` = #`args[1]` dot #`args[2]` + #`args[3]`$"
poly = ["-", ["idx", "args", 0],
  ["*", ["idx", "args", 1], ["idx", "args", 2]],
  ["idx", "args", 3]]

[[constraint_groups]]
name = "transition"

[[constraints.transition]]
kind = "arith"
constraint = "$!#`hint_input`_i and !#`hint_output` => #`registers`'_i = #`registers`_i$"
poly = ["*", ["not", ["idx", "hint_input", "i"]], ["not", "hint_output"], ["-", ["idx", ["next", "registers"], "i"], ["idx", "registers", "i"]]]
iter = ["i", 0, 4] # PARAM: ["i", 0, N - 1]

[[constraints.transition]]
kind = "arith"
# PARAM: $!#`hint_input`_i and !(limits(sum)_(j = 0)^T #`arg_register_powers`_(0,j) dot limits(sum)_(k = 0)^(d - 2) #`MUX`_(i+2,j,k) dot #`argument_registers`_0^k) => #`registers`'_i = #`registers`_i$
constraint = "$!#`hint_input`_i and !(limits(sum)_(j = 0)^1 #`arg_register_powers`_(0,j) dot limits(sum)_(k = 0)^3 #`MUX`_(i+2,j,k) dot #`argument_registers`_0^k) => #`registers`'_i = #`registers`_i$"
# PARAM: ["*", ["not", ["idx", "hint_input", "i"]], ["-", 1, ["sum", ["=", "j", 0], "T", ["*", ["idx", ["idx", "arg_register_powers", 0], "j"], ["sum", ["=", "k", 0], ["-", "d", 2], ["*", ["idx", ["idx", ["idx", "MUX", ["+", "i", 2]], "j"], "k"], ["^", ["idx", "argument_registers", 0], "k"]]]]]], ["-", ["idx", ["next", "registers"], "i"], ["idx", "registers", "i"]]]
poly = ["*", ["not", ["idx", "hint_input", "i"]], ["-", 1, ["sum", ["=", "j", 0], 1, ["*", ["idx", ["idx", "arg_register_powers", 0], "j"], ["sum", ["=", "k", 0], 3, ["*", ["idx", ["idx", ["idx", "MUX", ["+", "i", 2]], "j"], "k"], ["^", ["idx", "argument_registers", 0], "k"]]]]]], ["-", ["idx", ["next", "registers"], "i"], ["idx", "registers", "i"]]]
iter = ["i", 0, 4] # PARAM: ["i", 0, N - 1]

[[constraints.transition]]
kind = "arith"
constraint = "$!#`hint_output` => #`pc`' = #`pc` + 1$"
poly = ["*", ["not", "hint_output"], ["-", ["next", "pc"], "pc", 1]]

[[constraints.transition]]
kind = "arith"
# PARAM: $!(limits(sum)_(j = 0)^1 #`arg_register_powers`_(0,j) dot limits(sum)_(k = 0)^3 #`MUX`_(1,j,k) dot #`argument_registers`_0^k) => #`pc`' = #`pc` + 1$
constraint = "$!(limits(sum)_(j = 0)^1 #`arg_register_powers`_(0,j) dot limits(sum)_(k = 0)^3 #`MUX`_(1,j,k) dot #`argument_registers`_0^k) => #`pc`' = #`pc` + 1$"
# PARAM: ["*", ["-", 1, ["sum", ["=", "j", 0], "T", ["*", ["idx", ["idx", "arg_register_powers", 0], "j"], ["sum", ["=", "k", 0], ["-", "d", 2], ["*", ["idx", ["idx", ["idx", "MUX", 1], "j"], "k"], ["^", ["idx", "argument_registers", 0], "k"]]]]]], ["-", ["next", "pc"], ["+", "pc", 1]]]
poly = ["*", ["-", 1, ["sum", ["=", "j", 0], 1, ["*", ["idx", ["idx", "arg_register_powers", 0], "j"], ["sum", ["=", "k", 0], 3, ["*", ["idx", ["idx", ["idx", "MUX", 1], "j"], "k"], ["^", ["idx", "argument_registers", 0], "k"]]]]]], ["-", ["next", "pc"], ["+", "pc", 1]]]

[[constraints.transition]]
kind = "template"
tag = "IS_BIT"
input = ["ZERO"]

[[constraints.transition]]
kind = "arith"
constraint = "$#`ZERO`' => #`args`_0 = 0$"
poly = ["*", ["next", "ZERO"], ["idx", "args", 0]]

[[constraints.transition]]
kind = "arith"
constraint = "$!#`ZERO`' => #`args`_0 dot #`out_inverse` = 1$"
poly = ["*", ["not", ["next", "ZERO"]], ["-", 1, ["*", ["idx", "args", 0], "out_inverse"]]]
