name = "HALT"

[[variables.input]]
name = "timestamp"
type = "DWordWL"
desc = "timestamp at which to halt the program"

[[variables.auxiliary]]
name = "pc"
type = "DWordWL"
desc = "The `next_pc` value the CPU wrote during the instruction HALT was invoked"

[[assumptions]]
desc = "`IS_WORD[timestamp[i]]`"
iter = ["i", 0, 1]


[[constraint_groups]]
name = "all"

[[constraints.all]]
kind = "interaction"
tag = "MEMW"
input = [1, ["cast", ["*", 2, "i"], "DWordWL"], ["cast", 0, ["BaseField", 8]], ["cast", ["-", ["^", 2, 64], 1], "DWordWL"], 1, 0, 0]
iter = ["i", 1, 9]
multiplicity = 1
ref = "halt:c:zeroize_registers_lo"

[[constraints.all]]
kind = "interaction"
tag = "MEMW"
input = [1, ["cast", ["*", 2, 10], "DWordWL"], ["cast", 0, ["BaseField", 8]], ["cast", ["-", ["^", 2, 64], 1], "DWordWL"], 1, 0, 0]
output = ["cast", 0, ["BaseField", 8]]
multiplicity = 1
ref = "halt:c:read_zero_exit_code"

[[constraints.all]]
kind = "interaction"
tag = "MEMW"
input = [1, ["cast", ["*", 2, "i"], "DWordWL"], ["cast", 0, ["BaseField", 8]], ["cast", ["-", ["^", 2, 64], 1], "DWordWL"], 1, 0, 0]
iter = ["i", 11, 31]
multiplicity = 1
ref = "halt:c:zeroize_registers_hi"

[[constraints.all]]
kind = "interaction"
tag = "memory"
input = [1, ["arr", ["+", ["*", 2, 255], "i"], 0], ["arr", ["+", ["idx", "timestamp", 0], 1], ["idx", "timestamp", 1]], ["idx", "pc", "i"]]
multiplicity = 1
iter = ["i", 0, 1]
ref = "halt:c:consume_pc"

[[constraints.all]]
kind = "interaction"
tag = "memory"
input = [1, ["arr", ["+", ["*", 2, 255], "i"], 0], ["arr", ["+", ["idx", "timestamp", 0], 1], ["idx", "timestamp", 1]], ["idx", ["arr", 1, 0], "i"]]
multiplicity = -1
iter = ["i", 0, 1]
ref = "halt:c:emit_pc"

[[constraint_groups]]
name = "lookup"

[[constraints.lookup]]
kind = "interaction"
tag = "ECALL"
input = ["timestamp", ["cast", 93, "DWordWL"]]
multiplicity = ["-", 1]
ref = "halt:c:lookup"
