name = "KECCAK"

[[variables.input]]
name = "timestamp"
type = "DWordWL"
desc = "timestamp at which the permutation is performed"

[[variables.input]]
name = "addr"
type = "DWordBL"
desc = "memory address storing the first bit of the state"

[[variables.input]]
name = "input_state"
type = [[["Byte", 8], 5], 5]
desc = "state at the start of executing the permutation"

[[variables.output]]
name = "output_state"
type = [[["Byte", 8], 5], 5]
desc = "state after executing the permutation"

[[variables.auxiliary]]
name = "state_ptr"
type = [["DWordHL", 5], 5]
desc = "memory addresses storing the entire state"

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""

[[constraint_groups]]
name = "output"

[[constraints.output]]
kind = "interaction"
tag = "ECALL"
input = ["timestamp", ["arr", ["-", ["^", 2, 32], 1], ["-", ["^", 2, 32], 2]]]
multiplicity = ["-", "μ"]

[[constraint_groups]]
name = "mem"

[[constraints.mem]]
kind = "interaction"
tag = "MEMW"
input = [1, ["cast", ["*", 2, 10], "DWordWL"], "addr", "timestamp", 1, 0, 0]
output = "addr"
multiplicity = "μ"

[[constraints.mem]]
kind = "template"
tag = "ADD"
input = [["cast", "addr", "DWordWL"], ["cast", ["*", 8, ["+", ["*", 5, "x"], "y"]], "DWordWL"]]
output = ["cast", ["idx", ["idx", "state_ptr", "x"], "y"], "DWordWL"]
iters = [["x", 0, 4], ["y", 0, 4]]

[[constraints.mem]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", ["idx", ["idx", "state_ptr", "x"], "y"], "z"]]
iters = [["x", 0, 4], ["y", 0, 4], ["z", 0, 3]]
multiplicity = "μ"

[[constraints.mem]]
kind = "interaction"
tag = "MEMW"
input = [0, ["cast", ["idx", ["idx", "state_ptr", "x"], "y"], "DWordWL"], ["idx", ["idx", "output_state", "x"], "y"], "timestamp", 0, 0, 1]
output = ["idx", ["idx", "input_state", "x"], "y"]
iters = [["x", 0, 4], ["y", 0, 4]]
multiplicity = "μ"

[[constraint_groups]]
name = "round"

[[constraints.round]]
kind = "interaction"
tag = "KECCAK"
input = ["timestamp", 0, "input_state"]
multiplicity = "μ"

[[constraints.round]]
kind = "interaction"
tag = "KECCAK"
input = ["timestamp", 24, "output_state"]
multiplicity = ["-", "μ"]
