name = "KECCAK"

[[variables.input]]
name = "timestamp"
type = "DWordWL"
desc = "timestamp at which the permutation is performed"
pad = 0

[[variables.input]]
name = "addr"
type = "DWordWL"
desc = "memory address storing the first bit of the state"
pad = 0

[[variables.input]]
name = "input_state"
type = [[["Byte", 8], 5], 5]
desc = "state at the start of executing the permutation"
pad = 0

[[variables.output]]
name = "output_state"
type = [[["Byte", 8], 5], 5]
desc = "state after executing the permutation"
pad = 0

[[variables.virtual]]
name = "state_ptr_lo"
type = [["Word", 5], 5]
desc = "lower halves of the memory addresses storing the entire state"
def = {iters=[["x", 0, 4], ["y", 0, 4]], poly=["+", ["idx", "addr", 0], ["*", 8, ["+", ["*", 5, "y"], "x"]]]}

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""
pad = 0

[[assumptions]]
desc = "$(#`addr` mod 2^32) + 192 < 2^32$"
ref = "keccak:a:addr_alignment"

[[constraint_groups]]
name = "output"

[[constraints.output]]
kind = "interaction"
tag = "ECALL"
input = ["timestamp", ["cast", ["-", ["^", 2, 64], 2], "DWordWL"]]
multiplicity = ["-", "μ"]

[[constraint_groups]]
name = "mem"

[[constraints.mem]]
kind = "interaction"
tag = "MEMW"
input = [1, ["cast", ["*", 2, 10], "DWordWL"], ["arr", ["idx", "addr", 0], ["idx", "addr", 1], 0, 0, 0, 0, 0, 0], "timestamp", 1, 0, 0]
output = ["arr", ["idx", "addr", 0], ["idx", "addr", 1], 0, 0, 0, 0, 0, 0]
multiplicity = "μ"
ref = "keccak:c:read_addr"

[[constraints.mem]]
kind = "interaction"
tag = "MEMW"
input = [0, ["arr", ["idx", ["idx", "state_ptr_lo", "x"], "y"], ["idx", "addr", 1]], ["idx", ["idx", "output_state", "x"], "y"], "timestamp", 0, 0, 1]
output = ["idx", ["idx", "input_state", "x"], "y"]
iters = [["x", 0, 4], ["y", 0, 4]]
multiplicity = "μ"
ref = "keccak:c:load_store_state"

[[constraint_groups]]
name = "round"

[[constraints.round]]
kind = "interaction"
tag = "KECCAK"
input = ["timestamp", 0, "input_state"]
multiplicity = "μ"

[[constraints.round]]
kind = "interaction"
tag = "KECCAK"
input = ["timestamp", 24, "output_state"]
multiplicity = ["-", "μ"]
