name = "LT"


# Input

[[variables.input]]
name = "lhs"
type = "DWordHHW"
desc = "The left operand"
pad = 0

[[variables.input]]
name = "rhs"
type = "DWordHHW"
desc = "The right operand"
pad = 0

[[variables.input]]
name = "signed"
type = "Bit"
desc = "whether to interpret `lhs` and `rhs` as signed integers (1) or not (0)"
pad = 0

[[variables.input]]
name = "invert"
type = "Bit"
desc = "Whether to invert the result"
pad = 0

# Output

[[variables.output]]
name = "res"
type = "Bit"
desc = "The result"
pad = 0


# Auxiliary

[[variables.auxiliary]]
name = "lhs_sub_rhs"
type = "DWordHL"
desc = "$#`lhs` - #`rhs`$"
pad = 0

[[variables.auxiliary]]
name = "lhs_msb"
type = "Bit"
desc = "The most significant bit of `lhs`"
pad = 0

[[variables.auxiliary]]
name = "rhs_msb"
type = "Bit"
desc = "The most significant bit of `rhs`"
pad = 0

[[variables.auxiliary]]
name = "lt"
type = "Bit"
desc = "Whether $#`lhs` < #`rhs`$, taking `signed` into account"
pad = 0

# Virtual

[[variables.virtual]]
name = "carry"
type = ["Bit", 2]
desc = "The carry for adding `lhs_sub_rhs` back to `rhs`"
def = {idx = "i", polys = [
  {iter = 0, poly = ["*", ["^", 2, -32], ["-", ["+", ["idx", "rhs", 0], ["idx", ["cast", "lhs_sub_rhs", "DWordWL"], 0]], ["idx", "lhs", 0]]]},
  {iter = 1, poly = ["*", ["^", 2, -32], ["-", ["+", ["idx", ["cast", "rhs", "DWordWL"], 1], ["idx", ["cast", "lhs_sub_rhs", "DWordWL"], 1], ["idx", "carry", 0]], ["idx", ["cast", "lhs", "DWordWL"], 1]]]},
]}

[[variables.virtual]]
name = "unsigned_lt"
type = "Bit"
desc = "Whether $#`lhs` < #`rhs`$, as unsigned integers"
def = ["idx", "carry", 1]


# Multiplicity

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""
pad = 0


[[assumptions]]
desc = "`IS_WORD[lhs[0]]`"
ref = "lt:a:range_lhs"

[[assumptions]]
desc = "`IS_WORD[rhs[0]]`"
ref = "lt:a:range_rhs"

[[constraint_groups]]
name = "range"
desc = "Range-check the inputs"

[[constraints.range]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "lhs", 1]]
multiplicity = "μ"
ref = "lt:c:range_lhs"

[[constraints.range]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "rhs", 1]]
multiplicity = "μ"
ref = "lt:c:range_rhs"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["signed"]
ref = "lt:c:range_signed"

[[constraints.range]]
kind = "template"
tag = "IS_BIT"
input = ["invert"]
ref = "lt:c:range_invert"

[[constraint_groups]]
name = "defs"
desc = "Enforce that variables have been correctly computed"

[[constraints.defs]]
kind = "interaction"
tag = "MSB16"
input = [["idx", "lhs", 2]]
output = "lhs_msb"
multiplicity = "μ"
ref = "lt:c:lhs_msb"

[[constraints.defs]]
kind = "interaction"
tag = "MSB16"
input = [["idx", "rhs", 2]]
output = "rhs_msb"
multiplicity = "μ"
ref = "lt:c:rhs_msb"

[[constraints.defs]]
kind = "arith"
constraint = "$#`lt` = #`signed` dot (A (1 - B) + A C + (1 - B) C) + (1 - #`signed`) dot #`unsigned_lt`$"
desc = "Where $A = #`lhs_msb`$, $B = #`rhs_msb`$ and $C = #`carry[1]`$"
poly = ["-", "lt", ["*", "signed", ["+", ["*", "lhs_msb", ["not", "rhs_msb"]], ["*", "lhs_msb", ["idx", "carry", 1]], ["*", ["not", "rhs_msb"], ["idx", "carry", 1]]]], ["*", ["-", 1, "signed"], "unsigned_lt"]]
ref = "lt:c:lt"

[[constraints.defs]]
kind = "arith"
constraint = "$#`res` = #`lt` xor #`invert`$"
poly = ["-", ["+", "res", ["*", 2, "lt", "invert"]], "lt", "invert"]


[[constraint_groups]]
name = "sub"
desc = "Constrain the subtraction"

[[constraints.sub]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "carry", "i"]]
iter = ["i", 0, 1]

[[constraints.sub]]
kind = "interaction"
tag = "IS_HALF"
input = [["idx", "lhs_sub_rhs", "i"]]
iter = ["i", 0, 3]
multiplicity = "μ"
ref = "lt:c:lhs_sub_rhs_range"


[[constraint_groups]]
name = "output"
desc = "Each row contributes the following to the LogUp sum"

[[constraints.output]]
kind = "interaction"
tag = "ALU"
input = [["cast", "lhs", "DWordWL"], ["cast", "rhs", "DWordWL"], ["+", ["opsel", "LT"], ["*", 32, "signed"], ["*", 64, "invert"]]]
output = ["arr", "res", 0]
multiplicity = ["-", "μ"]
