name = "MEMW"
code = "MMW"

# Input

[[variables.input]]
name = "is_register"
type = "Bit"
desc = "Whether the address represents a register index"
pad = 0

[[variables.input]]
name = "base_address"
type = "DWordWL"
desc = "The base address to read from/write to. Gets offset by $[0, 7]$ depending on the size of the access"
pad = 0

[[variables.input]]
name = "value"
type = ["BaseField", 8]
desc = "The values to store in memory. For RAM, these should be (up to) 8 range-checked `Byte`s; registers are stored as two range-checked `Word`s"
pad = 0

[[variables.input]]
name = "timestamp"
type = "DWordWL"
desc = "The timestamp at which this memory access occurs"
pad = 0

[[variables.input]]
name = "write2"
type = "Bit"
desc = "Whether to write exactly 2 values"
pad = 0

[[variables.input]]
name = "write4"
type = "Bit"
desc = "Whether to write exactly 4 values"
pad = 0

[[variables.input]]
name = "write8"
type = "Bit"
desc = "Whether to write exactly 8 values"
pad = 0

# Output

[[variables.output]]
name = "old"
type = ["BaseField", 8]
desc = """The old value written at `base_address`. See `value` for information about representation.
Only the elements corresponding to the `writeN` bits are guaranteed"""
pad = 0

# Auxiliary

[[variables.auxiliary]]
name = "carry"
type = ["Bit", 7]
desc = "Whether `base_address[0] + i + 1` $>= 2^32$"
pad = 0

[[variables.auxiliary]]
name = "old_timestamp"
type = ["DWordWL", 8]
desc = "The timestamp at which address `base_address + i` was last accessed"
pad = 0

# Virtual

[[variables.virtual]]
name = "w2"
type = "Bit"
desc = "writing at least 2 bytes"
def = ["+", "write2", "write4", "write8"]

[[variables.virtual]]
name = "w4"
type = "Bit"
desc = "writing at least 4 bytes"
def = ["+", "write4", "write8"]

[[variables.virtual]]
name = "address_add"
type = ["DWordWL", 7]
desc = "`address_add[i] = base_address + i + 1`"
def.iter = ["i", 0, 6]
def.poly = ["arr",
  ["-", ["+", ["idx", "base_address", 0], "i", 1], ["*", ["^", 2, 32], ["idx", "carry", "i"]]],
  ["+", ["idx", "base_address", 1], ["idx", "carry", "i"]]]

[[variables.virtual]]
name = "μ_sum"
type = "Bit"
desc = ""
def = ["+", "μ_read", "μ_write"]

# Multiplicity

[[variables.multiplicity]]
name = "μ_read"
type = "Bit"
desc = "Whether we are performing a read (and hence return `out`)"
pad = 0

[[variables.multiplicity]]
name = "μ_write"
type = "Bit"
desc = "Whether we are performing a write (and hence not return `out`)"
pad = 0

[[assumptions]]
desc = "`IS_WORD[base_address[i]]`"
iter = ["i", 0, 1]

[[assumptions]]
desc = "`IS_BIT<write2>`"

[[assumptions]]
desc = "`IS_BIT<write4>`"

[[assumptions]]
desc = "`IS_BIT<write8>`"

[[assumptions]]
desc = "`IS_BIT<write2 + write4 + write8>`"

[[assumptions]]
desc = "`IS_WORD[timestamp[i]]`"
iter = ["i", 0, 1]

[[constraint_groups]]
name = "assumptions"

[[constraints.assumptions]]
kind = "template"
tag = "IS_BIT"
input = ["write2"]

[[constraints.assumptions]]
kind = "template"
tag = "IS_BIT"
input = ["write4"]

[[constraints.assumptions]]
kind = "template"
tag = "IS_BIT"
input = ["write8"]

[[constraints.assumptions]]
kind = "template"
tag = "IS_BIT"
input = [["+", "write2", "write4", "write8"]]

[[constraint_groups]]
name = "consistency"

[[constraints.consistency]]
kind = "template"
tag = "IS_BIT"
input = ["μ_read"]

[[constraints.consistency]]
kind = "template"
tag = "IS_BIT"
input = ["μ_write"]

[[constraints.consistency]]
kind = "template"
tag = "IS_BIT"
input = ["μ_sum"]

[[constraints.consistency]]
kind = "arith"
constraint = "$#`w2` => #`μ_sum`$"
poly = ["*", "w2", ["not", "μ_sum"]]

[[constraints.consistency]]
kind = "template"
tag = "IS_BIT"
input = [["idx", "carry", "i"]]
iter = ["i", 0, 6]

[[constraints.consistency]]
kind = "interaction"
tag = "ALU"
input = [["idx", "old_timestamp", 0], "timestamp", ["opsel", "LT"]]
output = ["arr", 1, 0]
multiplicity = "μ_sum"

[[constraints.consistency]]
kind = "interaction"
tag = "ALU"
input = [["idx", "old_timestamp", 1], "timestamp", ["opsel", "LT"]]
output = ["arr", 1, 0]
multiplicity = "w2"

[[constraints.consistency]]
kind = "interaction"
tag = "ALU"
input = [["idx", "old_timestamp", "i"], "timestamp", ["opsel", "LT"]]
output = ["arr", 1, 0]
iter = ["i", 2, 3]
multiplicity = "w4"

[[constraints.consistency]]
kind = "interaction"
tag = "ALU"
input = [["idx", "old_timestamp", "i"], "timestamp", ["opsel", "LT"]]
output = ["arr", 1, 0]
iter = ["i", 4, 7]
multiplicity = "write8"

[[constraint_groups]]
name = "memory"
prefix = "M"

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", "base_address", ["idx", "old_timestamp", 0], ["idx", "old", 0]]
multiplicity = "μ_sum"

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", "base_address", "timestamp", ["idx", "value", 0]]
multiplicity = ["-", "μ_sum"]

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", ["idx", "address_add", 0], ["idx", "old_timestamp", 1], ["idx", "old", 1]]
multiplicity = "w2"

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", ["idx", "address_add", 0], "timestamp", ["idx", "value", 1]]
multiplicity = ["-", "w2"]

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", ["idx", "address_add", ["-", "i", 1]], ["idx", "old_timestamp", "i"], ["idx", "old", "i"]]
multiplicity = "w4"
iter = ["i", 2, 3]

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", ["idx", "address_add", ["-", "i", 1]], "timestamp", ["idx", "value", "i"]]
multiplicity = ["-", "w4"]
iter = ["i", 2, 3]

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", ["idx", "address_add", ["-", "i", 1]], ["idx", "old_timestamp", "i"], ["idx", "old", "i"]]
multiplicity = "write8"
iter = ["i", 4, 7]

[[constraints.memory]]
kind = "interaction"
tag = "memory"
input = ["is_register", ["idx", "address_add", ["-", "i", 1]], "timestamp", ["idx", "value", "i"]]
multiplicity = ["-", "write8"]
iter = ["i", 4, 7]


[[constraint_groups]]
name = "output"
prefix = "O"

[[constraints.output]]
kind = "interaction"
tag = "MEMW"
input = ["is_register", "base_address", "value", "timestamp", "write2", "write4", "write8"]
output = "old"
multiplicity = ["-", "μ_read"]

[[constraints.output]]
kind = "interaction"
tag = "MEMW"
input = ["is_register", "base_address", "value", "timestamp", "write2", "write4", "write8"]
multiplicity = ["-", "μ_write"]
