name = "MUL"


# Input

[[variables.input]]
name = "lhs"
type = "DWordHL"
desc = "the left hand operator."

[[variables.input]]
name = "lhs_signed"
type = "Bit"
desc = "whether to interpret `lhs` as a signed integer (1) or not (0)."

[[variables.input]]
name = "rhs"
type = "DWordHL"
desc = "the right hand operator."

[[variables.input]]
name = "rhs_signed"
type = "Bit"
desc = "whether to interpret `rhs` as a signed integer (1) or not (0)."


# Output

[[variables.output]]
name = "res"
type = "QuadWL"
desc = "the (extended) multiplication result"

# Auxiliary

[[variables.auxiliary]]
name = "lhs_msb"
type = "Bit"
desc = "the most significant bit of `lhs`"

[[variables.auxiliary]]
name = "rhs_msb"
type = "Bit"
desc = "the most significant bit of `rhs`"

[[variables.auxiliary]]
name = "raw_product"
type = ["B51", 4]
desc = "raw multiplication output"

# Virtual

[[variables.virtual]]
name = "lhs_ext"
type = ["Half", 8]
desc = "sign-extended value of `lhs`"
def = {idx="i", polys=[
    {range=[0, 3], poly=["idx", "lhs", "i"]},
    {range=[4, 7], poly=["*", 0xFFFF, "lhs_signed", "lhs_msb"]},
]}

[[variables.virtual]]
name = "rhs_ext"
type = ["Half", 8]
desc = "sign-extended value of `rhs`"
def = {idx="i", polys=[
    {range=[0, 3], poly=["idx", "rhs", "i"]},
    {range=[4, 7], poly=["*", 0xFFFF, "rhs_signed", "rhs_msb"]},
]}

[[variables.virtual]]
name = "limb_product"
type = ["B35", 8]
desc = "raw multiplication output"
def = ["sum", ["=", "j", 0], "i", ["*", ["idx", "lhs_ext", "i"], ["idx", "rhs_ext", ["-", "i", "j"]]]]

[[variables.virtual]]
name = "carry"
type = ["B20", 4]
desc = "carry values"
def = {idx="i", polys=[
    {range=0, poly=["*", ["^", 2, -32], ["-", ["idx", "raw_product", 0], ["idx", "res", 0]]]},
    {range=[1, 3], poly=["*", ["^", 2, -32], ["-", ["+", ["idx", "raw_product", "i"], ["idx", "carry", ["-", "i", 1]]], ["idx", "res", "i"]]]},
]}


# Multiplicity

[[variables.multiplicity]]
name = "μ_lo"
type = "BaseField"
desc = ""

[[variables.multiplicity]]
name = "μ_hi"
type = "BaseField"
desc = ""

# Assumptions

[[assumptions]]
desc = "`IS_HALF[lhs[i]]`"
range = ["i", 0, 3]

[[assumptions]]
desc = "`IS_HALF[rhs[i]]`"
range = ["i", 0, 3]


# Constraints

[[constraint_groups]]
name = "def"

[[constraints.def]]
kind = "interaction"
tag = "MSB16"
input = [["idx", "lhs", 3]]
output = "lhs_msb"
multiplicity = ["+", "μ_lo", "μ_hi"]
ref = "mul:c:lhs_msb"

[[constraints.def]]
kind = "interaction"
tag = "MSB16"
input = [["idx", "rhs", 3]]
output = "rhs_msb"
multiplicity = ["+", "μ_lo", "μ_hi"]
ref = "mul:c:rhs_msb"

[[constraints.def]]
kind = "interaction"
tag = "IS_B20"
input = [["idx", "carry", "i"]]
range = ["i", 0, 7]
multiplicity = ["+", "μ_lo", "μ_hi"]
ref = "mul:c:carry"

[[constraint_groups]]
name = "prod"

[[constraints.prod]]
kind = "arith"
constraint = "$#`raw_product[i]` = #`limb_product[2i]` + 2^32 dot #`limb_product[2i + 1]`$"
poly = ["-", ["+", ["idx", "limb_product", "2i"], ["*", ["^", 2, 32], ["idx", "limb_product", "2i+1"]]], ["idx", "raw_product", "i"]]
range = ["i", 0, 3]

[[constraint_groups]]
name = "lookup"

[[constraints.lookup]]
kind = "interaction"
tag = "MUL"
input = ["lhs", "lhs_signed", "rhs", "rhs_signed", "0"]
output = ["idx", "res", "0:4"]
multiplicity = ["-", "μ_lo"]
ref = "mul:c:lookup_lo"

[[constraints.lookup]]
kind = "interaction"
tag = "MUL"
input = ["lhs", "lhs_signed", "rhs", "rhs_signed", "1"]
output = ["idx", "res", "4:8"]
multiplicity = ["-", "μ_hi"]
ref = "mul:c:lookup_hi"