name = "ROTXOR"

[[variables.input]]
name = "a"
type = "WordHL"
desc = "The input value"
pad = 0

[[variables.input]]
name = "r0_low"
type = "Byte"
desc = "The first amount of rotation, low nibble"
pad = 0

[[variables.input]]
name = "r0_high"
type = "Bit"
desc = "The first amount of rotation, high bit"
pad = 0

[[variables.input]]
name = "r1_low"
type = "Byte"
desc = "The second amount of rotation, low nibble"
pad = 0

[[variables.input]]
name = "r1_high"
type = "Bit"
desc = "The second amount of rotation, high bit"
pad = 0

[[variables.input]]
name = "r2_low"
type = "Byte"
desc = "The third amount of rotation, low nibble"
pad = 0

[[variables.input]]
name = "last_rot"
type = "Bit"
desc = "Whether the rotation by `r2` is a rotation (1) or just a shift (0)"
pad = 0

[[variables.output]]
name = "out"
type = "WordBL"
desc = "The output"
pad = 0

[[variables.auxiliary]]
name = "a0_left"
type = "WordHL"
desc = "`a << r0_low`"
pad = 0

[[variables.auxiliary]]
name = "a0_right"
type = "WordHL"
desc = "`a >> r0_low`"
pad = 0

[[variables.auxiliary]]
name = "a1_left"
type = "WordHL"
desc = "`a << r1_low`"
pad = 0

[[variables.auxiliary]]
name = "a1_right"
type = "WordHL"
desc = "`a >> r1_low`"
pad = 0

[[variables.auxiliary]]
name = "a2_left"
type = "WordHL"
desc = "`a << r2_low`"
pad = 0

[[variables.auxiliary]]
name = "a2_right"
type = "WordHL"
desc = "`a >> r2_low`"
pad = 0

[[variables.auxiliary]]
name = "a0"
type = "WordBL"
desc = "`a >>> r0`"
pad = 0

[[variables.auxiliary]]
name = "a1"
type = "WordBL"
desc = "`a >>> r1`"
pad = 0

[[variables.auxiliary]]
name = "a2"
type = "WordBL"
desc = "`a >>> r2` or `a >> r2`"
pad = 0

[[variables.auxiliary]]
name = "a01"
type = "WordBL"
desc = "$a_0 xor a_1$"
pad = 0

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""
pad = 0


[[assumptions]]
desc = "$1 <= #`r0_low`, #`r1_low`, #`r2_low` < 16$"

[[assumptions]]
desc = "$0 <= #`r0_high`, #`r1_high` < 2$"


[[constraint_groups]]
name = "shift"

[[constraints.shift]]
kind = "interaction"
tag = "HWSL"
input = [["idx", "a", "i"], ["-", 16, "r0_low"]]
output = ["arr", ["idx", "a0_left", "i"], ["idx", "a0_right", "i"]]
iter = ["i", 0, 1]
multiplicity = "μ"

[[constraints.shift]]
kind = "interaction"
tag = "HWSL"
input = [["idx", "a", "i"], ["-", 16, "r1_low"]]
output = ["arr", ["idx", "a1_left", "i"], ["idx", "a1_right", "i"]]
iter = ["i", 0, 1]
multiplicity = "μ"

[[constraints.shift]]
kind = "interaction"
tag = "HWSL"
input = [["idx", "a", "i"], ["-", 16, "r2_low"]]
output = ["arr", ["idx", "a2_left", "i"], ["idx", "a2_right", "i"]]
iter = ["i", 0, 1]
multiplicity = "μ"

[[constraints.shift]]
kind = "arith"
constraint = "$#`a0[i]` = (1 - #`r0_high`) * (#`a0_left[1 - i]` + #`a0_right[i]`) + #`r0_high` * (#`a0_left[i]` + #`a0_right[i - i]`)$"
poly = ["-", ["idx", ["cast", "a0", "WordHL"], "i"], ["*", ["not", "r0_high"], ["+", ["idx", "a0_left", ["-", 1, "i"]], ["idx", "a0_right", "i"]]], ["*", "r0_high", ["+", ["idx", "a0_left", "i"], ["idx", "a0_right", ["-", 1, "i"]]]]]
iter = ["i", 0, 1]

[[constraints.shift]]
kind = "arith"
constraint = "$#`a1[i]` = (1 - #`r1_high`) * (#`a1_left[1 - i]` + #`a1_right[i]`) + #`r1_high` * (#`a1_left[i]` + #`a1_right[i - i]`)$"
poly = ["-", ["idx", ["cast", "a1", "WordHL"], "i"], ["*", ["not", "r1_high"], ["+", ["idx", "a1_left", ["-", 1, "i"]], ["idx", "a1_right", "i"]]], ["*", "r1_high", ["+", ["idx", "a1_left", "i"], ["idx", "a1_right", ["-", 1, "i"]]]]]
iter = ["i", 0, 1]

[[constraints.shift]]
kind = "arith"
constraint = "$#`a2[0]` = #`a2_left[1]` + #`a2_right[0]`$"
poly = ["-", ["idx", ["cast", "a2", "WordHL"], 0], ["idx", "a2_left", 1], ["idx", "a2_right", 0]]

[[constraints.shift]]
kind = "arith"
constraint = "$#`a2[1]` = #`last_rot` dot #`a2_left[0]` + #`a2_right[1]`$"
poly = ["-", ["idx", ["cast", "a2", "WordHL"], 0], ["*", "last_rot", ["idx", "a2_left", 0]], ["idx", "a2_right", 1]]

[[constraint_groups]]
name = "xor"

[[constraints.xor]]
kind = "interaction"
tag = "XOR_BYTE"
input = [["idx", "a0", "i"], ["idx", "a1", "i"]]
output = ["idx", "a01", "i"]
multiplicity = "μ"
iter = ["i", 0, 3]

[[constraints.xor]]
kind = "interaction"
tag = "XOR_BYTE"
input = [["idx", "a01", "i"], ["idx", "a2", "i"]]
output = ["idx", "out", "i"]
multiplicity = "μ"
iter = ["i", 0, 3]

[[constraint_groups]]
name = "output"

[[constraints.output]]
kind = "interaction"
tag = "ROTXOR"
input = [["cast", "a", "Word"], "r0_low", "r0_high", "r1_low", "r1_high", "r2_low", "last_rot"]
output = ["cast", "out", "Word"]
multiplicity = ["-", "μ"]
