name = "SHA256_K"
code = "SHK"

[[variables.input]]
name = "index"
type = "BaseField"
desc = ""
precomputed = true

[[variables.input]]
name = "K"
type = "Word"
desc = ""
precomputed = true

[[variables.multiplicity]]
name = "μ"
type = "BaseField"
desc = ""

[[constraint_groups]]
name = "contributions"

[[constraints.contributions]]
kind = "interaction"
tag = "SHA256_K"
input = ["index"]
output = "K"
multiplicity = ["-", "μ"]
