name = "SHIFT"

# Input

[[variables.input]]
name = "in"
type = "DWordHL"
desc = "The word being shifted"

[[variables.input]]
name = "shift"
type = "BaseField"
desc = "Number of bits to shift `in` by."

[[variables.input]]
name = "direction"
type = "Bit"
desc = "Whether to shift left (0) or right (1)."

[[variables.input]]
name = "signed"
type = "Bit"
desc = "Whether to interpret `in` as a signed integer."


# Output

[[variables.output]]
name = "shifted"
type = "DWordHL"
desc = "`in <</>> (shift % 64)`"


# Auxiliary
[[variables.auxiliary]]
name = "bit_shift"
type = "Byte"
desc = "`shift && 0x0F`"

[[variables.auxiliary]]
name = "bit_shifted_uncarried"
type = "Half[4]"
desc = "result of left/right shifting the individual limbs of `in` by `bit_shift`, i.e., without the carry values."

[[variables.auxiliary]]
name = "carry"
type = "Half[4]"
desc = "the carry values of left/right shifting `in` by `bit_shift`."

[[variables.auxiliary]]
name = "is_negative"
type = "Bit"
desc = "whether `in` is negative."

[[variables.auxiliary]]
name = "limb_shift_0"
type = "Bit"
desc = "Whether $floor.l #`bit_shift` / 16 floor.r equiv 0 mod 4$."

[[variables.auxiliary]]
name = "limb_shift_1"
type = "Bit"
desc = "Whether $floor.l #`bit_shift` / 16 floor.r equiv 1 mod 4$."

[[variables.auxiliary]]
name = "limb_shift_2"
type = "Bit"
desc = "Whether $floor.l #`bit_shift` / 16 floor.r equiv 2 mod 4$."

[[variables.auxiliary]]
name = "limb_shift_3"
type = "Bit"
desc = "Whether $floor.l #`bit_shift` / 16 floor.r equiv 3 mod 4$."

# Virtual

[[variables.virtual]]
name = "extension"
type = "Half"
desc = "sign extension of `in`."
poly = ["*", 65535, "is_negative"]

[[variables.virtual]]
name = "left"
type = "Bit"
desc = "Whether to perform a left-shift."
poly = ["-", "μ", "direction"]

[[variables.virtual]]
name = "right"
type = "Bit"
desc = "Whether to perform a right-shift."
poly = "direction"

[[variables.virtual]]
name = "bit_shifted"
type = "DWordHL"
desc = "`in <</>> (shift % 16)`"
poly = ["+", ["idx", "bit_shifted_uncarried", "i"],  ["idx", "carry", "i"]]

# Multiplicities

[[variables.multiplicity]]
name = "μ"
type = "Bit"
desc = ""



# Assumptions

[[assumptions]]
desc = "`IS_HALFWORD[in[i]]`"
range = ["i", 0, 3]
ref = "shift:a:range_in"



# Constraints

[[constraint_groups]]
name = "defs"

[[constraints.defs]]
kind = "interaction"
tag = "AND_BYTE"
input = ["shift", "0x0F"]
output = "bit_shift"
ref = "shift:c:bit_shift"
multiplicity = "μ"

[[constraints.defs]]
kind = "interaction"
tag = "AND_BYTE"
input = ["shift", "0x30"]
output = ["+", ["-", 1, "limb_shift_0"], ["*", 15, "limb_shift_1"], ["*", 31, "limb_shift_2"], ["*", 47, "limb_shift_3"]]
ref = "shift:c:limb_shift_x"
multiplicity = "μ"

[[constraints.defs]]
kind = "template"
tag = "IS_BIT"
input = ["limb_shift_0"]
ref = "shift:c:limb_shift_0_is_bit"

[[constraints.defs]]
kind = "template"
tag = "IS_BIT"
input = ["limb_shift_1"]
ref = "shift:c:limb_shift_1_is_bit"

[[constraints.defs]]
kind = "template"
tag = "IS_BIT"
input = ["limb_shift_2"]
ref = "shift:c:limb_shift_2_is_bit"

[[constraints.defs]]
kind = "template"
tag = "IS_BIT"
input = ["limb_shift_3"]
ref = "shift:c:limb_shift_3_is_bit"

[[constraints.defs]]
kind = "template"
tag = "IS_BIT"
input = [["+", "limb_shift_0", "limb_shift_1", "limb_shift_2", "limb_shift_3"]]
ref = "shift:c:limb_shift_sum_is_bit"

[[constraint_groups]]
name = "intra_limb_left_shifting"

[[constraints.intra_limb_left_shifting]]
kind = "interaction"
tag = "HWSL"
input = [["idx", "in", "i"], "bit_shift"]
output = ["idx", "bit_shifted_uncarried", "i"]
range = ["i", 0, 3]
multiplicity = "left"
ref = "shift:c:hwsl"

[[constraints.intra_limb_left_shifting]]
kind = "interaction"
tag = "HWSLC"
input = [["idx", "in", ["-", "i", 1]], "bit_shift"]
output = ["idx", "carry", "i"]
range = ["i", 1, 3]
multiplicity = "left"
ref = "shift:c:hwsl"

[[constraints.intra_limb_left_shifting]]
kind = "arith"
constraint = "$#`direction` => #`μ`$"
poly = ["*", "direction", ["-", 1, "μ"]]
ref = "shift:c:direction_implies_mu"

[[constraints.intra_limb_left_shifting]]
kind = "arith"
constraint = "$#`left` => #`carry[0]` = 0$"
poly = ["*", "left", ["idx", "carry", 0]]
ref = "shift:c:left_zero_carry"


[[constraint_groups]]
name = "intra_limb_right_shifting"

[[constraints.intra_limb_right_shifting]]
kind = "interaction"
tag = "HWSR"
input = [["idx", "in", "i"], "bit_shift"]
output = ["idx", "bit_shifted_uncarried", "i"]
range = ["i", 0, 3]
multiplicity = "right"
ref = "shift:c:hwsr"

[[constraints.intra_limb_right_shifting]]
kind = "interaction"
tag = "HWSRC"
input = [["idx", "in", ["+", "i", 1]], "bit_shift"]
output = ["idx", "carry", "i"]
range = ["i", 0, 2]
multiplicity = "right"
ref = "shift:c:hwsrc"

[[constraints.intra_limb_right_shifting]]
kind = "interaction"
tag = "MSB16"
input = [["idx", "in", 3]]
output = "is_negative"
multiplicity = "signed"
ref = "shift:c:is_negative"

[[constraints.intra_limb_right_shifting]]
kind = "arith"
constraint = "$#`!signed` => #`is_negative` = 0$"
poly = ["*", ["-", 1, "signed"], "is_negative"]

[[constraints.intra_limb_right_shifting]]
kind = "interaction"
tag = "HWSRC"
input = ["extension", "bit_shift"]
output = ["idx", "carry", 3]
multiplicity = "right"
ref = "shift:c:right_sign_extend"


[[constraint_groups]]
name = "limb_shifting"

[[constraints.limb_shifting]]
kind = "arith"
constraint = "$#`limb_shift_0` => #`shifted[i]` = #`bit_shifted[i]`$"
poly = ["*", "limb_shift_0", ["-", ["idx", "shifted", "i"], ["idx", "bit_shifted", "i"]]]
range = ["i", 0, 3]


[[constraint_groups]]
name = "limb_left_shifting"

[[constraints.limb_left_shifting]]
kind = "arith"
constraint = "$#`left` and #`limb_shift_1` => #`shifted[i]` = #`bit_shifted[i-1]`$"
poly = ["*", "left", "limb_shift_1", ["-", ["idx", "shifted", "i"], ["idx", "bit_shifted", ["-", "i", 1]]]]
range = ["i", 1, 3]


[[constraints.limb_left_shifting]]
kind = "arith"
constraint = "$#`left` and #`limb_shift_2` => #`shifted[i]` = #`bit_shifted[i-2]`$"
poly = ["*", "left", "limb_shift_2", ["-", ["idx", "shifted", "i"], ["idx", "bit_shifted", ["-", "i", 2]]]]
range = ["i", 2, 3]


[[constraints.limb_left_shifting]]
kind = "arith"
constraint = "$#`left` and #`limb_shift_3` => #`shifted[3]` = #`bit_shifted[0]`$"
poly = ["*", "left", "limb_shift_3", ["-", ["idx", "shifted", 3], ["idx", "bit_shifted", 0]]]

[[constraint_groups]]
name = "limb_left_shifting_zero"

[[constraints.limb_left_shifting_zero]]
kind = "arith"
constraint = "$#`left` and (#`limb_shift_1` or #`limb_shift_2` or #`limb_shift_3`) => #`shifted[0]` = 0$"
poly = ["*", "left", ["+", "limb_shift_1", "limb_shift_2", "limb_shift_3"], ["idx", "shifted", 0]]

[[constraints.limb_left_shifting_zero]]
kind = "arith"
constraint = "$#`left` and (#`limb_shift_2` or #`limb_shift_3`) => #`shifted[1]` = 0$"
poly = ["*", "left", ["+", "limb_shift_2", "limb_shift_3"], ["idx", "shifted", 1]]

[[constraints.limb_left_shifting_zero]]
kind = "arith"
constraint = "$#`left` and #`limb_shift_3` => #`shifted[2]` = 0$"
poly = ["*", "left", "limb_shift_3", ["idx", "shifted", 2]]


[[constraint_groups]]
name = "limb_right_shifting"

[[constraints.limb_right_shifting]]
kind = "arith"
constraint = "$#`right` and #`limb_shift_1` => #`shifted[i]` = #`bit_shifted[i+1]`$"
poly = ["*", "right", "limb_shift_1", ["-", ["idx", "shifted", "i"], ["idx", "bit_shifted", ["+", "i", 1]]]]
range = ["i", 0, 2]

[[constraints.limb_right_shifting]]
kind = "arith"
constraint = "$#`right` and #`limb_shift_2` => #`shifted[i]` = #`bit_shifted[i+2]`$"
poly = ["*", "right", "limb_shift_2", ["-", ["idx", "shifted", "i"], ["idx", "bit_shifted", ["-", "i", 2]]]]
range = ["i", 0, 1]

[[constraints.limb_right_shifting]]
kind = "arith"
constraint = "$#`right` and #`limb_shift_3` => #`shifted[0]` = #`bit_shifted[3]`$"
poly = ["*", "right", "limb_shift_3", ["-", ["idx", "shifted", 0], ["idx", "bit_shifted", 3]]]

[[constraint_groups]]
name = "limb_right_shifting_extension"

[[constraints.limb_right_shifting_extension]]
kind = "arith"
constraint = "$#`right` and (#`limb_shift_1` or #`limb_shift_2` or #`limb_shift_3`) => #`shifted[3]` = #`extension`$"
poly = ["*", "right", ["+", "limb_shift_1", "limb_shift_2", "limb_shift_3"], ["-", ["idx", "shifted", 3], "extension"]]

[[constraints.limb_right_shifting_extension]]
kind = "arith"
constraint = "$#`right` and (#`limb_shift_2` or #`limb_shift_3`) => #`shifted[2]` = #`extension`$"
poly = ["*", "right", ["+", "limb_shift_2", "limb_shift_3"], ["-", ["idx", "shifted", 2], "extension"]]

[[constraints.limb_right_shifting_extension]]
kind = "arith"
constraint = "$#`right` and #`limb_shift_3` => #`shifted[1]` = #`extension`$"
poly = ["*", "right", "limb_shift_3", ["-", ["idx", "shifted", 1], "extension"]]


# Lookups

[[constraint_groups]]
name = "lookups"

[[constraints.lookups]]
kind = "interaction"
tag = "SHIFT"
input = ["in", "shift", "direction", "signed"]
output = "shifted"
multiplicity = "-μ"
ref = "shift:c:lookup"
