# cond => IS_BIT<X>
[[signatures]]
tag = "IS_BIT"
kind = "template"
input = ["BaseField"]
cond = "BaseField"

# IS_BYTE<X, μ>
[[signatures]]
tag = "IS_BYTE"
kind = "template"
input = ["BaseField"]
cond = "BaseField"

# cond => ADD<sum; lhs, rhs>
[[signatures]]
tag = "ADD"
kind = "template"
input = ["DWordWL", "DWordWL"]
output = "DWordWL"
cond = "BaseField"

# cond => SUB<diff; lhs, rhs>
[[signatures]]
tag = "SUB"
kind = "template"
input = ["DWordWL", "DWordWL"]
output = "DWordWL"
cond = "BaseField"

# cond => ADDNW<sum; lhs, rhs>
[[signatures]]
tag = "ADDNW"
kind = "template"
input = ["DWordWL", "DWordWL"]
output = "DWordWL"
cond = "BaseField"

# cond => NEG<neg; X>
[[signatures]]
tag = "NEG"
kind = "template"
input = ["DWordHL"]
output = "DWordWL"
cond = "Bit"

# SIGN<sign; X, signed>
[[signatures]]
tag = "SIGN"
kind = "template"
input = ["Half", "Bit"]
output = "Bit"

# DECODE[pc, imm, packed_decode]
[[signatures]]
tag = "DECODE"
kind = "interaction"
input = ["DWordWL", "DWordWL", "BaseField"]

# CPU32[half_instruction_length; timestamp, pc]
[[signatures]]
tag = "CPU32"
kind = "interaction"
input = ["Word", "DWordWL"]
output = "Byte"

# ALU[out; in1, in2, flags]
[[signatures]]
tag = "ALU"
kind = "interaction"
input = ["DWordWL", "DWordWL", "Byte"]
output = "DWordWL"

# MEMOP[out; timestamp, address, value, flags]
[[signatures]]
tag = "MEMOP"
kind = "interaction"
input = ["Word", "DWordWL", "DWordWL", "Byte"]
output = "DWordWL"

# BRANCH[next_pc; pc, offset, register, JALR]
[[signatures]]
tag = "BRANCH"
kind = "interaction"
input = ["DWordWL", "DWordWL", "DWordWL", "Bit"]
output = "DWordWL"

# MEMW[old; domain, base_address, value, timestamp, write2, write4, write8]
[[signatures]]
tag = "MEMW"
kind = "interaction"
input = ["BaseField", "DWordWL", ["BaseField", 8], "Word", "Bit", "Bit", "Bit"]
output = ["BaseField", 8]

# REG[old; base_address, value, timestamp]
[[signatures]]
tag = "REG"
kind = "template"
input = ["Byte", "DWordWL", "Word"]
output = "DWordWL"
cond = "BaseField"

# MEMW[domain, base_address, value, timestamp, write2, write4, write8]
[[signatures]]
tag = "MEMW"
kind = "interaction"
input = ["BaseField", "DWordWL", ["BaseField", 8], "Word", "Bit", "Bit", "Bit"]

# REG[base_address, value, timestamp]
[[signatures]]
tag = "REGW"
kind = "template"
input = ["Byte", "DWordWL", "Word"]
cond = "BaseField"

# LOAD[res; base_address, timestamp, flags]
[[signatures]]
tag = "LOAD"
kind = "interaction"
input = ["DWordWL", "Word", "Byte"]
output = "DWordWL"

# ECALL[timestamp, syscallnr]
[[signatures]]
tag = "ECALL"
kind = "interaction"
input = ["Word", "DWordWL"]

# CNB[timestamp, index, address, count]
[[signatures]]
tag = "CNB"
kind = "interaction"
input = ["Word", "BaseField", "DWordWL", "DWordWL"]

# DMA_NEXT[timestamp, src, dst, count]
[[signatures]]
tag = "DMA_NEXT"
kind = "interaction"
input = ["Word", "DWordWL", "DWordWL", "DWordWL"]

# BYTE_ALU[res; selector, X, Y]
[[signatures]]
tag = "BYTE_ALU"
kind = "interaction"
input = ["Byte", "Byte", "Byte"]
output = "Byte"

# MSB8[msb; X]
[[signatures]]
tag = "MSB8"
kind = "interaction"
input = ["Byte"]
output = "Bit"

# MSB16[msb; X]
[[signatures]]
tag = "MSB16"
kind = "interaction"
input = ["Half"]
output = "Bit"

# ZERO[is_zero; X]
[[signatures]]
tag = "ZERO"
kind = "interaction"
input = ["B20"]
output = "Bit"

# ARE_BYTES[X, Y]
[[signatures]]
tag = "ARE_BYTES"
kind = "interaction"
input = ["Byte", "Byte"]

# IS_HALF[X]
[[signatures]]
tag = "IS_HALF"
kind = "interaction"
input = ["Half"]

# IS_B20[X]
[[signatures]]
tag = "IS_B20"
kind = "interaction"
input = ["B20"]

# HWSL[res; X, shift]
[[signatures]]
tag = "HWSL"
kind = "interaction"
input = ["Half", "B4"]
output = ["Half", 2]

# The actual memory tokens, see MEMW, L2G and PAGE
[[signatures]]
tag = "memory"
kind = "interaction"
input = ["BaseField", "DWordWL", "Word", "BaseField"]

# Global memory: domain, address, epoch, value
[[signatures]]
tag = "GLOBAL_MEM"
kind = "interaction"
input = ["BaseField", "DWordWL", "B20", "BaseField"]

# SHA256 things
[[signatures]]
tag = "SHA256_K"
kind = "interaction"
input = ["BaseField"]
output = "Word"

[[signatures]]
tag = "SHA256_M"
kind = "interaction"
input = ["Word", "BaseField"]
output = "Word"

[[signatures]]
tag = "SHA256ROUND"
kind = "interaction"
input = ["Word", ["Word", 8], "BaseField"]

[[signatures]]
tag = "ROTXOR"
kind = "interaction"
input = ["Word", "Byte", "Byte", "Byte", "Bit"]
output = "Word"

# Keccak communication between rounds
[[signatures]]
tag = "KECCAK"
kind = "interaction"
input = ["Word", "BaseField", [[["Byte", 8], 5], 5]]

# Keccak round constants
[[signatures]]
tag = "KECCAK_RC"
kind = "interaction"
input = ["BaseField"]
output = ["Byte", 8]

# ECSM
[[signatures]]
tag = "ECDAS"
kind = "interaction"
input = ["Bit", "Word",  "U256BL", "U256BL", "U256BL", "U256BL", "Byte", "Bit"]

[[signatures]]
kind = "interaction"
tag = "BIT"
input = ["Word", "Byte"]
