//! Host-reference execution tests for the ethrex guest, relocated out of the
//! `executor` test suite: `ethrex-guest-program` pins rkyv with the
//! `unaligned` feature (a global archived-layout switch), which would
//! feature-unify with the main workspace's aligned rkyv and silently change
//! the proof wire format. This crate is a detached workspace so the two rkyv
//! configurations never meet.
//!
//! Fixtures are generated by `tooling/ethrex-fixtures`; the guest ELF comes
//! from `make compile-programs`. See `executor/tests/README.md`.

use executor::elf::Elf;
use executor::vm::execution::Executor;
use executor::vm::execution::ReturnValues;

fn run_program_without_expect(
    elf_path: &str,
    private_inputs: Vec<u8>,
) -> Result<ReturnValues, executor::vm::execution::ExecutorError> {
    println!("Testing {}", elf_path);
    let elf_data = std::fs::read(elf_path).unwrap();
    let program = Elf::load(&elf_data).unwrap();
    println!("Program entry: 0x{:016x}", program.entry_point);
    let mut executor = Executor::new(&program, private_inputs)?;
    while let Some(_logs) = executor.resume()? {}
    executor.finish()
}

fn run_program_and_check_public_output(
    elf_path: &str,
    expected_output: Vec<u8>,
    private_inputs: Vec<u8>,
) {
    let result =
        run_program_without_expect(elf_path, private_inputs).expect("Failed to run program");

    assert_eq!(result.memory_values, expected_output);
}

const ELF_PATH: &str = "../../executor/program_artifacts/rust/ethrex.elf";
const FIXTURES_DIR: &str = "../../executor/tests";

/// Larger-block smoke test: a synthetic ethrex block with 10 ETH transfers.
/// (Replaces the old `ethrex_hoodi.bin` real-block fixture, which was in the
/// pre-Crypto-trait ethrex format and no longer deserializes.)
#[ignore = "heavier synthetic block (10 txs); run in the dedicated --ignored CI step"]
#[test]
fn test_ethrex() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::fs;
    use std::sync::Arc;
    let inputs = fs::read(format!("{FIXTURES_DIR}/ethrex_10_transfers.bin")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    let output = execution_program(input, Arc::new(NativeCrypto)).unwrap();
    run_program_and_check_public_output(ELF_PATH, output.encode(), inputs);
}

/// Executes a stateless ethrex block containing a single (plain ETH transfer)
/// transaction. Execution only — no proving — against the ethrex guest ELF
/// built from the same pinned ethrex revision as the native reference.
#[test]
fn test_ethrex_simple_tx() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::sync::Arc;
    let inputs = std::fs::read(format!("{FIXTURES_DIR}/ethrex_simple_tx.bin")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    let output = execution_program(input, Arc::new(NativeCrypto)).unwrap();
    run_program_and_check_public_output(ELF_PATH, output.encode(), inputs);
}

/// Executes a stateless ethrex block with NO transactions (empty block).
/// Execution only — no proving. Pins the committed `ethrex_empty_block.bin`
/// fixture so its rkyv `ProgramInput` layout (the 0-tx edge case) is
/// exercised and stays consistent with the guest across ethrex rev bumps.
#[test]
fn test_ethrex_empty_block() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::sync::Arc;
    let inputs = std::fs::read(format!("{FIXTURES_DIR}/ethrex_empty_block.bin")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    let output = execution_program(input, Arc::new(NativeCrypto)).unwrap();
    run_program_and_check_public_output(ELF_PATH, output.encode(), inputs);
}
