//! Host-reference execution tests for the ethrex guest, relocated out of the
//! `executor` test suite: `ethrex-guest-program` pins rkyv with the
//! `unaligned` feature (a global archived-layout switch), which would
//! feature-unify with the main workspace's aligned rkyv and silently change
//! the proof wire format. This crate is a detached workspace so the two rkyv
//! configurations never meet.
//!
//! Fixtures are generated by `tooling/ethrex-fixtures`; the guest ELF comes
//! from `make compile-programs`. See `executor/tests/README.md`.

use executor::elf::Elf;
use executor::vm::execution::Executor;
use executor::vm::execution::ReturnValues;

fn run_program_without_expect(
    elf_path: &str,
    private_inputs: Vec<u8>,
) -> Result<ReturnValues, executor::vm::execution::ExecutorError> {
    println!("Testing {}", elf_path);
    let elf_data = std::fs::read(elf_path).unwrap();
    let program = Elf::load(&elf_data).unwrap();
    println!("Program entry: 0x{:016x}", program.entry_point);
    let mut executor = Executor::new(&program, private_inputs)?;
    while let Some(_logs) = executor.resume()? {}
    executor.finish()
}

fn run_program_and_check_public_output(
    elf_path: &str,
    expected_output: Vec<u8>,
    private_inputs: Vec<u8>,
) {
    let result =
        run_program_without_expect(elf_path, private_inputs).expect("Failed to run program");

    assert_eq!(result.memory_values, expected_output);
}

const ELF_PATH: &str = "../../executor/program_artifacts/rust/ethrex.elf";
const FIXTURES_DIR: &str = "../../executor/tests";

/// Larger-block smoke test: a synthetic ethrex block with 10 ETH transfers.
/// (The old `ethrex_hoodi.bin` real-block fixture predated the `Crypto` trait
/// and no longer deserializes; the current real-block fixture is separate.)
#[ignore = "heavier synthetic block (10 txs); run in the dedicated --ignored CI step"]
#[test]
fn test_ethrex() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::fs;
    use std::sync::Arc;
    let inputs = fs::read(format!("{FIXTURES_DIR}/ethrex_10_transfers.bin")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    let output = execution_program(input, Arc::new(NativeCrypto)).unwrap();
    run_program_and_check_public_output(ELF_PATH, output.encode(), inputs);
}

/// Executes a stateless ethrex block containing a single (plain ETH transfer)
/// transaction. Execution only — no proving — against the ethrex guest ELF
/// built from the same pinned ethrex revision as the native reference.
#[test]
fn test_ethrex_simple_tx() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::sync::Arc;
    let inputs = std::fs::read(format!("{FIXTURES_DIR}/ethrex_simple_tx.bin")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    let output = execution_program(input, Arc::new(NativeCrypto)).unwrap();
    run_program_and_check_public_output(ELF_PATH, output.encode(), inputs);
}

/// Executes a stateless ethrex block with NO transactions (empty block).
/// Execution only — no proving. Pins the committed `ethrex_empty_block.bin`
/// fixture so its rkyv `ProgramInput` layout (the 0-tx edge case) is
/// exercised and stays consistent with the guest across ethrex rev bumps.
#[test]
fn test_ethrex_empty_block() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::sync::Arc;
    let inputs = std::fs::read(format!("{FIXTURES_DIR}/ethrex_empty_block.bin")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    let output = execution_program(input, Arc::new(NativeCrypto)).unwrap();
    run_program_and_check_public_output(ELF_PATH, output.encode(), inputs);
}

const REAL_BLOCK_FIXTURE: &str = "ethrex_hoodi_1265656.bin";

/// Host-only acceptance gate for the real-block fixture produced by
/// `tooling/ethrex-real-block` (`make ethrex-real-block-fixture`): the block is
/// re-executed statelessly against its own witness, so a successful run means
/// the recovered tries, codes and headers reproduce the header's post-state
/// root. Needs no guest ELF, which is what keeps it runnable where the RV64
/// toolchain isn't available.
///
/// Checks the *serialized artifact* specifically — that the committed rkyv
/// bytes deserialize and execute — which is why it reads the `.bin` rather
/// than converting the cache itself. It runs under `NativeCrypto` (ethrex's
/// full precompile set) because this crate builds `ethrex-guest-program` with
/// default features, so it does NOT speak to the guest's reduced surface;
/// `tooling/ethrex-real-block`'s `real_block_executes_under_guest_crypto`
/// covers that, under `lambdavm` features + `LambdaVmEcsmCrypto`.
#[test]
fn test_ethrex_real_block_native() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::sync::Arc;
    let inputs = std::fs::read(format!("{FIXTURES_DIR}/{REAL_BLOCK_FIXTURE}")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    execution_program(input, Arc::new(NativeCrypto)).unwrap();
}

/// The same real block through the guest ELF, checking the VM's committed
/// output matches the native reference. Split from the native gate above
/// because this one needs the ethrex ELF and is far heavier than the synthetic
/// fixtures (a ~1 MB witness, real contract execution).
///
/// Deliberately excluded from the PR CI step, which otherwise runs everything
/// via `--include-ignored`: the cycle cost of a real block in the VM has not
/// been measured yet, so it is opt-in until we know what it does to job time.
/// Run it explicitly with:
///   cd tooling/ethrex-tests && cargo test --release test_ethrex_real_block_vm -- --ignored
#[ignore = "real block through the VM; unmeasured runtime, run explicitly on a build server"]
#[test]
fn test_ethrex_real_block_vm() {
    use ethrex_guest_program::crypto::NativeCrypto;
    use ethrex_guest_program::l1::{ProgramInput, execution_program};
    use rkyv::rancor::Error;
    use std::sync::Arc;
    let inputs = std::fs::read(format!("{FIXTURES_DIR}/{REAL_BLOCK_FIXTURE}")).unwrap();
    let input = rkyv::from_bytes::<ProgramInput, Error>(&inputs).unwrap();
    let output = execution_program(input, Arc::new(NativeCrypto)).unwrap();
    run_program_and_check_public_output(ELF_PATH, output.encode(), inputs);
}
